### ISSUE TITLE
Possibility to access, listen and modify fields with javascript

### ISSUE THREAD

**Issue by gogabidzia** [area17/twill#102]
Hi, 

I'm trying to create form where I show/hide some fields based on select field value. Is it possible to listen change events to a select field and access another fields?

Thanks

**Comment by ifox** [comment]
Hi @gogabidzia!

yes it is possible! Take a look at my comment in [#39](https://github.com/area17/twill/issues/39#issuecomment-426067947).

**Comment by gogabidzia** [comment]
Ah, I see. It worked, thanks a lot!
