### ISSUE TITLE
Files form fieldset order / position problem

### ISSUE THREAD

**Issue by ConstantMath** [area17/twill#1020]
Hello,
I am trying the file upload module but I have a problem with the reorder functionality, despite the presence of drag n drop, the position is not saved. After page admin reload, it's back on a random position.

If someone could explain me where the positions are saved, I don't see any column in the DB tables about position, nor in the **fileables** table, same in the **mediables** table (where the position works in my project by the way)

Thank you for your precious help !

### Versions

Twill version:  Version 2.3.1

**Comment by pboi20** [comment]
Hi @ConstantMath,

I can confirm this bug. When reordering the files in the frontend and clicking 'Update', the correct order is sent to the backend but it doesn't appear to be saved in the DB. When refreshing the page, I believe the items are ordered by `file_id`, ascending.

**Comment by ConstantMath** [comment]
Hello, thanks for this clarification, `file_id` & `media_id`are used for positioning (ordering) in the pivot table, indeed it works like this for the images.
