### ISSUE TITLE
How to get the width and height of an image?

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#103]
Hi,

I'd like to get the values of the width and height of an image (after the crop has been applied, rather than the dimensions of the original asset) so I can make aspect ratio boxes for images to sit in. How do I go about doing this?

I worked out how to get the ratio value, but that doesn't always help as some of my images are ratio 0.

Thanks,
Seb

**Comment by ifox** [comment]
Hi Seb!

The `imageObject` or `imageAsArray` helpers would provide you with that information.

When using `imageObject`, you will retrieve a `Media` record, with its pivot information from the `mediables` table, which include cropping parameters.

https://github.com/area17/twill/blob/1746dafec03b60909f384d96045b6075dabb240b/src/Models/Behaviors/HasMedias.php#L160-L165

The `imageAsArray` helper basically gather relevant information for you from that record and outputs it as an array:

https://github.com/area17/twill/blob/1746dafec03b60909f384d96045b6075dabb240b/src/Models/Behaviors/HasMedias.php#L76-L96

If you're going with `imageOject` then you can have a look in `imageAsArray` to figure out how you'd retrieve you what you need.

**Comment by milewski** [comment]
I guess this only works if you are using an online service or implemented your own cropping service otherwise even with your crops set it will always return the original size for all crops

**Comment by sebastianlenton** [comment]
Perfect- thanks again!
