### ISSUE TITLE
Twill has a lot of query on null column which is not compatible with Index

### ISSUE THREAD

**Issue by weburnit** [area17/twill#1046]
## Summary
To optimize with Index on deleted_at column (SoftDelete), I would like to suggest migrate column deleted_at from timestamp to int.
## Describe the solution you'd like
Instead of having null datetime for deleted_at, we use 0! otherwise set timestamp(int)

Override SoftDelete Trait
## Additional context

In the case Twill approves this concept, I would like to work on it right away.

**Comment by ifox** [comment]
Hi @weburnit, thanks for your interest in contributing.

I'm afraid what you're asking for should really be dealt with by the framework behind Twill, Laravel, as we're using the provided soft delete approach. I've read a few threads on the subject and the consensus seems to be that it can actually be detrimental to index such a column, unless your database is mostly storing soft deleted models. I would recommend purging those records programmatically instead, for example on a schedule.
