### ISSUE TITLE
Connected field doesn't work in modal

### ISSUE THREAD

**Issue by ammma** [area17/twill#1050]
Hi there,

Connected field doesn't work in create\edit modals. Error is:
![image](https://user-images.githubusercontent.com/11386705/125644366-a237fbd0-e165-49c9-9ba2-e1f810f25cdf.png)
As mentioned [here](https://github.com/area17/twill/discussions/1022) 

> The ConnectorField component is also only registered on the main form, not in the modal

I think it is an issue at least for `form.blade.php` because it must be working equally either it is shown in modal or not.
Also i'm sure that any custom components won't be working in edit form if you switch to modal.

Steps to reproduce: 
- add connected fields to `form.blade.php` \ `create.blade.php` as described here: https://github.com/area17/twill/blob/2.x/docs/.sections/form-fields.md#conditional-fields
- enable `'editInModal' => true` in controller `$indexOptions`
Result: both modals will produce same error and connected field won't be working as expected.

Twill version:  2.4
Laravel version: 8
PHP version: 7.4

**Comment by pboi20** [comment]
Hey @ammma, thanks for reporting this issue!

Just to clarify, `@formConnectedFields` and custom Vue components should work in `form.blade.php`. The issue only affects `create.blade.php`, is that right?

**Comment by ammma** [comment]
> Hey @ammma, thanks for reporting this issue!
> 
> Just to clarify, `@formConnectedFields` and custom Vue components should work in `form.blade.php`. The issue only affects `create.blade.php`, is that right?

no, it is not right. If you set `'editInModal' => true` in controller `$indexOptions` then `form.blade.php` will appear in modal and will have same issues that `create.blade.php` has.

**Comment by pboi20** [comment]
I believe `create.blade.php` is what's in the modal with `'editInModal' => true`, not `form.blade.php`. Can you confirm that?

**Comment by ammma** [comment]
> I believe `create.blade.php` is what's in the modal with `'editInModal' => true`, not `form.blade.php`. Can you confirm that?

yes, you are correct. Well...this approach looks odd to me and i didn't expect this. Using `create` for for editing, you know. Doesn't sound logical. Unless option name is `editInModalUsingCreateForm` ))

Ok, basically i don't care about if forms shown in modal or not, i can live without it. But if i don't make my edit form shown in modal then i see this mostly useless feature:
![image](https://user-images.githubusercontent.com/11386705/126222957-44afa721-24a8-4995-ae11-7a1b3df09cb7.png)
which i don't know how to get rid of. Many of entities i'm trying to manage with twill does not have single unique and self-explanatory field but set of fields. Simplest example - user with first and last names. So i went with `'editInModal' => true` and voila - twill doesn't even use my form now)

p.s. got another issue - media field doesn't save any data when in modal. I can see in request `medias: null`, then i switch back to normal and it saves.

**Comment by pboi20** [comment]
Hey @ammma, thanks for taking the time to report and discuss these issues.

I agree that a "create" partial for an "edit" feature is not perfect vocabulary, but I believe this came organically in Twill's development and could be redesigned in the future. For context, `editInModal` was initially thought for simple models with very few fields (e.g. "Category", "Keyword", etc.)  Those are refered as "Attributes" in the docs : https://twill.io/docs/#recommended-crud-content-types

Your main issue is duly noted: `create.blade.php` and `form.blade.php` should be more aligned in the kinds of fields that they support. I believe this also could be improved in the future.

Did you solve your `Missing title` problem? As far as I can tell, this is probably not related to the use of `editInModal` so I think it would deserve its own issue or discussion.

**Comment by ammma** [comment]
@pboi20 thanks a lot for your time.
