### ISSUE TITLE
Permalink slug is not loaded proper and is resetted after saving again

### ISSUE THREAD

**Issue by bosix** [area17/twill#1057]
## Description

A content manager of our company mentioned a bug while editing pages in our twill backend. We use twill as a headless content management system that has multiple content types a.k.a. modules configurated. The relevant module is named "page" and represents a content page that is displayed to a website visitor at our frontend. The module uses translations, slugs, files, media, revisions and the block editor. Additionally, we have german (de) and english (en) enabled for translations.

The bug occurs when our content manager wants to set a custom slug for the page permalink. 

### Steps to reproduce

- create a new page and set a random title
- on the edit page: click on the pen beside the title to get the edit title modal
- insert any custom and valid slug (e.g. `test123`)
- save the page
- you can now see, that the new permalink is displayed correctly and you can also see, that the change was saved to the database
- reload the edit page e.g. via browser reload (f5)
- now, no permalink or slug is shown; the input field for a slug is empty (database still correct)
- save the page again without any change
- finally, the old and auto-generated slug is active again

![image](https://user-images.githubusercontent.com/26360670/125915372-2b69c097-6611-481c-bcd1-d4e0c96d3d72.png)

### Expected result

After changing the permalink slug of a resource it should:
1. keep active until I change it by myself
2. be shown on the edit page

### Actual result

The slug is shown until I reload the page. If I save the page after reloading, the custom slug is reset to the auto-generated one.

### Versions

Twill version: 2.4.0
Laravel version: 6.20.30
PHP version: 7.4.20
Database engine: MySQL (cummunity) v8.0.17

Please let me know if you need any further information. Thank you :)

**Comment by pboi20** [comment]
Hi @bosix,

I'm unable to replicate your issue on my end. I followed your instructions carefully and when I got to this step :

>now, no permalink or slug is shown; the input field for a slug is empty (database still correct)

the slug field was not empty as you described, I could see the correct value in the slug field. I saved the page without any change and everything was as I expected, in the UI and in the DB.

Am I missing anything? Did you customize your model or repository in a way that would affect how slugs are processed?

**Comment by bosix** [comment]
Hi @pboi20, 

thank you for your reply. You mentioned a good point and you are right. We have adjusted the namespaces of all models, repositories etc to have them better organized. To get this work properly we have extended the HasSlug behaviour like this:

```php

use A17\Twill\Models\Behaviors\HasSlug as TwillHasSlug;

trait HasSlug
{
    use TwillHasSlug;

    /**
     * overwritten because namespace fix
     *
     * @return mixed
     */
    public function slugs()
    {
        $baseNamespace = static::MODEL_NAMESPACE;
        return $this->hasMany(
            $baseNamespace . '\Slugs\\' . $this->getSlugClassName()
        );
    }

    /**
     * overwritten because namespace fix
     *
     * @return mixed
     */
    public function getSlugClass()
    {
        $baseNamespace = static::MODEL_NAMESPACE;
        $slugClassName = $baseNamespace . '\Slugs\\' . $this->getSlugClassName();
        return new $slugClassName();
    }

// [...]
}
```

The repository has an adjusted way to get the namespace as well:

```php
use A17\Twill\Models\Model;
use A17\Twill\Repositories\ModuleRepository;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Str;
use ReflectionClass;

abstract class BaseRepository extends ModuleRepository
{
    /**
     * Override parent function to also handle models in packages.
     *
     * @param string $relation
     * @param null $model
     * @return mixed
     */
    protected function getModelRepository($relation, $model = null)
    {
        if (!$model) {
            if (class_exists($relation) && (new $relation()) instanceof Model) {
                $model = Str::afterLast($relation, '\\');
            } else {
                $model = ucfirst(Str::singular($relation));
            }
        }
        $reflectedClass = new ReflectionClass(static::class);
        $classFQCN = $reflectedClass->getNamespaceName() . '\\' . Str::afterLast($model, 'Models\\') . 'Repository';
        return App::make($classFQCN);
    }
}
```

We thought that this causes no problems and until version 2.2 that adjustments work very well. I've checked that the functions which are provided by HasSlugs are working (`getActiveSlug()` etc.) so I do not think that there is a basic issue. Further, everything else causes no problem (block editor, revisions, images etc.) Nevertheless, there could be a problem because something has changed since v2.2 and the way we overwrite does not work anymore.

It would be a pleasure if you could have a deeper look into this and maybe you have an idea why this is not working.

Have a nice day :)

**Comment by ifox** [comment]
Hi @bosix! Thanks for providing those details. Here is the current implementation of the functions you changed:

```php
    /**
     * Defines the one-to-many relationship for slug objects.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function slugs()
    {
        return $this->hasMany($this->getSlugModelClass());
    }

    /**
     * Returns an instance of the slug class for this model.
     *
     * @return object
     */
    public function getSlugClass()
    {
        return new $this->getSlugModelClass();
    }

    /**
     * Returns the fully qualified slug class name for this model.
     *
     * @return string|null
     */
    public function getSlugModelClass()
    {
        $slug = $this->getNamespace() . "\Slugs\\" . $this->getSlugClassName();

        if (@class_exists($slug)) {
            return $slug;
        }

        return $this->getCapsuleSlugClass(class_basename($this));
    }

    protected function getSlugClassName()
    {
        return class_basename($this) . "Slug";
    }
```

You might not need to change that anymore.

**Comment by bosix** [comment]
Hi @ifox 
thank you for the information. Although they do not help to fix the bug I found it at a place I had never expect to find it. Maybe you can have a look and check if it is a side effect of our customization or a general bug of twill.

We have multiple pages and I found out that one was working properly and the other one has the issue mentioned above. Each Module has it's own repository which is used to fetch the data for the frontend. There is a method called `getFormFields` which you can find inside `A17\Twill\Repositories\ModuleRepository`. This function fetches all attributes from the model and looks for behaviours like `HandleSlugs` or `HandleTranslations` inside the repository. The method list returned by `traitsMethods` looks like this:

```
// working 
array:6 [
  1 => "getFormFieldsHandleBrowsers"
  2 => "getFormFieldsHandleRepeaters"
  3 => "getFormFieldsHandleFieldsGroups"
  5 => "getFormFieldsHandleBlocks"
  6 => "getFormFieldsHandleTranslations"
  7 => "getFormFieldsHandleSlugs"
]

// not working
array:6 [
  1 => "getFormFieldsHandleBrowsers"
  2 => "getFormFieldsHandleRepeaters"
  3 => "getFormFieldsHandleFieldsGroups"
  5 => "getFormFieldsHandleBlocks"
  7 => "getFormFieldsHandleSlugs"
  8 => "getFormFieldsHandleTranslations"
]
```

In the beginning, I thought that the different index might be a problem but the foreach which iterates through the array does not care about indexes. Then I see that the order of `getFormFieldsHandleSlugs` and `getFormFieldsHandleTranslations` was different.

So the solution is :drum: ... switching the order of using the traits:

```php
// not working
class PageRepository extends BaseRepository
{
    use HandleBlocks;
    use HandleRepeaters;
    use HandleRevisions;
    use HandleSlugs;
    use HandleTranslations;
//[...]
}

// working
class PageRepository extends BaseRepository
{
    use HandleBlocks;
    use HandleRepeaters;
    use HandleRevisions;
    use HandleTranslations;
    use HandleSlugs;
//[...]
}
```

This changes the order of functions `getFormFields` executes and solved our problem.

The point why I would be pleased if you have a look at it is because I cannot really get why this was an issue and maybe it is a general bug that should be fixed. It could be that the issue does not occur normally because the module generator for artisan generates the use statements in the correct order but this is only an assumption.

You can close this issue if you like. Since our bug is solved I don't have any demand for it anymore.

**Comment by ifox** [comment]
Thanks @bosix, this makes sense and has been reported in the past in #94.
