### ISSUE TITLE
Route undefined

### ISSUE THREAD

**Issue by HeartlandTechie** [area17/twill#1061]
## Description

Route [admin.users.index] not defined. (View: /Users/xxxx/PhpstormProjects/tutoring/vendor/area17/twill/views/partials/navigation/_overlay_navigation.blade.php)

### Steps to reproduce

New install

### Expected result

Login in and see the admin panel . . . 

### Versions

   latest
 Laravel Framework 8.51.0
 PHP 7.3.29
 mysql 5.7

**Comment by pboi20** [comment]
Hi @HeartlandTechie, thanks for reporting the issue. Can you share your `twill.php` configuration?

**Comment by antonioribeiro** [comment]
Maybe also share your routes list, please, @HeartlandTechie. My experience is you that probably have something like `admin.admin.users.index` in your route list, due to the configuration of your admin domain or something else on your `.env` file.

**Comment by HeartlandTechie** [comment]
My twill.php:
`<?php

return [
    'enabled' => [
        'users-management' => false,
        'media-library' => true,
        'file-library' => true,
        'block-editor' => true,
        'buckets' => true,
        'users-image' => false,
        'settings' => true,
        'dashboard' => true,
        'search' => true,
        'users-description' => false,
        'activitylog' => true,
        'users-2fa' => false,
        'users-oauth' => false,
    ],
];`

**Comment by HeartlandTechie** [comment]
My latest error:  

InvalidArgumentException
Auth guard [twill_users] is not defined.

**Comment by pboi20** [comment]
Hey @HeartlandTechie, I believe the bug is related to `'users-management' => false,`. Can you try with a value of `true`?

**Comment by HeartlandTechie** [comment]
Yes, turning on users-management fixed the twill-users problem.

**Comment by pboi20** [comment]
I could be wrong, but I think it should fix your undefined route problem as well. Try :
```
php artisan config:clear
php artisan route:clear
```

**Comment by HeartlandTechie** [comment]
Ok - I think I've managed to get through the tutorial and figure out enough stuff to get it running.  I'm running straight from the php artisan serve command so that kind of makes it a bit harder to follow along.
