### ISSUE TITLE
$indexoptions - removing "Update and Create New" menu item in edit screen

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#107]
Hi,

In `$indexOptions` I set `'create' => false`, and that has removed the "Add New" button in the index view, which is great. However, in the edit view the menu to the right of the Update button (the little arrow) still gives access to the "Update and Create New" option. How do I remove this?

Thanks
Seb

**Comment by ifox** [comment]
Hi Seb,

you can't right now, good catch, we should use that option to remove it from the form too.

**Comment by sebastianlenton** [comment]
I can live with it for now- thanks anyway.
