### ISSUE TITLE
Repeater title is not parsed when using double quotes

### ISSUE THREAD

**Issue by kalkoen** [area17/twill#1077]
Hi, I am new to Twill and trying to learn. I came across something peculiar. Trying to use a Repeater without the (soon to be deprecated) twill.php registration. views/admin/repeaters/role.blade.php is as follows:

```
@twillRepeaterTitle('Role')

@formField('input', [
    'name' => 'title',
    'label' => 'Title',
    'note' => "Single noun.",
    'maxlength' => 200
])
```

Works. However, when instead using `@twillRepeaterTitle("Role")`, Block.php does not want to parse the 'title' property, it seems. I get Exception: Block role does not exists or the mandatory property 'title' was not found on this block. If you are still using blocks on the twill.php file, please check if the block is present and properly configured.

I presume this is a simple oversight in the parsing method.

**Comment by pboi20** [comment]
Hi @kalkoen, I can confirm this. Thanks for reporting!

You're exactly right, [BlockMaker](https://github.com/area17/twill/blob/2.x/src/Services/Blocks/BlockMaker.php#L207) is expecting single quotes for all `@twill` directives.
