### ISSUE TITLE
Exclude unpublished records from browser field list

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#108]
Hi,

Is it possible to prevent records that are set as draft/unpublished from appearing in a browser field list?

Thanks
Seb

**Comment by ifox** [comment]
Hi Seb,

Sorry for the delay here! You can, however those records won't automatically be removed from that browser when unpublished. You'd either always check if a record is published before rendering it on your frontend/API, or you could use some custom code for example using model events to remove the relationship when records are unpublished. 

To scope the list of records available to attach in a browser, override the `getBrowserData` function from your corresponding module controller:
```php
public function getBrowserData($prependScope = [])
{
    return parent::getBrowserData(['published' => true]);
}
```
This would apply to all browsers targeting that module.

If you want to selectively scope per browser field instance, you can add a `params` array to the `@formField` configuration. Those parameters are added to the route generated to access the browser endpoint, which means you could inspect the request in `getBrowserData` and add conditions selectively for example.

**Comment by sebastianlenton** [comment]
Excellent, thanks- all I want to do is exclude draft projects form being added in the first place, and that did the trick. I'm obviously not rendering draft records on the frontend anyway.

Thanks again!
