### ISSUE TITLE
BelongsTo form browser not working with revisions

### ISSUE THREAD

**Issue by alexhillel** [area17/twill#1082]
Browsers powered with a BelongsTo relationship appear to error when selecting an old revision. To recreate:

Create modules:
- Create a module 'Item', enabling revisions: `php artisan twill:module items -R`
- Create a module 'Owner' with no additional traits: `php artisan twill:module owners`

Add routes and navigation:
- In routes/admin.php:

```
Route::module('items');
Route::module('owners');
```

- In config/twill-navigation.php:

```
return [
    'items' => [
        'title' => 'Items',
        'module' => true
    ],
    'owners' => [
        'title' => 'Owners',
        'module' => true
    ]
];
```

Establish a BelongsTo/HasMany relationship between item and owner:
- Add a owner_id field in the Item's migration: `$table->integer('owner_id')->unsigned()->nullable();`
- Add owner_id field to Item model's `$fillables` array
- Add BelongsTo relationship to method Item model's class:

```
    public function owner()
    {
        return $this->belongsTo(Owner::class);
    }

```
- Add HasMany relationship to method Owner model's class:

```
    public function items()
    {
        return $this->hasMany(Item::class);
    }
```

Add Owner browser field and handler: 
- Add owner to ItemRepository browsers array: `protected $browsers = ['owner'];`
- Add owner browser to Item's admin edit form:

```
@section('fieldsets')
@formFieldset(['id' => 'owner', 'title' => 'Owner'])
@formField('browser', [
'label' => 'Owner',
'max' => 1,
'modules' => [
[
'name' => 'owners'
]
],
'name' => 'owner'
])
@endformFieldset
@stop

```

- Migrate DB
- In the admin, create two owners, Owner 1 and Owner 2
- Then create one item, Item 1
- Add Owner 1 to Item 1's browser, save, reload
- Remove Owner 1 in Item 1's browser, add Owner 2, save, reload
- Then try reverting to a previous revision - error logged:

```
[2021-08-10 15:17:53] local.ERROR: Call to a member function getTable() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function getTable() on null at /../vendor/area17/twill/src/Repositories/Behaviors/HandleRevisions.php:150)
[stacktrace]
#0 /../vendor/area17/twill/src/Repositories/Behaviors/HandleRevisions.php(130): App\\Repositories\\ItemRepository->hydrateOrderedBelongsTomany(Object(App\\Models\\Item), Array, 'owner', 'position', 'Owner')
#1 /../vendor/area17/twill/src/Repositories/Behaviors/HandleRevisions.php(26): App\\Repositories\\ItemRepository->hydrateBrowser(Object(App\\Models\\Item), Array, 'owner', 'position', 'Owner')

```

**Comment by pboi20** [comment]
Thanks for reporting @alexhillel !

From @ifox on Discord : 
> Hey guys, thanks for looking into this. The original author of that support fixed it later for previews, but not for revisions, it seems

Related to : https://github.com/area17/twill/pull/984
