### ISSUE TITLE
SSO functionality (SAML / SCIM)

### ISSUE THREAD

**Issue by LANopop** [area17/twill#1086]
## Summary

Support SAML 2.0 and JIT so that its easier to manage users. 
SCIM would also be great.

## Describe the solution you'd like

Let us configure the SAML settings in the TwillCMS interface so we can use a external identity provider for it. (e.g. okta, jumpcloud,...)

## Additional context

In enterprises its good practice to centrally manage all users and this is done via SAML or SCIM nowadays.

**Comment by haringsrob** [comment]
Hello @LANopop,

I will close this issue as this is out of the scope of Twill.

Kind regards,
