### ISSUE TITLE
Implementing form validation?

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#109]
Hi,

Can you provide a basic example of how to implement form validation? I've tried to implement it but haven't been able to get it working (apologies for my lack of Laravel experience here).

In this instance, I'm trying to set a field called `publication_date` in my Project CRUD module as required. What I tried was as follows:

1. Generated a form request class called StoreProject via `php artisan make:request StoreProject`
2. Added the following to the `rules()` function (and `rulesForUpdate()` and `rulesForCreate()` too, in case it helped):

```
return [
    'publication_date' => 'required'
];
```

3. Added a `store()` function to /Admin/ProjectController.php- this is the part I can't get working. On update it either errors or doesn't do anything.

Any help would be great! Thanks again.

**Comment by ifox** [comment]
Hi Seb,

Actually you do not need to add a FormRequest class manually as there should only be one generated when you created a module. It should be under `app/Http/Requests/Admin/ModuleNameRequest.php`. 

When you add rules in this file, the UI will show the corresponding validation error state or message next to the corresponding form field.

**Comment by sebastianlenton** [comment]
Thanks- got that working!

I got validation for block fields working too, but the invalid fields don't get highlighted in red (just to clarify, fields **not** in blocks are highlighting correctly).

I'm returning the following in rulesForUpdate()- am I doing something wrong?

```
return [
                'title' => 'required',
                'publication_date' => 'required',
                'medias.design_page_images' => 'required',
                'medias.index_page_image' => 'required',
                'medias.project_page_image' => 'required',
                'blocks.*.content.paddingtop' => 'sometimes|numeric|gte:45|lte:250',
                'blocks.*.content.paddingbottom' => 'sometimes|numeric|gte:45|lte:250',
];
```

**Comment by sebastianlenton** [comment]
Hi,

I'm still wondering re this- the fact that the fields get validated but don't highlight if invalid is really confusing for users, as it makes it really difficult to know where the problem is...

Thanks again!
