### ISSUE TITLE
Using enter to edit content leads to trimmed form input

### ISSUE THREAD

**Issue by kalkoen** [area17/twill#1105]
## Description

When attempting to change the value of a form field, by entering the value and then pressing Enter on the keyboard, the form value is not always (fully) updated.

### Steps to reproduce

Run
`php artisan twill:module events`
`php artisan migrate`

Add 
```
   "events" => [
        "title" => "Events",
        "module" => true
    ]`
``` 
to twill-navigation.php

Add `Route::module('events');` to routes/admin.php

Go to admin console, to Events
Create an Event named "Whatever" using buttons (similar problem with the title field in the modal, but I am not focusing on that now)
Change description to  "Description", press Enter.
Description should now be "Description"
Change description to "UpdatedDescription",  press Enter.

### Expected result

I expect the event to update with "UpdatedDescription" as description.

### Actual result

The actual value of description is a trimmed version of "UpdatedDescription", i.e. "UpdatedDescrip". Exact value seems to vary each try. It seems to happen when you press enter quickly after finishing typing. It seems as if there is a timer running in the background that only "truly" registers form field changes once every x seconds. Press enter before? Your last characters are not registered.

### Versions

Twill version:  2.4.0
Laravel version: 8.56.0
PHP version:  7.4.19
Database engine: MySQL

**Comment by pboivin** [comment]
Merged into 2.x https://github.com/area17/twill/commit/833198948ee27a3f367465d9ebc61af477e36de2
