### ISSUE TITLE
Disable subdomain/ domain route

### ISSUE THREAD

**Issue by karneaud** [area17/twill#111]
Hello,

I'm trying to run this application in a docker environment where I'm only able to access via IP:port is there a way to disable subdomain or even url in route for admin ?? I keep getting 404

**Comment by ifox** [comment]
Hi @karneaud,

You can use a path to access the admin instead of a subdomain using the following .env configuration in your case:

```
APP_URL=http://localhost
ADMIN_APP_URL=http://localhost
ADMIN_APP_PATH=admin #anything you prefer here actually
```
