### ISSUE TITLE
Detect invalid database permissions on install

### ISSUE THREAD

**Issue by Klievan** [area17/twill#1114]
## Summary

I was installing Twill today, and it seemed like my database permissions weren't 100% correct. The tables were being created but the super-user was not created. Even after manually using twill:superadmin. Every time the message "Your account has been created!" was displayed though, even though I could see the table was empty. After properly creating a separate MySQL account and granting all permissions to that database, the account was actually created.

## Describe the solution you'd like

An error message indicating that the database does not seem to have the correct permissions, or at least a message displaying that the user was not created.

**Comment by ifox** [comment]
Hi @Klievan, is Laravel giving you any error message with that database outside of Twill?

**Comment by Klievan** [comment]
Hi @ifox ! No, the migrations ran fine, and it even populated the migrations table, although it seemed Twill was not able to create the super-user.

**Comment by ifox** [comment]
Yup I got that. i was wondering if doing an insert from Tinker for example, without the Twill command, would let you know that there are permissions issues. I don't think it would, so the only thing we could do to improve this would be to check if the user was effectively created, but I don't think we'll be able to tell you why.
