### ISSUE TITLE
Browser fields implemented with HasRelated do not hydrate when previewing

### ISSUE THREAD

**Issue by joyceverheije** [area17/twill#1117]
## Description

When using the `HasRelated` trait to save a browser field, previewing a change does not work.

### Steps to reproduce

- Make changes to a browser field implemented with `HasRelated`, eg. reordering or changing selected records
- Preview without saving

### Expected result

The changes made to the browser field should be hydrated on the previewed model

### Actual result

The previewed model doesn't include the changes, like regular browser fields with a pivot table would

### Versions

Twill version:  2.x

**Comment by pboivin** [comment]
Hi @joyceverheije, I can confirm this issue. I was able to replicate it on 2.4.0

Thanks for reporting!

**Comment by poncianodiego** [comment]
I am having an issue trying to view saved items of custom pivot tables:

    public function afterSave(TwillModelContract $object, array $fields): void
    {
        $this->updateBrowser($object, $fields, 'artists');
        $this->updateBrowser($object, $fields, 'featured_artworks');
        parent::afterSave($object, $fields);
    }
    
    none are showing
