### ISSUE TITLE
[2.5] Admin frontend broken

### ISSUE THREAD

**Issue by mikerockett** [area17/twill#1135]
## Description

After updating from 2.4.x to 2.5.1, running migrations and `twill:update`, the admin frontend is no longer working fully. Icons are not visible, and the block editor does not appear. Runnng `twill:build` for good measure didn't help either.

No errors emitted in the console.

## Screenshots

![image](https://user-images.githubusercontent.com/4586280/132133699-7ebc2602-15cb-42ad-ba59-5b9ffdec12c8.png)

### Versions

Twill 2.5.1, Laravel 8.58.0

**Comment by ifox** [comment]
Hi @mikerockett, did you try clearing Laravel views cache?

**Comment by mikerockett** [comment]
That did the trick, thanks @ifox. Perhaps this could always be run as part of `twill:update`?

**Comment by ifox** [comment]
You're totally right. Feel free to submit a PR, if not we'll definitely do that.

**Comment by mikerockett** [comment]
@ifox Happy to.

On a similar note, I just noticed that the homepages capsule doesn't render blocks after this update. Anything in particular that needs to be changed?

**Comment by tdnguyen-PACE** [comment]
![image](https://user-images.githubusercontent.com/68363016/132569535-baf9c2ba-1217-402c-8e49-d13b801c0a7b.png)
I got same problem, then I checked the icons path. And, twill:update or clear cache/view also didn't work.
