### ISSUE TITLE
using Browsersync

### ISSUE THREAD

**Issue by karneaud** [area17/twill#115]
based on the issue https://github.com/area17/twill/issues/6

Would it not be better if your `twill-dev` initialized and used the browsersync options as well?

**Comment by ifox** [comment]
Hi @karneaud,

`twill-dev` actually use Webpack Hot Module Reloading through Mix, which should dynamically inject CSS/JS changes or reload the page when not possible.

I hear you about the issues in #6, we're still looking into moving away from npm scripts for a smoother developer experience.

**Comment by karneaud** [comment]
I'm having a problem with the URL assignment in my project at the moment( docker container misbehaving) so I'm resorting to some hard coded urls to get by. Would it be possible to default to the usual `npm run dev` and reference twill related assets?

**Comment by ifox** [comment]
Hi @karneaud, happy 2019!

Sorry for the delay in responding here, I took a short break between the holidays.

You could use `npm run dev` if you were building Twill assets from your own npm project. Right now you would have to require Twill's npm deps from your own `package.json` and adapt [Twill's Mix configuration](url) in your own `webpack.mix.js` file. We working towards a new build configuration if you read through #113 though, so I wouldn't invest too much time on this on your end for now if you have no problem actually building.
