### ISSUE TITLE
Typo in twill::lang.dashboard.unkown-author

### ISSUE THREAD

**Issue by ss-repos** [area17/twill#1153]
There is a typo in DashboardController.php, function formatActivity (line 180)

twillTrans('twill::lang.dashboard.**unkown**-author')

should be:

twillTrans('twill::lang.dashboard.**unknown**-author')

Btw, thanks for the great software! :)

**Comment by MukulKolpe** [comment]
Hey @pboivin can I work on this issue?

**Comment by pboivin** [comment]
Hi @MukulKolpe, yes please! Contributions are welcome.
