### ISSUE TITLE
Block definition with ")" gives extra unwanted characters

### ISSUE THREAD

**Issue by ss-repos** [area17/twill#1154]
When using a block name with a ")" character in it, there is an extra ') printed in the block:

For example, a block definition with:

@twillBlockTitle('Html **(code)**')

results in this:

![afbeelding](https://user-images.githubusercontent.com/24700601/133268476-585eb698-9c9b-4812-8a38-596561b82fe8.png)

Renaming the block to e.g @twillBlockTitle('Html **[code]**') is a workaround for now.

Or is it an easter egg you can play around with? 

![afbeelding](https://user-images.githubusercontent.com/24700601/133269292-cc17162c-0869-4fbf-89a1-33cde596ab60.png)

:)

Versions:

Twill version: 2.51
Laravel version: 8
PHP version: 7

**Comment by pboivin** [comment]
Hi @ss-repos, I can confirm this issue. Thanks for reporting!

Related: https://github.com/area17/twill/issues/1077
