### ISSUE TITLE
Can't able  to add Hook in Twill Users

### ISSUE THREAD

**Issue by venkataadithan** [area17/twill#1166]
## Description

Tried to add custom permissions to the twill users againt the twill modules, can't able to hook in before save or after save for User Module or User Repository

### Steps to reproduce
1) Add a new multiselect form field in twill users to manage permission.
2) Update the user model
3) can't able to regiter hooks 

### Expected result

Have to register Before Save and After Save hooks  for users Module 

### Actual result

Can't able to register Before Save and After Save hooks  for users Module 

### Versions

Twill version:  2.3.x
Laravel version: 6.20.x
PHP version: 7.4.x
Database engine: MySql

**Comment by pboivin** [comment]
Hi @venkataadithan, I agree that the built-in User module is not very extensible by default. This could be improved.

If you only want to register custom user roles and manage permissions for specific modules, maybe this short tutorial can be helpful: https://gist.github.com/pboivin/b81afbc9baa4e8a85a3982b83c3dc88a

**Comment by venkataadithan** [comment]
Hey @pboivin, Thanks for your suggestion, i have tried to give make this customizable/dynamic completely for the super admin access like this [click Here](https://imgur.com/icq4SUC)

**Comment by ifox** [comment]
Customizing the Twill user model is not supported beyond composer overrides, which you could also do for the repository class if you really wanted to though it is of course not recommended for upgradability.

Closing this as we're addressing those needs with #1138.
