### ISSUE TITLE
Crud/Edit form is not loading

### ISSUE THREAD

**Issue by Heqma** [area17/twill#1168]
problem
![](https://i.imgur.com/4VCXcfV.png)

![](https://i.imgur.com/LhaXo2t.png)

clear
![](https://i.imgur.com/tUhFk90.png)

console
![](https://i.imgur.com/7Z4paGJ.png)

twill:update
![](https://i.imgur.com/51uK0RU.png)

public_html->assets->admin
![](https://i.imgur.com/UP5cCFS.png)

laravel->public->assets->admin
![](https://i.imgur.com/A94wDll.png)

PHP: 8.0.1
Laravel Framework 8.61.0
Twill version:  2.5.2

MEDIA_LIBRARY_ENDPOINT_TYPE=local
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Glide

Shared Hosting: 
twill is genertae public folder inside laravel folder. assets are not working
```
Root:
    -Domain:
            -Laravel Folder
                      -public:
                             -assets:
                                      -admin
            -Public_html:
                      -assets:
                             -admin
                      -index.php
```

**Comment by pboivin** [comment]
Hi @Heqma, I've never tried this myself but it seems possible to reconfigure Laravel's `public` folder. Maybe this tutorial can help you:

https://developerhowto.com/2018/11/12/how-to-change-the-laravel-public-folder/

**Comment by ifox** [comment]
Closing as this is not explicitly supported by Laravel itself. If there is something in Twill that cannot be configured to do what you need, feel free to let us know, but I'm afraid we can't support you with challenges of hosting Laravel on shared hosting.
