### ISSUE TITLE
Manage Permissions Not working

### ISSUE THREAD

**Issue by venkataadithan** [area17/twill#1185]
## Description
Mange Permissions for user is not working properly, it just hides the menu and not the functionality

### Steps to reproduce
Add Permission to a Custom User rule and try to access it, only the twill navigation is hided and not the whole module.

### Expected result
Perimission management must redirect to home dashboard insted of accessing the module.

### Actual result
Module Permission/Secured is accessed by all user roles..

### Versions

Twill version: 2.x
Laravel version: 6.x
PHP version: 7.4
Database engine: MySql

**Comment by ifox** [comment]
Hi @venkataadithan, did you setup a route middleware on the module using `can:`? You need that to restrict access beyond the navigation itself.

**Comment by venkataadithan** [comment]
Hey, @ifox i have tried to do this and it's not working:

`Route::middleware('can:manage-content')->group(['prefix' => 'content'], function () {`
     `Route::module('blogs');`
    `Route::module('blogcategories');`
`});`

i'm getting an exception like this **Illuminate\Routing\RouteFileRegistrar::register(): Failed opening required Array**

**Comment by ifox** [comment]
This is a Laravel issue, I think. Try adding the middleware inside the route group array in instead of separately. Also, this tutorial should be helpful: https://gist.github.com/pboivin/b81afbc9baa4e8a85a3982b83c3dc88a.
