### ISSUE TITLE
Class 'Str' not found

### ISSUE THREAD

**Issue by mcouvreur** [area17/twill#1186]
## Description

When editing a form with a block editor an error occurs:
Class 'Str' not found (View: /vendor/area17/twill/views/partials/form/_block_editor.blade.php):4

### Steps to reproduce

Put a block editor in a form and edit the form in the admin-panel.

### Expected result

_block_editor.blade.php contains:
$title = $title ?? Str::title($name);
Works when changed to:
$title = $title ?? \Illuminate\Support\Str::title($name);:

### Versions
 version: 2.5.2
Laravel version: 8.63
PHP version: 7.4.23
Database engine: MariaDB: 10.5.9

**Comment by pboivin** [comment]
Hi @mcouvreur, did you customize your `config/app.php`? 
The `Str` alias is usually declared in there and made available to your Blade views:
https://github.com/laravel/laravel/blob/8.x/config/app.php#L227

**Comment by mcouvreur** [comment]
That was indeed the problem. Thanks for your quick response!
