### ISSUE TITLE
Problem re conditional logic, fields get blanked out when switching (bug?)

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#119]
Hi,

I successfully implemented conditional logic as per https://github.com/area17/twill/issues/39#issuecomment-426067947 - very nice and simple to implement, but I've hit a minor problem with it.

In this instance, I have a radio button that switches between a multi image input and a text input.

If I enter content into one field, and then switch to the other via the radio button and then back to the first again, all the input gets blanked out. This is a bit of a problem as if a user clicks on the radio button by mistake then they'll lose any input they've entered.

Anything I can do about this? Thanks!

**Comment by ifox** [comment]
Hey Seb,

this was on purpose to avoid saving content that is not relevant anymore when switching the value using in the condition, but we also faced use cases where it made sense to keep the existing content, users mistakes being the primary one, so we implemented a solution in d0a92f239c42462734843f6c63e0dc9816134e82. You will be able to use the `keepAlive` option for that once released.

**Comment by sebastianlenton** [comment]
Thanks!
