### ISSUE TITLE
Error creating tabble blocks

### ISSUE THREAD

**Issue by narr07** [area17/twill#120]
I have an error with this message

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `type` varchar(191) not null, `child_key` varchar(191) null, `par' at line 1 (SQL: create table `blocks` (`id` int unsigned not null auto_increment primary key, `blockable_id` int unsigned null, `blockable_type` varchar(191) null, `position` int unsigned not null, `content` json not null, `type` varchar(191) not null, `child_key` varchar(191) null, `parent_id` int unsigned null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by noxify** [comment]
Hi @narr07,

can you give us some more details and maybe some steps to reproduce?

**Comment by narr07** [comment]
+ Apache 2.4.37
  + MariaDB 10.1.37
  + PHP 7.3.0 (VC15 X86 32bit thread safe) + PEAR
  + phpMyAdmin 4.8.4

i use XAMPP

**Comment by ifox** [comment]
@narr07 The JSON table type was introduced in MariaDB 10.0.16 so I'm thinking your application is not trying to migrate to the database server you're thinking it is (which should support JSON since you're saying it is MariaDB 10.1.37). Maybe you have another MySQL server running on your machine?

**Comment by detector-v** [comment]
@ifox Hi
I have similar error

 Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `type` varchar(191) not null, `child_key` varchar(191) null, `par' at line 1 (SQL: create table `blocks` (`id` int unsigned not null auto_increment primary key, `blockable_id` int unsigned null, `blockable_type` varchar(191) null, `position` int unsigned not null, `content` json not null, `type` varchar(191) not null, `child_key` varchar(191) null, `parent_id` int unsigned null) default character set utf8 collate 'utf8_unicode_ci')

**Comment by ifox** [comment]
Hi @detector-v, I'm going to try to reproduce this but I'm really surprised, it should support the JSON type since 10.0.16 🤷‍♂️

**Comment by narr07** [comment]
Oke i'lltry, thanks for your respond

**Comment by sagaio** [comment]
Exactly same issue here, running XAMPP with MariaDB 10.1.38. Found this though which states that json is not supported for MariaDB yet: https://github.com/laravel/framework/issues/13622

**Comment by ifox** [comment]
According to MariaDB documentation, https://mariadb.com/kb/en/json-data-type/, 10.2.7 is the minimum required version. We'll update the docs with our requirements for MariaDB.
