### ISSUE TITLE
Add block validation directive for Blade blocks

### ISSUE THREAD

**Issue by pboivin** [area17/twill#1211]
## Summary

As discussed in https://github.com/area17/twill/discussions/1210, we can leverage the new [`parseMixedProperty()`](https://github.com/pboivin/twill/commit/9c210f6ce539929a4939b4b418f7c8091cee62b7#diff-744ba0dc396079abd7c5ead8e75d70e4e4ea2fcc94f6f765dae60bf4aae8f4d0R245) helper to add a `@twillBlockRules()` directive.

In the process, the `validBlocks` validation rule should be documented.

**Comment by haringsrob** [comment]
An alternative solution could be to continue building on top of https://github.com/area17/twill/pull/1308 to allow to enter the validation rules in a $rules property together with a validate method?

**Comment by haringsrob** [comment]
This is now in 2.x beta
