### ISSUE TITLE
Tags will not save

### ISSUE THREAD

**Issue by chrisssthomas** [area17/twill#1215]
## Description

Tags will not persist to the database when I include them in my modules form submission.

### Steps to reproduce

Add the `HandleTags` trait to my modules Repository class
Add `@formField('tags')` to my modules form.blade.php

### Expected result

When entering tags into the form field and updating the module, this would save to the db.

### Actual result

When entering tags into the form field and updating the module, this does not save to the db, no errors occur.

### Versions

Twill version:  2.0 
Laravel version: 8.54 
PHP version: php:7.4-fpm-alpine running in Docker 
Database engine: MySQL

**Comment by chrisssthomas** [comment]
@pboivin apologies I gave the incorrect version in my initial bug report, I am also on 2.5.2

**Comment by haringsrob** [comment]
Hello @chrisssthomas,

I also had a quick look on 2.6.0 and also there all seems fine.

I think you did, but you have to actually click on the tag in the dropdown to make it active and highlighted in grey:

<img width="350" alt="Screenshot 2022-01-05 at 14 26 22" src="https://user-images.githubusercontent.com/866743/148225012-df31a70b-da0b-493f-9363-96df6fd94fca.png">

**Comment by haringsrob** [comment]
Hey @chrisssthomas,

I am closing this as there has not been a reply for a while so I assume things are fine.

If you still encounter the issue, please provide some more examples of how to reproduce.

Kind regards,
