### ISSUE TITLE
config fn usage in config

### ISSUE THREAD

**Issue by AidasK** [area17/twill#1228]
## Description
`config()` function should not be used in config files as it creates uncertainty if config is already loaded properly. It should be replaced with env() calls.

https://github.com/area17/twill/blob/2.x/config/glide.php#L14

**Comment by pboivin** [comment]
Hi @AidasK, I agree this is a very good general advice. In this case though, the config loading order is deterministic (see [TwillServiceProvider](https://github.com/area17/twill/blob/2.x/src/TwillServiceProvider.php#L226)). If you have some time to explore this, a PR would be very much welcome :)
