### ISSUE TITLE
Refactor Twill Settings

### ISSUE THREAD

**Issue by pboivin** [area17/twill#1238]
## Summary

A number of issues with Settings have been reported over time. This groups all previous issues under a single one:

- [ ] https://github.com/area17/twill/issues/606
- [ ] https://github.com/area17/twill/issues/895
- [ ] https://github.com/area17/twill/issues/939
- [ ] https://github.com/area17/twill/issues/590
- [ ] https://github.com/area17/twill/issues/1342

**Comment by haringsrob** [comment]
This should also include: #1342

- [ ] Allow browser fields in settings

**Comment by razvaniacob** [comment]
Any progress on some of this issues?

**Comment by ifox** [comment]
Hi @razvaniacob, singleton modules are a much better approach to create settings pages if you are limited by those issues on settings. We're going to tackle them but they are not our highest priority at the moment. They will be right next after the 3.0 release as indicated by the project roadmap.

**Comment by razvaniacob** [comment]
I can't find any documentation on this.

**Comment by ifox** [comment]
It was just merged last week, you can find it [here](https://github.com/area17/twill/blob/2.x/docs/src/crud-modules/cli-generator.md#singleton). The docs site will be updated lated today.

**Comment by haringsrob** [comment]
I think all this comes down to is making some helpers, maybe an interface, a generator command and documentation.

We also have to think about refactoring old settings, or providing a guide to do so. Maybe we can automate, I don't really know.

**Comment by haringsrob** [comment]
Closing. this as the implementation is done in https://github.com/area17/twill/pull/1796
