### ISSUE TITLE
How to customize permalink / slug

### ISSUE THREAD

**Issue by noxify** [area17/twill#125]
Hi,

is it possible to customize the shown permalink in the form?

Currently it shows only the slug based on the given title.
![image](https://user-images.githubusercontent.com/521777/50106634-ab788980-0230-11e9-963f-60d7bed497b7.png)

But since this the title is not a unique value and the permalink will be updated each time my plan was to add a unique identifier to the url e.g. the ID.

I know it's a bit tricky, because the permalink is also shown in the create modal.
Not sure how user friendly it is to disable the possibility to change the title in the edit form.

Thanks!

**Comment by ifox** [comment]
Hi @noxify, happy 2019!

Sorry for the delay in responding here, I took a short break between the holidays.

This link is dynamically displayed by combining a prefix, customizable from the controller as you identified in other issues like #126, and a generated slug from the create modal. When using the `HasSlug` trait, the full history of slugs is stored in database, with a boolean column indicating the active one. We're using this information in our codebases to redirect users to the currently active slug when they reach an old url, previously shared on a social network for example. This is great for SEO and simply very convenient for CMS users that do not have to worry about asking to setup redirects for shared links. Using the `forSlug` helper from a module's repository automatically adds a `redirect` boolean property to the found record.

There are definitely other use cases though. Not wanting CMS users to edit a record title being one, for seeded pages for example that makes perfect sense and for that the `editableTitle` variable can be set to false in the form data. Twill also supports things like preventing users from deleting a specific record by accessing a `canDelete` attribute. Many little options that are worth documenting and I'm hopeful 2019 will see another major improvement there, but I invite everyone to read Twill's source code as you might find interesting options to match your needs!

**Comment by noxify** [comment]
Hi @ifox,

Thanks a lot for this detailed explanation!
Now it makes sense for me and I will close this issue.

Thanks again and happy new year to you, your family and your team!



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by arkid** [comment]
I think the solution here is very useful : https://spectrum.chat/twill/help/modify-permalink-url-format~c2526b31-a2e1-40f5-9dc9-4fc3a9d9a131
