### ISSUE TITLE
Permalinks not working for modules without localization

### ISSUE THREAD

**Issue by IllyaMoskvin** [area17/twill#1255]
## Description

After updating to Twill v2.5.2, we noticed that all of our permalinks to the frontend in the CMS have gone missing.

We tracked down the issue to this block:

https://github.com/area17/twill/blob/030554dd02ae36d35381b55fc73d1ff4996ddcd5/frontend/js/components/TitleEditor.vue#L109-L111

I'm not sure if this is a bug in Twill or something in our end, but we don't use translations for any of our modules, and all of our slugs are just strings, not objects with strings keyed by locale. We fixed the problem on our end with the following patch:

```diff
diff --git a/frontend/js/components/TitleEditor.vue b/frontend/js/components/TitleEditor.vue
index b3175ea1df832abc4b7e917a22da243101050e93..f62e73a2b0b10c160139710b269dd72b94e78619 100755
--- a/frontend/js/components/TitleEditor.vue
+++ b/frontend/js/components/TitleEditor.vue
@@ -107,7 +107,8 @@
         return titleValue || this.warningMessage
       },
       permalink: function () {
-        return this.fieldValueByName('slug')[this.currentLocale.value]
+        const slug = this.fieldValueByName('slug') ? this.fieldValueByName('slug') : ''
+        return typeof slug === 'string' ? slug : slug[this.currentLocale.value]
       },
       ...mapState({
         baseUrl: state => state.form.baseUrl,
```

This mirrors what is being done to `title` right above this block.

I noticed that permalinks are an area of current development according to the [CHANGELOG](https://github.com/area17/twill/blob/2.x/CHANGELOG.md), so I figured it might be best to let you know about this issue sooner rather than later, even if I don't fully understand the root cause. 😅 

### Steps to reproduce

Upgrade to Twill from v2.4.0 to v2.5.2.

### Expected result

Permalink appears.

### Actual result

Permalink does not appear.

### Versions

Twill version: 2.5.2
Laravel version: 8.67.0
PHP version: 7.4.24
Database engine: 13.4

**Comment by pboivin** [comment]
Hi @IllyaMoskvin, thanks for reporting this issue!

This is not something I've experienced myself but I'm looking into it, trying to reproduce with different configurations.

Did you customize anything related to slugs in your project? I'm thinking of `HasSlug` and `HandleSlug`, primarily.

As far a I can tell, slugs are always stored with a `locale` in the DB, even in single language contexts. Similarly, the `slug` field should make it into the Vuex store as `{ 'en': 'My Slug' }` (in the context of an English-only config). 

When you get a change, I'm curious to know if you can confirm this on your project. A simple test would be to toggle "view source" in the browser, on the module's Edit page. Then, near the bottom, you should see something equivalent to this:

```
if (fieldToStore) {
    window['TWILL'].STORE.form.fields.push({
        name: 'slug',
        value: {
            'en': "Lorem ipsum"
        }
    })
}
```

**Comment by IllyaMoskvin** [comment]
Hi @pboivin, thanks for the quick response.

We do not extend `HasSlug` or `HandleSlugs`. I've confirmed that this check gets called:

https://github.com/area17/twill/blob/030554dd02ae36d35381b55fc73d1ff4996ddcd5/src/Models/Behaviors/HasSlug.php#L263-L265

...and `$slug->slug` returns a string. 

    var fieldIndex = window['TWILL'].STORE.form.fields.findIndex(field => field.name === 'slug')
    var fieldToStore = fieldIndex == -1 ? true : false;
    
    if (fieldToStore) {
        window['TWILL'].STORE.form.fields.push({
            name: 'slug',
            value: "nancy-rubins-existing-in-flux"
        })
    }

> Similarly, the slug field should make it into the Vuex store as { 'en': 'My Slug' } (in the context of an English-only config).

Can you show us where this happens? Does the mapping of locales to slugs happen at this stage? Maybe we somehow overwrote the file that's responsible for doing that at some point.

**Comment by ifox** [comment]
Hi @IllyaMoskvin! Quick thought I just had about this issue. Are you using a custom `create.blade.php` partial where the permalink input field is setting `translated` to false?

**Comment by IllyaMoskvin** [comment]
Hi @ifox! Yup, that was exactly it!

We have a `resources/views/admin/partials/create.blade.php`, and when we were cleaning out our manually translated fields from an earlier attempt at localization, we also removed the `'translated' => true` key from the `slug` field there.

Restoring the key results in `{ 'en': 'My Slug' }` being added to the Vuex store as @pboivin described.

Thank you both for the help! We'll set `translated` back to `true` for all `slug` fields in our codebase.
