### ISSUE TITLE
Pages module

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#126]
First of, thanks for sharing your work, it looks amazing!

I am trying to create a pages module, but I am not sure how to go about it.

Documentation states that '_Pages are unstructured data models most often used for static content, such as an About page [...]_', which I understand should not be prefixed with 'pages'. I also don't know how to arrange it in page/subpage/... convention. Do you maybe have any more detailed docs about it?

I will also need pages to have different page templates with different fields. I read #54 and will try to implement it somehow, but I would appreciate if you have any ideas how to do that or where to start?

Also related: is it/or would be possible to implement a sort of addons system. For example a 'pages' addon that would scaffold all of this (tree structure, templates, ...) and leave user to populate template' fields, because it seems like something that a lot of projects requiring CMS would actually need. 

Thanks for your help!

**Comment by zipavlin** [comment]
Thank you @noxify the gists works perfectly! Now, I just need to figure how to make block(s) not flexible (so I don't need to have pages table with 50 columns) and I have everything :)

Your solutions for pages prefix doesn't work in my case, but I might need to try again, as there was no change after implementing either or both of those ($indexOptions, $permalinkBase).

Thanks again for your help, you are awesome! 👍

**Comment by ifox** [comment]
Hi @zipavlin, sounds good!

Docs are open to contributions, the `docs` folder is a [Vuepress](https://vuepress.vuejs.org/) project 🤓

Like I just mentioned on https://github.com/area17/twill/issues/46#issuecomment-452409567, a guides section would definitely makes sense, great suggestion!

**Comment by frixxx** [comment]
Has anyone used this nested module stuff? Is there a way to get nested slugs?

F.e. i have the following items:
- Item A - Nesting Depth 1
   - Item B - Nesting Depth 2

And now i want to have the slug /en/item-a/item-b) for the Item B and /en/item-a for the Item A.
Did anyone do this? Maybe someone could help?

**Comment by amirakbulut** [comment]
> Has anyone used this nested module stuff? Is there a way to get nested slugs?
> 
> F.e. i have the following items:
> 
> * Item A - Nesting Depth 1
>   
>   * Item B - Nesting Depth 2
> 
> And now i want to have the slug /en/item-a/item-b) for the Item B and /en/item-a for the Item A.
> Did anyone do this? Maybe someone could help?

Have you solved this yet?

**Comment by vacoup95** [comment]
> > Has anyone used this nested module stuff? Is there a way to get nested slugs?
> > F.e. i have the following items:
> > 
> > * Item A - Nesting Depth 1
> >   
> >   * Item B - Nesting Depth 2
> > 
> > And now i want to have the slug /en/item-a/item-b) for the Item B and /en/item-a for the Item A.
> > Did anyone do this? Maybe someone could help?
> 
> Have you solved this yet?

Have you solved this yet?

**Comment by layout-lab** [comment]
> 
> 
> > > Has anyone used this nested module stuff? Is there a way to get nested slugs?
> > > F.e. i have the following items:
> > > 
> > > * Item A - Nesting Depth 1
> > >   
> > >   * Item B - Nesting Depth 2
> > > 
> > > And now i want to have the slug /en/item-a/item-b) for the Item B and /en/item-a for the Item A.
> > > Did anyone do this? Maybe someone could help?
> > 
> > 
> > Have you solved this yet?
> 
> Have you solved this yet?

Some time has passed; not sure if anyone else has any input on how to get the nested slugs to work?

**Comment by zipavlin** [comment]
@layout-lab I recently needed pages (nested models). I solved nested slug problem by splitting url path and traversing upstream from last url slug towards its parents. I also rewrote Twill's slug prefix writing to include parent pages. It still needs some work, but I am happy to share my solution when I will be done (I hope I will remember about it).

**Comment by omzy** [comment]
Personally I think this is the killer feature missing in Twill. I know there are workarounds but from my experience it's not perfect (see here: https://spectrum.chat/twill/general/subpage-permalinks~e3c1932b-6a6c-4221-a5a9-70e6b99bf96d). I think there should be native support for multi-level pages and dynamic permalinks built in to Twill.

Often clients just want a quick and straightforward way of adding pages in a parent-child hierarchy, and therefore I tend to lean towards WordPress for that.

Can we expect to have this feature anytime soon?

**Comment by ifox** [comment]
Hey there, I didn't realize there was so much feedback around this missing. The nested-set package has all the functionality embedded to render the tree of pages as needed on the frontend, since each page generates its own slug. The permalink field and link can also be adjusted to render parent pages slugs as the prefix. It is not the most straightforward without better documentation. Our goal is to remove all this manual setup the documentation is currently having you go through and make the feature more robust and first-party in Twill. All that to say this is all possible and I'd love to share a demo that does it but I don't have that at hand right now, at least not something I could easily share. @pboivin and I can work on this soon, we'll keep this thread updated @mikerockett.

**Comment by mikerockett** [comment]
@ifox – thanks so much, looking forward to it! I'll try a manual implementation for the minute.

**Comment by rakeshmali** [comment]
Hi @ifox is this page nesting feature now available? Could you please provide steps to prepare nested pages for frontend?
