### ISSUE TITLE
Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found

### ISSUE THREAD

**Issue by michaeljcoyne** [area17/twill#1263]
Hi From a pretty fresh installation I get:

Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found (mysitedir/twill/vendor/area17/twill/views/partials/form/utils/_blocks_templates.blade.php) 

Seems like the _blocks_templates.blade.php is referencing and old symphony version?

**Comment by pboivin** [comment]
Hi @michaeljcoyne, can you share a bit more information on your configuration?

Twill version
Laravel version
PHP version
DB Engine version

**Comment by michaeljcoyne** [comment]
Hi @pboivin 
Fresh install. 
If you will look in that file you will see it is referencing and old symfony version and that class does not exist.
However for now it is not an issue for me as I fixed the error.
Thanks
