### ISSUE TITLE
Disabled options in select form field

### ISSUE THREAD

**Issue by hb-monah** [area17/twill#1266]
## Summary

Hi,

as far as I can see (please correct me if I'm wrong), there is no way to disable options in the[ select form field](https://twill.io/docs/#select) (like they are displayed but cannot be selected) with Twill v2.5.2. 

## Describe the solution you'd like

Twill's select component `VSelect` uses vue select. Vue Select v3.3+ has the prop `selectable` that determines if an option is selectable or not. Please update vue select to the given version or provide another solution to disable options in the select form field.

Thank you!

**Comment by pboivin** [comment]
Hi @hb-monah thanks for reporting this.

The work of updating to v3 has been started here: https://github.com/area17/twill/pull/674. I believe it will be picked up as part of the Twill 3.x effort.

If you feel comfortable with Vue.js and want to explore this on your end, you can have a look at [`VSelect.vue`](https://github.com/area17/twill/blob/2.x/frontend/js/components/VSelect.vue), which is Twill's wrapper component for `vue-select`.
