### ISSUE TITLE
Dashboard translation?

### ISSUE THREAD

**Issue by Krato** [area17/twill#13]
Hi. First thanks for your awesome package.

Will be useful if you add the dashboard strings as a Laravel syntax so in case we want to translate the dashboard we can use php array files or just the json file.

What do you think?

Regards!

**Comment by ifox** [comment]
Hi @Krato, thanks for your kind works about Twill!

This is definitely in our roadmap. We are working internally right now on defining our next releases and this is going to happen sooner than later so that you can contribute to translating Twill if you're into it!

**Comment by Krato** [comment]
@ifox Sure I will help. 😊

Good Job! 💪🏽

**Comment by eminos** [comment]
@ifox, Speaking of roadmap. Is that something that is or will be public? It would be great to see what the plans are for this project, where it's headed, and also what features it's currently missing (for us who haven't tried it yet).

**Comment by ifox** [comment]
For sure @eminos, we are looking into using the Projects feature here on GitHub to make it public, I'll let you know once it's ready!

**Comment by Leonardo-Max** [comment]
Hello, can I help with a translation to pt-BR :)

**Comment by yanhao-li** [comment]
We now have a PR for doing this: https://github.com/area17/twill/pull/405.
Closing it now.
