### ISSUE TITLE
How to create more user roles?

### ISSUE THREAD

**Issue by milewski** [area17/twill#130]
Hi currently i need more roles than the 3 default available ones, is there any config related for extending the `A17\Twill\Models\Enums\UserRole` ?

**Comment by ifox** [comment]
Hi @milewski, happy 2019! 

Sorry for the delay in responding here, I took a short break between the holidays.

Right now the only way to extend the default enum is to override it using Composer autoloading. I know this is not a good practice per se but until we make this configurable within the codebase this is a perfectly working solution.

In `composer.json`:

```json
"autoload": {
  "classmap": [
    "database/seeds",
    "database/factories"
  ],
  "files": ["app/Models/Enums/UserRole.php"],
  "psr-4": {
    "App\\": "app/"
  },
  "exclude-from-classmap": ["vendor/area17/twill/src/Models/Enums/UserRole.php"]
}
```

In `app/Models/Enums/UserRole.php` (or anywhere else you'd like actually, only the namespace needs to be the same):

```php
<?php

namespace A17\Twill\Models\Enums;

use MyCLabs\Enum\Enum;

class UserRole extends Enum
{
    const CUSTOM1 = 'Custom role 1';
    const CUSTOM2 = 'Custom role 2';
    const CUSTOM3 = 'Custom role 3';
    const ADMIN = 'Admin';
}
```

Finally, in your `AuthServiceProvider` class, redefine [Twill's default permissions](https://github.com/area17/twill/blob/e8866e40b7df4a6919e0ddb368990d04caeb705a/src/AuthServiceProvider.php#L26-L48) if you need to, or add your own, for example:

```php
<?php

namespace App\Providers;

use A17\Twill\Models\Enums\UserRole;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;

class AuthServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Gate::define('list', function ($user) {
            return in_array($user->role_value, [
                UserRole::CUSTOM1,
                UserRole::CUSTOM2,
                UserRole::ADMIN,
            ]);
        });

       Gate::define('edit', function ($user) {
            return in_array($user->role_value, [
                UserRole::CUSTOM3,
                UserRole::ADMIN,
            ]);
        });

        Gate::define('custom-permission', function ($user) {
            return in_array($user->role_value, [
                UserRole::CUSTOM2,
                UserRole::ADMIN,
            ]);
        });
    }
}
```

You can use your new permission and existing ones in many places like the `twill-navigation` configuration using `can`:

```php
'projects' => [
     'can' => 'custom-permission',
     'title' => 'Projects',
     'module' => true,
],
```

Also in forms blade files using `@can`, as well as in middleware definitions in routes or controllers, see [Laravel's documentation](https://laravel.com/docs/5.7/authorization#via-middleware) for more info.

**Comment by nikhiltri** [comment]
Thanks for the great details, @ifox!

Is more robust user permissions something you're planning on building into Twill? Or is the expectation that implementers will customize permissions as they need?
