### ISSUE TITLE
Submitting via enter doesn't reset the unsaved change warning

### ISSUE THREAD

**Issue by freshleafmedia** [area17/twill#1305]
## Description

The warning that shows when you attempt to leave the edit screen with unsaved changes will show up if you just focus on a field without changing it.

Suspect all that is needed is to move an event listener from the submit button to the form submit event but haven't looked into this

### Steps to reproduce

1. Edit a model which has regular text inputs
2. Focus on a field
3. Attempt to leave the page

### Expected result

No 'are you sure you want to leave' confirmation

### Actual result

The 'are you sure you want to leave' confirmation shows

### Versions

Twill version: 2.x-dev (9b276c5)
Laravel version: 8.75.0
PHP version: 8.1.0
Database engine: MySQL 5.7.34

**Comment by pboivin** [comment]
Hi @freshleafmedia, thanks for reporting this.

Unfortunately, I can't replicate the bug following your instructions: pressing enter on an input field and refreshing the page doesn't show the confirmation message.

Although, I've noticed that the following steps do trigger the confirmation message:

1. Edit a model which has regular text inputs
2. Click in one of the inputs to bring focus to it
3. Click out of the input to remove focus from it
4. Attempt to leave the page (without saving)

Does this make sense? Can you replicate it?
