### ISSUE TITLE
Custom language and date formatting 

### ISSUE THREAD

**Issue by maisen20** [area17/twill#1307]
Is it currently not possible to adjust the format of a date when listing the models? For example, the publish date is displayed as "Month Day, Year" (Dec 10, 2021), but I would rather have the German notation "dd.mm.yyyy H:i:s" (10.12.2021 10:00:00).
I am aware that it is possible via an additional function in the model (e.g. getFormattedPublishStartDateAttribute). But unfortunately the publish date is formatted wrong in several areas, for example also when displaying the publish status when editing an entry of the model.

Also, I have not found a way to translate the term "Scheduled" (which appears in various areas in twill) into German. I saw this word is output 1:1 in the Vue app and is not overridable with a custom language, is that correct? 

<img width="1241" alt="Bildschirmfoto 2021-12-13 um 09 38 29" src="https://user-images.githubusercontent.com/25121005/145783214-d7d7e608-ed09-41ea-97c8-c524e3f921e5.png">

**Comment by pboivin** [comment]
Hi @maisen20,

There are a few setting you could tweak in [`config/twill.php`](https://github.com/area17/twill/blob/2.x/docs/.sections/getting-started/configuration.md?plain=1#L163) for publication dates:
```
    'publish_date_24h' => false, // enable 24h format in publisher dates
    'publish_date_format' => 'd F Y H:i', // format used by publication date pickers
    'publish_date_display_format' => 'DD MMMM YYYY HH:mm', // format used when displaying the publication date
```

Another option to explore would be to override the [`serializeDate()`](https://laravel.com/docs/8.x/eloquent-serialization#customizing-the-default-date-format) method on your model:
```
protected function serializeDate(DateTimeInterface $date)
{
    return $date->format('Y-m-d');
}
```

You're right, it seems like the `Scheduled` label and a few others are still hardcoded in the Vue components. If you have some time to help out with this, the text can be translated via the `$trans()` helper method. Here's an example from a previous PR :
https://github.com/area17/twill/pull/954/files#diff-71c652ea6bb1e4909e58793f2d182bcdc5244d33c1ca96c020ad0a7c5fdc70a5R33
