### ISSUE TITLE
Repeater Collapse All Only Works Once

### ISSUE THREAD

**Issue by freshleafmedia** [area17/twill#1330]
## Description

The Collapse all feature for repeaters only works the first time it's clicked, or if items are initially collapsed not at all

### Steps to reproduce

1. Create a block which has a repeater
2. populate the repeater with items
3. Click the Collapse all link
4. Expand the now collapsed items
5. Click the Collapse all link again

### Expected result

Repeated items would be collapsed

### Actual result

Repeated items remain expanded

### Versions

Twill version: 2.x-dev (2523336)
Laravel version: 8.76.1
PHP version: 8.1.0
Database engine: MySQL 5.7.34

**Comment by haringsrob** [comment]
Hey @freshleafmedia,

Thank you for reporting this issue. I have added a pull request with a fix here: https://github.com/area17/twill/pull/1348

Kind regards,
