### ISSUE TITLE
Problem with npm run twill-build command

### ISSUE THREAD

**Issue by mediaboost** [area17/twill#134]
Hi

Impossible to install Twill

> npm doctor
> Check                               Value                           Recommendation
> npm ping                            OK
> npm -v                              v6.4.1                          Use npm v6.5.0
> node -v                             v10.15.0
> npm config get registry             https://registry.npmjs.org/
> which git                           C:\laragon\bin\git\bin\git.EXE
> Perms check on cached files         ok
> Perms check on global node_modules  ok
> Perms check on local node_modules   ok
> Verify cache contents               verified 1723 tarballs

 npm run twill-build

> @ twill-build D:\PROJECT\_server\www\twill
> npm run twill-copy-blocks && cd vendor/area17/twill && npm ci && npm run prod && cp -R public/* ${INIT_CWD}/public

> @ twill-copy-blocks D:\PROJECT\_server\www\twill
> npm run twill-clean-blocks && mkdir -p resources/assets/js/blocks/ && mkdir -p vendor/area17/twill/frontend/js/components/blocks/customs/ && cp -R resources/assets/js/blocks/ vendor/area17/twill/frontend/js/components/blocks/customs

> @ twill-clean-blocks D:\PROJECT\_server\www\twill
> rm -rf vendor/area17/twill/frontend/js/components/blocks/customs/*

> La syntaxe de la commande n’est pas correcte.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ twill-copy-blocks: `npm run twill-clean-blocks && mkdir -p resources/assets/js/blocks/ && mkdir -p vendor/area17/twill/frontend/js/components/blocks/customs/ && cp -R resources/assets/js/blocks/ vendor/area17/twill/frontend/js/components/blocks/customs`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @ twill-copy-blocks script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\MEDIABOOST\AppData\Roaming\npm-cache\_logs\2019-01-03T16_28_04_830Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ twill-build: `npm run twill-copy-blocks && cd vendor/area17/twill && npm ci && npm run prod && cp -R public/* ${INIT_CWD}/public`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @ twill-build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\MEDIABOOST\AppData\Roaming\npm-cache\_logs\2019-01-03T16_28_04_856Z-debug.log

**Comment by ifox** [comment]
Hi @mediaboost,

I see that you are on Windows, please check https://github.com/area17/twill/issues/31#issuecomment-437557464 for potential solutions and feel free to let us now on it goes there.

**Comment by mediaboost** [comment]
YES magic

thank you
