### ISSUE TITLE
Unable to get LQIP data

### ISSUE THREAD

**Issue by freshleafmedia** [area17/twill#1352]
## Description

When attempting to fetch the `lqip_data` field from the database via the `HasMedia->lowQualityImagePlaceholder()` method the transparent fallback is always returned because `$media->pivot` contains everything you'd expect except `lqip_data`

### Steps to reproduce

1. Upload an image
2. Attach the image to something - aka populate the mediables table
3. Generate the LQIP data (`php artisan twill:lqip`)
4. Attempt to read the `lqip_data` via the `HasMedia->lowQualityImagePlaceholder()` method

### Expected result

The value of `lqip_data` is returned from the DB

### Actual result

The `ImageService::getTransparentFallbackUrl()` is retuned

### Versions

Twill version: 2.6.0
Laravel version: 8.78.1
PHP version: 8.1.0
Database engine: MySQL 5.7.34

**Comment by haringsrob** [comment]
Hey @freshleafmedia,

Is this only happening in the editor preview?

Kind regards,
