### ISSUE TITLE
Checkbox input note doesn't appear

### ISSUE THREAD

**Issue by freshleafmedia** [area17/twill#1354]
## Description

If you create a checkbox input and define the note attribute it doesn't appear

### Steps to reproduce

Create a checkbox input like this:

```
@formField('checkbox', [
    'name' => 'checkbox',
    'label' => 'Checkbox',
    'note' => 'I am a note',
])
```

### Expected result

`I am a note` should appear to the right hand side of the field

### Actual result

No note appears

![Screenshot showing checkbox input without a note](https://user-images.githubusercontent.com/10062339/148409556-6a90080e-0c98-4e2c-a89b-65a347d79ec7.png)

### Versions

Twill version: 2.6.0
Laravel version: 8.78.1
PHP version: 8.1.0
Database engine: MySQL 5.7.34

**Comment by haringsrob** [comment]
<img width="265" alt="Screenshot 2022-01-06 at 22 00 28" src="https://user-images.githubusercontent.com/866743/148451335-9968f8d0-ecb2-4bb8-98b5-5d67a1385d2b.png">

@ifox so instead of showing the note above as the documentation mentions I feel it fits better below?

What do you think?
