### ISSUE TITLE
Allow to generate a preview blade file when generating blocks

### ISSUE THREAD

**Issue by haringsrob** [area17/twill#1356]
## Summary

When generating a block using the command `php artisan twill:make:block` add an option parameter or prompt to also generate the preview blade file.

## Describe the solution you'd like

The preview blade file could also contain the demo output of the fields that are in the default block.

Bonus: Do the same for modules?

**Comment by ifox** [comment]
Great idea! Going further in that direction, we should have a command to publish default layouts for full preview and blocks preview.
