### ISSUE TITLE
Repeater always create new row and delete old one.

### ISSUE THREAD

**Issue by yanhao-li** [area17/twill#136]
While using Repeater in the contentField as static content, the repeater's associate module always behave as creating new row and deleting the old one, even when actually update it.

From the best of my knowledge, there may have a slip in the updateRepeater function.

```php
    public function updateRepeater($object, $fields, $relation, $model = null)
    {
        $relationFields = $fields['repeaters'][$relation] ?? [];

        $relationRepository = $this->getModelRepository($relation, $model);

        // if no relation field submitted, soft deletes all associated rows
        if (!$relationFields) {
            $relationRepository->updateBasic(null, [
                'deleted_at' => Carbon::now(),
            ], [
                $this->model->getForeignKey() => $object->id,
            ]);
        }

        // keep a list of updated and new rows to delete (soft delete?) old rows that were deleted from the frontend
        $currentIdList = [];

        foreach ($relationFields as $index => $relationField) {
            $relationField['position'] = $index + 1;
            if (isset($relationField['id']) && starts_with($relationField['id'], $relation)) {
                // row already exists, let's update
                $id = str_replace($relation . '-', '', $relationField['id']);
                $relationRepository->update($id, $relationField);
                $currentIdList[] = $id;
            } else {
                // new row, let's attach to our object and create
                $relationField[$this->model->getForeignKey()] = $object->id;
                unset($relationField['id']);
                $newRelation = $relationRepository->create($relationField);
                $currentIdList[] = $newRelation['id'];
            }
        }

        foreach ($object->$relation->pluck('id') as $id) {
            if (!in_array($id, $currentIdList)) {
                $relationRepository->updateBasic(null, [
                    'deleted_at' => Carbon::now(),
                ], [
                    'id' => $id,
                ]);
            }
        }
    }
```

The below line should always return false if I'm thinking it right. 
```
    if (isset($relationField['id']) && starts_with($relationField['id'], $relation)) {
``` 

For the reason that the `$relationField` will be passed from $formRequest directly, `function getFormFieldsForRepeater` will not be called, thus the id will always be pure integer rather than the `$relation . '-' . $relationItem->id` format.

Can anyone else using Repeaters in their cases confirm this? Thanks in advance!

**Comment by zipavlin** [comment]
@yanhao-li Yeah, this is in fact happening! Did you find a fix for this?

**Comment by ifox** [comment]
I'm looking into this @yanhao-li @zipavlin, thanks for reporting.

**Comment by amrnn** [comment]
I am facing this as well, actually this happens for content blocks too not only repeaters. However, blocks delete old rows permanently, while repeaters soft delete them.

For repeaters I noticed that this method in [getFormData.js](https://github.com/area17/twill/blob/e02b2d4161f9cb8553bf9e385e2ac47f41f51503/frontend/js/utils/getFormData.js#L69-L92) which assigns the formatted id and then immediately overrides it with `Object.assign()`:
```js
        // and lastly we want to keep the id to update existing items
        repeaterBlock.id = repeaterItem.id

        return Object.assign(repeaterBlock, fields)
```

I changed it to this instead:
```js
        Object.assign(repeaterBlock, fields)

        // and lastly we want to keep the id to update existing items
        repeaterBlock.id = repeaterItem.id

        return repeaterBlock
```
And that partially fixed the problem, now old repeater rows get updated correctly but reordering doesn't work. I'm using a position field which gets set correctly on the model but twill doesn't seem to be using it in the frontend.

**Comment by amrnn** [comment]
To get reordering working I just had to sort the repeaters by `position` in the `getFormFieldsForRepeater()` method:
```php
        foreach ($object->$relation->sortBy('position') as $relationItem) {
            // ...
        }
```

**Comment by zipavlin** [comment]
> And that partially fixed the problem, now old repeater rows get updated correctly

@amrnn this only partly solved issue in my case. Namely: old items (items that existed when page was loaded) were updated as expected. New items (items that were just created) behave as before - but only those.

Did you noticed the same behavior?

**Comment by amrnn** [comment]
Hi @zipavlin,

>  New items (items that were just created) behave as before

I don't understand exactly what you're referring to, new items are supposed to create new rows (but only once) and that's the behavior I see, or are you talking about position issues?

**Comment by amrnn** [comment]
@zipavlin, 
I think the problem you're talking about happens when you add a new item and then save the form multiple times without refreshing the page. This happens because the frontend doesn't seem to update repeater items' ids in vuex store after submitting the form.

**Comment by zipavlin** [comment]
> I think the problem you're talking about happens when you add a new item and then save the form multiple times without refreshing the page

Hey @amrnn, yes, this is exactly the case! :)
