### ISSUE TITLE
Is the link to Twill on admin login page a security issue?

### ISSUE THREAD

**Issue by nikhiltri** [area17/twill#138]
Hello,

Our security team raised the concern that the link to the Twill project and version number on the login page of the admin could be of concern—since a malicious person might use that knowledge to figure out a way to break into the admin.

Do you see that as a concern? What are your thoughts?

Thanks!
nikhil

**Comment by ifox** [comment]
Hi @nikhiltri!

Very interesting question on the subject of [security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity), for which many debates can be read online. As long as obscurity is not used as the main security solution, it can definitely help reducing attacks, but only to a certain extent, as a determined attacker would not be stopped by obscurity.

Right now Twill's version is not displayed on the Login screen, but it is on the Reset password screen. I think it definitely makes sense to remove it from all non logged-in screens, but we think having it displayed once logged-in can prove itself very useful when editors report issues.

Another good mean of obscuring the admin interface, re: #137, is to use a different subdomain/path, something not as common as `admin`.

**Comment by nikhiltri** [comment]
Those are good recommendations!
