### ISSUE TITLE
Can't define crops for block editor's image gallery/media fields

### ISSUE THREAD

**Issue by tsekka** [area17/twill#1395]
## Description
I'm trying to set up crops for block editor's media field, but I cannot overwrite it in config/blocks.php

### Steps to reproduce
1. Go to laravel_base/config/blocks.php
2. Keep only one crop eg. tablet:
``` php
    'crops' => [
        'image' => [
            'tablet' => [
              // ...
            ],
        ],
    ],
```

### Expected result
When inserting image using block editor, I should be able to define crop for "tablet" only.

### Actual result
- I can still define crops for all 3 crop sizes: desktop, media and tablet on admin panel's block editor.
- `return config('blocks.crops');` outputs expected results
```
{
  "image": {
    "tablet": [
      // ...
    ]
  }
}
```
- When I head to laravel_base/vendor/area17/twill/config/blocks.php and do the same changes there, I will get expected results.

### Versions

Twill version:  2.6.0
Laravel version: v8.80.0
PHP version: 8.0

**Comment by ifox** [comment]
Hi @tsekka, the blocks crops config from your application goes in the `twill.php` config file, under the `block_editor` key, so `config('twill.block_editor.crops')`.

**Comment by tsekka** [comment]
Hi, 

My bad, thanks for quick reply.
