### ISSUE TITLE
Block Editor blocks are not rendered in CMS

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#140]
I followed docs, but I cannot get block editor to work in CMS.

- I have 'blocks' table
- Model has 'HasBlocks' trait
- Repository has 'HandleBlocks' trait
- I have run php artisan twill:blocks successfully

This is what I see in CMS after adding a new block:

![capture](https://user-images.githubusercontent.com/5628018/50819979-d6379880-132b-11e9-9f24-6d703b22f7a0.PNG)

And it looks like Vue component is not really rendered:

![capture2](https://user-images.githubusercontent.com/5628018/50820171-4e9e5980-132c-11e9-8883-e2cf734c5581.PNG)

resources/views/admin/blocks/quote.blade.php is
```
@formField('input', [
    'name' => 'quote',
    'type' => 'textarea',
    'label' => 'Quote text',
    'maxlength' => 250,
    'rows' => 4
])
```

resources/views/admin/news (model)/form.blade.php is
```
@extends('twill::layouts.form')
@section('contentFields')
    @formField('block_editor', [
        'blocks' => ['quote']
    ])
@stop
```

config/twill.php is
```
return [
    "block_editor" => [
        'blocks' => [
           'quote' => [
              'title' => 'Quote',
              'icon' => 'text',
              'component' => 'a17-block-quote',
           ],
        ],
    ]
];
```

resources/assets/js/blocks/BlockQuote.vue exists and is exactly like in docs.

I sort of run out of ideas how to solve this.

**Comment by nsivertsen** [comment]
@zipavlin Did you run `npm run twill-build` after generating the blocks with `php artisan twill:blocks`? The artisan script generates the raw Vue components and the npm script then compiles and bundles them up into JS assets that are loaded by the admin panel.

**Comment by zipavlin** [comment]
OK, solved. It was indeed issue with build script on Win 10 and folder structure.
```
-cp -R resources/assets/js/blocks/
+cp -R resources/assets/js/blocks/*
```
in ```"twill-copy-blocks"``` solves it.

See #31 for a complete solution.

**Comment by zipavlin** [comment]
#31

**Comment by rakeshmali** [comment]
I am still having this issue. Using ubuntu 20.04. I have followed all the steps including the npm run twill-build after npm run twill-build after php artisan twill:blocks but still no form is showing in the block. Anyone can please help?

1. Added new block into blocks array in module form:
```
@formField('block_editor', [
    'blocks'    => [
        'testing'
     ]
]
```
            
2. created the block in /resources/views/admin/blocks/testing.blade.php
```
@formField('input', [
    'name' => 'testing',
    'type' => 'textarea',
    'label' => 'Test text',
    'maxlength' => 250,
    'rows' => 4
])
```
5. added the new block into twill config
'content_header' => [
    'title'     => 'Testing',
    'icon'      => 'text',
    'component' => 'a17-block-testing'
],

6. Now run this command: php artisan twill:blocks

7. And then the following command: npm run twill-build

But still the form isn't showing

![Selection_1860](https://github.com/area17/twill/assets/8438390/3d3a0641-dc40-4c8c-99e5-32d6967e4e48)
