### ISSUE TITLE
WYSIWYG Not Saving?

### ISSUE THREAD

**Issue by harveydobson** [area17/twill#1409]
## Description

So I've followed the instructions from the documentation and I can't seem to get the WYSIWYG editor to save.. 

### Steps to reproduce

I create a new module with the following config:

- Block Editor - No
- Translations - Yes
- Slugs - No
- Images - No
- Files - Yes
- Position - No
- Revisions Yes
- Nesting Yes

I then add the following WYSIWYG config to the form.blade.php

```
@formField('wysiwyg', [
    'name' => 'description',
    'label' => 'Description',
    'toolbarOptions' => [
        ['header' => [2, 3, 4, 5, 6, false]],
        'bold',
        'italic',
        'underline',
        'strike',
        ["script" => "super"],
        ["script" => "sub"],
        "blockquote",
        "code-block",
        ['list' => 'ordered'],
        ['list' => 'bullet'],
        ['indent' => '-1'],
        ['indent' => '+1'],
        ["align" => []],
        ["direction" => "rtl"],
        'link',
        "clean",
    ],
    'placeholder' => '...',
    'maxlength' => 1000,
    'editSource' => false,
    'note' => 'Really sell it!',
    ])
```

### Expected result

As there is already a Migration in translation for Description which looks like this:

```
        Schema::create('XXXX_translations', function (Blueprint $table) {
            createDefaultTranslationsTableFields($table, 'XXXX');
            $table->string('title', 200)->nullable();
            $table->text('description')->nullable();
        });
```

I thought it would save to the database without me adding my own $table->text column for the field (as per the documentation).

### Actual result

Every other field is saved to the database apart from this one. 

and even if i add the column in against the main module migration, it is the same

### Versions

Using Laravel Sail

Twill 2.6.0
Laravel 8
PHP 8.1
MySQL 8.0

**Comment by harveydobson** [comment]
For the above, I made a new module from scratch just to check it wasn't anything I had done...  well, as far as I am aware :-/

**Comment by kallefrombosnia** [comment]
Worth asking, do you have column `description` in model `$fillable`?

**Comment by harveydobson** [comment]
Hi @kallefrombosnia 

I do indeed, but thanks very much asking, I did fall into that trap last night but worked it out. 

I think I have actually just cracked my issue.. 

By default the 'description' field is in this array against the module

```
    public $translatedAttributes = [
        'title',
        'description',
        'active',
    ];
```

Which makes sense - however with the WYSIWYG editor, you must have the attribute ` 'translated' => true,` present, otherwise it won't save, even if you have the field defined against your main module. 

So it would look something like this:

```
    @formField('wysiwyg', [
    'translated' => true,
    'name' => 'description',
    'label' => 'Description'
    ])
```
