### ISSUE TITLE
Add 'hidden' attribute to input field

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#143]
[this is a proposition for enhancement not a bug]

Would it make sense to add hidden attribute to 'input' field? It's a minor enhancement:

file: ```vendor/area17/twill/views/partials/form/_input.blade.php```
``` php
@php
    ...
    $hidden = $hidden ?? false;
    ...
@endphp
@if($translated)
    <a17-locale
        type="a17-textfield"
        :attributes="{
            label: '{{ $label }}',
            @include('twill::partials.form.utils._field_name', ['asAttributes' => true])
            type: '{{ $type }}',
            ...
            @if ($disabled) disabled: true, @endif
            @if ($hidden) hidden: true, @endif
            ...
    ></a17-locale>
@else
    <a17-textfield
        label="{{ $label }}"
        @include('twill::partials.form.utils._field_name')
        type="{{ $type }}"
        ...
        @if ($disabled) disabled @endif
        @if ($hidden) hidden @endif
        ...
        in-store="value"
    ></a17-textfield>
@endif
```

Also, sorry for creating so many issues every day. I am actively figuring out my way around Twill :)

**Comment by zipavlin** [comment]
Added a PR for this: #144

**Comment by ifox** [comment]
Hey @zipavlin,

No need to apologize! Please keep it going, we're more than happy to help, and improve Twill along the way.

Do you mind if I ask you which kind of project are you working on with Twill? Feel free to reach out privately on my [Twitter](https:twitter.com/ifox), my DMs are open.
