### ISSUE TITLE
How to add additional data to dashboard

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#146]
Is it possible to show additional data on dashboard?

We are building page where small part of data will be manually updated on a daily basis and I would like to add form for it on dashboard. Data would be stored as settings. Is something like that possible?

**Comment by ifox** [comment]
Hi @zipavlin,

you can take ownership of the dashboard view in your project in your need to add some custom parts to it, by duplicating `vendor/a17/twill/views/layouts/dashboard` into `resources/views/vendor/a17\twill/layouts/dashboard`. Of course that means you'll have to be careful about updating Twill by maintaining this custom view manually. There might be some opportunities to bring your work back into Twill by adding some slots to the original view too, I'd be happy to review.

As for storing data from there, definitely, you'd have to submit that form to a custom route you'd create, from where you should be able to save/retrieve settings "manually".

**Comment by zipavlin** [comment]
@ifox thank you for your help!

> Of course that means you'll have to be careful about updating Twill by maintaining this custom view manually.

This is not really ideal, because I am sure nobody will remember to update our custom dashboard controller in few months :)

> There might be some opportunities to bring your work back into Twill by adding some slots to the original view too, I'd be happy to review.

I will come back to this part after I finish other (more important) parts of this project and I will look into what would make sense.

**Comment by ferpetrelli** [comment]
Hi there,

Thank you for reporting. I will go ahead and close this issue as the original question has been answered. Feel free to open a pull request if you have any contribution.

If you still need support this could be better answered on Twill's [Spectrum channel](https://spectrum.chat/twill).

Thanks.
