### ISSUE TITLE
Adding custom items to navigation array.

### ISSUE THREAD

**Issue by manuelsofia** [area17/twill#147]
Hello,

I was wondering if there is any way to add custom links or items to the primary and the secondary navigation array. In my particular case, I would like to have the ability to add a "download" option in the index view of a module but I can't find the optimal way to achieve this.

Many thanks in advance!

**Comment by amrnn** [comment]
Hi @manuelsofia ,
Add an entry to twill's navigation such as this one:
```php
 'google' => [
   'title' => 'Google',
   'raw' => true,
   'route' => 'https://google.com'
 ]
```
You can see the relevant code that determines nav items' urls [here](https://github.com/area17/twill/blob/185bd5839652dab8b3a375538e43d275cf814183/src/Helpers/routes_helpers.php#L11-L26)

**Comment by manuelsofia** [comment]
Thank you very much @amrnn!
