### ISSUE TITLE
[3.x] Guides to create

### ISSUE THREAD

**Issue by haringsrob** [area17/twill#1482]
- [ ] How to set dynamic data to a block form: https://spectrum.chat/twill/help/pass-data-from-a-view-to-block~94a26d47-26c1-455e-9193-46cc7c2a395b?m=MTU3NzQzODEyODk1Ng==
-> Also we can use blockClasses for this. Methods like "getFormData" just as we do validation.
- [x] Inverse relations using many-many browsers
- [ ] Scheduling content

**Comment by dweerd** [comment]
Hi, I wanted to use scheduling, could you provide some quick steps? Or is the guide almost finished :)?

**Comment by ifox** [comment]
Scheduling only requires you to uncomment the `publish_start_date` and `publish_end_date` columns in the generated migration, or adding them later on, and making sure they are in your model fillable. From there, you can use the `visible` scope in addition to the `published` scope to render only published records in your frontend. Twill's `forSlug` helper already does this for you. For listing pages where you want to pull multiple entries, you can also use the `publishedInListings` scope, that is applying published and visible automatically depending on your fillables.
