### ISSUE TITLE
[Vue warn]: $listeners is readonly

### ISSUE THREAD

**Issue by michaeljcoyne** [area17/twill#1486]
## Description

I have a 3rd party javascript widget (Ti.to) buttton that updates the url. After upgrading to 2.6 to 2.7.0 I get the following error.

### Steps to reproduce

Use a button that updates url trough javascript to load content

### Expected result

Button would load content

Button is not loading content, throws error

[Vue warn]:

``$listeners is readonly.
found in
RouterLink
---> <RouterLink>
       <Anonymous>
         <InlineOverlay>
           <TitoOverlay>
             <Anonymous>
               <Root>``

Button loads content in popup

 2.7.0
 8.83
 7.4
 NA

**Comment by michaeljcoyne** [comment]
https://stackoverflow.com/questions/49936163/routerlink-attrs-is-readonly

**Comment by ifox** [comment]
Hi @michaeljcoyne can you please clarify which url you're updating?

**Comment by michaeljcoyne** [comment]
Front end - sorry. So not sure why router is being used as I am not usering it

**Comment by michaeljcoyne** [comment]
Think this was related to plugin, closing.
