### ISSUE TITLE
Twill 2.8.0-beta.1 Return value of A17\Twill\Services\Blocks\Block::getForType() must be an instance of A17\Twill

### ISSUE THREAD

**Issue by michaeljcoyne** [area17/twill#1489]
## Description

upgrade to Twill 2.8.0-beta.1

Build Twill - look at front end

### Expected result

Site not to break

### Actual result

Return value of A17\Twill\Services\Blocks\Block::getForType() must be an instance of A17\Twill\Services\Blocks\Block, null returned

### Versions

2.8.0-beta.1

 8.83.3

7.4

posgres

**Comment by haringsrob** [comment]
Hey @michaeljcoyne

Thank you for reporting, was this on a clean installation?

Kind regards,

**Comment by michaeljcoyne** [comment]
No

**Comment by haringsrob** [comment]
Hey @michaeljcoyne,

I am having trouble reproducing this issue.

Does this happen on /admin or on the edit page of a specific model?

All information that you can give will help us.

Kind regards,

**Comment by haringsrob** [comment]
@michaeljcoyne if you have this error again, could you send a backtrace here?

**Comment by michaeljcoyne** [comment]
@haringsrob 

I tried upgrading the error and persists.

The gist of it is if I have a browser block previously I would be able to do this on front end.

`@php
    $background = \App\Models\Background::find($item->background_id);
@endphp

@if($background)
{!! $background->renderBlocks() !!}
@endif
`

The render blocks would not throw an error.  I am assuming something has changed in the HasBlocks trait  or something related to this to break this.


Not sure what the easiest way to copy the stack trace out of Debug bar is.

**Comment by michaeljcoyne** [comment]
If I revert 
075aea60c2bc5c04a7e57ccd0f438ee77c83cf42
the error goes away.

**Comment by amsal** [comment]
Hi, I was able to reproduce this one. The error is thrown when a repeater is used inside a block. 

https://github.com/area17/twill/blob/075aea60c2bc5c04a7e57ccd0f438ee77c83cf42/src/Models/Behaviors/HasBlocks.php#L37

The issue is repeater parameter is not passed to getForType method. Hope it helps

**Comment by haringsrob** [comment]
Thanks that helps @amsal 

Fix is here: https://github.com/area17/twill/pull/1518

**Comment by michaeljcoyne** [comment]
Good stuff - forgot to mention it was in a repeater, soz :)
