### ISSUE TITLE
Possible issue with default configuration docs and block media

### ISSUE THREAD

**Issue by broakenmedia** [area17/twill#1499]
Have been wrestling with trying to add media to a block. Various bits of documentation reference adding the 'crops' field to the twill.php config file and to look at the 'Default configuration' page (https://twill.io/docs/block-editor/default-configuration.html)

Nothing was working, the media was never saved on blocks. Until I came across a comment here:

https://github.com/area17/twill/issues/1395#issuecomment-1019282742

Adding the 'block_editor' field immediately solved the issue. Should the default configuration example not have this key also or do they serve different purposes? Either way this comment was the first reference to 'block_editor' I've managed to come across and so probably shows a potential need to tweak something somewhere.

Thank you!

**Comment by broakenmedia** [comment]
Am on Twill 2.7.0 and Laravel 8 fyi. Fresh install.

**Comment by haringsrob** [comment]
Hey @broakenmedia,

This key is now specified in the 3.x docs.
