### ISSUE TITLE
Logout method type

### ISSUE THREAD

**Issue by cardi777** [area17/twill#1500]
## Description

When I hit log out on the top right nav dropdown, laravel says the method is wrong. I gather that It's a GET when it should be a POST?

When I inspect the code twill generates, the logout button is just an A tag:

`<a href="{{ route('admin.logout') }}">{{ twillTrans('twill::lang.nav.logout') }}</a>`

I guess I don't see how a tag like that can be anything but a GET method?

### Steps to reproduce

Log into the cms, hit log out on the top right nav dropdown.

### Expected result

It should log me out and go to the login screen.

### Actual result

`Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException.`
`The GET method is not supported for this route. Supported methods: POST.`

### Versions

```
"require": {
        "php": "^8.0",
        "area17/twill": "^2.7",
        "fideloper/proxy": "^4.4.1",
        "fruitcake/laravel-cors": "^v2.0.4",
        "guzzlehttp/guzzle": "^7.4.0",
        "htmlmin/htmlmin": "^8.0",
        "laravel/framework": "^v8.83.1",
        "laravel/tinker": "^v2.7",
        "laravelcollective/html": "^6.3",
        "spatie/laravel-sitemap": "^6.1",
        "webup/laravel-sendinblue": "^v3.4"
    },

```
Running on PHP 8.1

**Comment by haringsrob** [comment]
Hey @cardi777,

Did you by any chance upgrade twill recently?

It used to be a link but this has changed, perhaps you have published the twill views to customize and did not update them when you updated twill?

**Comment by cardi777** [comment]
Ok cool, i'm sure that's it, i can see the blade files have changed a tad. 

Having difficulty still but sure it's related.

So I need to remove all the published files, then republish, are there more steps when upgrading?

**Comment by haringsrob** [comment]
Great that it is solved!
