### ISSUE TITLE
Translated Block Fields Don't Get Any Visual Validation Feedback

### ISSUE THREAD

**Issue by freshleafmedia** [area17/twill#1508]
## Description

When using the new `@twillBlockValidationRulesForTranslatedFields` directive when a validation error occurs the field doesn't show the usual red border and error message like it does with non-translated fields.

### Steps to reproduce

1. Create a block as follows:

```
@twillBlockTitle('Text')
@twillBlockIcon('text')
@twillBlockValidationRulesForTranslatedFields([
    'text' => 'required',
])

@formField('wysiwyg', [
    'name' => 'text',
    'label' => 'Text',
    'translated' => true,
    'required' => true,
])
```
2. Add the block to an editor but leave it blank
3. Save

### Expected result

![text block with validation feedback](https://user-images.githubusercontent.com/10062339/157754402-cd69e2e3-46e0-4717-98d5-fab3231ba784.png)

### Actual result

![text block without validation feedback](https://user-images.githubusercontent.com/10062339/157754124-c4bb1032-87dd-4a60-bdce-04b5a25cede2.png)

### Versions

Twill version: 2.8.0-beta.1
Laravel version: 8.83.4
PHP version: 8.1.2
Database engine: 5.7.34

**Comment by haringsrob** [comment]
Hey @freshleafmedia just checking, did you run `php artisan twill:update`?

**Comment by freshleafmedia** [comment]
Hi @haringsrob Yes, well Composer ran it for me in the post-update hook. Just tried running it manually and still seeing the same issue

**Comment by haringsrob** [comment]
Ok thank you for checking, will have a look today

**Comment by haringsrob** [comment]
Ok after checking I found that it needed to be recompiled. I will make a new beta release later today.

**Comment by haringsrob** [comment]
Hey @freshleafmedia this should now be fixed in beta 2
