### ISSUE TITLE
Problem with the twill-copy-blocks npm script mentioned in docs

### ISSUE THREAD

**Issue by amrnn** [area17/twill#151]
Hello,

I was having issues getting custom blocks to work, and I believe the problem comes from **twill-copy-blocks** npm script illustrated in the documentation:
```json
  "twill-copy-blocks": "npm run twill-clean-blocks && mkdir -p resources/assets/js/blocks/ && mkdir -p vendor/area17/twill/frontend/js/components/blocks/customs/ && cp -R resources/assets/js/blocks/ vendor/area17/twill/frontend/js/components/blocks/customs",

```
In particular this part:

```sh
cp -R resources/assets/js/blocks/ vendor/area17/twill/frontend/js/components/blocks/customs
```

The problem is that it produces the following directory structure in twill's components (notice the extra **blocks** directory at the end):
`vendor/area17/twill/frontend/js/components/blocks/customs/blocks/`

But the [code](https://github.com/area17/twill/blob/185bd5839652dab8b3a375538e43d275cf814183/frontend/js/main-form.js#L95-L102) that dynamically requires block components expects this directory structure instead:
`vendor/area17/twill/frontend/js/components/blocks/customs/`

Simply adding a glob pattern to the copy command fixed the issue for me:
```sh
cp -R resources/assets/js/blocks/* vendor/area17/twill/frontend/js/components/blocks/customs
```

**Comment by ifox** [comment]
Hi @amrnn,

we've seen this happening depending on the operating system you're running those npm scripts from. We're aware of the issues these npm scripts can cause and are working towards new build scripts, but in the meantime, your fix makes perfect sense, thanks for sharing.

**Comment by galingong** [comment]
I actually had to remove the asterisk in order to get the script working. With the "fix" applied (as per documentation) npm threw an error.

**Comment by ifox** [comment]
Closing this one following the improvements in 1.2.1.  Checkout our [changelog](https://github.com/area17/twill/releases/tag/1.2.1)
