### ISSUE TITLE
Twill packages: Improvements

### ISSUE THREAD

**Issue by haringsrob** [area17/twill#1510]
## Summary

- [x] Allow publishing custom icons
- [ ] Publish block Vue components

## Describe the solution you'd like

This is a follow up of https://github.com/area17/twill/pull/1446 with nice to haves

**Comment by AndreSchwarzer** [comment]
> * [ ]  Allow publishing custom icons

Is #1538 covering what you've intended?

**Comment by ifox** [comment]
Closing this. There are separate discussions about supporting Vue components in packages like in #2285 that will help move this forward.
