### ISSUE TITLE
wrong phpdoc annotation for updateRepeater() and getFormFieldsForRepeater()

### ISSUE THREAD

**Issue by cpfpolkehn** [area17/twill#1511]
## Description

`vendor/area17/twill/src/Repositories/Behaviors/HandleRepeaters.php::updateRepeater()` has the following annotation for the 4th parameter `$modelOrRepository`: 
```
@param \A17\Twill\Models\Model|\A17\Twill\Repositories\ModuleRepository|null $modelOrRepository
```
However you typically pass a string here, e.g.:
```
$this->updateRepeater($object, $fields, 'items', 'AccordionItem', 'accordion-item');
``` 
this causes issues when linting the code with Tools like `PHPStan`, because the given parameter has the wrong type:

```
Parameter #4 $modelOrRepository of method
         A17\Twill\Repositories\ModuleRepository::updateRepeater() expects
         A17\Twill\Models\Model|A17\Twill\Repositories\ModuleRepository|null,
         string given.
```

the same issue holds true for the parameter `$modelOrRepository` of the method `vendor/area17/twill/src/Repositories/Behaviors/HandleRepeaters.php::getFormFieldsForRepeater()` 

### Steps to reproduce

see above

### Expected result

passing a string should be possible via the annotation. If that would be an acceptable solution for you, I will create a PR.

### Actual result

PHPStan does not accept passing a string and one needs to work around this by ignoring this line, e.g.

```php
/** @phpstan-ignore-next-line */
$this->updateRepeater($object, $fields, 'items', 'AccordionItem', 'accordion-item');
```

### Versions

Twill version:  2.7.0.
Laravel version: 8.x
PHP version: 8.1.x

**Comment by ifox** [comment]
This is not an issue anymore in Twill 3 as phpdoc is not used anymore and the string type is allowed. I'm going to close this but would be happy to review a PR targeting the 2.x branch if you would like a new Twill 2 release with that change.
