### ISSUE TITLE
indexTableColumn lables are not translated by default

### ISSUE THREAD

**Issue by crxiu** [area17/twill#1520]
## Summary

indexTableColumn lables are not translated by default

ModuleController->getIndexTableColumns does only use the indexColumns array item title filde directly without translation.

While the only possibility to set this indexColumns is to override the protected member var $indexColumns in my Controller, there is no possibility to access a translation function here.

`   protected $indexColumns = [
        'mycolumnname' => [
         'title' => twillTrans('admin.mycolumnname') // <-- can't be done here(!) twillTrans is not callable yet in the property declaration area of a class
...
`

The workarraound right now is I have to override the ModuleController method in each Controller I want it to happen. (Or create an inbetween Parent class inheritations like: ModuleController < MyAppModuleController < MyController)

For example the workarround could like this.
`    protected function getIndexTableColumns($items)
    {
        $columns = parent::getIndexTableColumns($items);
        array_walk($columns, function (&$column) {
            $column['label'] = twillTrans($column['label']);`
    });
      return $columns;

## Describe the solution you'd like

I would suggest to just use a twillTrans() call when setting the tableColumns['lable'] value in the Module Controller

`            $tableColumns[] = [
                'name' => $columnName,
                'label' => twilTrans($column['title']),...
`

## Additional context
none

**Comment by haringsrob** [comment]
This functionality is improved with Twill 3.x using the new tablebuilder.
