### ISSUE TITLE
Basic drag and drop reordering not working

### ISSUE THREAD

**Issue by ruudbwai** [area17/twill#1522]
## Description

I'm really enjoying Twill, great effort. I'm trying something super basic, with reordering a basic pages module. I have created a module, and pulled in the kalnoy/nestedset package.

### Steps to reproduce
Create a module with nesting.

My page model looks like below - 

```
namespace App\Models;

use A17\Twill\Models\Behaviors\HasBlocks;
use A17\Twill\Models\Behaviors\HasSlug;
use A17\Twill\Models\Behaviors\HasMedias;
use A17\Twill\Models\Behaviors\HasFiles;
use A17\Twill\Models\Behaviors\HasPosition;
use A17\Twill\Models\Behaviors\HasNesting;
use A17\Twill\Models\Behaviors\Sortable;
use A17\Twill\Models\Model;

class Page extends Model implements Sortable
{
    use HasBlocks, HasSlug, HasMedias, HasFiles, HasPosition, HasNesting;

    protected $fillable = [
        'published',
        'title',
        'description',
        'position',
        'body',
    ];
    
    public $slugAttributes = [
        'title',
    ];
    
    public $mediasParams = [
        'cover' => [
            'default' => [
                [
                    'name' => 'default',
                    'ratio' => 16 / 9,
                ],
            ],
            'mobile' => [
                [
                    'name' => 'mobile',
                    'ratio' => 1,
                ],
            ],
            'flexible' => [
                [
                    'name' => 'free',
                    'ratio' => 0,
                ],
                [
                    'name' => 'landscape',
                    'ratio' => 16 / 9,
                ],
                [
                    'name' => 'portrait',
                    'ratio' => 3 / 5,
                ],
            ],
        ],
    ];
}
```

Add the module to the twill nav - my twill-navigation looks like 
```
return [

    'pages' => [
        'title' => 'Pages',
        'module' => true
    ],

];

```
I can then see pages I create added to the dashboard. I create 2 pages. A and B

I can then drag and drop to reorder and UI reports order updated.

On page refresh, order is unchanged. `position` column is never updated in DB.

Same with nesting, `parent_id` in the `pages` table never updates.

### Expected result

Order change to persist on refresh.

I expect the `position` column in `pages` table to update according to new order. 

I expect when nested, the `parent_id` column in the `pages` table to update accordingly.

### Actual result
UI shows the reordering. My network tab shows a successful xhr POST to reorder - http://localhost:9500/admin/pages/reorder

```
{"message":"Page order changed!","variant":"success"}
```
Nothing updates in DB. `position` remains unchanged. `parent_id` remains null even when nested.

On page refresh, order of A and B remains unchanged.

Really sorry, feels like it's something really basic I'm missing? The docs suggested just adding the nestedset package is now enough, and no need for any extras to get reordering/nesting working, but can't seem to see what the problem is. 

If it helps, I'm spinning this up in docker. Mapping port 9500 -> 80.

### Versions
Twill - 2.7.0
Laravel - 8.4.0
PHP - 7.4.16
DB - MariaDB 10.5.5

**Comment by ifox** [comment]
Hi there! Check that your Laravel jobs are being correctly executed or use `sync` as your queue driver to make sure this is not the issue.

**Comment by ruudbwai** [comment]
@ifox that was it! I have my jobs pushed to the DB by default (one place for all my containers to access), and looking at the jobs table, I saw all the reordering jobs `A17\\Twill\\Jobs\\ReorderNestedModuleItems`  queued up. 

That explains it, I can successfully reorder items by starting up my worker containers to process my jobs queue. Using `sync` of course had the same effect and it works!

Sorry again for the silly question...nothing to see here 👀
