### ISSUE TITLE
twill:build errors on staging server

### ISSUE THREAD

**Issue by jheslop25** [area17/twill#1526]
## Description

Hey guys, I'm running into an issue with the twill:build command. 

I have a bunch of custom vue components that my team has written and they work excellently on local envs.
But when we push them to our staging env. and try to get them to compile it blows up. I have attached a screenshot of the output below. 

### Steps to reproduce

I'm not sure if this can be reproduced? But I'm looking for ideas.

We're running Laravel 8 (twill 2.x) on an ubuntu (20.x I believe) server with DO. Right now we're using node 16.x and npm 8.x although the results were the same with node 14 and npm 6.x.

### Actual result

![Screen Shot 2022-03-16 at 5 09 02 PM](https://user-images.githubusercontent.com/36897536/158705861-2cd5e943-a1e1-44b6-875c-dda70b8d1979.png)

**Comment by ifox** [comment]
Hi @jheslop25!

As noted in your screenshot, the npm command is not found. Is it in the user's PATH?

You can always add your custom build to version control to avoid having to build remotely (ignoring it for merges to avoid unnecessary conflicts between team members).

**Comment by domihagen** [comment]
Hey @jheslop25 !
You are running the command with `sudo`. Maybe the root user doesn´t have npm?
Try to run it without sudo or as www-data (or how your user is called that runs your webservers).

**Comment by haringsrob** [comment]
Hey @jheslop25,

Closing this, for now, please make sure that you have checked the above.

If you still run into issue's feel free to reopen or ask in our discord.

Kind regards,
