### ISSUE TITLE
Connected Fields - Not evaluated on page load

### ISSUE THREAD

**Issue by ChrisB-BTL** [area17/twill#1553]
## Description

When using Connected Fields, they do not evaluate on page load. You have to re-selected the toggling field in order for the connected fields to display.

### Steps to reproduce

    `@formField('radios', [
        'name' => 'external',
        'label' => 'Internal Article or External Link?',
        'default' => false,
        'inline' => true,
        'options' => [
            [
                'value' => false,
                'label' => 'Internal Article'
            ],
            [
                'value' => true,
                'label' => 'External Link'
            ]
        ]
    ])

    @formConnectedFields([
        'fieldName' => 'external',
        'fieldValues' => false,
    ])

        @formField('select', [
            'name' => 'author_id',
            'label' => 'Author',
            'options' => $authors,
            'searchable' => true,
        ])

    @endformConnectedFields`

### Expected result

If the field matches the fieldValues on pageload, the connected fields should display.

### Actual result

The connected fields do not display, until the field is interacted with.

**Comment by pboivin** [comment]
Related to : https://github.com/area17/twill/issues/1100

**Comment by ifox** [comment]
Hi @ChrisB-BTL thanks for reporting. This looks like a potential regression, as they are definitely supposed to evaluate on load. Are you sure you are saving the value of the toggling field in database?

**Comment by ChrisB-BTL** [comment]
@pboivin , good spot, my mistake!

**Comment by ChrisB-BTL** [comment]
@pboivin @ifox based on #1100 , I switched the boolean values to 0 / 1, and it works as expected.
