### ISSUE TITLE
Adding an open prop to repeater fields 

### ISSUE THREAD

**Issue by Wins0309** [area17/twill#1570]
## Summary

Hello team! I want the repeater to allow users to configure whether the block starts off opened or closed. As of now, the block is closed by default and no configuration can be done through the props. An example use case would be that a user wants to improve admin UI by showing fields straight off after laoding the page instead of having to click the open content button.

## Describe the solution you'd like

Adding a prop variable "opened" with a boolean value and configuring it in the mounted() function.

**Comment by ifox** [comment]
Hi there! The fact that repeater were closed on creation was a regression that was fixed. The behavior, which we believe is something that works well for editors, is the following:
- opened on create
- opened on page load if the number of blocks/repeaters is less than 5
- closed on page load if more or equal to 5
