### ISSUE TITLE
Translated settings do not save properly

### ISSUE THREAD

**Issue by haringsrob** [area17/twill#1572]
## Description

Translated settings are not saving properly. Only one value is being used.

### Steps to reproduce

Make a setting translatable

### Versions

Twill version:  2.8-rc

**Comment by thingasd** [comment]
It should be caused by the locale__item is not rendered, the payload only contain field with current locale, seems updating in settings is different from regular module.
https://github.com/area17/twill/pull/1350/commits/7df5f7a3302a6d9bb2c527164c790cb699898472

**Comment by haringsrob** [comment]
Great call @thingasd,

So this is most likely caused by https://github.com/area17/twill/pull/1350

I will investigate today to make it compatible.

**Comment by haringsrob** [comment]
Pr is ready: https://github.com/area17/twill/pull/1598
