### ISSUE TITLE
Error on preview when using Capsules (2.8-rc.1)

### ISSUE THREAD

**Issue by sauron** [area17/twill#1573]
## Description

After installing 2.8-rc.1 the application started returning an error when trying to preview a Capsule with revisions and translations.
The error is raised because in the `ModuleRepository` we are trying to access the repository of a Capsule as an Array

```php
    $capsule['repository']
```

We have a method that can return the Repository from a capsule like in `ModuleController`

```php
    TwillCapsules::getCapsuleForModel($model)->getRepositoryClass()
```

But in the `ModuleRepository` when trying to preview, the `getModelRepository` function is called and we are returning an Array:

```php
protected function getModelRepository($relation, $modelOrRepository = null)
{
...
    $capsule = TwillCapsules::getCapsuleForModel($modelOrRepository);

    if (blank($capsule)) {
        throw new Exception("Repository class not found for model '{$modelOrRepository}'");
    }

    return App::make($capsule['repository']);
}
```

And in TwillCapsules the definition of the `getCapsuleForModel` returns a Capsule object:
```
public function getCapsuleForModel(string $model): Capsule
```

### Versions

Twill version: 2.8-rc.1
Laravel: ^8.54
PHP: 8.08
DB: Mysql

**Comment by haringsrob** [comment]
Hey @sauron,

This is now in 2.x, I think we can make a new rc later today.

**Comment by sauron** [comment]
Works like a charm!

Thanks for the fix @haringsrob!
