### ISSUE TITLE
[3.x] Use bigInt by default

### ISSUE THREAD

**Issue by haringsrob** [area17/twill#1585]
I think we can remove the configurability of this to always use bigIncrements/bigInteger? Or are there drawbacks to this?

```php
if (!function_exists('twillIncrementsMethod')) {
    /**
     * @return string
     */
    function twillIncrementsMethod()
    {
        return config('twill.migrations_use_big_integers')
            ? 'bigIncrements'
            : 'increments';
    }
}

if (!function_exists('twillIntegerMethod')) {
    /**
     * @return string
     */
    function twillIntegerMethod()
    {
        return config('twill.migrations_use_big_integers')
            ? 'bigInteger'
            : 'integer';
    }
}

```

_Originally posted by @haringsrob in https://github.com/area17/twill/issues/1484#issuecomment-1088379379_

**Comment by ifox** [comment]
We could, however this will be creating more work to migration existing codebases as you might have created tables on Twill 2 with integers that would potentially be a problem when related to new module that use big integers. I may be making up that one, but I'd like to make sure we don't create such a breaking change just yet.

**Comment by haringsrob** [comment]
Somehow I expect bigInt to be compatible with int as it always allows for more data. But I will test this out first.

**Comment by haringsrob** [comment]
@ifox,

After checking, when a new field is bigInt and an old one is int, it seems to work just fine.

So removing the integer and increments in favour of bigIncrements, bigInteger should not result in compatibility issues.

**Comment by ifox** [comment]
Thanks so much for checking @haringsrob, let's move forward!

**Comment by haringsrob** [comment]
Pr is ready https://github.com/area17/twill/pull/1600
