### ISSUE TITLE
Browser doesn't indicate checked items initially

### ISSUE THREAD

**Issue by amrnn90** [area17/twill#159]
As you can see in the image below, the first checkbox should be selected. But there's an inconsistency between its `value` and `initialValue`. Things start working properly once I click on some checkboxes, but initially they're all always unchecked.

![screenshot from 2019-01-18 18-51-17](https://user-images.githubusercontent.com/38134195/51397697-cea99800-1b52-11e9-917d-a8000dcd4d64.png)

I believe the problem comes from [getBrowserTableData()](https://github.com/area17/twill/blob/3fd1aae817586baeef35c86b2645840591eae313/src/Http/Controllers/Admin/ModuleController.php#L877-L885) in *ModuleController.php*:

```php
            return [
                'id' => $item->id,
                'name' => $name,
                'edit' => moduleRoute($this->moduleName, $this->routePrefix, 'edit', $item->id),
                'endpointType' => $this->moduleName,
            ] + $columnsData + ($withImage && !array_key_exists('thumbnail', $columnsData) ? [
                'thumbnail' => $item->defaultCmsImage(['w' => 100, 'h' => 100]),
            ] : []);
```
And similar code in [getFormFieldsForBrowser()](https://github.com/area17/twill/blob/3fd1aae817586baeef35c86b2645840591eae313/src/Repositories/ModuleRepository.php#L493-L505) in *ModuleRepository.php*:
```php
            return [
                'id' => $relatedElement->id,
                'name' => $relatedElement->titleInBrowser ?? $relatedElement->$titleKey,
                'edit' => moduleRoute($moduleName ?? $relation, $routePrefix ?? '', 'edit', $relatedElement->id),
                'endpointType' => $relatedElement->getMorphClass(),
            ] + (classHasTrait($relatedElement, HasMedias::class) ? [
                'thumbnail' => $relatedElement->defaultCmsImage(['w' => 100, 'h' => 100]),
            ] : []);
```
Notice the inconsistency that happens when returning the `endpointType` field, one method returns the module name, while the other returns the morph class. Is there any reason for this?

**Comment by ifox** [comment]
This inconsistency in the code has been fixed. Please open a new issue if you are still seeing something wrong with browser fields.
