### ISSUE TITLE
[3.x]  Add type hinting, parameter hinting

### ISSUE THREAD

**Issue by haringsrob** [area17/twill#1599]
Make most methods, functions etc php8.0 standard

**Comment by sloniewski** [comment]
I second that, method should have defined signatures

**Comment by haringsrob** [comment]
https://github.com/rectorphp/rector/blob/62e856362bcb2f407f0c27ae1529cc8da531e65c/docs/rector_rules_overview.md 

AddPropertyTypeDeclarationRector

**Comment by ifox** [comment]
@haringsrob should we keep this open or are we good for now and will add more as we go in the future?
