### ISSUE TITLE
Where does the list of blocks come from?

### ISSUE THREAD

**Issue by nikhiltri** [area17/twill#160]
Hey Twilleographers,

I'm trying to apply sorting to this list:

<img width="297" alt="screen shot 2019-01-18 at 5 48 16 pm" src="https://user-images.githubusercontent.com/1613175/51418735-d49b7b00-1b4a-11e9-8ba5-0324e1549b11.png">

It appears to be in the same order as what's defined in the form views:

```
    @formField('block_editor', [
        'blocks' => [
            'paragraph', 'image', 'video', 'gallery', 'media_embed', 'list',
            ...
        ]
    ])
```

What I want is to find where this list gets pull before it's output to the admin UI so I can sort it differently. Where does that happen?

Thanks!
nikhil

**Comment by sauron** [comment]
Hey @nikhiltri,

The lists gets pull from your definition of the list of blocks on the form as you mentioned; if I understand your question correctly.
You can change the order and it will be displayed as you entered.
e.g:
```php
@formField('block_editor', [
        'blocks' => [
            'paragraph', 'image'
        ]
    ])
```
Will display _Paragraph Block_ first.
and 
```php
@formField('block_editor', [
        'blocks' => [
            'image', 'paragraph'
        ]
    ])
```
Will display _Image block_ first.

If you are displaying all the available blocks, 
```php
@formField('block_editor')
```
then the order will be given by the list of blocks inside _*config/twill.php*_

Let me know if that helps.

**Comment by nikhiltri** [comment]
Hey @sauron,

I see that the order is taken from the definition in the `@form_field` in the Vue. What I’m actually looking for is a universal way to order these options in the UI regardless of their order in the `@form_field` block. 

Where can I apply a custom ordering before this list gets displayed in the UI?

Thanks!
nikhil

**Comment by sauron** [comment]
Hey @nikhiltri,

There is no universal way of sorting the blocks.

The main order is given by the definitions of the Blocks in the _*config/twill.php*_ file.
If you use the generic render of blocks, 
```@formField('block_editor')```

You'll receive the list of blocks as entered in the configuration.
<img width="299" alt="screen shot 2019-01-19 at 10 55 32" src="https://user-images.githubusercontent.com/114308/51427739-f1cb5a80-1bd9-11e9-86de-b64024b8f761.png">
<img width="380" alt="screen shot 2019-01-19 at 10 55 59" src="https://user-images.githubusercontent.com/114308/51427741-f4c64b00-1bd9-11e9-84e6-2642c36857c9.png">

As you may noticed, that list gets overwritten by the definition on your ```'blocks' => ...``` and that sets the order.

If you want to reuse the same set of blocks with the same order in different forms, you can create a helper for that.
For example I'll add a new array _pages_blocks_ to the ```config/twill.php``` file.
e.g:
```php
    'block_editor' => [
        'block_single_layout' => 'layouts.block',
        'block_preview_render_childs' => false,
        'blocks' => [
            'quote' => [
                'title' => 'Quote',
                'icon' => 'text',
                'component' => 'a17-block-quote',
            ],
            ...
        ],
        'pages_blocks' => [
            'artworks','paragraph', 'image', 'video', 'media_embed', 'list',
            'child_pages', 'accordion', 'membership_banner', ...
        ]
        ...
```
And then you can access that array with:
```php
config('twill.block_editor.pages_blocks')
```
Adding a new helper file for example BlockEditor.php with a function for returning that array.
```php
<?php
namespace App\Helpers;

class BlockEditor {
  public static function getPagesBlocks()
  {
    $config = config('twill.block_editor.enabled_blocks');
    return $config[$location];
  }
}
```
And call that function on the form like:
```php
    @formField('block_editor', [
        'blocks' => \App\Helpers\BlockEditor::getPagesBlocks()
    ])
```

I hope that helps.

Best.

**Comment by nikhiltri** [comment]
Ahh, that makes sense. I’ll give that a try. Thanks!
