### ISSUE TITLE
Twill 2.8 producing 500 errors whenever rendering of local uploaded images is required by Glide

### ISSUE THREAD

**Issue by arkid** [area17/twill#1602]
Whenever I am in a form with an image field that has already had an image selected or when I go into the media browser I am now getting 500 errors.

Running over this the trace starts as follows... 
{
    "message": "Not a valid path.",
    "exception": "InvalidArgumentException",
    "file": "D:\\wwwroot\\fb2019\\vendor\\league\\glide\\src\\Urls\\UrlBuilder.php",
    "line": 73,
    "trace": [
        {
            "file": "D:\\wwwroot\\fb2019\\vendor\\area17\\twill\\src\\Services\\MediaLibrary\\Glide.php",
            "line": 113,
            "function": "getUrl",
            "class": "League\\Glide\\Urls\\UrlBuilder",
            "type": "->"
        },
       }

I've gone to the getUrl() glide function and checked the value that it is sending to parse_url().  I can confirm that path is invalid and this change occurred between Twill 2.7 to 2.8.

Here is the function...

```
public function getUrl($path, array $params = [])
    {
        $parts = parse_url($this->baseUrl.'/'.trim($path, '/'));
		
        if ($parts === false) {
            throw new InvalidArgumentException('Not a valid path.');
        }

        $parts['path'] = '/'.trim($parts['path'], '/');

        if ($this->signature) {
            $params = $this->signature->addSignature($parts['path'], $params);
        }

        return $this->buildUrl($parts, $params);
    }
```

The problem is $this->baseUrl.

On twill 2.7 that contained a value of "/storage".

Now with twill 2.8 its "http:///storage" which is clearly wrong.   I'm using local storage.  

This seems related to [this commit](https://github.com/area17/twill/pull/1545/commits/ab4b86023f21fee289ee8dd2654ed8d5930ac3c9) that was part of 2.8.     

My glide setup in the twill.php config is as follows:

```
'glide' => [
		'base_url' => '',
		'base_path' => 'storage/',
    ],

```

My setup:
Twill 2.8
Laravel 6.20.44
PHP 7.4.1

**Comment by haringsrob** [comment]
Hey @arkid,

I have a fix ready for this. May I ask why specifically you have this set to an empty string instead of the default?

**Comment by arkid** [comment]
Hi thanks for the fast response. This is an old site install that has been running 2/3 years.   Why I can't say.  What is the default / what would you recommend I set it to ?

**Comment by haringsrob** [comment]
Removing it will make it default to APP_URL which should work fine. We will add the fix nonetheless, but you might want to try it out.

**Comment by arkid** [comment]
Ah ok great thank you yes I can see that works, panic over.   Thanks again!
