### ISSUE TITLE
Error after access to admin dashboard

### ISSUE THREAD

**Issue by Bassem-mistu-digital** [area17/twill#1622]
when i access to /admin to get dashboard page, i get this error : 

Error retrieving credentials from the instance profile metadata service. (cURL error 7: Failed to connect to 169.254.169.254 port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/) (View: /var/www/html/vendor/area17/twill/views/layouts/dashboard.blade.php).

 Any help plz

**Comment by ifox** [comment]
Hi @Bassem-mistu-digital, set your media and file library environment variables to use the local storage driver using:
```
MEDIA_LIBRARY_ENDPOINT_TYPE=local
FILE_LIBRARY_ENDPOINT_TYPE=local
```

By default Twill 2 is expecting S3 credentials. We are changing this to be local by default in Twill 3 to avoid this confusion.

**Comment by Bassem-mistu-digital** [comment]
@ifox thank you bro. you save my day
