### ISSUE TITLE
Browser field inside repeater

### ISSUE THREAD

**Issue by nsivertsen** [area17/twill#164]
Hey again,

another question that has come up is whether one can have a browser field inside a repeater (not in a block, directly on a module).

I'm guessing one would need one Twill module for the repeater items and a pivot table for the relationships between the repeater items and the module referenced in the browser field?

Would I have to do anything special to save the browser relationship (apart from what one normally does for browser fields directly on a module)?

My use case is that I want a "Credits" repeater on articles, where each row has a "Role" text field and a "Person" browser field.

Maybe there are more idiomatic ways of solving this Twill?

As always, thank you!

**Comment by ifox** [comment]
Hi @nsivertsen,

I confirm this should be working correctly when implemented like you described (saving browser items from the repeated module's repository).

Your use case is definitely something we solve using repeaters as well, however I feel like we could provide a simpler repeater field that does not enforce creating another module. Being a module allow for complete flexibility and better data organization but I think there are use cases where a JSON column would make sense, like you identified in #162.

**Comment by zipavlin** [comment]
Hey, @nsivertsen could you elaborate on how you solved this at the end? I have a very similar issue where I need to assign a 'role' to relationship.

**Comment by ifox** [comment]
Closing as this is definitely possible. Our upcoming updates to the documentation include implementation details for each form field and compatibility with its context (form, block, repeater, repeater in a block, settings).
