### ISSUE TITLE
Quill link issue

### ISSUE THREAD

**Issue by iedex** [area17/twill#1640]
Hi,
Is here a problem?
https://github.com/area17/twill/blob/b32623b59c5bee4094f072419fed33067698cbe6/frontend/js/libs/Quill/QuillConfiguration.js#L138-L144
I noticed that links to the same site has target="_blank"
Value of `window['TWILL'].STORE.form.baseUrl` is `'https://domain.com/{language}/{preview}/pages/'`
Thank you!

**Comment by haringsrob** [comment]
Hey @iedex 

Thank you for reporting this, there indeed seems to be an issue, a fix is added in https://github.com/area17/twill/pull/1649
