### ISSUE TITLE
Medias field not loading in content editor

### ISSUE THREAD

**Issue by tijsbakker** [area17/twill#1652]
## Description

The media field, and any other fields present in the same block, are not loaded in the content editor. Console shows: TypeError: $parent.blockFieldName is not a function

### Steps to reproduce

Add any block containing a medias field to a block_editor form field and navigate to the content editor in the CMS.

### Expected result

The medias field is expected to be loaded within the content editor.

### Actual result

The medias field isn't  loaded within the content editor.

### Versions

Twill version: 2.8.2 (fresh install)
Laravel version: 9.2
PHP version: 8.1
Database engine: MySQL

**Comment by ifox** [comment]
Hi @tijsbakker, this seems to be a regression in 2.8.3, can you please try by setting your version to 2.8.2 in your composer.json file, `composer update`, followed by the `twill:update` command to get the 2.8.2 compiled assets?

**Comment by tijsbakker** [comment]
Hi, @ifox thanks for the quick reply. And yes indeed, it seems that 2.8.2 does not have this problem.

**Comment by tijsbakker** [comment]
The console does show: TypeError: Cannot read properties of undefined (reading 'forEach'), but the medias field works.

**Comment by haringsrob** [comment]
Hey @tijsbakker,

I checked this but could not find an issue directly. I did notice the console error and made a fix for that.

Is this wat is not working? Just so that I have a good understanding.

![Screen Recording 2022-05-23 at 07 31 18](https://user-images.githubusercontent.com/866743/169750091-08303dff-e05c-41db-9adb-0ff70b899dde.gif)

**Comment by haringsrob** [comment]
Hey @tijsbakker,

I just release version 2.8.4 which has a bugfix for this issue.

**Comment by tijsbakker** [comment]
Hey @haringsrob,

I overlooked your response, my apologies, but great … I'm going to try it right away! thanks :)
