### ISSUE TITLE
Vue build error

### ISSUE THREAD

**Issue by OoBook** [area17/twill#1661]
## Description
Hi, I've checked the last release(2.8.4). Because of not seeing any update about frontend/js/store/modules/config.js file, I want to tell about a issue. This file causes chunk-common.js created after both twill:build and twill:dev commands to fail.

I removed 2.line from frontend/js/store/modules/config.js, so that line
```
publishDateDisplayFormat: window[process.env.VUE_APP_NAME].STORE.config.publishDateDisplayFormat
```
eventually error is fixed. But this approach is not of my kind.
### Expected result

shouldn't give an error like that.

### Actual result

chunk-common.js file gives the error following
```
Uncaught TypeError: Cannot read properties of undefined (reading 'publishDateDisplayFormat')
```

### Versions

Twill: v2.8.3

Laravel: v.8.8

**Comment by haringsrob** [comment]
Hey @OoBook,

Am I right that you have custom js/vue components in your site?

Did you start the upgrade after 2.8.3?

Kind regards,

**Comment by OoBook** [comment]
> Hey @OoBook,
> 
> Am I right that you have custom js/vue components in your site?
> 
> Did you start the upgrade after 2.8.3?
> 
> Kind regards,

Yeap, I do.  After upgrading to 2.8.3, it gave an error on the first build after the upgrade, but not related to custom vue components.

Kind regards,

**Comment by haringsrob** [comment]
Hey @OoBook,

I reverted a (potentially related) change (introduced in 2.8.4) with the latest 2.8.5 release.

Could you have another shot at it with the latest release?

**Comment by OoBook** [comment]
It's not solved after upgraded to v2.8.5. Same expression remains at same line. I think that you need to analyze _window[process.env.VUE_APP_NAME].STORE.config_ attribute, because _config_ attribute is not assigned to  _window[process.env.VUE_APP_NAME].STORE_ anywhere.

**Comment by ifox** [comment]
Hi @OoBook, it definitely is, here: https://github.com/area17/twill/blob/308d4e393de6ff5b05c36f9b69facfc113ae8cbd/views/layouts/main.blade.php#L85.

Make sure you are keeping layouts up to date if you published them, or simply don't publish them if you are not making any modifications.

**Comment by OoBook** [comment]
Hi @ifox, thanks so much. I thought that the problem is in vue environment, but I was wrong. It is solved at now.
