### ISSUE TITLE
Browser Item missing edit after save and refresh

### ISSUE THREAD

**Issue by thingasd** [area17/twill#1662]
## Description

After saving browser, the currentItem edit missing, cannot click to edit item

### Steps to reproduce

Select Item from browser, save and refresh

### Expected result

Clickable Item go to edit page
![image](https://user-images.githubusercontent.com/29519267/170661831-b6594d00-cf46-4c0c-95ab-f0e1e88f7eab.png)

### Actual result

After saving and refresh, item missing edit, cannot click
![image](https://user-images.githubusercontent.com/29519267/170661966-00d38384-e503-4d04-9f19-9751968aa81e.png)

### Versions

2.8.0

**Comment by ifox** [comment]
Hi @thingasd, how are you saving and retrieving this browser data? You either need to specify a `routePrefix` when doing so with the route group your browser module is in, or implement `getAdminEditUrlAttribute()` on your browsed model.

**Comment by thingasd** [comment]
> Hi @thingasd, how are you saving and retrieving this browser data? You either need to specify a `routePrefix` when doing so with the route group your browser module is in, or implement `getAdminEditUrlAttribute()` on your browsed model.

Thanks Quentin, implementing getAdminEditUrlAttribute() works perfectly. But I am curious about the difference in the way of retrieving edit url in these methods. If I don't need a custom admin edit url, is this better to use moduleRoute instead of adminEditUrl?

https://github.com/area17/twill/blob/2.x/src/Repositories/Behaviors/HandleBrowsers.php#L159
https://github.com/area17/twill/blob/2.x/src/Http/Controllers/Admin/ModuleController.php#L1391
'edit' => moduleRoute($moduleName ?? $relation, $routePrefix ?? '', 'edit', $relatedElement->id)

https://github.com/area17/twill/blob/2.x/src/Repositories/Behaviors/HandleBrowsers.php#L183
 'edit' => $relatedElement->adminEditUrl
