### ISSUE TITLE
Removing repeater field with an image won't delete mediables

### ISSUE THREAD

**Issue by manuelsofia** [area17/twill#167]
Hello :)

I have a repeater field with an image and a text. I can perfectly add and remove the fields and everything work as expected. However, if I remove one of the repeater rows and save, the mediables created are not being deleted which is highly inconvenient as I can't remove the image from the media library later on because it says the image is in use. Is this a bug or is there anything I can do to avoid this issue?

Thank you very much

**Comment by ifox** [comment]
Hi @manuelsofia,

this is a bug, thanks for reporting. This is due to the fact that repeaters records are soft deleted. There are other open issues regarding repeaters (#136 #128) which I'll be looking at in the next couple of days.

**Comment by manuelsofia** [comment]
Thank you very much @ifox. Do you suggest any particular approach on my side to achieve this while there's no official fix released?

**Comment by toddvalentine** [comment]
Any progress on these repeater issues?

**Comment by ifox** [comment]
Lots of repeaters issues were fixed in Twill 1.2.2, [check it out](https://github.com/area17/twill/releases/tag/1.2.2)!

**Comment by ifox** [comment]
@haringsrob let's check of this is resolved with #1365.

**Comment by haringsrob** [comment]
Hey @ifox ,

I just checked:

- Create a repeater with a media field.
- Add the repeater to a block
- Add a block, then add the repeater with media
- Delete the repeater 
- ✅  db clean

- Create a repeater with a media field.
- Add the repeater to a block
- Add a block, then add the repeater with media
- Delete the block with repeater 
- ✅  db clean

**Comment by haringsrob** [comment]
This is actually already ok on 2.x
