### ISSUE TITLE
When editing an Attribute using the EditInModal the translated title field is not appearing.

### ISSUE THREAD

**Issue by sauron** [area17/twill#1674]
## Description

When editing an Attribute using the EditInModal the translated title field is not appearing.
<img width="998" alt="Screen Shot 2022-06-02 at 17 23 48" src="https://user-images.githubusercontent.com/114308/171731781-81668a13-218d-4586-9ead-20f347b2baf3.png">

On the other hand when creating a new one, it works as expected.

<img width="1060" alt="Screen Shot 2022-06-02 at 17 23 39" src="https://user-images.githubusercontent.com/114308/171731692-292c7430-3ae2-419b-99ec-2fa3fa7fb0e5.png">

Also if there is a customized `create.blade.php` file, all other fields that are not the Title, are showing up correctly

### Steps to reproduce

Create a new Attributes module.
Enable the `editInModal` in the controller.
```php
protected $indexOptions = [
        'editInModal' => true,
    ];
```
Add a new record, this will display the form properly.
Edit the record, the Title field will not appear.

So far I've only tried with a Translated title field.

### Versions

Twill: 2.8.5 
Laravel: 8.54  
PHP: 8.0.5  
MYSQL

**Comment by haringsrob** [comment]
Hey @sauron,

Thank you for reporting, a fix has been added in https://github.com/area17/twill/releases/tag/2.8.6

Kind regards,
