### ISSUE TITLE
@twillRepeaterTitleField gets echoed if below @twillRepeaterTrigger in repeater.blade.php file

### ISSUE THREAD

**Issue by S-ami** [area17/twill#1733]
## Description

`@twillRepeaterTitleField('heading', ['hidePrefix' => true])` gets echoed if the line is below `@twillRepeaterTrigger('...')` in repeater.blade.php file:

```PHP
@twillRepeaterTitle('Item')
@twillRepeaterTitleField('heading', ['hidePrefix' => false])
@twillRepeaterTrigger('Add Item')
```
This happens only if the options ( `['hidePrefix' => true]` ) are there

Screenshot:
![Screenshot 2022-07-10 163639](https://user-images.githubusercontent.com/1745059/178149416-f2bb3293-a28d-49d3-ae10-8108c3b83e6a.png)

Doesn't matter if other fields are below mentioned lines

### Versions

Twill version: 2.8.8
Laravel version: 8.83
PHP version: 7.4

**Comment by haringsrob** [comment]
Just curious, does the same happen when using double quotes?

**Comment by S-ami** [comment]
> Just curious, does the same happen when using double quotes?

Yes

**Comment by haringsrob** [comment]
Hey @S-ami,

I tested this with the same php and twill version and laravel 8.x everything displays fine.

Could you double check the twill version you are using?

If you still cannot manage a minimum reproducible repo could help us find the issue.

**Comment by S-ami** [comment]
> Hey @S-ami,
> 
> I checked with the same setup but I cannot reproduce the issue.
> 
> repeater:
> 
> ```
> @twillRepeaterTitle('Task')
> @twillRepeaterTitleField('title', ['hidePrefix' => false])
> @twillRepeaterTrigger('Add Task')
> 
> @formField('input', [
>     'name' => 'title',
>     'label' => 'Title',
>     'translated' => true,
> ])
> ```
> 
> <img alt="Screenshot 2022-07-11 at 10 08 37" width="1036" src="https://user-images.githubusercontent.com/866743/178218041-59ab5308-d73c-4daf-86a5-8ab612b3c49e.png">
> 
> There's not many things I can think of what could cause this but check:
> 
>     * A different name for your repeater
> 
>     * Double check the Twill version is 2.8.8
> 
> 
> If possible please provide us with a minimal reproducible repository that we can use to debug the issue.

Try switching the second and third line in repeater file
