### ISSUE TITLE
Translated Input fallback is not showing properly

### ISSUE THREAD

**Issue by thingasd** [area17/twill#1753]
## Description

For translatable fields, when current language do not have an input, it should show the fallback locale using translatedInput(). However, when the field once being filled and saved, fallback locale will not work.

### Steps to reproduce

https://user-images.githubusercontent.com/29519267/180354327-a0c5d7f6-4e32-4b3d-8393-4eeb1ecb4729.mp4

### Versions

Twill version:  2.8.8

**Comment by ifox** [comment]
Hi @thingasd did you correctly configure laravel-trnaslatable for the fallback to render?

**Comment by thingasd** [comment]
> Hi @thingasd did you correctly configure laravel-trnaslatable for the fallback to render?

@ifox I think it is correctly configured. The fallback show properly if the alternate locale never get filled and empty.

**Comment by haringsrob** [comment]
Hey @thingasd 

When you set     `'use_property_fallback' => true,` in you `translatable.php` it should work without changes.
