### ISSUE TITLE
npm twill-build not working on laradock

### ISSUE THREAD

**Issue by freeyland** [area17/twill#177]
verb `which` failed    'Error: not found: python\n    at getNotFoundError (/var/www/twill/vendor/area17/twill/node_modules/which/which.js:13:12)\n    at F (/var/www/twill/vendor/area17/twill/node_modules/which/which.js:68:19)\n    at E (/var/www/twill/vendor/area17/twill/node_modules/which/which.js:80:29)\n    at /var/www/twill/vendor/area17/twill/node_modules/which/which.js:89:16\n    at /var/www/twill/vendor/area17/twill/node_modules/isexe/index.js:42:5\n    at /var/www/twill/vendor/area17/twill/node_modules/isexe/mode.js:8:5\n    at FSReqCallback.oncomplete (fs.js:159:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error 
...

**Comment by luislavena** [comment]
Hello @freeyland, I've no past experience with Laradock, but seems that the containers might be missing `python`, which is required to compile some extensions (most likely node-sass).

[This](https://github.com/laradock/laradock/issues/1898) [appears](https://github.com/laradock/laradock/issues/1238) to be reported several times in Laradock GitHub repository. Can you check if one of those provides answers to your issue?

Cheers.

**Comment by freeyland** [comment]
@luislavena Your were correct. I had to enable python in .env of laradock
thanx!!
