### ISSUE TITLE
Command twill:module with option --hasNesting(-N) throws "option does not exist" error

### ISSUE THREAD

**Issue by aljazromih** [area17/twill#1771]
## Description

When creating a module the option --hasNesting(-N) is not supported anymore?
It throws **'The "-N" option does not exist.'** / **'The "--hasNesting" option does not exist.'**

### Steps to reproduce

I tried all of the following examples:
`php artisan twill:module Page -N`
`php artisan twill:module -N Page`
`php artisan twill:module Page --hasNesting`
`php artisan twill:module --hasNesting Page`

### Versions

Twill version:  2.8.8
Laravel version: v9.20.0
PHP version: 8.0

**Comment by ifox** [comment]
Hi @aljazromih, try with `twill:make:module`.

**Comment by haringsrob** [comment]
Hey @aljazromih I have pushed a pr to fix the docs. This will be released in the short future.

**Comment by aljazromih** [comment]
Great, thank you :)
