### ISSUE TITLE
How to get tags

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#178]
I added HandleTags trait to repository and field to form template. The field is rendered and tags are saved. I just don't know how to actually get tags now or even better how to get all items with specific tags.

Thanks! :)

**Comment by zipavlin** [comment]
OK, never mind I figured it out 😄 

For future self:
1. add ```use HandleTags;``` to model repository
2. add ```@formField('tags')``` to form.blade.php
3. get tags with ```model->tags```
4. use ```model::withTag([])``` to get all items with tags

@ifox we (I) need guides/recipies in docs so I can stop writing self-closing issues! :stuck_out_tongue: 😊

**Comment by awgul** [comment]
Hey @zipavlin 
I tried that and I just get error:
Call to a member function count() on null (View: T:\www\mm\vendor\area17\twill\views\partials\form\_tags.blade.php)

**Comment by arkid** [comment]
As a reference for others, do NOT do any of the following as they will stop it from working and cause errors...

- do NOT add  'name' => 'description' to the tag field you add to your view file.
- do NOT add a column in your database for this field, its handled by the 'tags' tables twill creates on install.
- do NOT add a fillable for tags inside of your model file.
