### ISSUE TITLE
Slug get modified automatically when reordering item in self-nested modules

### ISSUE THREAD

**Issue by thingasd** [area17/twill#1784]
## Description

When reordering item nested, the target slug get modified automatically according to the title.

### Steps to reproduce

https://user-images.githubusercontent.com/29519267/185088187-601f0841-5739-45dd-9232-92dfc502e836.mp4

### Expected result

The slug should not get modified/updated.

### Actual result

The slug is modified according to the title.

### Versions

2.x

**Comment by denis-gorin** [comment]
Hi, this behavior is repeated also in models without self-nesting feature.

**Comment by ifox** [comment]
This should be fixed in Twill 3.1, but feel free to reopen an issue if you are still experiencing this.
