### ISSUE TITLE
[3.x] Column 'name' does automatically create link to edit

### ISSUE THREAD

**Issue by S-ami** [area17/twill#1795]
If there is an index column `name`, it automatically becomes a link to module edit route.
If I understood correctly, this happens from JS frontend code and should be fully controllable from backend and `getIndexTableColumns()` function

[Link to Discord message](https://discord.com/channels/811936425858695198/811986149064441927/1014546649181335653)

Twill 3.0.0-alpha1

**Comment by haringsrob** [comment]
Disable the automatic linking and make it form builder only.

**Comment by haringsrob** [comment]
May be related/solve with https://github.com/area17/twill/issues/1761
