### ISSUE TITLE
The setup process as described does not work

### ISSUE THREAD

**Issue by rokde** [area17/twill#18]
The installation steps in the documentation does not work with the provided examples. The created module is not routable, because Route::module('resource') can not resolve the right Controller at the created path.
Nothing is running locally. Maybe it is a problem with the used sub domain, but no url from the route:list is accessible without any exception screen.

Please fix your documentation at the setup process.

Used package version constraint is: `^1.1`

**Comment by ifox** [comment]
Hi @rokde! Thanks for reporting your issue.

However, our examples do not contain something looking like `Route:: module('resource')`.

Module names should be plural in route definitions. Our example are `Route::module('yourPluralModelName')` or `Route::module('people')`.

I guess you also created the module using the singular form of the name you want it to have. It is in our roadmap to make sure that the input of our artisan command is automatically pluralized to avoid the confusion.

Working with plural and singular forms of a model depending on context is a convention you'll come across a lot with Laravel.

**Comment by rokde** [comment]
No, I created a module named projects and this does not work with your generator. Theroute resolver tries to find it in an administration folder, but was created in a level above.

**Comment by ifox** [comment]
I'm sorry @rokde but "this does not work" is not enough for me to help you out. Any steps to reproduce? Feel free to share your repository if possible.

The folder your module's controller should have been created in is `admin`, not `administration`.

I see no reason for it to be created above, see this code in our generator:

https://github.com/area17/twill/blob/4d58468db4c2aec3bcbb7ed8c8de3dfb78c5240b/src/Commands/ModuleMake.php#L195-L212

**Comment by ifox** [comment]
Hi @jamais, we're sorry to see that your introduction to Twill hasn't been successful. We are currently working on many documentation improvements .

Your specific error is not really helping as this is usually another underlying error that is caught by the exception handler.

What do you mean by an installer like Worpdress? Wordpress is a blogging platform and a packaged solution, you can unzip a directory or use their installer and be ready to go to install a theme and create content (posts and pages). Twill is not opinionated and does not provide you with predefined content types. Everything is up to you. I agree that we could make the setup more seamless and improve docs (which we are) but you'll eventually need to set it up in code like any other Laravel package.

**Comment by vishalVDevmurari** [comment]
@ifox 
Same problem here, 

My route:list as below,
 admin.192.168.0.14/demotwill/public/ | GET|HEAD  | http://192.168.0.14/demotwill/public/admin/login                | admin.login.form                                                       | A17\Twill\Http\Controllers\Admin\LoginController@showLoginForm                | web,noDebugBar,guest     

When i visited http://192.168.0.14/demotwill/public/admin/login it's "NotFoundHttpException".

But when i check i can not found any folder with name "A17", vendor folder contains "area17".
so is there problem with "A17\Twill\Http\Controllers\Admin\LoginController@showLoginForm"

i install it in fresh laravel, complete all step as documentation but no luck to get working, Can you please help to fix this?

**Comment by vishalVDevmurari** [comment]
@ifox, 
Is valet is functionality or hardly required for twill? I think it should not.
