### ISSUE TITLE
Edit form doesn't load

### ISSUE THREAD

**Issue by bastienrobert** [area17/twill#180]
I'm following the documentation to add Twill (1.2.*) on a fresh install (php ^7.1.3 & laravel 5.7.*).

For now, I only set these env values on the .env: 
```
MEDIA_LIBRARY_ENDPOINT_TYPE=local
MEDIA_LIBRARY_LOCAL_PATH=uploads/
FILE_LIBRARY_ENDPOINT_TYPE=local
FILE_LIBRARY_LOCAL_PATH=uploads/
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Local
```

And I setup the database to use sqlite3.

No problem with the installation, everything is going well. I've my administration credentials but when I'm trying to access to the dashboard settings, (it redirects me to `http://admin.localhost:8000/users/1/edit` but) the form is never appearing. The loader never stops. When I look at the DOM, the fields seem to be well generated. 

![image](https://user-images.githubusercontent.com/14930937/52412996-9ad1ea80-2ae0-11e9-83e1-52ca293e5664.png)

I think it's a DOM error. Here is the logs in the JS console.

![image](https://user-images.githubusercontent.com/14930937/52413043-b63cf580-2ae0-11e9-80cc-ee6183411e6c.png)

```
Uncaught SyntaxError: Unexpected token &

Uncaught TypeError: Cannot read property 'medias' of undefined
```

**Comment by bastienrobert** [comment]
Ok, I found the bug. In the `form.blade.php` layout, the line:

`published: {{ json_encode(isset($item) ? $item->published : false) }},`

returns `&quot;0&quot;`

So, I migrate my db from sqlite to postgresql. It works.

**Comment by benmacgowan** [comment]
I have just run into this issue when publishing my application to a production environment. Does anyone have any fixes other than @bastienrobert migrating from sqlite to postgresql?

**Comment by bastienrobert** [comment]
I'm now using MariaDB, still no problem. The issue seems to come from sqlite.

**Comment by benmacgowan** [comment]
@bastienrobert Must also be an issue with mysql as that is what I am using. Hesitant to have to migrate as I have populated over 100 records on local with no issues, its only when I publish to the production environment.

**Comment by ifox** [comment]
Hi @benmacgowan, MySQL shouldn't be the issue here. Can you share more about your error? Do you have something in your Laravel log? In the browser console?

**Comment by benmacgowan** [comment]
Hi @ifox 

Browser console shows the following whenever loading the edit form (for all modules):

![](https://monosnap.com/image/O1gYG8teQcjBflkXGAA5T9WpD2Poa9.png)

Nothing seems to be appearing in the Laravel logs.

**Comment by bastienrobert** [comment]
Yep, got exactly the same under SQLite but I don’t have this issue anymore with maria 🙃

**Comment by adelinferaru** [comment]
Hi! I also have the same error but it is not related to MySQL. In my local machine it is working just fine. The error appeared after I published on the server (cloudlinux, MariaDB 10.1.38, PHP 7.2 - cPanel).

As you probably know .. cPanel has the public_html folder so I have created another folder on the account root where I have uploaded everything except the "public" folder ... The "public" folder contents I have uploaded to the "public_html" folder in my cPanel account. I have done all necessary changes to reflect the new public_path() ... and everything is working fine both in frontend and the Twill's admin ... except the "EDIT" form. I can create new models ... but the edit part is same as @benmacgowan reported.

Chrome's reported error in vendor.js:

```
var d, p = {
            state: {
                crops: window.STORE.medias.crops || {},
                types: window.STORE.medias.types || [],
                type: "image"
```,

The page however has a <script/> tag where "window.STORE.medias.crops" is initialized. So I do not know where to look.
Anybody got this fixed? Thank you!

**Comment by ifox** [comment]
What sounded like it wasn't a DB issue actually ended up being one for Ben. The charset of the DB he exported from was different from the DB he imported it in. Ben ended up setting up a server through Forge. But you should be able to match charset on both environments. Can you confirm you imported your database and didn't set it up through fresh Laravel migrations?

**Comment by adelinferaru** [comment]
Hi Quentin! I confirm I did mysql import. I have exported it from my local dev and imported on the prod server... both using utf8mb4_unicode_ci collation.

**Comment by ifox** [comment]
Ok! Can you share a gist of the HTML source of your edit page?

**Comment by adelinferaru** [comment]
https://gist.github.com/adelinferaru/8da35fb5d0edfcdda3bbf6b1c7c745fd

**Comment by adelinferaru** [comment]
I have sent you to your email address more info.

**Comment by adelinferaru** [comment]
Hi .. again! I think I've found the issue ... at least for me ... In the blade template twill/layouts/form.blade.php there are some JS  ojects that are initialized like below:

```
window.STORE.publication = {
        withPublicationToggle: {{ json_encode(($publish ?? true) && isset($item) && $item->isFillable('published')) }},
        published: {{ json_encode(isset($item) ? $item->published : false) }},
```

Please notice:  {{ json_encode ... is using **{{** instead of **{!!**  therefore the single quote is encoded to &quote; in the generated html page... and the error breaks loose afterwards....

Hope this is helpful for somebody.

**Comment by vacoup95** [comment]
Can someone help me? I have the exact same issue. I exported the database from one server to another (both MySQL) and now I am getting this error. Setting it to {!! doesn't fix the problem for me. It just sets all of my languages to green. Even though they are 0 in the database.

**Comment by bsnbsn** [comment]
Hey guys,

I ran into the same issue like @adelinferaru when I was deploying from dev to prod. The error message was a little different: `TypeError: window.STORE is undefined`. First i tried @vacoup95 solution but nothing changed. I also checked the collation. All good.

In the end, I was able to fix the problem with the help of this comment.: https://github.com/area17/twill/issues/180#issuecomment-488345322

Don't know if there is a relation, but the hoster which I have to use provide only mysql 5.6 so I was forced to use longtext instead of json.

**Comment by nkorent** [comment]
> Hi .. again! I think I've found the issue ... at least for me ... In the blade template twill/layouts/form.blade.php there are some JS ojects that are initialized like below:
> 
> ```
> window.STORE.publication = {
>         withPublicationToggle: {{ json_encode(($publish ?? true) && isset($item) && $item->isFillable('published')) }},
>         published: {{ json_encode(isset($item) ? $item->published : false) }},
> ```
> 
> Please notice: {{ json_encode ... is using **{{** instead of **{!!** therefore the single quote is encoded to &quote; in the generated html page... and the error breaks loose afterwards....
> 
> Hope this is helpful for somebody.

I had this exact issue. Replacing the {{ with {!! on json_encode methods fixed the thing.
@ifox maybe take a look?

**Comment by sandeepkapri** [comment]
Its because **getLanguageLabelFromLocaleCode()** in _vendor\area17\twill\src\Helpers\i18n_helpers.php_ 
is using **ucfirst** in line 74 **ucfirst(Locale::getDisplayLanguage($code, $code))**.

Note that 'alphabetic' is determined by the current locale.
 For instance, in the default "C" locale characters such as umlaut-a (ä) will not be converted.


So when **$code** is 'zh-Hans' i.e. chinese simplified, it got translated by **Locale::getDisplayLanguage($code, $code)** to **"中文"** but **ucfirst** makes it **b"Ä¸­æ–‡"** .

In simple words its i18n error. Function **getLanguageLabelFromLocaleCode($code, $native = false)** can't get Language label from locale code.

@shabaz-ejaz Meanwhile you can change 2nd parameter to false on **line 56**: 
'**label' => getLanguageLabelFromLocaleCode($locale, true)**  in _vendor\area17\twill\views\users\form.blade.php_.



@ifox Please Fix it.

**Comment by IllyaMoskvin** [comment]
After upgrading past [Twill 2.0.0](https://github.com/area17/twill/blob/2.x/CHANGELOG.md#blocks-and-frontend-build-workflow), where this was introduced:

> We also namespaced our inline javascript variables to prevent any conflict in the global window moving forward. [..] You should update to `window.TWILL.STORE` and `window.TWILL.vm` or even better, using `window.{{ config('twill.js_namespace') }}` instead of directly using `window.TWILL` if you are in a Blade file and `process.env.VUE_APP_NAME` if you are in a Vue file.

I made the changes suggested above, but the admin still wasn't loading, even after running `twill:build`. I had this error:

> TypeError: window.STORE is undefined

Running `view:clear` fixed the issue. It looks like an old `layouts/main.blade.php` got cached. `twill:build` calls `twill:update`, which runs `cache:clear`, but it seems like that might not be enough in some cases?

**Comment by ifox** [comment]
Thanks for reporting @IllyaMoskvin, I think it would definitely make sense to include a `view:clear` in the Twill build/update flow.

**Comment by Heqma** [comment]
I have this same problem.. i need to refresh 30 times to see edit form.. for now i only configured library.. 
Laravel v8.49.2 (PHP v7.4.15) + Twill 2.4.0

**Comment by LuxusMEDIA** [comment]
Same problem as @Heqma here. Any solutions yet?
