### ISSUE TITLE
Cannot add Link or Text Align buttons to Tiptap WYSIWYG editor

### ISSUE THREAD

**Issue by Tom-revere** [area17/twill#1805]
## Description

I am trying to add a link button and a text align button to the Tiptap editor, however they are not added.

### Steps to reproduce

Add a WYSIWYG field:

```php
@formField('wysiwyg', [
    'name' => 'content',
    'label' => 'Content',
    'type' => 'tiptap',
    'toolbarOptions' => [
        'bold',
        'italic',
        'clean',
        'underline',
        'link',
        ["align" => []],
        [ 'header' => [1, 2, 3, 4, 5, 6, false] ],
        ['list' => 'ordered'], 
        ['list' => 'bullet'],
        ['script' => 'sub'],
        ['script' => 'super'],
    ],
])
```

### Expected result

These buttons should be added, as they do with the Quill editor.

### Actual result

They are not added.

### Versions

Twill version:  2.8.8
Laravel version:  9.26.1
PHP version: 8.0.11

**Comment by nickcheek** [comment]
I know this works

['align' => ['center']]

I haven't tried others

**Comment by nickcheek** [comment]
['align' => ['center']]

**Comment by ifox** [comment]
Align has been added to Tiptap in #2305
