### ISSUE TITLE
Cloning repeater item inside a block editor results with duplicated item's form fields empty.

### ISSUE THREAD

**Issue by tsekka** [area17/twill#1818]
## Description

When repeater is inside a block editor, the "duplicate" action does not work as expected. New repeater item will be pushed but it's form fields are empty.

### Steps to reproduce

1. Define a block editor with repeater block.
2. Add new repeater item & fill it's form fields.
3. Duplicate the field.
[Download example video.](https://onedrive.live.com/?authkey=%21AH9EGHPvUAkbBnE&cid=3955D15A2F99EAB4&id=3955D15A2F99EAB4%21730822&parId=3955D15A2F99EAB4%21730821&o=OneUp)

### Expected result
New, duplicated repeater item should have form fields filled with same content as the item that was duplicated. 

### Actual result
All form fields of new, duplicated repeater item are empty.

### Versions

Twill version: 2.9.0
Laravel version: 9.26.1
PHP version: 8.1.5
Database engine:

**Comment by ptrckvzn** [comment]
I can reproduce this bug and made a block Table [here](https://github.com/ptrckvzn/twill-app/tree/bug/block-repeater-duplicate) with nested Row > Column repeaters.
