### ISSUE TITLE
Single word naming in module cause problems

### ISSUE THREAD

**Issue by Equruler** [area17/twill#182]
Simple.
When generating module using single word for example:
php artisan twill:module messages

the string generated in app\Http\Controllers\Admin\MessageController.php
```
protected $moduleName = "Messages";
```
which is starting with capital letter, and this will make revision and preview functions down as the url is not "Message" but "message"
\vendor\area17\twill\src\Http\Controllers\Admin\ModuleController line:973

Not sure this problem is happening in other files.

Thank you for your hard work.

**Comment by ifox** [comment]
Hi @Equruler!

I assume you have a typo in your message here and you meant to say that you ran the following command: `php artisan twill:module Message`, right?

What end up in the moduleName variable is basically your command input.

We do have an open issue and conversation about this on #71, so I'll close this one if you don't mind, feel free to follow up there.
