### ISSUE TITLE
Files in JsonRepeaters

### ISSUE THREAD

**Issue by davidfaber** [area17/twill#1838]
Hi there,

I'm trying to use a files-field and a media-field within a json-repeater, but I can't get this to work.

All the other fields get saved and displayed correctly.

Is there anything special, I'm not seeing or is this simply not possible?

Thanks in advance,
David

**Comment by haringsrob** [comment]
I will double check, but json repeaters afaik do not support files or media.

**Comment by davidfaber** [comment]
Hi @haringsrob,

Thanks for the quick response. That's a bummer and would be an awesome feature.

Maybe, if I get to know Twill better and feel comfortable on how things work in the background I'll give it a go.

Thanks for your work on Twill. Just doing my first project with it and I love it.

The documentation could use some more work, but maybe I'll start contributing there.

Have a nice day,
David

**Comment by haringsrob** [comment]
@davidfaber what you can do alternatively is use a second block editor that you limit to one block type. Block editors support all fields.

**Comment by haringsrob** [comment]
Same issue as with https://github.com/area17/twill/issues/2102

Closing this as there are alternatives to make this work.

**Comment by kfina-planxy** [comment]
It seems only displaying the file is not working in the current version.
I have tested it with an inline repeater with Media + File and
- Medias work completely
- For Files, saving works, at least I get an entry in the json, called "file[de]" see below. Only after reloading the page it doesn't show the saved file.

So the fix should only require reading the correct field in the json.

```[
	{
		"id": 1720420492204,
		"is_repeater": false,
		"medias": {
			"file[de]": [
				{
					"id": 1,
					"name": "abstract_-_44385-(720p).mp4",
					"src": "\/storage\/uploads\/5c29fece-1afe-49da-8a60-92764730f83f\/abstract_-_44385-(720p).mp4",
					"original": "\/storage\/uploads\/5c29fece-1afe-49da-8a60-92764730f83f\/abstract_-_44385-(720p).mp4",
					"size": "4.46 Mb",
					"filesizeInMb": "4.46",
					"tags": [],
					"deleteUrl": null,
					"updateUrl": "http:\/\/127.0.0.1:8000\/cms\/file-library\/files\/single-update",
					"updateBulkUrl": "http:\/\/127.0.0.1:8000\/cms\/file-library\/files\/bulk-update",
					"deleteBulkUrl": "http:\/\/127.0.0.1:8000\/cms\/file-library\/files\/bulk-delete",
					"disabled": false
				}
			]
		...
```
