### ISSUE TITLE
Medias inside Blocks get saved, but not loaded when using `'translated' => false,`

### ISSUE THREAD

**Issue by davidfaber** [area17/twill#1839]
## Description

Whenever I create a block with a non-translateable medias-field in an environment, where I need translated medias in some other places, non-translated medias in blocks will get saved, but not displayed.

Thanks in advance!

### Steps to reproduce

Create a block using a medias-field:
```php
@twillBlockTitle('Video Slideshow')
@twillBlockIcon('slideshow')
@twillBlockGroup('app')

@formField('medias', [
    'name' => 'gallery_background',
    'label' => 'Hintergrundbild',
    'withVideoUrl' => false,
    'translated' => false,
])
```

```php
    'block_editor'    => [
        'files' => ['category_icon'],
        'crops' => [
            'gallery_background' => [
                'default' => [
                    [
                        'name'  => 'default',
                        'ratio' => 16 / 9,
                    ],
                ],
            ],
        ],
    ],
    'media_library'   => [
        'translated_form_fields' => true,
    ],
```

### Expected result

The image gets saved and loaded.

### Actual result

The image gets saved over and over and over again, resulting in multiple Entries in the mediables-table.

**Comment by ifox** [comment]
Related to #483. At the moment enabling `translated_form_fields` is an all or nothing situation. The logic is made to fallback to the main language so that editors do not have to provide the same image for each language.

**Comment by ifox** [comment]
Closing in favor of #483 which has been added to the roadmap.
