### ISSUE TITLE
Translation of Title

### ISSUE THREAD

**Issue by Equruler** [area17/twill#184]
Just a simple question. If the module has translation, can the title be "not translatable"?

**Comment by sauron** [comment]
Hey @Equruler,
When you create a new CMS module by using the ```twill:module``` command, you'll find a commented piece of code in the Model as:
```php
    // uncomment and modify this as needed if you use the HasTranslation trait
    // public $translatedAttributes = [
    //     'title',
    //     'description',
    //     'active',
    // ];
```
As the instruction states you only need to uncomment that snippet and remove the *title* from that array.

Keep in mind that the migration should reflect this change, e.g.:
in the migration you'll have to modify the creation of the translation table from
```php
        Schema::create('<your_model>_translations', function (Blueprint $table) {
            createDefaultTranslationsTableFields($table, 'setting');
            $table->text('title')->nullable();
            $table->text('description')->nullable();
            ...
        });
```
to
```php
        Schema::create('<your_model>_translations', function (Blueprint $table) {
            createDefaultTranslationsTableFields($table, 'setting');

            $table->text('description')->nullable();
            ...
        });
```
by moving the ```$table->text('title')->nullable();``` from the translation table to the main table.

I hope this helps.

**Comment by ifox** [comment]
Hi @Equruler!

Thanks for answering here @sauron :)

This only part I think is missing is that when a module is translatable the views of that module need to know that the title is not to be translated by using `"translateTitle" => false` from formData or the Blade `@extend` directive in the module's `form.blade.php` file.

**Comment by ifox** [comment]
#532 which was merged earlier today makes this automatically handled for you, check out @antonioribeiro's PR description.
