### ISSUE TITLE
Restoring revision in nestedmodules throws an error

### ISSUE THREAD

**Issue by haringsrob** [area17/twill#1840]
When restoring a revision in a nested module it gives a 404.

This can be reproduced with a basic parent/child setup.

![image](https://user-images.githubusercontent.com/866743/193515436-3a783b4b-0dbe-41c6-9176-0d946e40f6f4.png)

**Comment by thingasd** [comment]
Hey @haringsrob ! I face the same problem, in my case, it seems caused by passing null to getById() in module repository, as the restore route having param id instead of page
![image](https://user-images.githubusercontent.com/29519267/195014546-09fae4d6-bf31-4fd9-8996-a37652503f23.png)
