### ISSUE TITLE
Sorting queries by slug status

### ISSUE THREAD

**Issue by philippdaun** [area17/twill#185]
First of all, thanks for making Twill and open-sourcing it! We've been sorely missing an elegant CMS solution built upon Laravel and this is it :)

Now for my question: how do you handle/recommend querying for conflicting or duplicate slugs in the history?

Assuming I create a record with a slug of `slug-a`, then rename it to `slug-b` and create a new record with a slug of `slug-a`. Now we have:

- page_id: `1`, slug: `slug-a`, active: `0`
- page_id: `1`, slug: `slug-b`, active: `1`
- page_id: `2`, slug: `slug-a`, active: `1`

Can you think of a solution that orders the results by the slug's active state and returns either the active slug page or the first inactive slug page if no active slug matched? So querying for `slug-a` would return page `2` in this case.

My current solution is this. I'd love to get it down to one query somehow.

```php
$pageQuery = Page::with('blocks')->published()->visible();

// Try to find page by current slug (active = 1)
try {
    $page = (clone $pageQuery)->whereHas('slugs', function ($q) use($slug) {
        $q->where('slug', $slug)->where('active', 1);
    })->firstOrFail();
}

// Try to find page in slug history
catch(ModelNotFoundException $e) {
    $page = (clone $pageQuery)->whereHas('slugs', function ($q) use($slug) {
        $q->where('slug', $slug);
    })->firstOrFail();
}
```

Thanks!

**Comment by ifox** [comment]
Hi @philippdaun, thanks a lot for your kind words 👍 

We do actually have a bunch of helpers for this. See the following from the repository:

```php
public function forSlug($slug, $with = [], $withCount = [], $scopes = [])
{
    $query = $this->model->where($scopes)->scopes(['published', 'visible']);
    foreach (class_uses_recursive(get_called_class()) as $trait) {
        if (method_exists(get_called_class(), $method = 'getPublishedScopes' . class_basename($trait))) {
            $query->scopes($this->$method());
        }
    }
    $item = (clone $query)->forSlug($slug)->with($with)->withCount($withCount)->first();
    if (!$item && $item = (clone $query)->forInactiveSlug($slug)->first()) {
        $item->redirect = true;
    }
    return $item;
}
```

This helper will return the item with the provided slug, active if possible. If not active it will add a redirect property on the item so that you can redirect to the active url when your controller.

You can also see the underlying helpers in the HasSlug model trait:

```php
public function scopeForSlug($query, $slug)
{
    return $query->whereHas('slugs', function ($query) use ($slug) {
        $query->whereSlug($slug);
        $query->whereActive(true);
        $query->whereLocale(app()->getLocale());
    })->with(['slugs']);
}

public function scopeForInactiveSlug($query, $slug)
{
    return $query->whereHas('slugs', function ($query) use ($slug) {
        $query->whereSlug($slug);
        $query->whereLocale(app()->getLocale());
    })->with(['slugs']);
}
```

**Comment by philippdaun** [comment]
Thanks! That clarifies things quite a bit.

In my case the API exporting the data is not locale-aware, i.e. it queries by slug regardless of locale and returns results with all translations for the client to sort it out themselves.

I assume in that case it's best to stick with my custom implementation since Twill's repository methods query by the current app locale?

**Comment by ifox** [comment]
Definitely. However I would love to have a look at your custom implementation as I think this could benefit other users as well. We could then introduce new helpers that are not locale-aware.

**Comment by ifox** [comment]
Our upcoming updates to the documentation include more details about those helpers. Closing.

**Comment by arkid** [comment]
Is there an eta on the docs roughly @ifox  - more info on this is exactly what I'm after
