### ISSUE TITLE
filesList returns amazon link when using local adapter

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#188]
I followed instructions on how to set up local file adapter. Files are stored in public folder and are accessible from model/blocks. However when I try to get filesList I get AWS links for example: ```https://s3.amazonaws.com/ANYTHING/9a7c3c22-97c9-42e3-b986-68bd9d40e9d0/result.pdf```

Similarly using ```$fileModel->toCmsArray()``` returns AWS links.

Is there a way around this?
I guess #173 should fix this. Are there any reservations against merging it?

**Comment by ifox** [comment]
Hi @zipavlin,

Thanks for reporting this.

We're currently working on #173 and related issues to release a new version, stay tuned!

**Comment by zipavlin** [comment]
Hey @ifox,

Thanks for your reply! I am therefore eagerly awaiting for new release 😄

**Comment by ifox** [comment]
Hey @zipavlin,

1.2.1 doesn't include #173 yet but I'm on it. In the meantime, changing the `twill.file_library.disk` configuration to a disk you define like the following in your app `filesystems.php` configuration works:

```
'uploads' => [
            'driver' => 'local',
            'root' => public_path(),
            'url' => '/', // avoids default behavior of Laravel that adds "storage" to any local driver generated URL.
],
```

**Comment by zipavlin** [comment]
> In the meantime [...]

Thanks, @ifox I will try it out and report back
