### ISSUE TITLE
Dashboard log reordered activities

### ISSUE THREAD

**Issue by thingasd** [area17/twill#1887]
## Summary

It is convenient to use drag and drop to control the parent child relation in nested modules, but sometime may drag accidentally, it is helpful to have log of dragging activities

## Describe the solution you'd like
![image](https://user-images.githubusercontent.com/29519267/199890126-11b4d32a-e6c5-4d9c-8a66-ef89aa2c5f3e.png)

Log the reorder activities

## Additional context
Just log the Initiator instead of all saved node?

**Comment by haringsrob** [comment]
As mentioned in the pr. We are not adding this feature at the moment.
