### ISSUE TITLE
[Media Library] Filesystem Config not used - Invalid image url

### ISSUE THREAD

**Issue by noxify** [area17/twill#19]
Hi,

i have currently the challenge, that the returned url values for images which has been uploaded locally.

I configured the twill app as following:

```
//.env
APP_URL=twill.local 
ADMIN_APP_URL=twill.local
ADMIN_APP_PATH=manage
SESSION_DOMAIN=.twill.local
MEDIA_LIBRARY_ENDPOINT_TYPE=local
MEDIA_LIBRARY_LOCAL_PATH=uploads

//config/twill.php
    'media_library' => [
        'disk' => 'public',
        'endpoint_type' => env('MEDIA_LIBRARY_ENDPOINT_TYPE', 's3'),
        'cascade_delete' => env('MEDIA_LIBRARY_CASCADE_DELETE', false),
        'local_path' => env('MEDIA_LIBRARY_LOCAL_PATH'),
        'image_service' => env('MEDIA_LIBRARY_IMAGE_SERVICE', 'A17\Twill\Services\MediaLibrary\Imgix'),
        'acl' => env('MEDIA_LIBRARY_ACL', 'private'),
        'filesize_limit' => env('MEDIA_LIBRARY_FILESIZE_LIMIT', 50),
        'allowed_extensions' => ['svg', 'jpg', 'gif', 'png', 'jpeg'],
    ],
```

Return URL is the following:
```
https://uploads235189ba-1726-4a94-930a-0314e749c112/34984697-2186605328021771-2297187018024681472-o.jpg?auto=compress%2Cformat&dpr=1&fit=min&fm=jpg&h=256&q=60
```

The image is saved successfully, but I expected the file in a different directory (in my case `public/storage/uploads/` instead of `public/uploads<uuid>/`.
( `public/storage` is available as symlink via `php artisan storage:link` )

Correct me if I'm wrong, but it seems, that the `filesystem` configuration is not used in the current version.

Thanks & Greets

**Comment by ifox** [comment]
Hi @noxify,

Filesystem configuration is used, you are missing a trailing slash in `MEDIA_LIBRARY_LOCAL_PATH`. Not sure why it would be on you to not forget it though, noting as an improvement to do!

As for the domain missing: by default the image rendering service is `A17\Twill\Services\MediaLibrary\Imgix`. You would need to use an [imgix](https://www.imgix.com/) source that you'd define in the .env `IMGIX_SOURCE_HOST` variable. 

If you need to render images with something else, you can either create your own image rendering service as documented [here](https://twill.io/docs/#image-rendering-service), or use the simple `A17\Twill\Services\MediaLibrary\Local` service (but with this one you wouldn't benefit from cropping features and optimizations). 

If you are interested into creating a new image service, your contribution would be very appreciated!

**Comment by noxify** [comment]
Adding the following line to my `.env` file solves the problem - Just User Handling. Sorry :)

```
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Local
```
