### ISSUE TITLE
How to fuzzy search in blocks

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#190]
Hey,

We are using blocks for creating modular content for a lot of content type (news, pages, ...).
We are also using Laravel/Scout with TNTSearch adapter for searching. It works seamlessly for general content (titles, ...) with using ```Searchable``` trait and setting ```toSearchableArray()``` in required modules.

Having in mind, that most of the content will be set in blocks I would like to also include those results, but I am unsure how to set up Block module to be searchable.

Do you have any experience with this? Or any thoughts/guidelines/help on how to do something like that?

Thanks!

**Comment by ifox** [comment]
Hey @zipavlin,

Very good question! We actually created a trait for this in one of our recent project. It is not ready to be used generically in Twill's codebase yet but happy to share the approach. We loop over attached blocks from the `toSearchableArray` and create a string concatenating all text fields values that should be searchable. With some time, we could implement a helper to call from "searchable" function (to be agnostic to the package or third party used ie. Elastic Search, Algolia...). This helper could read from the blocks configuration to identify searchable fields.

Hope that helps!

**Comment by zipavlin** [comment]
Hey @ifox,

Thank you for sharing your approach! It is a great idea and it fixed my issue perfectly!

**Comment by layout-lab** [comment]
Hi @ifox,

Wondered if this trait is now included in Twill? Or if yourself or @zipavlin would be able to share the approach taken?

Thanks

**Comment by zipavlin** [comment]
Hey @layout-lab I was doing this recently :)

You can easily do this by gaving a method (in my case this was `content` in separate trait that I added to all searchable models with blocks) that collect all text content and joins it into one long string as follows:

```php
    public function content()
    {
        return $this->blocks()
            ->whereIn('type', [
                'accordion_item',
                'big',
                'cta',
                'exposition',
                'exposition_item',
                'features',
                'features_item',
                'files',
                'image_text',
                'navigation_break',
                'offer_item',
                'options_card_item',
                'options_table_item',
                'quote',
                'table',
                'text',
                'title'
            ])
            ->get()
            ->map(function ($block) {
                return collect($block->content)
                    ->only(['text', 'title', 'table', 'subtitle', 'quote', 'tags'])
                    ->map(function ($item) {
                        return ucfirst(trim(strip_tags($item)));
                    })
                    ->join('. ');
            })
            ->join('. ');
    }
```
This method basically calls all blocks from `blocks()` relationship with block type set to those that contain text fields. It then maps returned `Block` instances to text fields only and joins then into one long searchable string.

Populating scout index is then simply
```
    public function toSearchableArray()
    {
        return collect($this->toArray())->only(['id', 'title'])->put('content', $this->content())->toArray();
    }
```

Hope this will help you :)

**Comment by razvaniacob** [comment]
this is in the documentation

`// add orWhereHas clauses
    $this->searchIn($query, $scopes, 'field_in_scope', ['field1', 'field2', 'field3']);
 `

But there's no such method in vendor/area17/twill/src/Repositories/ModuleRepository.php

Why id that method missing?
