### ISSUE TITLE
Cloudflare R2 Compatibility

### ISSUE THREAD

**Issue by mikerockett** [area17/twill#1906]
## Summary

Twill currently supports S3, by default, but does not inherently support the recently-launched Cloudflare R2, which is S3-compatible. I should probably be filing this as a bug report, but it is technically a feature request, as it is a request for compatibility with another service.

I have not gone too deep on this, but noticed that the `x-amz-credential` that comes back for signed uploads via the frontend does not match the regular expression provided in Twill’s code.

Given `189dab6b042…/20221113//s3/aws4_request`, which comes back from R2, the expression `/.+\/(.+)\\/(.+)\/s3\/aws4_request/` will never match it.

## Describe the solution you'd like

A fix that makes Twill work seamlessly with both S3 and R2 as they are compatible.

## Additional context

I attempted to change the expression to `/.+\/(.+)\/(.*)\/s3\/aws4_request/` to see what would happen, but landed up with a CORS error from Cloudflare.

Not entirely sure if this relates to the credential itself, or simply that CF does not have a CORS policy for posting. 

Might be that my production domain has been linked, but I’m uploading with my local `.test` domain. Regardless, the regular expression does not match, and that’s what appears to need correction.

**Comment by jbs-fm** [comment]
> Going to close this off – realised my bucket was not set to "auto", but rather "" (which I read somewhere).

Hey @mikerockett running into some CORS upload issues, please could you expand on your fix for this?

Do you remember if this is laravel config related or something that can be done in the cloudflare r2 dashboard?
