### ISSUE TITLE
Block translations

### ISSUE THREAD

**Issue by galingong** [area17/twill#191]
Is translating blocks supported? As far as my assumptions go, there should be a `block_translations` table in the database, which there is not, so I guess the feature is not yet implemented, making blocks somewhat useless in multilingual sites. Is there a simple way to implement it without hacking the package?

**Comment by layout-lab** [comment]
Hi,

Just checked this on my install, and there's no separate `block_translation` table, but the multilingual content saves in the `blocks` table. The content column stores the data as JSON for each language.

The data can then be rendered on the front end like a normal field using:
`{{ $block->translatedinput('inputName') }}` don't forget to set `'translated' => true` on your form fields.

Thanks

**Comment by galingong** [comment]
Thank you for you input! I must be missing something, in my case the block is saved with a single language. Checked the `content` column, there are also no separate properties in the JSON for the languages, it's just simply `{"property": "value"}`. I've set `'translated' => true` both on the block fields(`blocks/block.blade.php`), and also on the `@formField('block_editor')` in `module/form.blade.php`, but no luck.

**Comment by layout-lab** [comment]
Oh no, another thing to check do you have the `HasTranslation` trait on the model that you're adding the blocks to?

**Comment by galingong** [comment]
Yes, and also my other (fixed, non-block) fields translate correctly, as they should.

**Comment by galingong** [comment]
I've read the docs all over again, and managed to figure it out, it's a bit trivial looking back. Initially I hadn't had `translated => true` on the fields, I ran `twill:blocks` and only then did I start experimenting with translation. Obviously it didn't work because artisan generates the Vue components which get compiled by Webpack.
Running `twill:blocks` resolved it.
