### ISSUE TITLE
[2.x] BlockMaker command is loading blocks on every Artisan call

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#1915]
## Description

While upgrading an application from Twill 2.2 to 2.11, during a `php artisan` (yes, just to see the help screen), I was surprised by this error:

```
Could not find a view for the block or repeater 'a17-block-people'.
```

After digging this a little bit I found that the BlockMaker command constructor is instantiating the BlockCollection which also [loading all blocks also during construction](https://github.com/area17/twill/blob/2.x/src/Services/Blocks/BlockCollection.php#L39):

``` php
public function __construct($items = [])
{
    parent::__construct($items);

    $this->fileSystem = app(Filesystem::class);

    $this->missingDirectories = collect();

    $this->load(); /// HERE
}

```

Which seems unnecessary as I'm not issuing the block maker command and I don't need blocks to be loaded every time. This also has potential to make artisan run a lot slower as it's possibly scanning and loading all blocks.

### Steps to reproduce

Remove a block file from your application and just run `php artisan`

### Expected result

Not load all blocks on every artisan command.

### Versions

Twill version:  2.11
Laravel version: 9
PHP version: 8.1

**Comment by haringsrob** [comment]
Thanks @antonioribeiro this has been solved in 2.x (will be ported to 3.x).
