### ISSUE TITLE
Choose your own password not working

### ISSUE THREAD

**Issue by nelsonsamples15** [area17/twill#1921]
I am newbie on using Twill.
Then I encountered a bug when creating a new user.
It will sent an email for creating a password.
![image](https://user-images.githubusercontent.com/29938891/202325096-04be2f03-7c93-4803-937d-caeed33bd14b.png)

![image](https://user-images.githubusercontent.com/29938891/202325292-9db5a0c7-8501-475d-b3df-346df77ae5bf.png)

But when I click the "Choose your own password" it will redirect only to the main public page.
Even the url, I copied it and paste to the address bar it will redirect to the public page also.

Reset Password is fine. but for the Welcome create password it is not working on my end.

Thank you for the future response.

**Comment by nelsonsamples15** [comment]
Sorry for late reply @haringsrob 
I am using "area17/twill": "^2.0" on my project.

**Comment by zumbidoweb** [comment]
I my case logging out of the admin before or going in another browser fix the issue. 
if you are logged you are redirect to the dashboard.
