### ISSUE TITLE
getTranslationModelNameDefault not using configured namespace

### ISSUE THREAD

**Issue by jeepey** [area17/twill#193]
Hi, 

Appreciate all the great work on this project.

I ran into an issue with the namespace of my Translations. Currently these are determined in the HasTranslation trait as follows:

```php
public function getTranslationModelNameDefault() 
{
        return "App\Models\Translations\\" . class_basename($this) . 'Translation';
}
```

Wouldn't it be better to use:

```php
public function getTranslationModelNameDefault() 
{
        return config('twill.namespace') . "\Models\Translations\\" . class_basename($this) . 'Translation';
}
```

Same thing for the revisions I guess.

Many thanks!

**Comment by ifox** [comment]
Good catch @jeepey!
