### ISSUE TITLE
Add Laravel 5.8 to composer.json

### ISSUE THREAD

**Issue by titanomachy** [area17/twill#195]
Can't use the composer require command for Twill, because Laravel 5.8 is missing in composer.json
`"laravel/framework": "~5.3.0|~5.4.0|~5.5.0|~5.6.0|~5.7.0",`

The 5.8 version was released on the 26th of February. Probably just adding the 5.8 tag would fix it.

**Comment by ifox** [comment]
Hi @titanomachy, definitely, we're going to release Laravel 5.8 support this week. We just needed a couple of days to make sure all dependencies were updated as well:

- https://github.com/dimsav/laravel-translatable/releases/tag/v9.4.0
- https://github.com/spatie/laravel-activitylog/releases/tag/3.2.2
- https://github.com/spatie/laravel-analytics/releases/tag/3.6.3
- https://github.com/cartalyst/tags/releases/tag/v8.0.0

**Comment by marcorieser** [comment]
When will the release be made?

**Comment by OwenMelbz** [comment]
Maybe an unhelpful message :D

Just in case anybody needs, the default asset path in laravel has changed from `resources/assets/js` to `resources/js` so npm tasks fail as they're looking in the wrong places

**Comment by ifox** [comment]
Checkout 1.2.1 guys!

@OwenMelbz this should not fail anymore even when not existing yet but we still use `resources/assets/js` to store generated blocks. We should now probably move to `resources/js` to follow Laravel 5.8 change or decide to store them in a new folder, maybe simply `resources/twill` to avoid being affected by another change in Laravel in the future.

**Comment by Riaan-ZA** [comment]
This works but I had to manually create the /resources/assets/js/blocks folder first
