### ISSUE TITLE
[2.x] [Forms] List of repeaters : counter without Dropdown looks broken

### ISSUE THREAD

**Issue by mrdoinel** [area17/twill#1950]
## Listing Repeaters : counter without Dropdown looks broken

When listing repeater items into Forms :
When no dropdown are around the counter number, the item is misaligned with the label.

### Steps to reproduce

Latest version.
Create a list of repeater items.

### Expected result

Counter should be aligned with text

### Actual result

Counter is misaligned (see image)

### Versions

Twill version 2.11.0

![Capture d’écran 2022-11-24 à 18 38 26](https://user-images.githubusercontent.com/546129/203842109-e446041c-75ed-479e-99a0-87143d21b896.png)

![Capture d’écran 2022-11-24 à 18 38 55](https://user-images.githubusercontent.com/546129/203842220-a9f7e88c-45a0-4b43-bcae-439c87b5ab78.png)

**Comment by haringsrob** [comment]
Hey @mrdoinel this is a regression, I will look into a bugfix tomorrow and make a new release.

**Comment by haringsrob** [comment]
I have checked this briefly, but I cannot immediately reproduce the issue.

Did you run `php artisan twill:update` after the composer update? 

If that does not help, can you share how you are implementing the block editor field?

**Comment by mrdoinel** [comment]
I updated the content of the issue so this is more precise : the issue is happening with Repeater items.
