### ISSUE TITLE
❗ [2.x] Too few arguments to function Illuminate\Routing\Router::singleton()

### ISSUE THREAD

**Issue by haringsrob** [area17/twill#1961]
## Summary

In Laravel 9 a new Route::singleton method was added. This conflicts with our usage of the singleton macro.

Because of this we have released [Twill 2.12.0](https://github.com/area17/twill/releases/tag/2.12.0) which renames `Route::singleton` to `Route::twillSingleton`.

To fix this, you have to update the routes `routes/admin.php`

**Comment by AndreSchwarzer** [comment]
Context: PR from @jessarcher https://github.com/laravel/framework/pull/44872
