### ISSUE TITLE
3.x restoreRevision does not show the form

### ISSUE THREAD

**Issue by deckchan** [area17/twill#1969]
## Description

When do restoreRevision, the form is disappeared.

### Steps to reproduce

Go to any entity (e.g. Page), select the any revision and click Restore

### Expected result

A form with old data should show up

### Actual result

The form is disappeared.
![image](https://user-images.githubusercontent.com/27337895/205573229-38adac48-0076-4a82-a7bf-09cc37f23083.png)

### Versions

Twill version: 3.0.0-beta2
Laravel version: v9.40.1
PHP version: 8.1.2
Database engine: MySQL version: 5.7.36

**Comment by haringsrob** [comment]
Hey @deckchan thanks and thank you for the pr, I have merged the pr and this will be added in the next beta.
