### ISSUE TITLE
How to Create Image Blocks as per the video demo

### ISSUE THREAD

**Issue by jkhamler** [area17/twill#197]
@yanhao-li @ifox 

Now I've got my S3 storage sorted...

I'm trying to make some blocks exactly as per the video demo on your homepage but I can't for the life of me get the image panels to load like this -->

![image](https://user-images.githubusercontent.com/7847437/53897286-b53eab80-402d-11e9-807d-5818caaa2711.png)

There doesn't seem to be any documentation on how to set up fixed/flexible image grids - could you shine some light for me? This is the code in my current block, 'flexible_image_grid'. 

```
@formField('medias', [
'name' => 'slideshow',
'label' => 'Slideshow',
'max' => 5,
'note' => 'Minimum image width: 1500px'
])
```

However, I have no ability to add any images when I switch to the content editor view:

![image](https://user-images.githubusercontent.com/7847437/53897426-fdf66480-402d-11e9-8006-c1f6d31f60b9.png)

**Comment by ifox** [comment]
Hey @jkhamler,

I definitely see where you're coming from. Let me clarify a few things for you:

- the video demo on twill.io's homepage showcases one of our Twill's implementation, for pentagram.com
- fixed and flexible image grids are blocks that we created for this implementation specifically
- blocks are composition of form fields, every Twill project needs different blocks, and we only ship 2 default block (text and image)
- as far as the form itself, your block's Blade file code is correct, but you need to generate Vue components out of Blade blocks using `php artisan twill:blocks` and then make sure you build the CMS assets again with `npm run twill-build` (or `twill-dev` to automatically rebuild after you run `twill-blocks` in another command line tab/window.
- the part on the right of the editor screen is the rendering of each blocks, how they look in the frontend of pentagram.com
- Twill does not ship with a frontend theme, pre-defined content types or anything like that, it is up to your to setup to your liking
- our blocks rendering and preview documentation could be much improved, but I'm sure [this thread](https://github.com/area17/twill/issues/116) will help too.

Cheers!

**Comment by jkhamler** [comment]
@ifox this is a massive help. I just hope I can create the fixed and flexible image blocks myself as that's exactly what I need.

```'make sure you build the CMS assets again'``` - Ah this is a fairly important step that I was missing! 

Awesome. Thanks for the help - I will refer closely to what you've written here as well as the contents of the thread that you've linked in.

**Comment by jkhamler** [comment]
So I assume the multiple image grid blocks are just image blocks with repeaters?

**Comment by jkhamler** [comment]
Hi @ifox it's all coming together nicely but I'm not sure how to render the images in my 'fixed image grid' component. Could you kindly share some of your great wisdom?

```
/views/site/blocks/fixed_image_grid.blade.php

<!-- This block renders the contents of the image grid -->

@php
    /** @var $block \A17\Twill\Models\Block */

foreach ($block->images() as $image) {

 /** Do something with the image... render in an <img> tag etc? */

}

@endphp
```

**Comment by jkhamler** [comment]
I tried this (as per the documentation)

```
{{ $block->images('mediaFieldName', 'cropNameFromBlocksConfig')}}
```

But it's giving the following error:

```
[2019-03-07 13:13:42] darwin.ERROR: htmlspecialchars() expects parameter 1 to be string, array given (View: /Users/jonathanhamler/PhpstormProjects/darwin/resources/views/site/blocks/fixed_image_grid.blade.php) (View: /Users/jonathanhamler/PhpstormProjects/darwin/resources/views/site/blocks/fixed_image_grid.blade.php) {"userId":1,"email":"jkhamler@gmail.com","exception":"[object] (ErrorException(code: 0): htmlspecialchars() expects parameter 1 to be string, array given (View: /Users/jonathanhamler/PhpstormProjects/darwin/resources/views/site/blocks/fixed_image_grid.blade.php) (View: /Users/jonathanhamler/PhpstormProjects/darwin/resources/views/site/blocks/fixed_image_grid.blade.php) at /Users/jonathanhamler/PhpstormProjects/darwin/vendor/laravel/framework/src/Illuminate/Support/helpers.php:578, ErrorException(code: 0): htmlspecialchars() expects parameter 1 to be string, array given (View: /Users/jonathanhamler/PhpstormProjects/darwin/resources/views/site/blocks/fixed_image_grid.blade.php) at /Users/jonathanhamler/PhpstormProjects/darwin/vendor/laravel/framework/src/Illuminate/Support/helpers.php:578, ErrorException(code: 0): htmlspecialchars() expects parameter 1 to be string, array given at /Users/jonathanhamler/PhpstormProjects/darwin/vendor/laravel/framework/src/Illuminate/Support/helpers.php:578)
```

**Comment by jkhamler** [comment]
Also I can't get the blocks with images to save - I'm not getting any errors, but when I refresh the page the images have been lost.

**Comment by jkhamler** [comment]
Got it!

```<img src="{{ $block->image('image', 'desktop') }}"/>```

Wow, that was simple...

**Comment by jkhamler** [comment]
Ok so the problem remains that I can't save any data from my custom 'image_grid' block. I've followed the instructions very carefully and I'm not getting any errors, only that nothing is saving to the 'medias' or 'mediables' tables when I click save (so when I refresh the page my images are lost), which is presumably why I am unable to render any images.

@ifox @yanhao-li any ideas?

Thanks!

Image Grid:
![screenshot 2019-03-08 at 12 31 00](https://user-images.githubusercontent.com/7847437/54028966-d377e900-419e-11e9-987c-b649287bc08a.png)

Block View:
![screenshot 2019-03-08 at 12 30 14](https://user-images.githubusercontent.com/7847437/54028983-e094d800-419e-11e9-9d58-56e5b89bf103.png)

**Comment by imknight** [comment]
you need to declare the image crop under Twill Config file and take note the crop should be child entity of block_editor in the Twill Config file

**Comment by Larsklopstra** [comment]
How would it be possible to render the alt tag with this method?
