### ISSUE TITLE
League\Flysystem\AwsS3V3\AwsS3V3Adapter::__construct(): Argument #2 ($bucket)

### ISSUE THREAD

**Issue by shivratanbhanu100** [area17/twill#1985]
League\Flysystem\AwsS3V3\AwsS3V3Adapter::__construct(): Argument #2 ($bucket) must be of type string, null given

i am not using AWS for my project.

**Comment by ifox** [comment]
In Twill 2 if you haven't configured your media and file library to NOT use AWS S3, you are. The default in Twill 3 is now local to avoid this confusion. Please follow the installation documentation: https://twill.io/docs/getting-started/installation.html#setting-up-the-media-library

**Comment by haringsrob** [comment]
Hey @shivratanbhanu100 as mentioned please check the related docs, if after changing that you still are able to reproduce feel free to re-open this issue.
