### ISSUE TITLE
"Array to string conversion in <module>_slugs table

### ISSUE THREAD

**Issue by noxify** [area17/twill#20]
Hi, 

while testing the app, I got the following error message:

```
Array to string conversion (SQL: insert into `article_slugs` (`active`, `slug`, `locale`, `article_id`) values (1, test, MX, 1))
```

STRs:

### Create new module

```
php artisan twill:module articles -R -P -M -S -B
```

### Update the generated files

https://gist.github.com/noxify/3317922ca2202df14c47768212a95d02

(all other generated files are untouched)

### Migrate the new tables

```
php artisan migrate
```

### Create a new article record
1. Open the admin page for the modules ( in my case, it is http://twill.local/manage/content/articles ) 
2. Click `Add new` Button
3. Enter something in the `Title` field
4. Click the `Create` Button

### Expected Result
A new record has been created in all needed tables

### Current Result

In the UI, the following error is shown:
```
Your content can not be edited, please retry
```

In the console log you can see a `500` response with the following error:
```
{
    "error": {
        "type": "Illuminate\\Database\\QueryException",
        "message": "Array to string conversion (SQL: insert into `article_slugs` (`active`, `slug`, `locale`, `article_id`) values (1, testrecord, MX, 3))",
        "file": "\/home\/vagrant\/code\/twill\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php",
        "line": 664
    }
}
```

## Environment
* Host: OSX
* App running via Homestead

composer.json
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "area17/twill": "^1.1",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

----

I hope the STRs are enough :) If you need more information, please let me know.

Thanks!

**Comment by ifox** [comment]
Hi @noxify, those are awsome STRs, thanks!

I will look into this later today.

**Comment by noxify** [comment]
Hi @ifox,
sorry for the delay.

Here my `config/translatable.php`:

```
<?php

return [

    'locales' => [
        'en',
        'fr',
        'es' => [
            'MX', // mexican spanish
            'CO', // colombian spanish
        ],
    ],

    'locale_separator' => '-',

    'locale' => null,

    'use_fallback' => false,

    'use_property_fallback' => true,

    'fallback_locale' => 'en',

    'translation_suffix' => 'Translation',

    'locale_key' => 'locale',

    'to_array_always_loads_translations' => true,
];

```

**Comment by ifox** [comment]
No problem @noxify!

That's what I had in mind. 

The `translatable.php` configuration file is published by [dimsav/laravel-translatable](https://github.com/dimsav/laravel-translatable/) during Twill's installation.

By default, it includes nested locales:

```php
'locales' => [
    'en',
    'fr',
    'es' => [
        'MX', // mexican spanish
        'CO', // colombian spanish
    ],
],
```

Twill does not support nested locales, you have to use a flat list.

It is noted in our documentation but I can see how this can be frustrating as this is just what comes by default. I think we could decide to publish our own `translatable.php` config file to avoid it.

**Comment by noxify** [comment]
Hi,

i changed the `locales` to 

```
'locales' => [
    'en'
]
```

Also i removed my previous created module and created it from scratch with the following command:

``` 
php artisan twill:module articles -R -P -M -S -B -T
```

After this, I added the needed fields to the new migration file and activated the basic stuff in the new created models.

Now everything is working :)

Just a question: If I create a new module w/o the `-T` - Do I have to create the `<module>_translations` table anyway or was the nested array the problem? 

But thanks for the hints :) 

I will close this issue now, because we have a working solution :)

**Comment by ifox** [comment]
The nested array was the problem yes. 

If you do not include the translations trait using `-T` you do not have to create the translations table.

Always happy to help! Curious to know if you have plans to build something with Twill or still testing it out too!

**Comment by noxify** [comment]
I have a plan, but currently it‘s just testing :)
