### ISSUE TITLE
Dropping CKEditor into Twill Block

### ISSUE THREAD

**Issue by jkhamler** [area17/twill#200]
Is it possible to drop the latest CKEditor into a Twill Block? I'm looking for a very powerful rich text editor which offers more functionality than the standard text block.

https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html

**Comment by akizor** [comment]
Hello, I'm also interested in injecting CKEditor into Twill. @jkhamler have you managed to that?
