### ISSUE TITLE
gray background image in backend table

### ISSUE THREAD

**Issue by SevendaysCompany** [area17/twill#2005]
## Description

I've added an image to my backend table of a model. Behind the images, there is a gray background which I can't seem to remove.  Only when I use "->rounded()" there is no background, but this is a rather small thumbnail...  Is it possible to use for example a square image without this gray background?  I'v tried with mediaParams, crops,... but the background was always there...

### Versions

Twill 3.0.0.beta2
Laravel 9.39
Php 8.1

![Schermafbeelding 2022-12-15 om 12 08 06](https://user-images.githubusercontent.com/56922633/207846688-875d1a85-71e1-4954-8bf6-ee8109a08841.png)

**Comment by ifox** [comment]
Hi @SevendaysCompany this is a regression in Twill 3 that I thought @haringsrob had addressed. Thanks for reporting. Can you make sure you are using the latest Twill assets build?

**Comment by haringsrob** [comment]
It was confirmed that a build was fixing the issue.
