### ISSUE TITLE
Showing block content in Editor without Previewing

### ISSUE THREAD

**Issue by jkhamler** [area17/twill#201]
Hi guys,

On your video demo, the content of each block shows without having to toggle to the 'Preview' section (i.e. as photos are added to an image grid, they show/re-order instantly)

How is this possible? Everything else is working perfectly for me now.

![Screenshot 2019-03-11 at 17 30 36](https://user-images.githubusercontent.com/7847437/54144666-15659100-4424-11e9-9910-cba4d46a0c2a.png)

**Comment by yanhao-li** [comment]
Hi @jkhamler ,

When you dragged the component from left sidebar to the content area, you should be able to see the block's fields on the left like this:

<img width="1440" alt="Screen Shot 2019-03-11 at 5 59 56 PM" src="https://user-images.githubusercontent.com/12378652/54161142-a68a3700-4427-11e9-958b-af3b49001559.png">

If you canceled the edit mode by mistake, you could also access it again by clicking the azury block in content area.

Hope this helps!

Best,
Yanhao

**Comment by ifox** [comment]
Hey @jkhamler!

@yanhao-li I think @jkhamler wants to better understand how to render the preview of a single block in the content editor view.

#116 should help a lot. Also check out errors returned by the preview requests in your browser console. It should help you figure which file is missing or failing to render those blocks.

**Comment by jkhamler** [comment]
Hi @ifox yes that's exactly right - I want to render the blocks within the editor without having to go to 'Preview'. I will check out #116 and only come back to you if I really have to. Thanks guys!

**Comment by jkhamler** [comment]
Sorted with one line of code. Thanks guys
