### ISSUE TITLE
[3.x] DatePicker stored data not showing in form field

### ISSUE THREAD

**Issue by KeithPun13** [area17/twill#2025]
## Description

DatePicker stored data not showing in the form field after saving.

It was successfully stored in the database and shown on actual pages. 
However, it always shows nothing but placeholder in the form field.

### Steps to reproduce

1. Create DatePicker Field
2. Update the DatePicker field and saving
3. Reload the page

### Expected result

Saved Date
![image](https://user-images.githubusercontent.com/108759216/209781065-21d1f796-96e2-4480-804f-0419c7d9fa43.png)

### Actual result

Only Placeholder
![image](https://user-images.githubusercontent.com/108759216/209781118-31faf2f8-a69a-47ca-b01e-a967fff55413.png)

### Versions

Twill version:  3.0.0-rc1
Laravel version: 9.40.1

**Comment by haringsrob** [comment]
hey @KeithPun13 have you added dates casts?

**Comment by KeithPun13** [comment]
Oh, sorry. Yes, I was missing casts of the fields.
Thank you for your answer and patient.

**Comment by KeithPun13** [comment]
Hi, may I learn more about a case similar to this?
Is there any way I can cast the data type in block/repeater?

**Comment by KeithPun13** [comment]
@haringsrob May I ask more about this question?
What if the date_picker fields are a repeater, 
Is there any possible way to add casts for a block or repeater?
Or, is there other ways to handle it?

**Comment by haringsrob** [comment]
hey @KeithPun13, can you try to do a `php artisan twill:build` and see if the issue is still there?

**Comment by KeithPun13** [comment]
@haringsrob Thanks so much! `php artisan twill:build` does help in this case.

**Comment by haringsrob** [comment]
The stranger thing is that it should already be part of the build. Maybe you did not do "php artisan twill:update" after the latest update?

**Comment by KeithPun13** [comment]
@haringsrob Just having a quick test, I try to :
```
Downgrade to 3.0-bata2 > run php artisan twill:update
```
Issue happend, then :
```
Upgrade to 3.0-cr1 > run php artisan twill:update
```
Still got this issue, then :
```
run php artisan twill:build
```
Issue solved, then I try to run updated again:
```
run php artisan twill:update
```
Issue happening again.

**Comment by KeithPun13** [comment]
Update: 
Just remove all vendor files and re-install, then cannot reproduce the issue anymore... 
I don't think I have any changes to any of those, so weird...

Anyways, thanks for your time.

**Comment by haringsrob** [comment]
hmm.. Not sure. I will pay extra attention to it next release.
