### ISSUE TITLE
[2.x] BC Break - ModuleRepository::listAll() signature changed

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#2036]
## Description

The signature changed on [this commit](https://github.com/area17/twill/commit/2b23fc9b6b00b67fec0c67f5582a89e65454c349), and I believe we cannot safely change this without breaking other applications overloading this method, can we?

### Steps to reproduce

Just overload the `listAll()` method on any Twill repository using the previous signature.

### Versions

Twill version:  2.12.3

**Comment by haringsrob** [comment]
hey @antonioribeiro,

You are right, php does not allow this, only adding more.

Will remove this from the code and take it to 3.x only. Meanwhile, this should not be released yet, can you check that you project is not on 2.x-dev?

**Comment by haringsrob** [comment]
Commit has been reverted.

Thanks!

**Comment by antonioribeiro** [comment]
@haringsrob , nope we are stable, I recently moved the the branch I'm working to `^2.12.2` to get some other stuff fixed recently, but I had to lock it to `2.12.2` after finding this.

Thank you!

**Comment by haringsrob** [comment]
talking about a rough start of the year lol...

https://github.com/area17/twill/releases/tag/2.12.4

That should do it, we are also taking measures to avoid bc issues from happening again.
