### ISSUE TITLE
How to get translated blocks

### ISSUE THREAD

**Issue by frixxx** [area17/twill#204]
How do i get translated content blocks? What are the steps to implement it?

I read this issue: https://github.com/area17/twill/issues/191

But this didnt relly help. Maybe I'm missing something ... ?

Any Tipps?

**Comment by ifox** [comment]
Hi @frixxx,

Translations in blocks are at the field level, by using `'translated' => true` in @formField. You can then retrieve the translated value by using `$block->translatedInput('fieldName')`. It will use the current locale of your Laravel application.

If you're looking at being able to create different blocks per language, we've started some work on #112 that should make this possible in the future.

**Comment by frixxx** [comment]
What I did is to add a form field like so:
`@formField('block_editor', [ 'translated' => true ])`

This left me with content i cannot translate in the admin area.
If i write something, lets say in french and then switch to english - the content is still french not english and vice versa.

I'm not sure if I understood correctly. But If I don't change the blocks in the different languages I can translate the content of the existing blocks  with this configuration. But that doesn't work for me.

Maybe i just misunderstood something or something is just broken ...?

**Comment by ifox** [comment]
Hi @frixxx,

the block editor field itself is not translatable, right now you need to use the same blocks in all languages, but you are able to translate fields in there.

An option if you're looking at different blocks per languages is to create as many records as languages you need but only publish a single language in each.

I think #112 will definitely help with your use case in the future!

**Comment by frixxx** [comment]
@ifox : Thanks for your fast reply!

> the block editor field itself is not translatable, right now you need to use the same blocks in all languages, but you are able to translate fields in there.

So if i understand you correctly I just need to create my own blocks and in these blocks i have to configure the fields as translateable, right? Then the content will be stored in the corresponding language?

**Comment by ifox** [comment]
Exactly!

**Comment by frixxx** [comment]
Ah .... My head was totally stuck on that part, but it makes sense! Great thank you for your help :-)
