### ISSUE TITLE
[3.x] Restore revision always getting current data

### ISSUE THREAD

**Issue by KeithPun13** [area17/twill#2042]
## Description

Revision restore function is not working in 3.0.0-rc1

After research, I think it may cause by changes at :
https://github.com/area17/twill/commit/93058a26057326e59c1c41cb92fb77f953be8251#diff-8a3084d617335690e3d80eadc43ada1afa56002be98b5b69ca778ead9a4849ecR1360

I think ```$item``` should still need to be passed to ```$this->form()``` for data resotring to make it work

### Steps to reproduce

1. Modify Fields
2. Save Draft
3. Preview Revision 
4. Click Restore Button

### Expected result

![image](https://user-images.githubusercontent.com/108759216/210740835-0f173c17-0ec5-4aa8-a16b-c820c7612aab.png)

### Actual result

![image](https://user-images.githubusercontent.com/108759216/210742900-a19aac63-6fdc-4bd8-8c03-ebdee6a1baa5.png)

### Versions

Twill version: 3.0.0-rc1

**Comment by haringsrob** [comment]
could be https://github.com/area17/twill/pull/2010

**Comment by haringsrob** [comment]
Tested and confirmed this is resolved with https://github.com/area17/twill/pull/2010
