### ISSUE TITLE
Repeaters have wrong field values inside a cloned block

### ISSUE THREAD

**Issue by ianinadavydova** [area17/twill#2044]
## Description

When repeater is inside a block editor, and we clone this block, repeater's data is wrong, fields values are the same within several repeaters.
Maybe it is connected with https://github.com/area17/twill/issues/1818, but in that issue repeater's fields are empty and in my case I have them filled with wrong data

### Steps to reproduce

1. Define a block editor with repeater block.
2. Add several repeater items & fill it's form fields.
3. Duplicate the field.

Also possible to watch the video to understand: [Download example video.](https://drive.google.com/file/d/1dgdRmY3Yx30F4jHT7RT_uedsZ33UMlNx/view?usp=share_link)
### Expected result

Repeaters fields values in cloned block are exactly the same as in the initial block

### Actual result

Cloned repeaters fields data is wrong, it has the same values within several items instead of all different data in each of them, exactly like in the initial block
![photo1663749667](https://user-images.githubusercontent.com/17748052/211036545-fda117b5-dd4a-4525-a107-fca94659447e.png)

### Versions

Twill version:  2.8.7
Laravel version: 8.0
PHP version: 7.4
 Database engine: Mysql: 5.7

**Comment by haringsrob** [comment]
hey @ianinadavydova is this a json repeater?

**Comment by ianinadavydova** [comment]
@haringsrob Hey, it is this repeater https://twill.io/docs/1.x/#adding-repeater-blocks

**Comment by ifox** [comment]
Related to #1818
