### ISSUE TITLE
Inconsistencies in directory casing cause issues on case-sensitive OS (Linux)

### ISSUE THREAD

**Issue by luislavena** [area17/twill#2053]
## Description

When using `twill:make:capsule`, the generated directory structure creates a `database` directory (notice being all lowercase) but PSR4 is expecting the namespace/directory to match (Eg. `Database`).

Looking at the code, found that `createCapsuleSingletonSeeder` in `ModuleMake` calls `getDatabaseNamespace`, which returns `\Database` (good), but then `databasePath()` uses `getDatabasePsr4Path`, which returns inconsistent responses depending if the directory exists or not:

https://github.com/area17/twill/blob/3.x/src/Helpers/Capsule.php#L150-L156

```php
    public function getDatabasePsr4Path(): string
    {
        if (File::exists($this->path . DIRECTORY_SEPARATOR . 'Database')) {
            return $this->path . DIRECTORY_SEPARATOR . 'Database';
        }
        return $this->path . DIRECTORY_SEPARATOR . 'database';
    }
```

Here, in all scenarios it should be returning `Database` or `database`, consistently, but not sure if that will have an impact when loading database migrations or other Laravel conventions.

### Steps to reproduce

Use `artisan twill:make:capsule SomeName --singleton` and make sure to include seeds.

Please note that this is observable **only** on case-sensitive file systems like Linux.

### Expected result

The module that uses seeds should load without issues.

### Actual result

An exception is thrown when visiting the module since is not found:

```
App\Twill\Capsules\ContactPages\Database\Seeds\ContactPageSeeder is missing
{"userId":1,"exception":"[object] (Exception(code: 0): App\\Twill\\Capsules\\ContactPages\\Database\\Seeds\\ContactPageSeeder is missing at /app/vendor/area17/twill/src/Http/Controllers/Admin/SingletonModuleController.php:67)
[stacktrace]
#0 /app/vendor/area17/twill/src/Http/Controllers/Admin/SingletonModuleController.php(31): A17\\Twill\\Http\\Controllers\\Admin\\SingletonModuleController->seed()
#1 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): A17\\Twill\\Http\\Controllers\\Admin\\SingletonModuleController->editSingleton()
#2 /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('editSingleton', Array)
```

### Versions

Twill version:  `3.0.0-rc1`
Laravel version: `9.46.0`
PHP version: `8.1.13`
Database engine: PostgreSQL

**Comment by haringsrob** [comment]
hey @luislavena thanks for the report.

I will setup my system to use a case sensitive filesystem and check this later on this week.

**Comment by ifox** [comment]
Thanks @luislavena. 

Regarding the following:
> in all scenarios it should be returning Database and not database
I don't think that's correct. The directory name convention is lowercase `database`. That's why Laravel has a custom mapping in its default composer.json to map the starting with uppercase namespace to the starting with lowercase path.

**Comment by luislavena** [comment]
Hello @ifox, you're correct, I didn't check that Laravel's convention is `database` vs what was on the code checking for `Database`. Ideally the conventions should be honored, making more easy for people to use them.

@haringsrob you don't need to reinstall your machine! 😅 

You can create a case sensitive volume that shares the same disk space using something like the following command:

```console
$ diskutil apfs addVolume disk3 \"Case-sensitive APFS\" myvolume
```

This will create `myvolume` inside `/Volumes` which you can use to clone repositories there and run the app. Not sure if something like Valet will work (since is not inside user's home) but a symlink could also work.

Thank you for looking at this!
❤️ ❤️ ❤️

**Comment by haringsrob** [comment]
Hey @luislavena great tip. Here's a related article that I followed: https://brianboyko.medium.com/a-case-sensitive-src-folder-for-mac-programmers-176cc82a3830

**Comment by haringsrob** [comment]
I have checked, and we should default to `Database` instead of `database`.

Reason is, that, because the is is project code, there is no composer telling that `database` is psr4 by the composer mapping. 

For this reason we should attempt Database first, and when building default to that as well.

**Comment by haringsrob** [comment]
Fixed with https://github.com/area17/twill/pull/2057

**Comment by luislavena** [comment]
Thank you @haringsrob, took a look at #2057 but based on what you wrote, I'm not sure I understood the check for `database` existence and then testing for `Database`.

Based on what you said, `database` wouldn't work, so why testing for it?

Curious to understand the change. 😊 

Thank you.
❤️ ❤️ ❤️

**Comment by haringsrob** [comment]
database can work, if you setup your composer. Which may be the case for package capsules, that's why I am leaving it in.

The double checking is there because the generator uses the same method.
