### ISSUE TITLE
[Question] How to prefix DB tables

### ISSUE THREAD

**Issue by OwenMelbz** [area17/twill#206]
Hi,

Twill creates a `twill_users` table, which is absolutely fine :)

However, it doesn't take this liberty with other tables, e.g. tags, files etc

This causes problems for adding Twill to pre-existing projects that already use those tables for domain entities.

Is it be possible to make sure all twill tables are namespaced correctly to prevent conflicts?

Thanks

**Comment by ifox** [comment]
That's a very good suggestion @OwenMelbz, I'll add the ability to provide custom table names from configuration like for the twill_users table. We'll keep defaults in 1.2.2 to the current non prefixed names but when it is time for 1.3 we can definitely change all table names to prefixed.

**Comment by ifox** [comment]
Resolved by 7fced6057183e624b0acdf0805f4513b1d9b9623.
