### ISSUE TITLE
[3.x] Settings only return the first child in the block

### ISSUE THREAD

**Issue by sauron** [area17/twill#2060]
When using `getGroupDataForSectionAndName` it returns only the first child of the block.
https://github.com/area17/twill/blob/c4977b66c900175abfde87cfb257c1287ae2aa14/src/TwillAppSettings.php#L97

A use case that I see for the Settings is to set the Navigation or Footer which may consist in a Repeater with Links. for example:
```php
    @twillBlockTitle('Main Navigation')
    @twillBlockIcon('text')
    @twillBlockGroup('app')
    
    <x-twill::repeater
        type="links"
    />
```
With the actual implementation it will only return the first item.

I think it worth to have a helper that makes it easier even when this can be manually achieve by using 
```php
    TwillAppSettings::getGroupForName($group)->getSettingsModel()->blocks()->where('editor_name', $section)->get())
```
Maybe a `getAllBlocksForSectionAndName` function.

**Comment by haringsrob** [comment]
hey @sauron,

This was actually a bug getGroupDataForSectionAndName should return the parent block not the repeater.

I did fix this, and also added child accessor. So for example:

```
TwillAppSettings::get('homepage.homepage.links')
```

Should give a collection of the repeater if the name is 'links'

https://github.com/area17/twill/compare/2060-fix-accessor?expand=1
