### ISSUE TITLE
[3.x] Settings: Ability to add more than one SettingGroup

### ISSUE THREAD

**Issue by sauron** [area17/twill#2073]
## Summary

Since the new Settings gives much more flexibility than before, it will be great to be able to add more than one Setting group.
Something like:
```php
        TwillAppSettings::registerSettingsGroups(
            SettingsGroup::make()
                ->name('site-settings')
                ->label('General settings'),
            SettingsGroup::make()
                ->name('footer-settings')
                ->label('Footer settings'),
        );
```
And it will be render as tabs similar to the secondary navigation.

**Comment by haringsrob** [comment]
This is added in https://github.com/area17/twill/pull/2092
