### ISSUE TITLE
Is it possible to override the default login route view?

### ISSUE THREAD

**Issue by tbrasington** [area17/twill#208]
I have been implementing Google Login as per the guidance in https://github.com/area17/twill/issues/150 I have everything working except overriding the login page with my cloned version of the page. (I am using a different route to serve the custom login page at the moment)

Is this even possible with Twill? I have been reading up on older versions of Laravel let you do a straight override of routes if they had the same path but with the later versions the autoload of packages has stopped that working. I have tried adding the Twill provider before the routes provider to no avail. 

I am using admin as a folder for the domain and have tried combinations

```
Route::get('/admin/login', 'Auth\LoginController2@showLoginForm')->name('login');
Route::get('/login', 'Auth\LoginController2@showLoginForm')->name('login');

Route::get('/admin/login', 'Auth\LoginController2@showLoginForm')->name('login.form');
Route::get('/login', 'Auth\LoginController2@showLoginForm')->name('login.form');

Route::get('/admin/login', 'Auth\LoginController2@showLoginForm');
Route::get('/login', 'Auth\LoginController2@showLoginForm');
```

Any guidance on this would be appreciated greatly 🙏

**Comment by ifox** [comment]
Hi Thomas!

You should be able to override Twill's login view at `resources/vendor/twill/auth/login.blade.php` to add your custom route. We should just make it a configuration variable though.

**Comment by tbrasington** [comment]
Hey, thank you for getting back to me. I have set up my view here:

<img width="2032" alt="Screenshot 2019-03-17 at 13 48 44" src="https://user-images.githubusercontent.com/662056/54492106-8c36da00-48bb-11e9-9136-22f2302957f2.png">

and then have a my routes setup in web.php like this:

<img width="2032" alt="Screenshot 2019-03-17 at 13 58 21" src="https://user-images.githubusercontent.com/662056/54492257-da98a880-48bc-11e9-9cca-16bdf3548b23.png">

Which leads to two login pages existing:

**Custom Route**
<img width="2032" alt="Screenshot 2019-03-17 at 13 52 06" src="https://user-images.githubusercontent.com/662056/54492263-e71d0100-48bc-11e9-91de-d09f1e95ff49.png">

**Twill Route**
<img width="2032" alt="Screenshot 2019-03-17 at 13 51 58" src="https://user-images.githubusercontent.com/662056/54492261-e71d0100-48bc-11e9-826d-d892a7bdaed9.png">

^^ these two I just want to merge as the Logout action sends users back to `admin/login`

--

I see that in 1.2.1 that setting google login to enabled now works with the blade template. What would be nice if we could also then set the path with something like this:

```
 'enabled' => [
        'google-login' => true,
        'google-login-route'=> 'redirect'
    ],
```

```
<a href="{{ config('twill.enabled.google-login-route') }}" class="login__google" tabindex="4">
```

As that would then solve this particular request

**Comment by ifox** [comment]
Hi @tbrasington,

try removing the `area17` folder from your override. It should be under `resources/views/vendor/twill/auth/login.blade.php`. 

Once that is working, you won't need to add a custom route to access the form anymore, only the ones to process the actual login request.

**Comment by tbrasington** [comment]
Such a simple fix. Thank you!
