### ISSUE TITLE
How can I check several items on a multi_select form field by default?

### ISSUE THREAD

**Issue by manuelsofia** [area17/twill#210]
Is there a way to do this? The content on this multi_select is not based on a relationship so I need to manually mark the ones I want to be checked by default. Perhaps is there an option like ```"checked" => true``` or something similar that I'm missing? Thanks!

**Comment by yanhao-li** [comment]
Hi @manuelsofia ,

There are several methods in ModuleRepository.php could be overridden to modify the default behavior of the form fields. 
For your use case, I would use the `prepareFieldsBeforeCreate ` function, check out the documentation [here](https://twill.io/docs/#repositories).

**Comment by manuelsofia** [comment]
Hello @yanhao-li , thank you very much for your answer. I think I didn't explain my issue correctly. If I'm not mistaken, the ```prepareFieldsBeforeCreate``` method will let me add default values after the form is submitted. What I need to do is to load a the form view with some options checked by default on a multi_select form component. On an input field I can add the "default" property, but on a multi_select, if I'm not mistaken, there's no way to do that. Is there any other way I can achieve this? Thanks!

**Comment by yanhao-li** [comment]
Hi @manuelsofia ,
>If I'm not mistaken, the prepareFieldsBeforeCreate method will let me add default values after the form is submitted. 

Yes, you are right. However, different from another method `prepareFieldsBeforeSave`, `prepareFieldsBeforeCreate` is used to construct the formFields before the instance created, that means the actions order will be `form submit => prepareFieldsBeforeCreate() => instance created`.

Right there in the `prepareFieldsBeforeCreate` method you could provide default values to the fields, and once the instance created and form get rendered, you should be able to see the form with default values you set before!

Hope this helps!

**Comment by manuelsofia** [comment]
@yanhao-li thank you so much! I really appreciate your help, you guys are amazing :)
