### ISSUE TITLE
Issue in repeater field in image display

### ISSUE THREAD

**Issue by devimako** [area17/twill#2102]
In repeaters if i save images in the json field the image is not display only title is displayed and i try to upload another image for next fields previous image in json fields is getting deleted 
<img width="875" alt="Screenshot 2023-01-16 at 10 06 54 PM" src="https://user-images.githubusercontent.com/99637767/214512059-3d619e79-3e3b-44aa-937f-a7f736910db4.png">

**Comment by kallefrombosnia** [comment]
It would be good if you can provide us with more info regarding this issue.

Twill version: 
Laravel version: 
PHP version: 
Database engine:
Any dev console errors?

**Comment by haringsrob** [comment]
Did you add block crop configurations to your config/twill.php file?

**Comment by devimako** [comment]
Twill version:2.0
Laravel version:9
PHP version:8.2
Database engine:pqsql

**Comment by devimako** [comment]
not added any block crop configuration in twill.php and i didnt used any block form only used repeater method

**Comment by devimako** [comment]
In the twill 
<img width="826" alt="Screenshot 2023-01-25 at 5 29 50 PM" src="https://user-images.githubusercontent.com/99637767/214558080-f5648267-966d-41fa-a8c0-bf01bbf218a8.png">
documentation they have given demo project in that they display image in repeaters fields
 my i know how it is

**Comment by haringsrob** [comment]
If your repeater is another model/module it can work.

This is document here https://twill.io/docs/form-fields/repeater.html#using-repeater-fields
