### ISSUE TITLE
[3.x] Index table actions are not triggered anymore

### ISSUE THREAD

**Issue by joyceverheije** [area17/twill#2111]
Actions like unpublish and delete in the screenshot below are not working anymore. It is still possible to use them by using the bulk feature. The edit action/link still works.

<img width="178" alt="Screen Shot 2023-01-27 at 12 27 33" src="https://user-images.githubusercontent.com/18153771/215075520-85e3c80e-88ce-449f-bc92-a8f9eed80551.png">

### Versions

Twill version:  3.0.0-rc2

**Comment by haringsrob** [comment]
Hey @joyceverheije,

I cannot reproduce this. Do you see any console errors?
