### ISSUE TITLE
CMS search case sensitivity with translated models and Postgres

### ISSUE THREAD

**Issue by joyceverheije** [area17/twill#2112]
## Description

When using translated models, the index search field in the CMS is case-sensitive.

### Expected result

When using translated models, the index search field in the CMS is case-insensitive.

**Comment by haringsrob** [comment]
Hey @joyceverheije are you on postgresql? 

Might be related to https://github.com/Astrotomic/laravel-translatable/issues/17

**Comment by joyceverheije** [comment]
Hey @haringsrob, yes I'm using postgresql, thanks for the link!
