### ISSUE TITLE
ViewException - Unable to create a directory on fresh install

### ISSUE THREAD

**Issue by kerkness** [area17/twill#2119]
## Description

Creating a fresh install of Laravel 9 and Twill 3.x results in a View exception when trying to edit main admin profile or any module. It is the same result with `3.x-dev`  and `3.0.0-rc3`

### Steps to reproduce

Created a laravel project with
 `composer create-project laravel/laravel mfa-twill`
Added Twill with
```
composer require area17/twill:3.x-dev
php artisan twill:install
php artisan storage:link
```
Then logged into admin console and tried to access my profile at 
`https://content.crid.ca/admin/users/1/edit`

### Result

Full error is  `Illuminate\View\Exception`
`Unable to create a directory at /var/app/current/mfa-twill/app/View/Components/Twill/Blocks. (View: /var/app/current/mfa-twill/vendor/area17/twill/views/partials/form/utils/_blocks_templates.blade.php) (View: /var/app/current/mfa-twill/vendor/area17/twill/views/partials/form/utils/_blocks_templates.blade.php) (View: /var/app/current/mfa-twill/vendor/area17/twill/views/partials/form/utils/_blocks_templates.blade.php)`

Does not appear to be the result of folder permissions.  Ensured the folders were owned by nginx user and also changed permissions to `777` with same result.

### Work around

I was able to work around the issue by changing the permissions on `app` and `vendor` folders and then reverting permissions

```
chmod -R 777 app
chmod -R 777 vendor
# refresh /admin/user/1/edit and form loads and works
chmod -R 775 app
chmod -R 775 vendor
# form still loads and works
```

This is curious. Would possibly indicate the issue only exists when accessing the form for the first time.

### Versions

Twill -  `3.x-dev` and `3.0.0-rc3`
Laravel `^9.19`
PHP `^8.0.2`
MySQL/Nginx

**Comment by kerkness** [comment]
### Update

After running `php artisan twill:install`   the folder  `app/View/Components/Twill/Blocks` is successfully created with permissions `drwx------`

So this will be the issue for me.  When I create my project I am doing so from the command line as a sudoer user.  Nginx however is running as `www-data` .   My user belongs to the `www-data` group.  This is usually sufficient permissions for my laravel projects and packages that I build.

So the error is not that the directory doesn't exist but that it doesn't like the permissions.

**Comment by haringsrob** [comment]
hey @kerkness 

Thank you for the extensive report.

While this issue was more related to your environment, we should not create the directory if there is no need.

In https://github.com/area17/twill/pull/2124 we added a check that will avoid this directory to be created.

Kind regards,
