### ISSUE TITLE
Block Icons

### ISSUE THREAD

**Issue by jkhamler** [area17/twill#212]
What icons are there available for the blocks - just 'image' and 'text'? It would be great to have a few other options to differentiate my blocks.

![image](https://user-images.githubusercontent.com/7847437/54370683-f6f3d580-466f-11e9-83bd-d344d66b416d.png)

**Comment by yanhao-li** [comment]
Hey @jkhamler ,

Checkout the [icon folder](https://github.com/area17/twill/tree/1.2/frontend/icons) in the codebase. I believe any file names there could be used.

**Comment by jkhamler** [comment]
Thanks @yanhao-li I knew there would be loads of options.

**Comment by CaelanStewart** [comment]
Also, you can do:

`artisan twill:list:icons` to get a current list without looking at the codebase.

Though that command is of limited utility, and you'll likely still want to download a copy of them so you can see how the look.

On that point, a visual icon grid would be a useful addition to the docs. There's not many in there at the moment so you could probably forego filter/search.

**Comment by pboivin** [comment]
Quite undocumented but there is a version of that, which you can access at `http://app.test/admin/admin/icons` (or `http://admin.app.test/admin/icons` depending on your setup). This will likely be improved in the near future :)

**Comment by CaelanStewart** [comment]
@pboivin – Oh perfect, that's handy!

Many thanks for that.
