### ISSUE TITLE
Error retrieving credentials from the instance profile metadata service. 

### ISSUE THREAD

**Issue by broswilli** [area17/twill#2130]
## Description

After authentication the admin users sees the following error:
` Error retrieving credentials from the instance profile metadata service. (cURL error 28: Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/) (View: /var/www/learning/php/laravel/twill/vendor/area17/twill/views/layouts/dashboard.blade.php)
http://twill.test/admin `

### Steps to reproduce

After installation on an new and empty laravel installation:
the env settings were as follows:
`##Twill Configuration settinds
ADMIN_APP_URL=http://twill.test
ADMIN_APP_PATH=admin
MEDIA_LIBRARY_ENDPOINT_TYPE=local
MEDIA_LIBRARY_LOCAL_PATH=uploads
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Glide
MEDIA_LIBRARY_FILESIZE_LIMIT=50
`

### Expected result

Expected to see the twill dashboard

### Actual result

` Error retrieving credentials from the instance profile metadata service. (cURL error 28: Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/) (View: /var/www/learning/php/laravel/twill/vendor/area17/twill/views/layouts/dashboard.blade.php)
http://twill.test/admin `

### Versions

Twill version:  2
Laravel version: 8
PHP version: PHP 7.4.3-4ubuntu2.17
Database engine: MySql

**Comment by ifox** [comment]
Hi @broswilli, please try adding: `FILE_LIBRARY_ENDPOINT_TYPE=local`.

Also, I'd recommend you try Twill 3 where this is not an issue anymore on first install as we defaulted to a local setup as it is clear that S3 by default was not adequate. We are about to release RC4 and the stable will be out in the next few weeks.

**Comment by broswilli** [comment]
@ifox Thank you it is resolved. I will install version 3 making media and file config default to local is more intuitive. Thank you so much
