### ISSUE TITLE
Enable access to Auth::user() from getForm & getSideFieldsets Method in 3.x

### ISSUE THREAD

**Issue by kerkness** [area17/twill#2132]
## Summary

The methods `ModuleController::getForm` & `ModuleController::getSideFieldsets`  are called within the class `__construct` method.  As a laravel limitation, the class is constructed before any middleware on the route has run and the request lifecycle does not yet have knowledge of who the authenticated user is.

Because of this trying to use any of the following methods to gain knowledge of the active user while using the FormBuilder in a module results in `null`

```
auth()->user();
auth('twill_users'`)->user();
$this->user;
$this->request->user();
```  

Applying inline middleware inside the `__construct` method does not seem to provide a solution.

`ModuleController::__construct`  does  assign `$this->user = auth('twill_user')->user()`  within a `$this->middleware` closure before it executes `getForm` & `getSideFieldsets`. However doing a trace on this reveals that  the form builder methods are still executed before this inline middleware.

## Describe the solution you'd like

Move the calls to  `ModuleController::getForm` & `ModuleController::getSideFieldsets`  outside of the `__construct` method and possibly as part of the actual `TwillRoutes::module` callback.  I haven't learned enough about Twill yet to know if this is possible or be able to test that out.

## Additional context

For my own purposes the reason I wanted to do this is because my larger Laravel project uses Teams permissions as provided by `spatie/laravel-permission`   I wanted to modify the options on a Select field based on the team membership of the current authenticated user.  I added a middleware which matched TwillUser with my own User model for authorization,  but as described above the FormBuilder process has already been executed before this authorization happens.

I was able to achieve what I wanted by not using the Form builder and just using the more traditional blade forms.

**Comment by haringsrob** [comment]
Hey @kerkness in order to properly tackle this issue we need to know how/why you are using the user.

As we are supporting dynamic repeaters, we may need to build the form as an anonymous user.

This does not mean that the user cannot be used, but we may have to change the strategy so that you have to use a closure instead.

It would be greatly appreciated if you could show us how you are using it.

**Comment by kerkness** [comment]
In my project I already manage users using the spatie/laravel-permission and make use of the `teams` feature.  We have multiple organizations, and multiple users per organization.  Each organization manages their own objects across 8 or 9 primary models.  This is all done outside of Twill.  It's essentially a product database, but used across multiple organizations and with specific organizations owning specific products.

We are using Twill (at least in our development branch atm)  to manage the content requirements for public website pages. 

On the Twill side I have created a Module call `TwillArtist`.  This purpose is to hold biography content on that artist primarily through blocks.  However I need to connect or link this artist with a non Twill model called  `Creator`  which will be owned by a specific organization.

The plan is to provide a simple Select field on TwillArtist form which is populated with a list of `Creators`.   However to load this list I must know what organization the current Twill User belongs to.

I have already created a middleware which links  a `TwillUser` with an organization `User`

```
class TwillUserHasArtMoiUser
{
    public function handle(Request $request, Closure $next)
    {

        if(!empty(auth('twill_users')->user())) {

            $user = User::where('email', auth('twill_users')->user()->email)->first();

            if($user) {
                session(['twill_artmoi_user' => $user]);
            }

        }

        return $next($request);
    }
}
```

For the select form, I am now using the Blade Component since the session data or auth()->user() isn't populated with the `getForm` method.

```
    public function __construct($item)
    {
        //
        $this->item = $item;
        $this->artmoiUser = session('twill_artmoi_user', false);

        if($this->artmoiUser) {
            $this->fetchCreators();
        }

    }

    protected function fetchCreators()
    {
        // Find ArtMoi Creators.
        $creators = Creator::withPermissions($this->artmoiUser)
            ->withSearch($this->item->name, $this->artmoiUser)
            ->get();

        if($creators->isNotEmpty()) {
            $this->creatorOptions = $creators->map(function($creator) {
                return [
                    'value' => $creator->id,
                    'label' => '#' . $creator->id . '- ' . $creator->display_name,
                ];
            })->toArray();
        }

    }
```

Then the blade template for the form

```
<x-twill::select 
    name="creator_id"
    label="ArtMoi Creator"
    placeholder="Match with ArtMoi Creator"
    :options="$creatorOptions"
/>
```

 I realize there are probably several ways to tackle this scenario and it maybe out of scope for Twill's roadmap.
 
 Essentially what I want to do is create relationships between Twill Modules and non-Twill models.  It would seem like this would allow Twill to integrate into a lot of other projects without being the primary "object" management tool.

HTH

**Comment by haringsrob** [comment]
Hey @kerkness thank's a lot, really helpfull.

I have added closure support to the options field (we may do this in more places in the future.)

This will allow you to do the following (Very dumb example but it illustrates the possibility):

```php
            Select::make()->name('cover')->options(function (): Options {
                $user = Auth::user();
                return Options::make()->add(Option::make($user->id, $user->name));
            })
```

That should resolve the issue you have as the options will only be evaluated when the form is built for usage.

**Comment by kerkness** [comment]
Amazing.  That will be very useful.  Very much appreciated.
