### ISSUE TITLE
Multiple browsers for same module not working properly - Twill v 2.12

### ISSUE THREAD

**Issue by power-media** [area17/twill#2134]
## Description

For single module, I tried to add two browsers referring to the same module, using different browser names.
This works partially, the entries in "related" table are created, but nothing displays in the browsers upon module reload.
Using one browser per module in module works as expected.

### Expected result

I expect adding multiple browsers referring to the same module (in single module) be possible.

### Versions

Twill version: 2.12.4

Laravel: 9.50.2

PHP: 8.2.2

Database: MySql

**Comment by haringsrob** [comment]
Hey @power-media I checked this and you may need to setup relatedbrowsers in a different way:

Here's an example:
```php
protected $relatedBrowsers = [
    'page_1' => [
        'moduleName' => 'pages',
        'relation' => 'page_1'
    ],
    'page_2' => [
        'moduleName' => 'pages',
        'relation' => 'page_2'
    ]
];
```
