### ISSUE TITLE
Rows per page is not working in admin panel

### ISSUE THREAD

**Issue by devimako** [area17/twill#2137]
## Description
I need to display the records using pagination in twill dashboard and i used per page = 20 in controller but is not working 

### Expected result
Need pagination in dashboard to list the records

### Versions
Twill version: 2
 Laravel version: 9
 PHP version: 8.2
Database engine: pgsql

<img width="1385" alt="Screenshot 2023-02-08 at 1 46 30 PM" src="https://user-images.githubusercontent.com/99637767/217472987-7d0061a1-49fd-48b2-84ed-f73b16f38132.png">

<img width="685" alt="Screenshot 2023-02-08 at 1 46 40 PM" src="https://user-images.githubusercontent.com/99637767/217472950-9d638fed-b172-4a5b-afe5-0de3b7043a09.png">

**Comment by devimako** [comment]
@kallefrombosnia  thanks for your reply now per page is working  but i need the form directly if i click the menu but what i am getting is index page
This is what i need 
<img width="1440" alt="Screenshot 2023-02-09 at 7 35 02 PM" src="https://user-images.githubusercontent.com/99637767/217835040-0a1adf8b-85af-46c4-af10-282297082a69.png">
but getting this page
<img width="1438" alt="Screenshot 2023-02-09 at 7 35 07 PM" src="https://user-images.githubusercontent.com/99637767/217835053-659ab5ff-bf35-495a-8c29-1782046c2bf9.png">

**Comment by kallefrombosnia** [comment]
Then you used the wrong feature for that.
What you see on the Twill demo page is the `singleton` feature, what you are using is the `module`.

Check docs: https://twill.io/docs/crud-modules/cli-generator.html#singleton

**Comment by haringsrob** [comment]
As the original and follow up questions were answered I will close this issue.

**Comment by devimako** [comment]
how to separate the two blocks in the same module because i am getting all the block if i use in the same module 

i need to use this blocks as separate for each section in page 
<img width="1423" alt="Screenshot 2023-02-13 at 12 20 39 PM" src="https://user-images.githubusercontent.com/99637767/218390716-9385fa8a-ae29-4b0e-ba20-7a056122d080.png">

<img width="691" alt="Screenshot 2023-02-13 at 12 23 10 PM" src="https://user-images.githubusercontent.com/99637767/218390727-8c6e1be0-2739-443f-8e1a-649c8fabaa68.png">
