### ISSUE TITLE
How to override/overwrite twill blade templates in our theme view folder? 

### ISSUE THREAD

**Issue by vrdvishwas** [area17/twill#214]
I'm try to add logo in Admin Login Blade and admin internal pages.
But got no way to override the templates.

**Comment by ifox** [comment]
Hi @vrdvishwas,

You can override any template under `resources/views/vendor/twill`. I would suggest to only override the `_title` partial if you're trying to add a logo there.

**Comment by vrdvishwas** [comment]
Thanks It works.
