### ISSUE TITLE
[3.x] Add Dusk to require-dev

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#2153]
Because Twill 3 is refering to `Laravel\Dusk\Browser` I believe Dusk should be added to composer.json. Otherwise any packages doing static analysis on a Twill based code will have to add Dusk to their own composer.json.

```bash
Error thrown in /Users/antonioribeiro/code/area17/twill-google-recaptcha/vendor/area17/twill/src/DuskServiceProvider.php on line 17 while loading bootstrap file /Users/antonioribeiro/code/area17/twill-google-recaptcha/vendor/nunomaduro/larastan/bootstrap.php: Class "Laravel\Dusk\Browser" not found
```

**Comment by haringsrob** [comment]
Hey @antonioribeiro,

Might be wrong but require-dev is never installed as part of the install process of packages.

Are you running composer install in twill vendor's folder?

**Comment by antonioribeiro** [comment]
Hey @haringsrob, if you are developing a package and you need to do a `composer install` inside the package folder (vendor/area17/twill-firewall for instance) to have all dependencies plus PHPUnit and PHPStan available for running package tests, Twill will be installed, because it's a dependency of the package, so when I run 

```bash
vendor/bin/phpstan analyse -v
```

I get 

```
Error thrown in 
/Users/antonioribeiro/code/client/project/vendor/area17/twill-firewall/vendor/area17/twill/src/DuskServiceProvider.php 
on line 17 while loading bootstrap file 
/Users/antonioribeiro/code/client/project/vendor/area17/twill-firewall/vendor/nunomaduro/larastan/bootstrap.php: 
Class "Laravel\Dusk\Browser" not found
```

Another solution would be to add Dusk to the package, but Dusk is not really a dependency of the package, and it's only a dependency for Twill 3.x, on Twill 2.x it works fine.

**Comment by pboivin** [comment]
Hi @antonioribeiro, I ran into the same issue recently. I added Dusk as a dev dependency of my package as you said. I agree that the package doesn't really care if Twill is using Dusk in its own test suite. Could this be handled on Twill's side, by only registering `DuskServiceProvider` if class `Laravel\Dusk\Browser` exists?
