### ISSUE TITLE
No Title On Model

### ISSUE THREAD

**Issue by devilwacause** [area17/twill#2156]
## Description

I have a model which I changed the "title" field to "name" - to fit a specific need.  In the editor - I get a "missing title" - how can we solve this to where it shows the name instead here.

### Steps to reproduce

Create new module.

Modify the migration and model, changing title to "name".

 2.12
 9.51
 8.1
 MariaDB 10.6

**Comment by ifox** [comment]
Hi @devilwacause, you can use the `$titleColumnKey` property of your module controller to indicate that you would like to use the `name` column instead of the default `title` column:

```php
protected $titleColumnKey = 'name';
```

**Comment by devilwacause** [comment]
Awesome - and thanks for the quick response :)

**Comment by poncianodiego** [comment]
What if I don't want a title at all? @devilwacause 

I can help PR if the docs are missing this info

**Comment by poncianodiego** [comment]
For now I'm just hiding it:

```
<style type="text/css">
    .titleEditor__title{
        display: none;
    }
</style>
```

Ugly but works
