### ISSUE TITLE
Fallback locale for translated fields

### ISSUE THREAD

**Issue by layout-lab** [area17/twill#216]
Hi,

Is the `fallback_locale` supported with `$block->translatedinput`? I have specified the fallback as per the `dimsav/translatable` documentation but I'm getting a null returned rather than the input for the fallback locale specified in my config.

Thanks

**Comment by ifox** [comment]
Hi @layout-lab,

It currently does not support using `fallback_locale` but you should be able to decide to support it globally in your application by using the `use_fallback` and `use_property_fallback` configuration of the `dimsav/translatable` package.
You can then disable it at the model level if needed too. Checkout their documentation, it's really good!

It could be nice to provide an option in Twill that only enables it when rendering blocks if that's something you need.

**Comment by ifox** [comment]
This is now supported in 1.2.2!
