### ISSUE TITLE
Files field in modal edit

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#220]
I noticed that I cannot use 'files' field (field is not shown) when I try to edit in modal with
```
protected $indexOptions = [
    'editInModal' => false,
];
```

I can, however, use it in 'create' modal if I disable above configuration and form view exists.

Is this intentional behavior?

**Comment by ifox** [comment]
Hi @zipavlin,

I assume your snippet should say `'editInModal' => true`, right?

I have to admit we never really had a use case for that, so the modal hasn't been tested to work with every single form field.

Are you saying that during the initial create action from the modal it correctly ends up saving the attached file?

**Comment by zipavlin** [comment]
Hi @ifox, thanks for your reply!

I tried again and I think I figured what is going on. I guess file field need record to already be created. Therefore it is hidden on 'create' view, but visible on 'edit' view. Therefore setting 'editInModal' doesn't really have any influence on it and I imagine this is actually desired behavior.
