### ISSUE TITLE
Running Twill within a Frame

### ISSUE THREAD

**Issue by jkhamler** [area17/twill#221]
Is it possible to run Twill within an iframe or similar container within the parent application? (i.e. within the panel highlighted in red) - if so, is this relatively easy to implement or am I potentially opening a huge and enormously expensive can of worms?

Thanks!

![Screenshot 2019-03-26 at 14 55 57](https://user-images.githubusercontent.com/7847437/55007832-fba57b80-4fd7-11e9-955d-4f87ea0af4eb.png)

**Comment by ifox** [comment]
Hi @jkhamler!

I would say why not? I can't think of anything that wouldn't work except for the challenge you have with logging in existing users transparently from your parent application. I have to give more thoughts to that.

**Comment by ifox** [comment]
Hi @jkhamler,

closing this as we didn't hear from you in a while. The challenge is not really in Twill's purview but rather a cross domain and iframing concern that you should be able to solve without changes to Twill's internals.
