### ISSUE TITLE
Sidefieldsets doesn't get rendered if there is only a fieldset

### ISSUE THREAD

**Issue by EpicKau** [area17/twill#2214]
## Description

Sidefieldsets doesn't get rendered if there is only a fieldset

### Steps to reproduce

`    public function getSideFieldsets(TwillModelContract $model): Form
    {
        $form = parent::getSideFieldsets($model);

        //  test dummy
        //  $form->add(Input::make()->name('dummy')->label('dummy'));

        $form->addFieldset(
            Fieldset::make()->title('Opengraph')->id('opengraph')->fields([
                Input::make()->name('og_title')->label('OG Title'),
                Input::make()->name('og_description')->label('OG Description'),
                Files::make()->name('og_image')->label('OG Image')
            ])
        );

        return $form;
    }`

### Expected result

the fieldset should be rendert without a extra field

### Actual result

nothing get rendered 

### Fix for this
Services\Forms\Forms.php Line 97
` public function hasSideForm(): bool
    {
        return $this->isNotEmpty() || ($this->sideForm && $this->sideForm->isNotEmpty());
        // return $this->sideForm && $this->sideForm->isNotEmpty();
    }`

### Versions

Twill: 3.00 - RC4 (git)

**Comment by ifox** [comment]
Thanks for reporting @EpicKau.

For reference, in the Blade forms, we have 2 sections (`sideFieldset` and `sideFieldsets`) to allow adding fields to a single fieldset or have the ability to add multiple fieldsets manually: https://github.com/area17/twill/blob/3.x/docs/content/1_documentation/4_form-fields/index.md#sidebar

**Comment by EpicKau** [comment]
fixed - https://github.com/area17/twill/pull/2234
