### ISSUE TITLE
Unable to completely delete values in Settings

### ISSUE THREAD

**Issue by madsem** [area17/twill#222]
Created a settings view, multiple input fields, I made them all required.
Then filled everything out, and realized that last field should be optional, to not lose everything I saved a value in that last field and then expected to be able to just delete the value and save the form again.

Doesn't work sadly, whenever I clear the value it simply doesn't update the table.
I see the `value` is set to `allow null`, so this is a bug I assume.

Always need a value, or it won't update:
![Screen Shot 2019-03-27 at 12 35 54 PM](https://user-images.githubusercontent.com/3166991/55073102-2a315e00-508d-11e9-884f-405a7428a363.png)

![Screen Shot 2019-03-27 at 12 38 18 PM](https://user-images.githubusercontent.com/3166991/55073130-39b0a700-508d-11e9-9c1e-b2147c8f526b.png)

**Comment by ifox** [comment]
Hi @madsem,

are you running Twill 1.2.1?

**Comment by madsem** [comment]
Yes, it's a fresh install from today

**Comment by ifox** [comment]
Ok cool. I identified the issue in the settings repository. Empty fields are not sent by the frontend so those settings are not getting updated.

**Comment by ifox** [comment]
I'm not able to reproduce this on our latest builds. Feel free to open a new issue if you still run into this on `master`.
