### ISSUE TITLE
Can't use Form Columns in BlockComponent

### ISSUE THREAD

**Issue by kerkness** [area17/twill#2229]
## Description

Using `Columns::make()` in a BlockComponent doesn't appear to work.  Inputs render as expected but values are not saved.

### Steps to reproduce

Create a blockComponent with the following `getForm` method

```
public function getForm(): Form
{
    return Form::make([
        Medias::make()->name('content_image'),
        Input::make()->name('title')->label('Title'),
        Wysiwyg::make()->name('text')->label('Caption'),
        Columns::make()
            ->left([
                Input::make()->name('height')->label('Height'),
            ])
            ->right([
                Input::make()->name('width')->label('Width'),
            ]),
    ]);
}

```

### Expected result

Would expect that `height` and `width` input values are saved and accessible 

### Actual result

Height and Width inputs are not saved.   Form however renders as expected.

### Versions

Twill 3.x
Laravel 10.x

**Comment by ifox** [comment]
Hi @kerkness, we are going to need more detail. What do you mean by "can't use Form"?

**Comment by kerkness** [comment]
I hit enter before adding my comment :P

**Comment by ifox** [comment]
Thanks @kerkness, no worries!

This [PR](https://github.com/area17/twill/pull/2192) was meant to fix columns support in block components, we'll take another look!

**Comment by kerkness** [comment]
Okay my bad.  looks like i didn't have the latest release
