### ISSUE TITLE
Cannot use response()->download method in controller

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#224]
Hey,

response()->download() fails with error when tried to use it in custom ModuleController method:
```
Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header()
```
in vendor\area17\twill\src\Http\Middleware\ValidateBackHistory.php

```
namespace A17\Twill\Http\Middleware;
 
use Closure;
 
class ValidateBackHistory
{
 
    public function handle($request, Closure $next)
    {
        $response = $next($request);
 
        return $response
            ->header('Cache-Control', 'nocache, no-store, max-age=0, must-revalidate')
            ->header('Pragma', 'no-cache')
            ->header('Expires', 'Sat, 01 Jan 1990 00:00:00 GMT');
 
    }
}
```

Removing 'ValidateBackHistory' middleware from Twill's RouteServiceProvider resolves this issus (as one would imagine :))

Do you have any thoughts on how to resolve this?

**Comment by zipavlin** [comment]
It is possible to simply check response type in middleware, like that:

```
class ValidateBackHistory
{
    public function handle($request, Closure $next)
    {
        $response = $next($request);
        return get_class($response) == 'Symfony\Component\HttpFoundation\BinaryFileResponse' ? $response : $response
            ->header('Cache-Control', 'nocache, no-store, max-age=0, must-revalidate')
            ->header('Pragma', 'no-cache')
            ->header('Expires', 'Sat, 01 Jan 1990 00:00:00 GMT');

    }
}
```

But I am unsure of possible complications with this approach.

**Comment by ifox** [comment]
Hey @zipavlin,

Thanks for identifying the issue. Should we check for  the header method existence on the response object instead? Or maybe the response object has something for us to check if the response type can return headers already? I guess BinaryFileResponse isn't the only one affected.

**Comment by zipavlin** [comment]
Hey @ifox,

You are absolutely right! Checking for specific class seemed wrong, but I didn't thought of simply checking if method exists. Thanks!

Will you implement this, or should I make a PR?

**Comment by ifox** [comment]
I'll happily review a PR @zipavlin, thanks for proposing!

**Comment by zipavlin** [comment]
OK, I made a PR
