### ISSUE TITLE
Issue restoring revisions that have blocks with repeaters

### ISSUE THREAD

**Issue by layout-lab** [area17/twill#225]
Hi,

I am an experiencing an issue when a user restores an item to a previous revision that contained a block with repeater item(s) the content within the repeater (translated inputs, media) is lost. 

The content does appear in the preview / compare version view.

Does anyone have any tips on what to look for? Or can anyone else replicate this?

Thanks

**Comment by ifox** [comment]
Hi @layout-lab,

I can certainly replicate but have a question first: are you sure the content does appear in the preview / compare view, even after changing something and not saving? After saving it obviously shows as it is actually in database. What can happen during preview or restore is that the hydration of the model isn't at parity with the model coming from database. Happy to elaborate if that's not clear, but basically during those operations the model is dynamically filled with exactly what would be coming out of the database if it was actually saved.

**Comment by layout-lab** [comment]
Hi @ifox,

Thanks for the reply. To elaborate on my comments on the item preview; I was referring to the previous revision rendering correctly, rather than the preview of the item post restore, apologies if this misled you.

Currently I have recommended my users to not use the restore function, which is a shame as it's a great feature!

Thanks again for your work, and for taking the time to reply.

**Comment by ifox** [comment]
Hey @layout-lab! Just a ping to confirm I have found the root of this issue and will push a fix this week!

**Comment by nmsde** [comment]
Hey @ifox 
great work with Twill btw! 
Is this issue fixed? I've been experiencing the same issue. 

Can you tell what was the fix? 

Thank you!

**Comment by ifox** [comment]
Fixed in c2703b259142012e75dec16605793c08ed3c06f6 and released in Twill 1.2.2!
