### ISSUE TITLE
Legacy Settings Sections return values doesn't work

### ISSUE THREAD

**Issue by Antony-PL** [area17/twill#2257]
## Description

https://discord.com/channels/811936425858695198/1103932645773160510

### Expected result

Return values after save

### Actual result
After save, filedset is empty, values doesn't return.

### Versions

 Twill version:  3x
 Laravel version: 10x
 PHP version: 8.1
Database engine: MariaDB 10.11
Docker: yes
Ubuntu version: 22.04
# @ifox

**Comment by EPInformatyka** [comment]
@ifox - did you check, why Settings doesn't work ?

**Comment by ifox** [comment]
Hi @Antony-PL sorry for the delay on this, legacy settings are working fine in Twill 3 now: #2417.
