### ISSUE TITLE
Not able to load a custom component

### ISSUE THREAD

**Issue by toonvank** [area17/twill#2260]
## Description

I am trying to make a custom component for adding custom buttons to a wysiwyg field in twill admin forms.
I've created a project from scratch trying to implement the steps. This github repo: [Twill From Test](https://github.com/toonvank/Twill-form-test)

### Steps to reproduce

in `resources/assets/js/components/HelloWorld.vue`
```
<template>
 <!-- eslint-disable -->
 <div>
   Hello {{ name }}
 </div>
</template>
<script>
  /* eslint-disable */
  export default {
    props: ['name']
  }
</script>
```
in `resources/views/twill/partials/form/_hello-world.blade.php:`
`<a17-hello-world name="test"></a17-hello-world>`

and in my form: 
`@formField('hello-world')`

last step is that i execute this to build the component
`php artisan twill:build`

### Expected result

Renders "Hello test" on my form

### Actual result

The component is not loaded. In the place where the component should be loaded it's not working. 
If the vue component is loaded `@formField('hello-world')` it doesn't work and also like this `<a17-text-edit></a17-text-edit>`

**Comment by ifox** [comment]
Hi @toonvank, your reproduction repository does render "Hello test". There doesn't seem to be any issue with loading custom components,

<img width="967" alt="Screenshot 2023-06-01 at 2 54 55 AM" src="https://github.com/area17/twill/assets/708498/a82fef69-b130-405d-aed6-15a86b6599c6">
