### ISSUE TITLE
Function getSideFieldsets() doesn't work properly

### ISSUE THREAD

**Issue by marcindurlak** [area17/twill#2261]
## Description

Module function getSideFieldsets() doesn't work properly, because of incorrect definition of hasSideForm() function in A17\Twill\Services\Forms\Form class.

Below is hasSideForm() function from 3.x branch.
```
public function hasSideForm(): bool
{
    return $this->sideForm && ($this->sideForm->isNotEmpty() || ($this->sideForm->fieldsets && $this->sideForm->fieldsets->isNotEmpty()));
}
```

But after installing twill via
```
composer require area17/twill:"^3.0"
```

we have version 3.0.0, where hasSideForm() function looks like that
```
public function hasSideForm(): bool
{
    return $this->sideForm && $this->sideForm->isNotEmpty();
}
```
It is the same in the version tagged as 3.0.1.

**Comment by ifox** [comment]
Hi @marcindurlak, yes, we need to tag 3.0.2 with this fix. I want to merge a couple more fixes before doing so, but you can use `3.x-dev` as your composer version constraint for now if you want to have that fix until it is released.

**Comment by ifox** [comment]
Hi @marcindurlak, yes, we need to tag 3.0.2 with this fix. I want to merge a couple more fixes before doing so, but you can use `3.x-dev` as your composer version constraint for now if you want to have that fix until it is released.
