### ISSUE TITLE
Nested blocks don't seem to work

### ISSUE THREAD

**Issue by dweerd** [area17/twill#2267]
I have a module with a block_editor in its form. To one of these blocks, I added a nested block_editor, like in the examples:

`nested-block.blade.php`
```
@twillBlockTitle('Nested Block left right')
@twillBlockIcon('text')

<x-twill::block-editor name="left"/>
<x-twill::block-editor name="right"/>
```

But now in the editor I get this javascript error: `ReferenceError: nestedEditorName is not defined`, and I cannot add any nested blocks. Any clue why this is? I actually do provide a name as you can see.

Twill 3.0.1 (upgraded from 2.8.5), Laravel 10.11, PHP 8.1.12

**Comment by ifox** [comment]
Hi @dweerd, if this function is missing it means you probably did not update your Twill assets when upgrading. Try `php artisan twill:update`.

**Comment by dweerd** [comment]
Indeed, that fixed it. Thanks for quickly looking into it! How could I have known to do this? Maybe add it to the upgrade instructions (which I followed) at https://twillcms.com/docs/getting-started/upgrading.html?

(Also I did expect those instructions to tell you how to edit your composer file to get 3.0 in the first place, and maybe tell that you might need to upgrade Laravel first, as I had to)

Just want to say though, great work on this new version!! I appreciate the effort you put into making Twill even better and easier to work with 🙏!

**Comment by ifox** [comment]
That's a good point. In all our previous release notes we have this, which is missing from the 3.0 upgrade guide:

> Run composer update in your project and then, run Twill's own update command: php artisan twill:update. This will force update your published Twill assets. You can delete the old ones from your repository if you are versioning them. If you are using custom Vue components, you should rebuild Twill assets using php artisan twill:build.
