### ISSUE TITLE
Class-defined block doesn't render when nested.

### ISSUE THREAD

**Issue by dweerd** [area17/twill#2268]
In Twill 3.0, I have nested blocks. The block I am nesting is defined by class instead of as a view-file inside of `views/twill/blocks`. Rendering this block works fine on the top-level. But when I try to nest it, it is looking for the wrong view path.

In the frontend I render the nested blocks with ``` {!! $renderData->renderChildren('subblocks') !!} ```

This works fine for view-file defined blocks, but the class defined block gives this error:

```
An error occured trying to render:

View [site.blocks.app-related] not found. in (path to project)\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php
```

The correct view file path is defined in the render function of the block, but this doesn't seem te be used:

```
    public function render(): View
    {
        return view('components.twill.blocks.related');
    }
```

Is this a bug?

**Comment by ifox** [comment]
This is fixed on the 3.x branch and will be released shortly. You can try it with `3.x-dev` as your composer version in the meantime.
