### ISSUE TITLE
Upgrading from 2 -> 3 - seems helper functions are missing

### ISSUE THREAD

**Issue by kirkbushell** [area17/twill#2275]
## Description

Last night trying to upgrade from 2 -> 3: Getting lots of errors around helper functions. Specifically, functions like isActiveNavigation are missing - and I can't see them anywhere in the repo.

### Steps to reproduce

Upgrade Twill CMS from 2 -> 3

### Expected result

Helper functions should be available.

### Actual result

Helper functions are missing.

### Versions

 3.0.2
 9.52.7
 8.1.15
 MySQL

**Comment by ifox** [comment]
Hi @kirkbushell please share at least one of the error message/stack so we can help you.

Are you using helpers like isActiveNavigation in your own code? 

My first thought is that you published Twill blade layouts in the past, so you need to update them (or just delete them from your codebase if you aren't modifying them).

**Comment by kirkbushell** [comment]
@ifox yeah, that's exactly what it was - I simply had to re-publish the views :)

Cheers!
