### ISSUE TITLE
Is there a place to view examples?

### ISSUE THREAD

**Issue by raymondtri** [area17/twill#229]
Hello!

I am looking at CMS alternatives, and Laravel / Vue is an existing skillset of mine, as well as some of the other devs I work with on occasion. However, there seems to be some incomplete / outdated documentation with Twill, and I personally enjoy learning by example.

Are there any example projects or implementations laying around that I could take a look at? I like the architecture of Twill that I have seen so far, but I'm still a bit more washy than I would like on the architecture and recommended way of doing things.

Thanks!

**Comment by yanhao-li** [comment]
Hey @raymondtri ,

There are a few resources you maybe interested.
- [Step by step - Creating a Twill app](https://spectrum.chat/twill/tips-and-tricks/step-by-step-creating-a-twill-app~ac9bd7f7-d1e3-46a8-8e6f-6075d92cdac7)
- [Twill Demo](https://demo.twill.io/)

**Comment by raymondtri** [comment]
Yeah, I lived on the step by step for a few hours.

I'm starting to definitely get the hang of it, and I'm really hoping nested blocks becomes a thing soon.

I haven't tried this yet, but could you have multiple different repeaters within a block?

**Comment by yanhao-li** [comment]
@raymondtri 

hmm, nested block, i haven't tried it so far, but I believe it is possible, there is an interesting discussion about playing with embed blocks in Twill. https://github.com/area17/twill/issues/211#issuecomment-474252593

and multiple different repeaters within a block is definitely supported!

**Comment by ifox** [comment]
Hi @raymondtri, 

repeaters in blocks are definitely supported, is this what you are calling nested blocks?

**Comment by raymondtri** [comment]
No, not repeaters. Actual nested blocks. 

The issue to me with repeaters seems to be that you would have to define each potential kind of block that could be repeated, and you couldn't order multiple types of repeaters inside of each other.

IE:
n * repeater-item-1, n * repeater-item-2, n * repeater-item-3, and it must be in that order. 
Whereas I would rather have something like:
1-item-1, 1-item-2, 2-item-1, 1-item-3, so that you could move items around inside of themselves.

If you could, instead, nest block editors, it would allow you to have much more complexity as far as the order of blocks and which blocks could be nested.

Beyond that, a great potential use case would be the same as was described by the individual in #211. Navigation is a fantastic example of nesting blocks. You should be able to have a nav_group, which contains n * nav_group or n * link (after all, navigation may not be directly referenced to pages on the current site. An external e-commerce site being a prime example), If a nav_group can contain other nav_groups, or other links, you could build out a navigation menu for as many levels as you desired.

To be frank I'm really liking what you all have going on here with the Twill framework, and I have enjoyed my time looking at implementing it in a few projects. It feels just a few degrees away from being unbelievably extensible.

**Comment by ifox** [comment]
Nested repeaters are now supported. As for examples, there are now a lot of more Twill projects on GitHub to take inspiration from, and we'll also be releasing more educational materials this year. Thanks for sharing your use cases!
