### ISSUE TITLE
AncestorsSlug 3rd level and more does not show correctly

### ISSUE THREAD

**Issue by mefutu01** [area17/twill#2302]
## Description

Incorrect behavior of nested pages from the 3rd and further levels. Nesting is reversed in the file src/Models/Behaviors/HasNesting.php:38 and the final uri is formed incorrectly

```php 
    /**
     * Returns the combined slug for all ancestors of this item.
     */
    public function getAncestorsSlug(?string $locale = null): string
    {
        return $this->getAncestors()->reverse()
            ->map(function ($i) use ($locale) {
                return $i->getSlug($locale);
            })
            ->implode('/');
    }
```

```php 
  ->reverse()
```

### Steps to reproduce

Update PageCotroller 

```php 
    protected function form(?int $id, ?TwillModelContract $item = null): array
    { 
        $item = $this->repository->getById($id, $this->formWith, $this->formWithCount);

        $this->permalinkBase = $item->ancestorsSlug;

        return parent::form($id, $item);
    }
```

1. Creating nested pages;
  2. Create page /1st/;
  3. Create page /1st/2nd/;
  4. Create page  /1st/2nd/3rd;
  5. Create page  /1st/2nd/3rd/4th;

### Expected result
I expect that after creating the 3rd level, the ancestorsSlug will look like: 
_/1st/2nd/3rd_
_/1st/2nd/3rd/4th_

### Actual result

_/2nd/1st/3rd_
_/3rd/2nd/1st/4th_

### Versions

Twill version: 3.0.2  
Laravel version: v9.52.9 
PHP version: PHP v8.1.12-1ubuntu4
Database engine: PostgreSQL: 15.2

**Comment by ifox** [comment]
Thanks for reporting @mefutu01. We appear to be missing a call to `defaultOrder`: https://github.com/lazychaser/laravel-nestedset#default-order to fix this.

**Comment by mefutu01** [comment]
Thanks for the quick response @ifox )  You make a great CMS :)
