### ISSUE TITLE
Wrong type of parameter of $forceLocale in Models/Block::translatedInput()

### ISSUE THREAD

**Issue by pvdbroek** [area17/twill#2309]
## Description

I believe that when adding types in V3, the wrong type is set in this function in Models/Block:

```

public function translatedInput(string $name, bool $forceLocale = null): mixed
    {
        $value = $this->content[$name] ?? null;

        $locale = $forceLocale ?? (
        config('translatable.use_property_fallback', false) && (! array_key_exists(
            app()->getLocale(),
            array_filter($value ?? []) ?? []
        ))
            ? config('translatable.fallback_locale')
            : app()->getLocale()
        );

        return $value[$locale] ?? null;
    }
```

$forceLocale is defined to a bool, whereas this should be a string, e.g. "nl_NL". With this new code $locale will be a bool as well, and $value[1] is not set. $value["nl_NL"] however is.

### Versions

 Twill version: 3.x

**Comment by pvdbroek** [comment]
Any change to get this bug fixed soon? It's really a very minor fix imho :)

As always, thanks for your time & efforts on this great product!

**Comment by ifox** [comment]
Hi @pvdbroek thanks for your kind words. Contributions are open. Since your humble opinion is that it is very minor, why don't you submit a pull request to fix it?
