### ISSUE TITLE
Media Library Helpers - Typo

### ISSUE THREAD

**Issue by adelinferaru** [area17/twill#231]
Hi! While checking the source code for media_library_helpers.php, I noticed a small typo:

"if (!function_exists('**s3Enpoint**')) {"

`if (!function_exists('s3Enpoint')) {
    function s3Endpoint($disk = 'libraries')
    {
        $scheme = config("filesystems.disks.{$disk}.use_https") ? 'https://' : '';
        return $scheme . config("filesystems.disks.{$disk}.bucket") . '.' . Storage::disk($disk)->getAdapter()->getClient()->getEndpoint()->getHost();
    }
}`

**Comment by ifox** [comment]
Good catch @adelinferaru!

**Comment by ifox** [comment]
Fixed in 1.2.2!
