### ISSUE TITLE
Twill 3: Handle Permissions should avoid trying to display deleted content.

### ISSUE THREAD

**Issue by sauron** [area17/twill#2319]
I was able to replicate a bug that when a `permissionable` is deleted the `getFormFieldsHandleUserPermissions` raises an error for `$model->id` ([link](https://github.com/area17/twill/blob/88ec426ac4026a4b39effe2bc08534ae3ab562ec/src/Repositories/Behaviors/HandleUserPermissions.php#L20))

While this can be fixed by adding a defensive or failsafe check, It worth to verify if we should cascade delete or if we should display the "deleted" `permissionable` model despite the fact that is not `visible`.

@ifox Assigning to you for discussion.

**Comment by ifox** [comment]
Fix in #2372
