### ISSUE TITLE
npm run watch Error on node > 16.15.0 (maintenance lts @ EOL)

### ISSUE THREAD

**Issue by raymondtri** [area17/twill#2329]
## Description

Directly referencing this issue https://github.com/area17/twill/issues/1658

It wasn't a big issue when 16 was active LTS, but now that 16 is in maintenance LTS and 10 days from EOL it's becoming a larger issue.

### Steps to reproduce

1. Clone the repo
2. Switch to current LTS (`nvm use 18.17.1`)
3. `npm run build` or `npm run watch`

### Expected result

I expect the javascript to build

### Actual result

```
 Building for development...

 ERROR  Failed to compile with 1 error                                                                                   12:12:30 PM
 error  in ./frontend/js/main-buckets.js

Syntax Error: Error: error:0308010C:digital envelope routines::unsupported
    at Generator.next (<anonymous>)
    at new Promise (<anonymous>)


 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at Watching.handler (C:\Users\Ray\Sites\twill\node_modules\@vue\cli-service\lib\commands\build\index.js:207:23)
    at C:\Users\Ray\Sites\twill\node_modules\webpack\lib\Watching.js:290:9
    at eval (eval at create (C:\Users\Ray\Sites\twill\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
```

### Versions

Twill version:  3.x
Laravel version: 9
PHP version: 8.1
Database engine: Postgresql

**Comment by raymondtri** [comment]
I can confirm that adding "NODE_OPTIONS=--openssl-legacy-provider" to the env before compiling does work

However this is unfortunate as the command to set environment variables is different in mac / ubuntu / windows so it's not easy to embed into the build script directly.

**Comment by Jigsaw5279** [comment]
I think the cross-env npm solves this issue?
At least that's how it was solved in the Laravel skeleton for years

**Comment by ifox** [comment]
Tested Node 16, 18 and 20 successfully. Don't hesitate to reopen if you are still seeing this.
