### ISSUE TITLE
SettingRepository byKey helper

### ISSUE THREAD

**Issue by layout-lab** [area17/twill#233]
Hi,

I'm currently running Twill with 2 languages / locales, the inputs/blocks are working fine in both languages, but I am seeking advice on using the `byKey` helper to retrieve site settings using the current locale.

Using the example provided in the documentation only renders English, although a second locale has an entry.

Thanks

**Comment by ifox** [comment]
Hey @layout-lab,

do you set the locale programmatically before using `byKey`? The value should be retrieved exactly like any other translated module, using the current application locale.

**Comment by layout-lab** [comment]
Hi @ifox,

Firstly I feel this query is on the border of being a general Laravel question, so may not be appropriate here!

I am currently sharing the settings keys with my views using `AppServiceProvider` as they're used on multiple models. 

In my `boot` function I am trying to fetch the locale using `App::getLocale` and then set it using `App::setLocale`. If I manually set the locale here, I am able to get the alternate locale value. My initial thought is my middleware hasn't had chance to run? 

Thanks

**Comment by ifox** [comment]
Sorry for the very long delay getting back to your issue, but yes, middlewares run after your providers boot method. I would look into view composers.
