### ISSUE TITLE
Login form action is rendered to blade and sent in http in an https context

### ISSUE THREAD

**Issue by xoxefdp** [area17/twill#2332]
## Description
I'm serving a twill application locally with self-signed certificates, the login form to the admin panel is printing an HTTP request as action instead of HTTPS which im serving, that makes a redirection from http to https /login route making dashboard page unaccesible

![Screenshot from 2023-09-09 16-35-42](https://github.com/area17/twill/assets/4589403/45e4e79d-4da7-40f2-981d-f8f2ecf16e52)
![Screenshot from 2023-09-09 16-55-32](https://github.com/area17/twill/assets/4589403/5a554332-d8ab-467b-bee6-157eb4cdef60)

### Steps to reproduce
* Running an Ubuntu 22.04.3 LTS system

* Having:
```env
APP_ENV=local
APP_DEBUG=true
APP_TIMEZONE=Europe/Madrid
APP_URL="app.domain.local"
ADMIN_APP_URL="app.domain.local"
ADMIN_APP_PATH="/"
```

* A fresh laravel-twill application with php-fpm on docker with an nginx up front

* place the testing domain on your hosts file

### Expected result
Expected the POST login request to be sent successfully allowing a redirection to admin panel

### Actual result
POST login request is been sent in plain http which is not allowed in a secure context

### Versions
```env
Twill version: ^3.0
Laravel version: ^10.10
PHP version: ^8.1
Database engine: MariaDB 11.1.2
```

**Comment by ifox** [comment]
Hi @xoxefdp, I don't think this is a Twill issue. Your Laravel application is responsible for generating URLs, and if it doesn't receive headers indicating an HTTPS request, it won't generate HTTPS URLs.

**Comment by ifox** [comment]
Try to create a dummy form and route outside of Twill in your application, does it generate an HTTPS URL in your form action?

**Comment by Jigsaw5279** [comment]
You'll most likely have to set up your trusted proxies (trustproxies Middleware) or configure your nginx to set the X-Forwarded-Proto Header

**Comment by xoxefdp** [comment]
> You'll most likely have to set up your trusted proxies (trustproxies Middleware) or configure your nginx to set the X-Forwarded-Proto Header

This is the way to go, configuring trusted proxies for the load balancers did the trick, it was nothing to do with twill but laravel

**Comment by xoxefdp** [comment]
> Hi @xoxefdp, I don't think this is a Twill issue. Your Laravel application is responsible for generating URLs, and if it doesn't receive headers indicating an HTTPS request, it won't generate HTTPS URLs.

You got ir, nothing to do with twill but laravel, defining the trusted proxies did the trick
