### ISSUE TITLE
TypeError: argument of type 'function' is not iterable

### ISSUE THREAD

**Issue by AhmedGHDev** [area17/twill#2339]
## Description
I am trying to login to a website using twill  commands

### code:
from twill.commands import *
go(url)
showforms()
fv("1", un_id, un)
fv("1", ps_id, ps)

submit('0')

### error
File "C:\log\lab\login.py", line 31, in <module>
    go(url)
  File "C:\log\Lib\site-packages\twill\commands.py", line 69, in go
    browser.go(url)
  File "C:\log\Lib\site-packages\twill\browser.py", line 110, in go
    if '://' in url:
       ^^^^^^^^^^^^
TypeError: argument of type 'function' is not iterable

### Versions

Twill version:  3.1

**Comment by ifox** [comment]
Hi @AhmedGHDev I think you're looking for https://github.com/twill-tools/twill.
