### ISSUE TITLE
Image of model is empty (white)

### ISSUE THREAD

**Issue by jayhaluska** [area17/twill#235]
**What I did:**
- created a CRUD module with translations
- added `use HasMedias`, `$mediaParams` to _\<myModel\>Translations.php_
- added `use HandleMedias` to _\<myModel\>Repository.php_
- added image form field to _myModule\form.blade.php_ form
- added image to an instance of my model in admin interface

**Problem:**
`myModelInstance->image('myRole', 'default')` returns empty base64 encoded string (just white).
`data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7`

Any ideas for troubleshooting? Shouln't the method return the URI to the image instead of base64?

Out of curiosity: how does Twill save the images to my model?
I checked the SQL tables: Neither the medias table nor the \<myModel\>Translations table saves the connection between image and model

**Comment by ifox** [comment]
Hey @Paluschki,

The `mediables` table is the polymorphic table storing the connection between all models and images.

From what you said you did, it seems like it might be `use HandleMedias` missing from the module repository.

**Comment by Paluschki** [comment]
Thanks for the `mediables` information, makes my understanding of Twill much clearer

Didn't mention it, but I already added `use HandleMedias` in _\<myModel\>Repository.php_

**Comment by ifox** [comment]
You can now use translated `medias` form fields so that your users can provide different images per language. Check out Twill [1.2.2](https://github.com/area17/twill/releases/tag/1.2.2)!
