### ISSUE TITLE
Integrity constraint violation: 1048 Column 'active' cannot be null

### ISSUE THREAD

**Issue by Tofandel** [area17/twill#2356]
## Description

Related #757

### Steps to reproduce

Create a module with the slugs feature and **translation** feature and enable it
Go to the page to create a new entity
![image](https://github.com/area17/twill/assets/6115458/2ce703ab-0e21-4770-8bd0-3ee86cb1790f)
Click `Create`

### Expected result

Successful creation

### Actual result

```txt
"message": "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'active' cannot be null (Connection: mysql, SQL: insert into `seminar_slugs` (`slug`, `locale`, `active`, `seminar_id`) values (test, fr, ?, 1))",
```

### Versions

Twill version:  3.0.2

**Comment by ifox** [comment]
Is your Laravel default locale set to `fr`? What is your translatable.php config looking like?

**Comment by Tofandel** [comment]
Yes it is


In `translatable.php`
```php
    /*
    |--------------------------------------------------------------------------
    | Application Locales
    |--------------------------------------------------------------------------
    |
    | Contains an array with the applications available locales.
    |
     */
    'locales' => [
        'fr',
    ],
```

And in `app.php`

```php
    'locale' => 'fr',
    'full_locale' => 'fr_FR',
```
