### ISSUE TITLE
Check for TTY support in twill:build

### ISSUE THREAD

**Issue by philippdaun** [area17/twill#236]
**Issue:** When running `twill:build` in an environment without TTY support (Gitlab Pipeline), the command will fail since it explicitly enables TTY without checking for support first: `$npmInstallProcess->setTty(true)` . Symfony's Process will then abort since it detects that TTY isn't supported.

**Expected behaviour**: The command should gracefully degrade to a version without TTY on unsupported systems.

**Proposed solution**: Symfony provides an internal helper to check for TTY support. This is straight from their documentation and would solve the issue:

```php
// vendor/area17/twill/src/Commands/Build.php

$npmBuildProcess->setTty(Process::isTtySupported());
```

**Comment by Dani-Diga** [comment]
Same problem here with local Virtual Machine provision via Vagrant.
I removed the "$npmBuildProcess->setTty(true);" from the Command and i haven't found any problem.

Anyways @philippdaun solution looks much more smart. Fancy colors are fancy :)
