### ISSUE TITLE
Multiple NestedData columns all show final entry's relations.

### ISSUE THREAD

**Issue by BezBIS** [area17/twill#2364]
## Description
When adding mutiple nested data columns to a controller, they all show the relations for the last to be added, and link to that same list of records. 

### Steps to reproduce
Setup multiple `NestedData` entries in the `additionalIndexTableColumns()` function of a Controller. In my case my `Users` controller looks like this:
```
protected function additionalIndexTableColumns(): TableColumns
    {
        $table = parent::additionalIndexTableColumns();

        $table->add(
            Text::make()->field('name')->title('Name')
        );

        $table->add(
            Text::make()->field('email_verified_at')->title('Email Verified')
        );

        $table->add(
            NestedData::make()->field('addresses')->title('Addresses')
        );

        $table->add(
            NestedData::make()->field('derfs')->title('Derfs')
        );


        return $table;
    }
```

### Expected result
Each column to show the number of records for that relation, and links to the correct list of records.

### Actual result
All columns show the number of records for the final relation, and link to that list.
![Screenshot 2023-11-01 at 10-08-22 Laravel Twill](https://github.com/area17/twill/assets/94355317/a3b08faf-d535-4ff5-9e40-97beb335cfcb)

### Versions
Twill version: 3.0.2
Laravel version:  10.10
PHP version: 8.1.2
Database engine: mysql 8.0.34

**Comment by ifox** [comment]
Fixed in https://github.com/area17/twill/pull/2314, and released in 3.1.0. thanks for reporting! 

Generally, please make sure to test your project on Twill 3.x-dev to see if an issue has already been addressed. I'm mentioning this because it appears that you reported this after the fix had already been merged.
