### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ukaytac** [area17/twill#2379]
Hello,

I'm trying to install twill to a new Laravel application but it fails.

![Screenshot 2023-12-07 at 14 15 09](https://github.com/area17/twill/assets/5268938/c59c254f-609b-4240-93bd-f67c5454e1b4)

**Comment by buddy94** [comment]
I have the same problem!

**Comment by ifox** [comment]
Twill is definitely compatible with Laravel 10 and PHP up to 8.2 (8.3 support coming this month). If you are starting from a fresh Laravel app, try deleting your composer.lock file before requiring the Twill package. There is most likely a dependencies conflict, I'll investigate.
