### ISSUE TITLE
How to save multiple select checkbox in single field?

### ISSUE THREAD

**Issue by vrdvishwas** [area17/twill#238]
`@extends('twill::layouts.form')

@section('contentFields')
@formField('checkboxes', [
    'name' => 'attributes',
    'label' => 'Attributes',
    'inline' => false,
    'options' => [
        [
            'value' => 'text',
            'label' => 'Text'
        ],
        [
            'value' => 'textarea',
            'label' => 'Textarea'
        ],
        [
            'value' => 'editor',
            'label' => 'WYSIWYG Editor'
        ],
        [
            'value' => 'image',
            'label' => 'Image'
        ],
        [
            'value' => 'file',
            'label' => 'File Upload'
        ],
    ]
])
@stop
`

I can't able to save multiple select in table field. How i can save this.

**Comment by vrdvishwas** [comment]
Does this problem has no solutions?

**Comment by ifox** [comment]
Hi @vrdvishwas,

Take a look at https://spectrum.chat/twill/general/db-type-for-multi-select-fields~956d322d-07ba-4a76-a6ab-5a2b7e57da8e.

Depending on how you want to structure data you really have many choices here: one boolean column per value, one json column storing selected values, a belongsToMany relationship, etc.

In the repository section of the documentation you'll find that Twill gives you hooks to prepare data before saving (`prepareFieldsBeforeSave`), save more data after the model itself has been saved (`afterSave`) and to format data out of the database to feed your form fields if the data structure doesn't match 1 to 1 (`getFormFields`). 

If you find yourself having to repeat code across multiple models, you can use the same approach Twill takes to share features through PHP traits. It is inspired by Laravel trait booting where the name of the hook in the trait contains the name of the trait itself. For example in Twill, the `HandleMedias` trait defines a `afterSaveHandleMedias` method that is called by the `afterSave` method of the repository including that trait.

**Comment by yanhao-li** [comment]
Confirmed `checkboxes` has been supported in the PR: https://github.com/area17/twill/pull/410
Closing this issue for now.
