### ISSUE TITLE
When rendering an image, how do you load the original?

### ISSUE THREAD

**Issue by raymondtri** [area17/twill#239]
I'm familiar with crops, but on the admin side it always shows the original height and width. If I just want to render the original image on the frontend, say in a block or something, how would I do that? No crops, just the original image.

Thanks!

**Comment by yanhao-li** [comment]
Hey @raymondtri ,

You could simply set the `ratio` to `null` like this:

```php
    'cover' => [
        'default' => [
            [
                'name' => 'default',
                'ratio' => null,
            ],
        ],
]
```

**Comment by ifox** [comment]
Hey guys,

thanks @yanhao-li. That will allow user to crop to any ratio which mean by default the image with not get cropped at all when attached.

Now, if you want to render the original image even if it has been cropped from the CMS, you can use the following:

```
$image = $item->imageObject('cover');
$rawImageUrl = ImageService::getRawUrl($image->uuid)
```

**Comment by raymondtri** [comment]
Excellent, thank you!
