### ISSUE TITLE
Fieldsets in blocks?

### ISSUE THREAD

**Issue by raymondtri** [area17/twill#240]
Is it possible to use fieldsets inside of blocks? If you wanted to really customize blocks, tabs would be useful for separating out data.

**Comment by ifox** [comment]
Hey @raymondtri, I want to say, why not? We didn't consider it in design and UX but I'm sure it technically works.

**Comment by raymondtri** [comment]
I tried using fieldsets in blocks and it gets really unhappy about fieldsets or sections inside of blocks. Tends to just blank out the entire block and display nothing, with no error messages. I also tried injecting custom vue components into blocks and it doesn't work well when you inject multiple layers of vue components (parent->child->n). One works just find though, even though that feature is not fully supported yet. I used the information from another github issue on here.

**Comment by Stiropor** [comment]
@raymondtri For tabs I used [css tabs](https://kyusuf.com/post/completely-css-tabs/) and it works like a charm, also css-only so no messing around with any js :)

**Comment by ifox** [comment]
I don't think we intend to officially support this as our design system has no definition of how a fieldset should look like inside of a block. Closing as this hasn't been active in a while, feel free to open a new issue if you still need support with blocks customization.
