### ISSUE TITLE
twill-build fails in Vagrant at creating symlink

### ISSUE THREAD

**Issue by bredmor** [area17/twill#242]
I thought this was specifically of interest because of the prevalence of services like Homestead, which is recommended in the Twill documentation. 

This occurs when using Windows as a host, with a VirtualBox provider. I have not tested with any other configurations.

If you choose to run twill-build within vagrant instead of the host OS for any reason, the following output occurs.

```4027 error path ../@babel/parser/bin/babel-parser.js
4028 error code EPROTO
4029 error errno -71
4030 error syscall symlink
4031 error EPROTO: protocol error, symlink '../@babel/parser/bin/babel-parser.js' -> '/home/vagrant/code/vendor/area17/twill/node_modules/.bin/parser'
```

This can be worked around by running `npm run twill-build --script-shell bash` on the host OS, but installing/using NPM locally can be undesirable for security reasons, especially on Windows.

Full NPM run log attached.
[2019-04-15T17_31_02_790Z-debug.log](https://github.com/area17/twill/files/3081412/2019-04-15T17_31_02_790Z-debug.log)

**Comment by ifox** [comment]
Hi @bredmor!

It seems like this is a known issue with Homestead on Windows, see the symbolic links on Windows section here: https://laravel.com/docs/5.8/homestead#provider-specific-virtualbox.

**Comment by bredmor** [comment]
Thanks @ifox, will give that a try and see if it resolves the issue.
