### ISSUE TITLE
URL is missing : when clicking through from Page Builder

### ISSUE THREAD

**Issue by jkhamler** [area17/twill#245]
When clicking the link at the top of the content editor page, the URL is malformed, missing a single ':' after ```http```.

E.g. clicking this:

<img width="327" alt="Screenshot 2019-04-17 at 14 46 04" src="https://user-images.githubusercontent.com/7847437/56292756-a57fb000-611f-11e9-8f40-521588cbba28.png">

Leads to this:

<img width="698" alt="Screenshot 2019-04-17 at 14 46 15" src="https://user-images.githubusercontent.com/7847437/56292757-a57fb000-611f-11e9-8eb4-fd7f1bf3fe72.png">

**Comment by ifox** [comment]
Hi @jkhamler!

I'm really surprised by this one considering where the url is coming from in the [codebase](https://github.com/area17/twill/blob/2ee1080d84f7f6c0b254947f3c45829008736c8a/src/Http/Controllers/Admin/ModuleController.php#L1103). 

The base url can also come from a `urlWithoutSlug` attribute, maybe you implemented an accessor for this?

**Comment by Riaan-ZA** [comment]
I can confirm this is happening for me too

**Comment by LCD344** [comment]
This happens to me as well:

![image](https://user-images.githubusercontent.com/15718141/60900148-65d6e900-a274-11e9-9abc-bb02bec857e5.png)

**Comment by LCD344** [comment]
@jkhamler - I think it happens becuase in your .env file you have the http:// as part of the APP_URL - I looked at the documentation and they obviously don't have it, removed it and it fixed the issue
