### ISSUE TITLE
Related model on same model

### ISSUE THREAD

**Issue by tchapi** [area17/twill#246]
Hi,

I'm trying to add 'related articles' on an 'article' entity. In the migration process, I'm doing :
    
            createDefaultRelationshipTableFields($table, 'article', 'article');

... which does not work since it tries to the same column twice (`article_id`). Any workaround for that ?

Thanks !

**Comment by ifox** [comment]
Hi @tchapi!

Right, our helper doesn't support creating a relationship table for the same model. However you can take a look at the source code and replicate for your use case, something like this:

```php
Schema::create('article_article', function (Blueprint $table) {
            $table->increments('id');

            $table->integer("article_id")->unsigned();
            $table->foreign("article_id")->references('id')->on('articles')->onDelete('cascade');
            $table->integer("related_article_id")->unsigned();
            $table->foreign("related_article_id")->references('id')->on('articles')->onDelete('cascade');

            $table->integer('position')->unsigned()->index();

            $table->timestamps();
});
```

And in your Article model:

```php
public function voices()
{
    return $this->belongsToMany(Article::class, 'article_article', 'article_id', 'related_article_id')->withPivot('position')->orderBy('position');
}
```

**Comment by tchapi** [comment]
Ooh that's so simple I had forgotten `belongsToMany()` had arguments for that kind of case. Sorry for the inconvenience and thanks for your time (and that wonderful project).

**Comment by emilsomm** [comment]
@ifox Hi, and first off thank you very much for this wonderful CMS and the time your putting in to helping us out:) I have this far tried to find out what i can with extensive Googling, but am now at a loss. I have implemented the above code, but to store the related project I would need to add something to the `ProjectRepository` i guess. I have currently this, wich returns an error `Call to a member function map() on null`
```
public function afterSave($object, $fields) {
        $this->updateBrowser($object, $fields, 'projects');
        parent::afterSave($object, $fields);
    }
    public function getFormFields($object) {
        $fields = parent::getFormFields($object);
        $fields['browsers']['related'] = $this->getFormFieldsForBrowser($object, 'project');
        return $fields;
    }
```

I hope you find time to help, and appreciate your time! Cheers

**Comment by bdahlinger** [comment]
I'm at the same point as @emilsomm is. Love to know how to handle this. Thanks!
