### ISSUE TITLE
[Package Capsules] Broken getModulePermalinkBase

### ISSUE THREAD

**Issue by Tofandel** [area17/twill#2470]
## Description

Package capsules which have a namespace different than `config('twill.namespace')` (Usually it's a namespace with the package name) will fail at https://github.com/area17/twill/blob/17803f1cb0546c6e88d0a24bb9621ba3a9957834/src/Http/Controllers/Admin/ModuleController.php#L2412-L2448 because `$name` is not a model class but a simple singular no uppercased word

### Steps to reproduce

Create a package with 2 capsules with nesting enabled

Go to the route for the nested capsule

### Expected result

No error

### Actual result

No capsule found for `seminar`

### Versions

Quick fix would be to uppercase `$name` before getting the capsule

Better fix would be to build on https://github.com/area17/twill/pull/2423 and improve the way all the classes are located (and maybe add a cache as well)

**Comment by ifox** [comment]
Hi @Tofandel,

Thanks for reporting this. Capsules were initially meant to be self-contained and were all housed under the same namespace but with the introduction of packages, it is clear that those improvements are welcome. I'm open to reviewing more changes to make resolution cleaner and more robust.

**Comment by Tofandel** [comment]
I PR'd the quick fix for now, I'll send a PR to generalize and allow to configure all the namespaces resolutions sometime this month when I have more time
