### ISSUE TITLE
An error occurred when I ran the command 'php artisan twill:setup'

### ISSUE THREAD

**Issue by linqiuyu** [area17/twill#25]
![image](https://user-images.githubusercontent.com/29515280/43558413-f96b7244-963b-11e8-9332-efe46c4f3970.png)

**Comment by linqiuyu** [comment]
![tmlt xsp d rmmmt g o30](https://user-images.githubusercontent.com/29515280/43558398-dbd18c5a-963b-11e8-8137-4a87e9918645.png)

**Comment by ifox** [comment]
Hi @linqiuyu! 

Thanks for reporting. We are aware of this one and have a fix coming up but you don't have to worry about it. This is old code trying to locate a folder that does not exist anymore. As long as the rest of the setup worked, you're good!

**Comment by dehboris** [comment]
Hi everybody!
Good job @ifox 
I have save same problem today.
Thanks!
