### ISSUE TITLE
More instruction on how to use presenters with blocks

### ISSUE THREAD

**Issue by nikhiltri** [area17/twill#251]
Bonjour!

I'm trying to use a custom Presenter for my Block models, and I'm having trouble making sense of how this is to be wired up. In some places, it appears that a path is expected, in others it appears that a fully resolved class is expected.

In [config.blocks](https://github.com/area17/twill/blob/1.2/config/blocks.php#L17) I see this property, that seems to expect a path (not sure if that's a file path or class path?):

```
    'block_presenter_path' => null, //Allow to set a custom presenter to a block model
```

And in the [Blocks model](https://github.com/area17/twill/blob/1.2/src/Models/Block.php) I see this path is used to set the `presenter` property:

```
    public function getPresenterAttribute()
    {
        if (($presenter = config('twill.block_editor.block_presenter_path')) != null) {
            return $presenter;
```

But then in the [HasPresenter](https://github.com/area17/twill/blob/1.2/src/Models/Behaviors/HasPresenter.php#L11) behavior, it appears that this property is expected to be a fully resolved class, not a path as it's set to in the model:

```
    public function present($presenter = 'presenter')
    {
        if (!$this->$presenter or !class_exists($this->$presenter)) {
```

Can you provide some guidance on how this is to be used? Is it expected that each different type of block can have its own presenter class? Or should there be a single presenter class to be used with all blocks? I'm happy to make edits and submit a PR, just let me know the direction you had intended on taking!

Thanks!
nikhil

**Comment by ifox** [comment]
Bonjour @nikhiltri!

You are right, the config property naming is confusing. It expects a fully qualified class name and the intended usage is a single presenter class for all blocks.

It would be great to support an array of FQCN keyed by block type too!

**Comment by nikhiltri** [comment]
Yup! Setting it to a FQCN did it. Thanks!
