### ISSUE TITLE
Axios breaks datatable filters 

### ISSUE THREAD

**Issue by florianschrottenloher-iu** [area17/twill#2518]
## Description

The Axios update to v0.28.0 had some breaking changes in parameter serialization. Objects and Arrays are now provided in a bracket style instead of an object style:

New: &filter[status]=published
Old: &filter={"status":"published"}

This change leads to json_decode errors in src/Http/Controllers/Admin/ModuleController.php due to Twill expecting a json_decodeable string attached to the "filter" request parameter.

`Object { message: "json_decode(): Argument #1 ($json) must be of type string, array given", exception: "TypeError", file: "./vendor/area17/twill/src/Http/Controllers/Admin/ModuleController.php", line: 2135}
`

### Steps to reproduce

- navigate to a Twill datatable in the backend
- use a Quickfilter or Tablefilter
- analyze the request

### Expected result

- filters work as expected and do not result in a 500 error

### Actual result

- filtering results in a 500 error

### Versions

Twill 3.2.0

**Comment by Tofandel** [comment]
There is a possibility it's breaking more than this

I didn't dig into it but titles are saved like this
![image](https://github.com/area17/twill/assets/6115458/6c79da85-9dd8-4d6e-b507-f2a52b40a87e)

After digging, it's completely unrelated just missed a `$field = ` in  `$field = parent::prepareFieldsBeforeSave($object, $fields);`
