### ISSUE TITLE
Frontend assets builds

### ISSUE THREAD

**Issue by danielvalchev** [area17/twill#252]
The doc says:

> Once you create custom blocks for your admin console, Twill's assets needs to be recompiled to include your generated Vue components. In order to do that, add the following npm scripts to your project's package.json:

```
"scripts": {
  "twill-build": "rm -f public/hot && npm run twill-copy-blocks && cd vendor/area17/twill && npm ci && npm run prod && cp -R public/* ${INIT_CWD}/public",
  "twill-copy-blocks": "npm run twill-clean-blocks && mkdir -p resources/assets/js/blocks/ && cp -R resources/assets/js/blocks/ vendor/area17/twill/frontend/js/components/blocks/customs/",
  "twill-clean-blocks": "rm -rf vendor/area17/twill/frontend/js/components/blocks/customs"
}
```

As you use the default mix-manifest file (located in /public dir), this will cause conflicts in case the project uses default mix configuration. It would be better if you put all your assets in single directory located in public (e.g. twill). You can do this in webpack.mix.js by using:
```
// Assets will be stored in public/twill folder
mix.setPublicPath('public/twill');

// Urls will be prefixed with twill path
mix.setResourceRoot('twill');
```

Then you need to pass the directory when using `mix()` helper:
```
<link href="{{ mix('/assets/admin/css/app.css', 'twill')}}" rel="stylesheet" />
```

**Comment by m4n1ok** [comment]
Hello @danielvalchev. 
Thanks for reporting and steps to enhance default behaviour.
Could you provide a pull request with those updates. I will be happy to review it.

**Comment by ifox** [comment]
Our new build process does not conflict with the default Laravel Mix configuration anymore. Thanks for reporting!
