### ISSUE TITLE
\Hash::make instead of bcrypt

### ISSUE THREAD

**Issue by stoutZero** [area17/twill#254]
As titled, please use `\Hash::make` instead of `bcrypt` function in  
[CreateSuperAdmin#handle](https://github.com/area17/twill/blob/1.2.1/src/Commands/CreateSuperAdmin.php#L33), this way people that opted to use argon  
instead of bcrypt will have argon hashed password

**Comment by stevanpavlovic** [comment]
@ifox @stoutZero Can I solve this one?

**Comment by yanhao-li** [comment]
@stoutZero The corresponding PR has been created here https://github.com/area17/twill/pull/445, thanks for the suggestion!
