### ISSUE TITLE
Dependency Conflict: Laravel 11.9.2, Twill 3.3, Symfony Http-Foundation v7.1.0, and Doctrine DBAL 3.8.4, please update to dbal 4

### ISSUE THREAD

**Issue by mebron** [area17/twill#2594]
Problem 1
    - Root composer.json requires area17/twill 3.3 -> satisfiable by area17/twill[3.3.0].
    - carbonphp/carbon-doctrine-types 3.2.0 conflicts with doctrine/dbal 3.8.4.
    - area17/twill 3.3.0 requires doctrine/dbal ^3.0 -> satisfiable by doctrine/dbal[3.0.0, ..., 3.8.4].
    - nesbot/carbon 3.5.0 requires carbonphp/carbon-doctrine-types * -> satisfiable by carbonphp/carbon-doctrine-types[3.2.0].
    - symfony/http-foundation v7.1.0 conflicts with doctrine/dbal 3.5.4.
    - symfony/http-foundation v7.1.0 conflicts with doctrine/dbal 3.4.6.
    - symfony/http-foundation v7.1.0 conflicts with doctrine/dbal 3.3.8.
    - symfony/http-foundation v7.1.0 conflicts with doctrine/dbal 3.3.5.
    - symfony/http-foundation v7.1.0 conflicts with doctrine/dbal 3.2.2.
    - symfony/http-foundation v7.1.0 conflicts with doctrine/dbal 3.1.5.
    - symfony/http-foundation v7.1.0 conflicts with doctrine/dbal 3.1.0.
    - symfony/http-foundation v7.1.0 conflicts with doctrine/dbal 3.0.0.
    - laravel/framework v11.9.2 requires nesbot/carbon ^2.72.2|^3.0 -> satisfiable by nesbot/carbon[3.5.0].
    - laravel/framework v11.9.2 requires symfony/http-foundation ^7.0 -> satisfiable by symfony/http-foundation[v7.1.0].
    - laravel/framework is locked to version v11.9.2 and an update of this package was not requested.

### Versions

Twill version: 3.3
Laravel version: 11.9.2
PHP version:8.3

**Comment by Tofandel** [comment]
Laravel 11 removed the need for dbal, it also originally is a requirement of laravel and not twill so it should be removed from the list of dependencies in v4 but we can simply allow dbal v4 in twill v3 without issue
