### ISSUE TITLE
Twill UI?

### ISSUE THREAD

**Issue by vilav** [area17/twill#26]
Working on a different project but want to use Twill's clean UI components, CSS and colors.
Any way to isolate the specific files?

**Comment by ifox** [comment]
Hi @vilav, that's a very good question!

For now, we did not develop Twill's Vue components to be used specifically outside of Twill, so at this stage you might find that they are too tightly coupled to be isolated. But it's really not that bad, most of them are using mixins to share code needed to work in the overall architecture of our Vue apps and with Twill's backend, so our components could be refactored to be more generic and used outside of our package. 

However, global styles could perfectly be already. There's a good part of our styling that is bundled from SASS files, so outside of our Vue single file components. Check out `frontend/scss`.

Icons are obviously ready to be used outside. Font is Inter UI, [an open source font by Rasmus Andersson](https://github.com/rsms/inter).  

Isolating UI components is not the primary focus of our team at the moment but we would definitely be happy to review any proposition the community might have to make it happen.
