### ISSUE TITLE
How to create frontend routes in Twill?

### ISSUE THREAD

**Issue by vacoup95** [area17/twill#260]
I don't understand how frontend routes are created for CRUD Modules. I made a module called Blogs via the command without any of the parameters. 

Later, I added the slugs to it manually. Added:

    use HasMedias, HasSlug;
    public $slugAttributes = [
         'title',
    ];

Also added my own 'Slugs/BlogSlugs' model  (not documented anywere, why?). 
Made sure the repository uses these: 

    use HandleMedias, HandleSlugs;

OK, so now I expected it to work on the frontend by going to mysite.com/blogs/the-slug
But it returns a 404. Why is that? Everything in the backend works properly, I also checked the database and everything seems to be working properly. How do I create frontend routes guys it's not documented anywere.

**Comment by bchellingworth** [comment]
This is a headless CMS, meaning it doesn't do anything 'front end' 

Just make a normal laravel route and corresponding controller pull in your model etc etc, normal laravel stuff.

That being said, I am trying to do some basic stuff with this CMS and it looks so promising but the documentation is awful. its all over the place and skips so much vital info.

**Comment by geid** [comment]
@vacoup95 please join us on https://spectrum.chat/twill as the entire team is active there and we can support you as you prep for your meeting. 

@bchellingworth We made some big improvements to the docs but yes there is still much much much room to improve. We would love your support in improving them, either by contributing to the docs directly or starting a thread on Spectrum pinpointing ideas for improvements and vital info that is missing. 

Thanks a million!

**Comment by vacoup95** [comment]
Thank you for your replies, helps me a lot. I'll be joining the chat for further questions. 
Great looking CMS btw!
