### ISSUE TITLE
Custom Dashboard Reports?

### ISSUE THREAD

**Issue by raymondtri** [area17/twill#262]
Hello again!

I've been experimenting with Twill some more, and I'm enjoying it more every day.

I was wondering if there was a recommended way to display user-facing data on the admin dashboard. An example use-case of this would be if someone submitted a contact form on the user-facing side, you'd want to be able to filter through the submitted contact forms on the administrative side.

I see where you can roughly view activity in different areas, but what if you actually wanted to view something like contact form submissions where there are multiple fields, or even orders, etc.?

Thanks!

**Comment by ifox** [comment]
Hi @raymondtri, sorry for the delay on this one!

To clarify, do you mean displaying user generated content from the frontend (like a contact form submission) in the admin as a module (as in with a listing and potentially a form), or specifically on the dashboard screen?

For the former, you should be able to make any Laravel model compatible with becoming a module you can display in your Twill instance.

For the latter, our dashboard controller is not really helping with extensibility at the moment aside from the existing features. You could override the Blade template and grab some data to display from there for now, but that's not sustainable. Can you elaborate on where you'd like to add new modules to your dashboard?

**Comment by raymondtri** [comment]
Hey @ifox, no problem, I'm surprised I missed your response!

Yes, I mean user generated content from the frontend (like a contact form).

So for something like form submissions where there is data to view, I suppose we would just need to access the response information and display it in the form blades as normal, since it would be a user response and not editable.

**Comment by raymondtri** [comment]
Actually, reading through the source solved this (as it does most things).

The solution I came up with is to create a new layout (you can reference twill/views/layouts/settings.blade.php for an example of this) and then extend the new custom layout instead of the normal twill::layouts.form in your "read-only" module's form.blade.php file.

**Comment by JacoboDominguez** [comment]
I was looking to implement the same use case and benefit from table and cruds operations to list show and filter some form submission performed in the frontend.
I tried disabling in the controller most of the actions (delete, publish, edit...) expecting to have a form showing data without publishing, editing,drafts... buttons and references but the controls where still there, also the "live" switch. Theses controls do not have much sense over user form submissions so I am planning to follow your approach by using a custom layout.
How was your experience @raymondtri ?, what do you mean about that is better to manipulate the VuexStore, do you have a ref to an example?
Cheers!
Jacq
