### ISSUE TITLE
Form fields error messages are not flashed when validating (again)

### ISSUE THREAD

**Issue by kfina-planxy** [area17/twill#2632]
## Description

Same as #697 and #605.
When using the FormBuilder with Request Rules no error messages are shown
```
// MyModelController.php
    public function getForm(TwillModelContract $model): Form
    {
        $form = parent::getForm($model);

        $form->add( Input::make()->name('title')->label('Title')->translatable() );
        $form->add( Input::make()->name('item number')->label('Item Number') );

        [...]

        return $form;
    }
```

```
// MyModelRequest.php
    public function rulesForUpdate()
    {
        return [
            'item_number' => 'required',
            'title' => Rule::unique('my_model_translations', 'title')
        ];
    }
```

### Steps to reproduce

1. Enter code as above
2. Try to submit something that break
Network Tab shows correct messages: (manually translated by myself to english, because the messages were correctly localized)
```
{
    "item_number": [
        "The field \"item number\" is required"
    ],
    "title": [
        "That title is already used."
    ]
}
```

### Expected result

Red outlined fields and a message telling what's wrong
( See screenshots in #697 )

### Actual result

Only a red notification saying: "Your submission could not be validated, please fix and retry"...

**Comment by ifox** [comment]
Hi @kfina-planxy you are not using the form request class correctly to validate translated field. You need to use `$this->rulesForTranslatedFields([<non translated field rules>], [<translated field rules>])`

**Comment by kfina-planxy** [comment]
Thank you! Got it to work. I still wonder why the item_number message did not work initially though.
