### ISSUE TITLE
[BUG] Wrong check in VSelect component

### ISSUE THREAD

**Issue by danielvalchev** [area17/twill#266]
The check here is wrong. You are checking for property, but isAjax is method. This will cause every searchable select to perform ajax requests.

https://github.com/area17/twill/blob/60a239b8bad3e2f2da383f88577cedadea81aee3/frontend/js/components/VSelect.vue#L192

https://github.com/area17/twill/blob/60a239b8bad3e2f2da383f88577cedadea81aee3/frontend/js/components/VSelect.vue#L181

**Comment by mrdoinel** [comment]
Good catch!
Yes it should be a computed instead.

**Comment by ifox** [comment]
Hi guys! I fixed this for our next release, I'll close this asap.
