### ISSUE TITLE
Another problem with hot module replacement (npm run twill-dev)

### ISSUE THREAD

**Issue by plexus77** [area17/twill#267]
Hi there, I am running a twill dev environment on homestead and running npm/yarn from my computer itself...  The scripts and styles are available eg localhost:8080/assets/admin/css/app.css, however the hot module replacement is not working and is throwing a JS error `Invalid Host/Origin header` when the socket trys to connect.

To get it working I needed to add the following lines into the mix.webpackConfig inside /vendor/area17/twill/webpack.mix.js

```
  devServer: {
    disableHostCheck: true
  }
``` 
webpack/webpack-dev-server#1604

**Comment by yanhao-li** [comment]
Hi @plexus77 ,

Thank you for reporting this! Similar issue and discussion are here: https://github.com/area17/twill/issues/152
add `-disable-host-check` to hot script can also fix such issue.

**Comment by ifox** [comment]
Hi guys,

this is fixed in our upcoming release, stay tuned!

**Comment by ifox** [comment]
Fixed in [1.2.2](https://github.com/area17/twill/releases/tag/1.2.2).
