### ISSUE TITLE
Call to undefined method stdClass::unsetRelation()

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#2671]
## Description

We re getting this error when rendering blocks on preview. [This is the line that might have introduced the bug](https://github.com/area17/twill/commit/463bd594af560da06cd05122d6ef7ebf1e10e361#diff-fdd83a455929e4b24f5499c60bb93849a9c7655eb6ad54ae67e2c6b6c19c0299R54).

### Steps to reproduce

It's being generated by having browsers to related items in the block editor.

### Versions

Twill version: 3.4
Laravel version: 11
PHP version: 8.3

/cc @Tofandel

**Comment by Tofandel** [comment]
$item is assumed to be a Model because it is coming from a relationship/query, which should absolutely have this method, why are you getting a stdClass instead of a model?

Did you somewhere maybe force the relation `relatedItems` or change the `relatedItems` method? Do you maybe have a global scope that's doing something it shouldn't?

**Comment by antonioribeiro** [comment]
Hard to tell, can't dive deep down this now. But it's a block editor with many repeaters and related browsers to multiple modules:

```php
Browser::make()
    ->name($browserName ?? 'linked_item')
    ->label('Internal page')
    ->modules(Constants::BROWSER_ALL_ENDPOINTS)
    ->connectedTo($prefix . 'type', 'internal', ['keepAlive' => true]),
```

**Comment by Tofandel** [comment]
This might be coming from this line which is doing something it shouldn't 
https://github.com/area17/twill/blob/3297066f3fc009b68c1c8238eee7494c05f9db9c/src/Repositories/BlockRepository.php#L46-L59

**Comment by antonioribeiro** [comment]
Yes, I just saw that `$item` is a `stdClass` that has the model in `$item->related`

**Comment by ifox** [comment]
@antonioribeiro by "when rendering blocks", do you mean inside Twill's editor, or your frontend controllers?

**Comment by antonioribeiro** [comment]
For some reason we only have this on preview, @ifox, I forgot to add to the ticket

**Comment by ifox** [comment]
This other PR might be related: https://github.com/area17/twill/pull/2535

**Comment by Tofandel** [comment]
I was looking at it but it's not this, it's the code I pointed to that stores objects into the relatedItem relation, sending a PR in 3 minutes

**Comment by Tofandel** [comment]
Btw @ifox I see a lot of `Schema::hasTable(config('twill.related_table', 'twill_related'))` in this class (which is a somewhat expensive query) running in a very heavy loop

Is there any actual case where this table would not exist? Isn't related a non disableable feature?

**Comment by ifox** [comment]
This was for backwards compatibility when the migrations were not all loaded automatically like they are now. This can be safely removed.

**Comment by Tofandel** [comment]
@antonioribeiro Any chance you could give a try to the PR?

Adding to your composer.json

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/tofandel/twill"
        }
    ],
    "require": {
        "area17/twill": "dev-patch-18 as 3.4.1"
    }
```

And then `composer upgrade`

**Comment by antonioribeiro** [comment]
Sorry, I was already out of the office, I will try to look at this later,
as I also don’t have my local environment with me 😁

**Comment by cambad** [comment]
Good morning here! I tried it with the PR @Tofandel, and I can confirm it is all good, I can preview the pages with related content!

Thanks, @Tofandel, for the fix 🙏🏽 🥳 

cc @antonioribeiro
