### ISSUE TITLE
3.4.0 - regression - "Don't load relation for each column and allow dot notation in field name for index table"

### ISSUE THREAD

**Issue by jandol5** [area17/twill#2674]
## Description

The 3.4.0 has introduced "Don't load relation for each column and allow dot notation in field name for index table" (https://github.com/area17/twill/pull/2603) which breaks previous behavior.

### Steps to reproduce

Add additional relation index table columns in controller, eg
```php
protected function additionalIndexTableColumns(): TableColumns
{
    return parent::additionalIndexTableColumns()
        ->add(Relation::make()->relation('measure')->field('title')->title('Naslov'))
        ->add(Relation::make()->relation('measure')->field('category.title')->title('Naziv kategorije'));
}
``` 

### Expected result

Index table should have additional two columns:
- "Naslov" containing the title of the "measure" relation instance
- "Naziv kategorije" containing the title of category category relation of "measure" relation instance

### Actual result

Using the dot notation in filed name throws `Illuminate\Database\QueryException` stating `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category.title' in 'field list' (Connection: mysql, SQL: select `category`.`title` from `measures` where `measures`.`deleted_at` is null)`.
When I remove `Relation::make()->relation('measure')->field('category.title')->title('Naziv kategorije')` and use only `Relation::make()->relation('measure')->field('title')->title('Naslov')`, the index table renders the additional 'Naslov' column but the data is wrong: all titles of all of the relation model instances are displayed.

### Possible fix

The PR https://github.com/area17/twill/pull/2603 changes `$relation` type from `\Illuminate\Database\Eloquent\Collection` to `\App\Models\[model]` as seen in [src/Services/Listings/Columns/Relation.php](https://github.com/area17/twill/pull/2603/files#diff-fe1d5c808346ec4c6b56d578333ace90fca46ea89f594a1ef64fb04fd622d901). If I replace the new `$relation = $model->getRelation($this->relation);` with previous `$relation = $model->{$this->relation}()->get();` I get the expected result.

@Tofandel is this an innocent regression or did I miss something?

### Versions

Twill version:  3.4.0
Laravel version: 11.28.0
PHP version: 8.3.4
Database engine: MySQL 5.7.24

**Comment by Tofandel** [comment]
Could you please share your models

```php
$model->loadMissing($this->relation);
$relation = $model->getRelation($this->relation);
``` 

And 

```php
$relation = $model->{$this->relation}()->get();
```

Should be functionnally equivalent (except one uses the cache and one runs a query everytime)


Is `measure` a one to one relation?

Edit: just checked and yeah in one to one ->get still returns a collection but not getRelation

In the PR I mentionned that "however the Relation column doesn't actually use the loaded relation (and doesn't work with one to one relation)"

So I did try originally with a one to one and didn't get it to work, so I guess that's why I didn't catch this regression
