### ISSUE TITLE
Compiling admin assets ?

### ISSUE THREAD

**Issue by imknight** [area17/twill#269]
If I run yarn watch to build my frontend, I can't login the backend because some assets file will be missing and I need to run twill:build again in order to login backend.

**Comment by bdahlinger** [comment]
@imknight the manifest file that mix uses indeed gets written over if you run your own mix for the front end. This removes the admin's own mix manifest pointers. To fix this all you need to do is require laravel-mix-merge-manifest in your webpack.mix.js. Like this:

```
const mix = require('laravel-mix');
require('laravel-mix-merge-manifest');

mix
    .js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .browserSync({
        proxy: 'site.test'
    })
    .mergeManifest();
```
Of course configured to your setup.

`npm i --save-dev laravel-mix-merge-manifest`

**Comment by imknight** [comment]
yup it work, thanks !
