### ISSUE TITLE
Cannot reorder images on A17\Twill\Services\Forms\Fields\Medias

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#2690]
## Description

We cannot reorder images on version 3.4.1.

### Steps to reproduce

It's very simple, change the order, update, refresh the cms page and the images are back on the old order.

### Versions

Twill version:  3.4.1

**Comment by ConstantMath** [comment]
I also have the same problem with the latest version of Twill (3.4.1). 
Worse, the image is deleted if it has already been uploaded and you try to change the order afterwards.
