### ISSUE TITLE
Old URLs returning a 404 when the slug is updated

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#2691]
## Description

We noticed this on 3.4.1.

### Steps to reproduce

- Create a record that has permalinks enabled
- Edit the permalink
- Try to hit both pages
- The new one works, the old one returns a 404

### Versions

Twill version:  3.4.1 and 3.3.1

**Comment by zeezo887** [comment]
@antonioribeiro How are you fetching the record? Are you using the model or repository? I noticed using the repository works fine
`app(PageRepository::class)->forSlug($slug)`

**Comment by antonioribeiro** [comment]
Yeah, I just saw we were not using the Repository, @zeezo887 :

```php
Page::query()->published()->forSlug($slug)->firstOrFail()
```
