### ISSUE TITLE
Languages "Live" fails to save on update.

### ISSUE THREAD

**Issue by bdahlinger** [area17/twill#271]
Hello,

_Twill v1.2.1_
**Issue:** My app has 16 languages. Whenever I choose what languages to make live, and "Update and close", returning back to the content shows just one language live.

**Step 1:** Select some languages
![image](https://user-images.githubusercontent.com/1479792/57988145-63f46480-7a3f-11e9-9769-cd575fef0787.png)

**Step 2:** "Update and close"

**Step 3:** Go back to the edit view for that model.

**Result:** 
![image](https://user-images.githubusercontent.com/1479792/57988158-91411280-7a3f-11e9-8471-8487c4cd20c3.png)

But the interesting thing is the list view for all the models show enabled languages properly. 
![image](https://user-images.githubusercontent.com/1479792/57988171-bafa3980-7a3f-11e9-8c7e-a9aa855689ca.png)

But again, the edit view does not.
![image](https://user-images.githubusercontent.com/1479792/57988178-ca798280-7a3f-11e9-8859-52df9ebee920.png)

Perhaps this is just a visual bug with the edit views?

**Comment by ifox** [comment]
Hi @bdahlinger, thanks for reporting this!

I'm not able to reproduce in a Twill codebase where we too have a lot of languages, 32 actually!. It might be a missing `active` fillable in your `translatedAttributes` of your model.

The active state for this specific module on the form template is coming from [this line](https://github.com/area17/twill/blob/16ec48037efab10c20ffb09728bd885ad9a1aa4a/src/Helpers/i18n_helpers.php#L21) in which the `form_fields` have been set by the following code:

https://github.com/area17/twill/blob/16ec48037efab10c20ffb09728bd885ad9a1aa4a/src/Repositories/Behaviors/HandleTranslations.php#L65-L68.

**Comment by bdahlinger** [comment]
@ifox I'm sorry it took so long to respond. I had been off that project and back on. Yes, 'active' was missing from the translatedAttributes. Thank you so much for your help!
