### ISSUE TITLE
Edge: form display issues

### ISSUE THREAD

**Issue by luislavena** [area17/twill#272]
Tested Settings form in Demo (https://demo.twill.io/settings/seo) and noticed some display issues under Microsoft Edge.

* OS: Windows 10
* Browser: Microsoft Edge 
* Browser version: 18.17763
* Screen resolution (as reported by Edge): 1435 x 688
* Real screen resolution (HiDPI, 225%): 3200 x 1800

See screenshot:

![ApplicationFrameHost_GgUeGYaTCf](https://user-images.githubusercontent.com/4182/58042745-da619700-7b11-11e9-9b29-256b3658cad1.png)

Thank you!
❤️ ❤️ ❤️

**Comment by ifox** [comment]
I know this is cheating because Edge is now based on Chromium, but this is now working fine on Windows 10 with Edge 98.
