### ISSUE TITLE
Edge: dashboard analytics widget display issues

### ISSUE THREAD

**Issue by luislavena** [area17/twill#273]
Seeing under Dashboard in Demo (https://demo.twill.io/) and noticed some display issues under Microsoft Edge.

* OS: Windows 10
* Browser: Microsoft Edge 
* Browser version: 18.17763
* Screen resolution (as reported by Edge): 1435 x 688
* Real screen resolution (HiDPI, 225%): 3200 x 1800

See screenshot:

![ApplicationFrameHost_2uhPIwlxEw](https://user-images.githubusercontent.com/4182/58042852-1e549c00-7b12-11e9-8018-9b7387be9e7b.png)

Thank you!
❤️ ❤️ ❤️

**Comment by ifox** [comment]
I know this is cheating because Edge is now based on Chromium, but this is now working fine on Windows 10 with Edge 98.
