### ISSUE TITLE
Edge: Preview displays blank page

### ISSUE THREAD

**Issue by luislavena** [area17/twill#275]
Tested Preview of Work in Demo (https://demo.twill.io/work/works/2335/edit) and noticed that Preview displays an empty page under Microsoft Edge. Selecting any other revision produces the same result (which also happens when comparison mode is enabled)

* OS: Windows 10
* Browser: Microsoft Edge 
* Browser version: 18.17763
* Screen resolution (as reported by Edge): 1435 x 688
* Real screen resolution (HiDPI, 225%): 3200 x 1800

See following screenshots:

![ApplicationFrameHost_Lh1Zq9Fqee](https://user-images.githubusercontent.com/4182/58043922-ddaa5200-7b14-11e9-8ec1-36ac903301ea.png)
![ApplicationFrameHost_M5tg17RAuU](https://user-images.githubusercontent.com/4182/58043925-e00cac00-7b14-11e9-8343-d98d08f2714e.png)

Thank you!
❤️ ❤️ ❤️

**Comment by dubcanada** [comment]
Edge 18 does not support srcdoc, so that's why it is blank.

**Comment by ifox** [comment]
srcdoc has been supported on Edge for a while now, I think we can close this!
