### ISSUE TITLE
Cant delete Files using local storage, and cascade in true.

### ISSUE THREAD

**Issue by Ayguid** [area17/twill#276]
I cant seem to delete files using the following config, any ideas?

  'media_library' => [
    'disk' => 'libraries',
    'endpoint_type' => env('MEDIA_LIBRARY_ENDPOINT_TYPE', 'local'),
    'cascade_delete' => env('MEDIA_LIBRARY_CASCADE_DELETE', true),
    'local_path' => env('FILE_LIBRARY_LOCAL_PATH', 'uploads/images/'),
    'image_service' => env('MEDIA_LIBRARY_IMAGE_SERVICE', 'A17\Twill\Services\MediaLibrary\Local'),
    'filesize_limit' => env('MEDIA_LIBRARY_FILESIZE_LIMIT', 50),
    'allowed_extensions' => ['svg', 'jpg', 'gif', 'png', 'jpeg'],
    'init_alt_text_from_filename' => true,
    ],

  'file_library' => [
    'disk' => 'libraries',
    'endpoint_type' => env('FILE_LIBRARY_ENDPOINT_TYPE', 'local'),
    'cascade_delete' => env('FILE_LIBRARY_CASCADE_DELETE', true),
    'local_path' => env('FILE_LIBRARY_LOCAL_PATH', 'uploads/files/'),
    'file_service' => env('FILE_LIBRARY_FILE_SERVICE', 'A17\Twill\Services\FileLibrary\Disk'),
    'filesize_limit' => env('FILE_LIBRARY_FILESIZE_LIMIT', 50),
    'allowed_extensions' => [],
  ],

**Comment by amirakbulut** [comment]
Same issue, anyone solved this?

**Comment by ifox** [comment]
Hi guys!

There are a bunch of know issues with the local driver, that #173 is trying to solve. I'm working on making this available in our next release. In the meantime, I would suggest you to define your own disk configuration in your `filesystems.php` config file, something like this:

```
'uploads' => [
    'driver' => 'local',
    'root' => public_path('uploads/files'),
    'url' => '/', // avoids default behavior of Laravel that adds "storage" to any local driver generated URL.
],
```
You'd then replace the default `libraries` disk in your config to `uploads`.

**Comment by ifox** [comment]
The `local` driver is now using Laravel default storage location and this should not be a problem anymore. Check out Twill [1.2.2](https://github.com/area17/twill/releases/tag/1.2.2)!
