### ISSUE TITLE
Twill searches for blade file in /Models/Slugs folder

### ISSUE THREAD

**Issue by amirakbulut** [area17/twill#281]
I followed the documentation on using slugs.

1. Added UseSlugs and slugAttributes array to the model.
2. Added HandleSlugs to it's repository file.
3. Uncommented the migration scheme {model_name}_slugs for the database table
4. Have a {model_name}_slugs.php inside /Models/Slugs folder

However, instead of picking up the {model_name}_slugs.php inside /Slugs folder, it searches for a Blade version of that file instead, as I'm getting this error:

ErrorException (E_WARNING)
include(D:\projects\mdh\vendor\composer/../../app/Models/Slugs/PageSlug.blade.php): failed to open stream: No such file or directory

I have the exact same configuration for another model of mine, without any problems. I created a reproduction Git repository of my project which can be found at:

[https://github.com/amirakbulut/Twill-reproduce](https://github.com/amirakbulut/Twill-reproduce)

Hope someone can help me out.

**Comment by sauron** [comment]
Hey @amirakbulut , 
I took a quick look at your repo.
Can you please verify the correct capitalization?
On
```php
use A17\Twill\Models\Behaviors\hasTranslation;
use A17\Twill\Models\Behaviors\hasSlug;
```
and

```php
use HasBlocks, HasMedias, hasTranslation, hasSlug;
```

It should be `HasSlug` and `HasTranslation`

Also after you uncommented the migration scheme {model_name}_slugs for the database table, did you run rolled-back and run the migration task again, or you just run the migration task?

**Comment by ifox** [comment]
Hi @amirakbulut! Thank you so much for providing such a good report, especially with a reproduction repo, this is really appreciated.

Thanks @sauron! This caught my eyes too.

The fact that it would try to load a Blade is really a mystery to me though 🤔 so let us know how it goes!

**Comment by amirakbulut** [comment]
> Hey @amirakbulut ,
> I took a quick look at your repo.
> Can you please verify the correct capitalization?
> On
> 
> ```
> use A17\Twill\Models\Behaviors\hasTranslation;
> use A17\Twill\Models\Behaviors\hasSlug;
> ```
> 
> and
> 
> ```
> use HasBlocks, HasMedias, hasTranslation, hasSlug;
> ```
> 
> It should be `HasSlug` and `HasTranslation`
> 
> Also after you uncommented the migration scheme {model_name}_slugs for the database table, did you run rolled-back and run the migration task again, or you just run the migration task?

I managed to get it to work, don't ask me how hehe.
