### ISSUE TITLE
Images are not saved to model instance on refresh

### ISSUE THREAD

**Issue by amirakbulut** [area17/twill#283]
**What I did:**

- created a CRUD module with translations
- added use HasMedias, $mediaParams to <myModel>.php
- uncommented the $mediasParams array in <myModel>.php
- added use HandleMedias to <myModel>Repository.php
- added image form field to myModule\form.blade.php form
- added data and an image to an instance of my model through the admin interface

**Problem:**

Upon saving, all the data gets correctly saved to the model instance, except for the images. After refresh all the images of the model instance are gone.

Anyone knows what I'm missing?

**Comment by ifox** [comment]
Hi @amirakbulut!

Can you make sure that the `name` key of your `@formField('medias')` is present in your model's `$mediasParams` array?

It doesn't seem like you would be missing anything else from what you describe.

**Comment by amirakbulut** [comment]
> Hi @amirakbulut!
> 
> Can you make sure that the `name` key of your `@formField('medias')` is present in your model's `$mediasParams` array?
> 
> It doesn't seem like you would be missing anything else from what you describe.

Thank you, it's working now. Will close the issue. :)
