### ISSUE TITLE
Already selected Browser items are not checked

### ISSUE THREAD

**Issue by amirakbulut** [area17/twill#284]
My browser field is working correctly, except for the fact that already checked items are not being shown as checked.

Thanks to @riaan his topic (https://spectrum.chat/thread/2479fe4f-f327-419d-ac82-c44edad1b7c4)https://spectrum.chat/twill/help/set-alread-related-content-to-be-selected-in-browser-window~2479fe4f-f327-419d-ac82-c44edad1b7c4) I found out that it's CSS related.

The file that needs some CSS tweaking is vendor/area17/twill/frontend/js/components/Checkbox.vue, how do I overwrite it to add some custom CSS to it?

**Comment by yanhao-li** [comment]
As the `@stack('extra_css')` is defined in Twill's form layout, you could push to it in your form blade.
```php
@push('extra_css')
  <style>
      .yourclass {
       }
  </style>
@endphp
```

This is very weird, and I can't reproduce it in my project, which has a browser outside of block editor. It will be very helpful if you can share a Twill project which has this issue.

**Comment by yanhao-li** [comment]
Hey @amirakbulut,

I came across the same issue as you this morning, instead of append additional css, I figured out   forget to define the morphMap in `AppServiceProvide`

```
use Illuminate\Database\Eloquent\Relations\Relation;
...
public function boot()
{
    Relation::morphMap([
        'posts' => 'App\Models\Post',
    ]);
}
```
 Hope this helps!
