### ISSUE TITLE
Flash message to the frontend stopped working?

### ISSUE THREAD

**Issue by milewski** [area17/twill#287]
> I first opened this issue on spectrum, reposting here

Hi guys, previous version of twill I was able to flash messages to the client using `session()->flash('status', 'Hello World'));` however it is no longer working with the latest version `1.2.1` is there any alternative way accomplish this now?

**Comment by yanhao-li** [comment]
Hi @milewski ,

By saying the `frontend`, are you meaning the Twill UI? 
If so, I have just tested it, and it works fine on my side.

**Comment by milewski** [comment]
Yes, I mean if you add a new entry on the twill-navigation and send it as a get request for a route like this for example:

```php
$router->get('/test', function() {
    
    session()->flash('status', 'Hello World');

    return redirect()->back();

})
```

In previous twill version I would see that yellow banner at the bottom with "Hello World", but the latest version nothing happens,

I use such mechanism to create custom buttons on the navigation that does some background work.. like schedule a job for example, but currently there is no way to notify the user the action was successful

**Comment by ifox** [comment]
Hi @milewski,

I literally pasted your snippet into a Twill app and got the yellow banner when hitting /test. 

Maybe you are overriding some Twill views?

The only thing that changed there in 1.2 is actually a UX improvement, I added a close action: https://github.com/area17/twill/blob/1.2/views/partials/toaster.blade.php#L5

This partial is loaded from the `footer` partial.

**Comment by milewski** [comment]
@ifox  thanks for that link, I added a `@dd(session('status'))` in that file and it was returning as null... then I realized I was using the api.php route file.. which does not use the start session middleware.. moving the route to web.php it works again...  sorry was my mistake 😳
