### ISSUE TITLE
Setting $indexOptions = [ 'edit' => false] prevents delete

### ISSUE THREAD

**Issue by Riaan-ZA** [area17/twill#289]
Came across an issue, when I set:

```
protected $indexOptions = [
    'create' => false,
    'edit' => false,
    'delete' => true,
];
```

No delete functionality is enabled, I need to set 'create' => true even though I might not want to allow create

**Comment by yanhao-li** [comment]
Hi @Riaan-ZA ,

Yes, that's working as expected. The delete functionality on UI is controlled by the line 617 of `ModuleController.php`: https://github.com/area17/twill/blob/1.2/src/Http/Controllers/Admin/ModuleController.php#L617

As you can see in the code, the item can be deleted only if `delete` and `edit` are both set as true in `$indexOptions`. I believe there is nothing to do with `create` option, are you sure that set `'create' => true` can re-enable the delete functionality here?

Back to your case, if I'm not understanding it wrong -- are you implying that your module, could be deleted, however, can not be edit nor created?

**Comment by Riaan-ZA** [comment]
Hi @yanhao-li, yes sorry you're correct, I meant to write "edit"

The issue I'm having is that I have a module to store submissions from a form. The functionality in the back end that I require is that form submissions can be viewed and deleted on the listing page, but not edited or created. This doesn't seem possible given the above constraint.

**Comment by yanhao-li** [comment]
@Riaan-ZA 

Interesting use case, it should be a good improvement for Twill to separate the canDelete and canEdit logics. However, for now, you can always try overriding the `getIndexTableData ` method (or other methods) to fit your requirement!

**Comment by yanhao-li** [comment]
This issue has been fixed in https://github.com/area17/twill/pull/446, closing this issue.
