### ISSUE TITLE
Undefined index: max

### ISSUE THREAD

**Issue by vacoup95** [area17/twill#292]
>        'usp_repeater' => [
>                 'title' => 'USP',
>                 'trigger' => 'Add new',
>                 'component' => 'a17-block-usp_repeater',
>             ],

Block defined as above allows itself to be created in Twill. But once you save it and re-open it using the listview it will show the error: Undefined index: max

You can fix it by adding a 'max' value to the array, but sometimes you do not want to set a maximum.

**Comment by amirakbulut** [comment]
Just set max to an extreme high integer.

**Comment by yanhao-li** [comment]
Hi @vacoup95 @amirakbulut ,

I can confirm this is a bug, just created a PR to fix it: https://github.com/area17/twill/pull/297.

Thank you for reporting it!
