### ISSUE TITLE
Cannot get repeater to show

### ISSUE THREAD

**Issue by verbeeksteven** [area17/twill#293]
Hello,

I am not sure if I am missing something but I have latest version of twill and Laravel 5.8. I am trying to get a repeater to show up.

I have a model called Font and I want a repeater of Weights where I can add like 700 and a file.

I have

views/admin/fonts/form.blade.php

    @formField('repeater', ['type' => 'weights'])

views/admin/blocks/weight.blade.php

```
@formField('files', [
    'name' => 'weight_file',
    'label' => 'File',
    'noTranslate' => true,
    'max' => 1
])
```

config/twill.php

    'repeaters' => [
        'weight' => [
            'title' => 'Weight',
            'trigger' => 'Add weight',
            'component' => 'a17-block-weight',
            'max' => 15,
        ],
    ]

And I have an eloquent relationship and migration all setup. But I can't get the weights repeater to show on the Font admin edit form. So basically `@formField('repeater', ['type' => 'weights'])` is doing nothing.

Not sure what I am missing?

Thanks!

**Comment by verbeeksteven** [comment]
Got it working, I followed #131

**Comment by arkid** [comment]
@verbeeksteven what isn't clear in that other issue is how the form fields within the repeater are handled.  Specifically, in what view file do they go.  Can you clarify ?

**Comment by devimako** [comment]
how to display images from json repeaters in twill (image is not displayed)

**Comment by haringsrob** [comment]
Hey @devimako,

While this is on Twill 3, here's my aproach:

```
$repeaterItem->image('icon', 'default', ['h' => 150])
```

**Comment by devimako** [comment]
Hi @haringsrob 
<img width="875" alt="Screenshot 2023-01-16 at 10 06 54 PM" src="https://user-images.githubusercontent.com/99637767/212727585-a927ed5a-aca5-4039-a244-c201c4c87d9c.png">
aringsrob  here i try display image but image is not displayed in json repeaters in twill do u have any idea or solution
