### ISSUE TITLE
Use scopes on a Feature::forBucket() call

### ISSUE THREAD

**Issue by tchapi** [area17/twill#300]
Hi

I would like to scope the results of a bucket; So far, I'm putting `Article`s in a bucket, but in case I unpublish an article that is already in a bucket, the following still returns it :

        $articles = Feature::forBucket('home_articles')->all();

What I would like to do is something like this : 

    $articles = Feature::forBucket('home_articles')->scopes(['published', 'visible'])->all();

.. but it doesn't seem possible. Am I missing something here ?

Thanks a lot !
Best

**Comment by ifox** [comment]
Hi @tchapi! 

You are right, it isn't possible. The `forBucket` scope returns all items without conditions. To add support for Eloquent scopes, we'd need to investigate Laravel support for scoped polymorphic queries, not sure that's a thing without reverting to manual joins.

You can filter the results by checking the models "manually" but, I totally hear you, you're loosing the power of scopes... Like, published is easy enough, but visible is much more complex to verify and you can't really share code in a way that feels right with scopes and a custom accessor for example. 

To be honest I would love to see something possible in Laravel: using an Eloquent scope on an Eloquent model instance to verify its compliance to it. In your case you'd filter the articles like this: 

```php
$articles = Feature::forBucket('home_articles')->all()->filter(function ($article) {
    return $article->published()->visible();
});
```

I'm sure this is a problem a lot of Laravel developers are running into. Unless I'm missing something? I'd be curious to hear some thoughts here.

**Comment by tchapi** [comment]
Hello @ifox 

I've thought about it a bit, and the solution I've come up with at the moment is to add a scope in my model (`Article`): 

    public function scopeBucket($query, $bucketKey)
    {
        return $query->select('articles.*')
                     ->leftJoin('features', 'features.featured_id', '=', 'articles.id')
                     ->where([
                        ['bucket_key', '=', $bucketKey],
                        ['featured_type', '=', 'articles'],
                     ])
                     ->orderBy('features.position');
    }

that I can use with : 

    $articles = $repository->bucket('home_features')->scopes(['published', 'visible']);

instead of 

    $articles = Feature::forBucket('home_features')->all();

What do you think of that ?
Thanks

**Comment by ifox** [comment]
That's definitely a viable approach, thanks for sharing! Since then, https://github.com/beyondcode/laravel-scope-checks has been released which can help as well.
