### ISSUE TITLE
Preview and Restore URL generation for submodules

### ISSUE THREAD

**Issue by stevanpavlovic** [area17/twill#302]
I've created a submodule, let's call it `bars`, under a module, let's call it `foos`. I've registered their routes:

```
Route::module('foos');

Route::group(['prefix' => 'foos/{foo}'], function () {
    Route::module('bars');
});
```

The module `bars` has the Preview enabled. So when I tried to access the `bars` edit action `/foos/1/bars/2/edit`, I got the `Illuminate \ Routing \ Exceptions \ UrlGenerationException` with the message: `Missing required parameters for [Route: admin.foos.{foo}.bars.preview] [URI: foos/{foo}/bars/preview/{id}].`. I've investigated the issue and it appears the `Admin\ModuleController` is not handling the URL generation for Preview action for a submodule.

Please check this line:
https://github.com/area17/twill/blob/b85df5ac2c1982041aa5d6b5766263051fb262c6/src/Http/Controllers/Admin/ModuleController.php#L1002

It's trying to generate the URL but it's passing only the `foo`'s id, and misses the `bar`'s id -- meaning, instead of only passing the item's id, it should pass both parent module's id and item's id. So my solution for this particular case was: overriding the `form` method and replacing that line with:

```
'previewUrl' => moduleRoute($this->moduleName, $this->routePrefix, 'preview', $this->submodule ? [$this->submoduleParentId, $item->id] : $item->id),
```

This also applies to the `restoreUrl` generation: https://github.com/area17/twill/blob/b85df5ac2c1982041aa5d6b5766263051fb262c6/src/Http/Controllers/Admin/ModuleController.php#L1005

Has any of you bumped into this issue? Am I missing something? Is this an issue we should fix?
In case this is an issue, I would love to fix this!

**Comment by ifox** [comment]
Hey @stevanpavlovic, thanks for this!

I think we haven't bumped into this issue because of the way we've been declaring routes for submodules: with dot notation. So in your case it would be: `Route::module('foos.bars');`. Your module controller should then be `FooBarsController` and your `moduleName` be `foos.bars`. Can you give it a try and see if it resolves your url generation issues?

**Comment by stevanpavlovic** [comment]
Hey @ifox, thanks for the reply.
I thought I could define a route that could have the following path: `/foos/1/bars` or `/foos/1/bars/2`. That's because a `foo` has its `bars`, meaning there is one-to-many relation between, meaning model `Bar` has a `belongsTo` relation pointing to model `Foo`. That way I could achieve to have `/foos/1/bars` so I could list all `bars` related to a `foo` there. So, your suggestion would not work in this situation, am I right?

**Comment by ifox** [comment]
It would actually! You can display the link to the `bars` listing belonging to a `foo` by adding the following to your admin's `FooController`:

```
'bars' => [
    'title' => 'Bars',
    'nested' => 'bars',
    'html' => true,
],
```

**Comment by ifox** [comment]
See https://laravel.com/docs/5.1/controllers#restful-nested-resources

**Comment by stevanpavlovic** [comment]
Oh, I didn't know about this. Thanks a lot! I will check it out and let you know.

**Comment by stevanpavlovic** [comment]
I can confirm that you are completely right, your suggestion works like a charm! Thank you so much.
