### ISSUE TITLE
Imgix 403 -> DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by raymondtri** [area17/twill#305]
Hello!

I have seen 403s start to pop up all over the admin side of the site, as imgix (when using nocache), is returning 403s. Nothing has changed in terms of my configuration, and the error that I am getting is DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

Does anyone have any experience with this error or any thoughts on how it could be fixed?

**Comment by ifox** [comment]
Hi @raymondtri!

We encountered this issue during the implementation of that component and resolved it using the `crossOrigin` attribute on the `img` tag but I know this can be picky. Maybe the cors setting on Imgix would help? https://support.imgix.com/hc/en-us/articles/360000537526-Cross-Domain-Policy
