### ISSUE TITLE
Saving an empty setting results in errors

### ISSUE THREAD

**Issue by Riaan-ZA** [area17/twill#307]
https://github.com/area17/twill/blob/a7fd4573fcae840980b53977a0573576da0e1ce6/src/Repositories/SettingRepository.php#L49

The ->filter() portion of the above line results in the $settingsTranslated variable not being set when I save a settings page with one setting and I try to leave the setting blank. This results in a php "undefined variable" error.

Removeing the ->filter() fixes it but not sure if this is the best solution

**Comment by ifox** [comment]
This should be fixed in [1.2.2](https://github.com/area17/twill/releases/tag/1.2.2), thanks @ferpetrelli !
