### ISSUE TITLE
Retreiving Browser relationships through elequent Where clause?

### ISSUE THREAD

**Issue by amirakbulut** [area17/twill#314]
I have a Properties Module, which contains a Browser field that adds a City to a specific Property when creating it.

Now I'm in the situation where I need to fetch Properties from a specific Country on my webpage, but I'm not able to get it to work (with just `Property->where('country', 'x')` ) as the relation is declared in another table, named `city_country`.

How am I able to filter my Proprties based on their Country using Elequent Where clause?

My Propery model contains:

```
 public function cities()
    {
        return $this->belongsToMany(\App\Models\City::class);
    }
```

Whereas my City model contains:

```
 public function country()
    {
        return $this->belongsToMany(\App\Models\Country::class);
    }
```

And ofcourse my Country model contains a BelongsToMany Cities. It's working correctly, however I'm not sure how to retreive all Properties from a specific Country.

**Comment by yanhao-li** [comment]
Hey @amirakbulut ,

Checkout Laravel's documentation [https://laravel.com/docs/5.8/eloquent-relationships#has-many-through](Has Many Through) method, I think that's what you are looking for!

**Comment by amirakbulut** [comment]
> Hey @amirakbulut ,
> 
> Checkout Laravel's documentation [Has One Through](https://laravel.com/docs/5.8/eloquent-relationships#has-one-through) or [Has Many Through](https://laravel.com/docs/5.8/eloquent-relationships#has-many-through) methods, I think that's what you are looking for!

Thanks man! However, these methods search for {relation}_id column name within the relation's database table. While Twill handles my relation in a seperate table called City_country.

It returns:

`Column not found: 1054 Unknown column 'cities.country_id' in 'field list' (SQL: select `properties`.*, `cities`.`country_id` as `laravel_through_key` from `properties` inner join `cities` on `cities`.`id` = `properties`.`city_id` where `cities`.`deleted_at` is null and `cities`.`country_id` = 1 and `properties`.`deleted_at` is null)`

**Comment by yanhao-li** [comment]
Hi @amirakbulut , could you clarify your question? 

> How am I able to filter my Properties based on their City using Elequent Where clause?
In this case, have you defined `properities()` Many to Many relation in your `City` model? if so, you could use `City::where('name', $name)->first()->properities()`, otherwise, you could try [WhereHas](https://laravel.com/docs/5.8/eloquent-relationships#querying-relationship-existence)
```php
Property::whereHas('cities', function($query) use ($cityName) {
    $query->where('name', $cityName);
})
```

>however I'm not sure how to retreive all Properties from a specific Country?

If your question is to retrieve all properties from a specific country, please try:

```php
public function properties()
{
    $city_ids = $this->cities()->pluck('id');
    return Property::whereHas('cities', function($query) use ($city_ids) {
        $query->whereIn('id', $cityIds);
    })
}
```

Hope this helpers and please let me know how does it work!

**Comment by amirakbulut** [comment]
> Hi @amirakbulut , which one following is your question?
> 
> > How am I able to filter my Properties based on their City using Elequent Where clause?
> 
> In this case, have you defined `properities()` Many to Many relation in your `City` model? if so, you could use `City::where('name', $name)->first()->properities()`, otherwise, you could try [WhereHas](https://laravel.com/docs/5.8/eloquent-relationships#querying-relationship-existence)
> 
> ```
> Property::whereHas('cities', function($query) use ($cityName) {
>     $query->where('name', $cityName);
> })
> ```
> 
> > however I'm not sure how to retreive all Properties from a specific Country?
> 
> If your question is to retrieve all properties from a specific country, please try:
> 
> ```
> public function properties()
> {
>     $city_ids = $this->cities()->pluck('id');
>     return Property::whereHas('cities', function($query) use ($city_ids) {
>         $query->whereIn('id', $cityIds);
>     })
> }
> ```
> 
> Hope this helpers and please let me know how does it work!

Sorry, I wrote this thread yesterday night (sleepy) and now notice some mistakes. You're right, my question is to retrieve all properties from a specific country, I updated the thread accordingly.

So I tried the following within my Country model:

```
public function properties()
{
    $city_ids = $this->cities()->pluck('id');
    return Property::whereHas('cities', function($query) use ($city_ids) {
        $query->whereIn('id', $cityIds);
    })
}
```

And it returns:

```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous (SQL: select `id` from `cities` inner join `city_country` on `cities`.`id` = `city_country`.`city_id` where `city_country`.`country_id` = 1 and `cities`.`deleted_at` is null)
```

I tried to find the issue but were not able to solve it. I really appriciate your time.

**Comment by yanhao-li** [comment]
Change the line from
```
$query->whereIn('id', $city_ids);
```
to 
```
$query->whereIn('cities.id', $city_ids);
```

**Comment by amirakbulut** [comment]
> Change the line from
> 
> ```
> $query->whereIn('id', $city_ids);
> ```
> 
> to
> 
> ```
> $query->whereIn('cities.id', $city_ids);
> ```

I modified the code to my project:

```
public function properties()
    {
        $city_ids = $this->cities()->pluck('city_id');
        return Property::whereHas('cities', function($query) use ($city_ids) {
            $query->whereIn('cities.city_id', $city_ids->all());
        });
    }
}
```
and call it using:

```
$country = Country::findOrFail(1);
$properties = $country->properties();
print_r($properties);
exit();
```
which returns:

`Allowed memory size of 134217728 bytes exhausted (tried to allocate 60821504 bytes)`

**Comment by yanhao-li** [comment]
Hey @amirakbulut ,

My above code only serve as an example of one approach that my solve such problem. If it can't work, always feel free to use `join` or `with` to do the job!
