### ISSUE TITLE
Overriding some properties in controller doesn't work

### ISSUE THREAD

**Issue by manuelsofia** [area17/twill#315]
Hi all :)

I am using Twill 1.2.0 and I can't get the $perPage and $defaultOrders module properties to work. I can successfully override any value on the $indexOptions array or change the $titleColumnKey successfully, but when I try with the other two mentioned properties it simply doesn't work. I've tried clearing all the laravel cache options but it didn't help. Any ideas? Thanks!

**Comment by Turpoint** [comment]
My $perPage doesn't seem to have any effect too.

**Comment by ferpetrelli** [comment]
Hi @manuelsofia, @Turpoint,

Are your models implementing the `Sortable` interface?
If that's the case, then this behavior is expected. The reason is that enabling drag&drop reordering in a multi-page listing will bring new UX challenges.

Having said that, this is not the first time a `Sortable` related issue has been reported, so we will definitely create a path forward to improve Twill docs, and to create a cleaner way to implement this.

**Comment by manuelsofia** [comment]
Thank you very much for your reply @ferpetrelli. Yes, I implemented the Sortable interface, I realised that was the problem. However, the $perPage doesn't seem to work at all. Thank you :)

**Comment by pramithagayan** [comment]
@manuelsofia its easy fix this. 

This happens due to a 2 lines of code in the vendor/area17/twill/src/Http/Controllers/Admin/ModuleController.php

```
        // don't apply default orders if reorder is enabled
        $reorder = $this->getIndexOption('reorder');
        $defaultOrders = ($reorder ? [] : ($this->defaultOrders ?? []));
```

So to fix this replace orderScope() function in your module controller file. So your module controller would look like this.

```
<?php

namespace App\Http\Controllers\Admin;

use A17\Twill\Http\Controllers\Admin\ModuleController;

class CareerController extends ModuleController
{
    protected $moduleName = 'careers';


    /*
     * Options of the index view
     */
    protected $indexOptions = [
        'reorder' => true,
    ];

    protected $defaultOrders = ['position' => 'asc'];

    protected function orderScope()
    {
        $orders = [];
        if ($this->request->has('sortKey') && $this->request->has('sortDir')) {
            if (($key = $this->request->get('sortKey')) == 'name') {
                $sortKey = $this->titleColumnKey;
            } elseif (!empty($key)) {
                $sortKey = $key;
            }

            if (isset($sortKey)) {
                $orders[$this->indexColumns[$sortKey]['sortKey'] ?? $sortKey] = $this->request->get('sortDir');
            }
        }

        $defaultOrders = $this->defaultOrders;

        return $orders + $defaultOrders;
    }
}
```

**Comment by manuelsofia** [comment]
Thank you @pramithagayan, will try this out! :)

**Comment by pramithagayan** [comment]
@manuelsofia sure thing :) hope it worked for you. even though im not sure if its the best way to get this sorted. someone from twill can confirm it.

**Comment by ershadow786** [comment]
> Hi all :)
> 
> I am using Twill 1.2.0 and I can't get the $perPage and $defaultOrders module properties to work. I can successfully override any value on the $indexOptions array or change the $titleColumnKey successfully, but when I try with the other two mentioned properties it simply doesn't work. I've tried clearing all the laravel cache options but it didn't help. Any ideas? Thanks!

How can you able to override $indexOptions?
