### ISSUE TITLE
Link Quill image button with media library

### ISSUE THREAD

**Issue by tchapi** [area17/twill#318]
Hello

The Quill wysiwyg editor is nice, but when adding images, it dumps a data/base64 image in the middle of the content, which is not ideal for big images, and is not ideal for reuse, too.

Is there a possibility to link the image button of the Quill editor to the Media library, so we can choose / upload an image, and a `<img>` tag is placed in the content?

Thanks a lot !

**Comment by ifox** [comment]
As explained elsewhere and in our docs:  the image module is not integrated with Twill's media library. It outputs the base64 representation of the uploaded image. It is not a recommended way of using and storing images, prefer using one or multiple medias form fields or blocks fields for flexible content. This will give you greater control over your frontend output.

**Comment by henzeb** [comment]
to be clear, the frontend designer as more control over over the frontend output. the content editor is limited in his creativity and for simple website designs where there is no issue in adding an image with text-wrapping, this is a huge overkill. it basically is a limitation from Twill.

**Comment by Tofandel** [comment]
I think it would still make a lot of sense to add the possibility, I don't know what has changed since this issue was about Quill and now we are using tip tap, which should offer to add this much more easily than Quill did
