### ISSUE TITLE
Nested relationship save

### ISSUE THREAD

**Issue by LCD344** [area17/twill#322]
I'm working some more on the CMS and igging through the docs, and trying to find out how to actually use the nested relationship and I see that it works if I manually feed the database, but I'm trying to make it a field on the model.

I added a browser field to the form

```
@formField('browser', [
		'label' => 'Parent',
		'max' => 1,
		'name' => 'parent',
		'moduleName' => 'pages',
	])
```

I also tried to call the name parent_id, hoping this will make it save but it didn't happen.

Then I started reading the documentation, and I saw that there is a built in documentation for saving browser, but it is related to the  belongToMany while parent id is a belongs to. So my question is, is there a recommended way to do this and is it documented and I missed it? or should I write my own logic for that in the afterSave on the repository?

Thanks

**Comment by zedee** [comment]
Hi!

Check this post on Twill Spectrum:

https://spectrum.chat/twill/help/browser-field-not-inside-a-block~6dbee805-8542-4a39-87dc-5eb1c658aed4

**Comment by LCD344** [comment]
@zedee  - thanks!

**Comment by ferpetrelli** [comment]
Closing this as the issue seems to be solved. Please feel free to send us a message on Spectrum if you continue to have difficulties.
