### ISSUE TITLE
maximum width and height in mediaParams

### ISSUE THREAD

**Issue by dijitaq** [area17/twill#323]
Hi,
I noticed in a tutorial on [spectrum chat](spectrum.chat/twill/tips-and-tricks/step-by-step-creating-a-twill-app~ac9bd7f7-d1e3-46a8-8e6f-6075d92cdac7) that the crops included a 'minValues' parameters. I am wondering whether Twill support 'maxValues' parameters? I tried `maxValues => [ width => 1280, height => 720]`, but the image would not crop to the specified dimensions.

**Comment by ifox** [comment]
Very late than never, but this is indeed not supported. The min values are actually just a visual indicator in the cropping tool right now. PRs are welcome to add new features like that!
