### ISSUE TITLE
Select not translateble

### ISSUE THREAD

**Issue by vacoup95** [area17/twill#325]
I've added a formfield to my block which I would assume would allow me to select a field based on the selected language. But select fields do not seem to be translatable. 

```
@formField('select', [
    'name' => 'icon',
    'label' => 'Select an icon',
    'placeholder' => 'Icons',
    'translated' => true,
    'options' => [
        [
            'value' => 'markets',
            'label' => 'Markets'
        ],
        [
            'value' => 'support',
            'label' => 'Support'
        ],
        [
            'value' => 'career',
            'label' => 'Career'
        ],
        [
            'value' => 'recycle',
            'label' => 'Recycle'
        ],
        [
            'value' => 'sla',
            'label' => 'SLA'
        ],
        [
            'value' => 'spareparts',
            'label' => 'Gears'
        ]
    ]
])
```

**Comment by kedves** [comment]
Did you managed to translate select type?

**Comment by yanhao-li** [comment]
Doesn't make sense to me to have a translatable/editable `select` field, I would suggest using Laravel's [Translation String](https://laravel.com/docs/master/localization) instead. 
Closing this issue now, feel free to reopen it if further discussion is needed.

**Comment by antonioribeiro** [comment]
Kind of make sense if the select is a modifier. Let's say it's a video source selector the source and the video in French is hosted on Youtube, but the same video in English was somehow hosted on Vimeo. Not only the Video ID and the Caption are translatable, but we also need the type of source to be stored according to the language.

**Comment by devimako** [comment]
how to save the select fields value in table (value is not saved in table ) after submitting the form
