### ISSUE TITLE
Error Twill on Raspbian latest

### ISSUE THREAD

**Issue by EPInformatyka** [area17/twill#326]
Error when we use command php artisan twill:build on Raspbian latest: The process "'npm' 'ci'" exceeded the timeout of 60 seconds.

General, Twill doesn't work good (compile frontend via npm) of Raspbian latest

**Comment by mazeeblanke** [comment]
try using npm, 

add this to your package.json script section `"twill-build": "rm -f public/hot && npm run twill-copy-blocks && cd vendor/area17/twill && npm ci && npm run prod && cp -R public/* ${INIT_CWD}/public",`

then run npm run twill-build
