### ISSUE TITLE
error PDOException on php artisan twill:setup

### ISSUE THREAD

**Issue by khyoz** [area17/twill#33]
(Windows10 / Mamp Pro 4 / php 7.1.7)

1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'fk_your_plural_module_name_translations_your_plural_module_name_id' is too long")
      D:\MAMP\htdocs\twill\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

  2   PDOStatement::execute()
      D:\MAMP\htdocs\twill\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

**Comment by noxify** [comment]
Hi @khyoz,

* I assume you have created a new module with a command like this `php artisan twill:module yourPluralModuleName -B -T -S -M -F -P -R`
* Did you tried it with an other module name?  ;)


@ifox - I can reproduce the error in my vagrant box, but this issue occurs based on the limitation in mysql.

Possible workaround/solution is to define other key names: https://laraveldaily.com/migration-index-too-long-choose-the-name-yourself/

**Comment by ifox** [comment]
Hi @khyoz,

Like @noxify correctly identified, it seems like you created a new CRUD module without choosing a name for it.

In our docs, `yourPluralModuleName` is not a proper example, but rather an indication that you should use the plural form of your Laravel model in the artisan command parameter. 

So actual examples would be `php artisan twill:module articles` or `php artisan twill:module events`.

**Comment by khyoz** [comment]
ok thanks, you were right, I used `yourPluralModuleName`. I will retry following your advices.
