### ISSUE TITLE
/admin-preview route doesn't work?

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#334]
Hi,

Re the page preview link (underneath the module title when editing a module):

If a module is set as draft, the URL is as follows:

mydomain.com/**admin-preview**/project/myproject

The /admin-preview route doesn't seem to work, and on my frontend it goes to 404. (When the module is set to live, the preview URL changes to mydomain.com/project/myproject and it works fine).

What mistake am I making here?

I'm now getting around it by redirecting via a front-end route.
~BTW I managed to get around this by overriding getPermalinkBaseUrl() in my admin module controller (removing the line that adds the /admin-preview route), but I don't feel very comfortable doing that!~

Thanks,
Seb

**Comment by ferpetrelli** [comment]
Hi @sebastianlenton,

This behavior should be disabled by default, and enabled only through configuration.
Right now it also seems to be attached only to models using revisions, which is incorrect. We will release a new version of Twill this week and a fix for this will be pushed right after.

**Comment by sebastianlenton** [comment]
Thanks @ferpetrelli!

**Comment by Tofandel** [comment]
Has this actually been fixed? This issue still seems to be present in the latest twill

**Comment by ifox** [comment]
There is nothing to fix there @Tofandel. We can certainly make it configurable, but this is meant to be a way for developers to set up an authenticated route in their frontend to preview draft records outside of the CMS, eg. for external users. Developers are free to set up something like basic HTTP authentication or any sort of auth for that route in the frontend, and of course that's out of Twill's scope.

I agree it lacks documentation, is opinionated, and could be improved, don't get me wrong, but I wanted to provide some context.

**Comment by Tofandel** [comment]
There is other ways to achieve this, it could be done with a query parameter and a signed route for example we can store it in the session as well, then in the published scope we can ignore it if the conditions are met, this would put this feature entirely in twill, without a custom route and without burden to the user while still being shareable to non twill users, as long as they have the preview url
