### ISSUE TITLE
Pagination not working when model implements Sortable

### ISSUE THREAD

**Issue by stu177** [area17/twill#336]
Pagination in the index view doesn't apply when the model implements Sortable.

Running version 1.2.1.

Pagination works:
```php
class Blog extends Model
```

Broken:
```php
class Blog extends Model implements Sortable
```

**Comment by ferpetrelli** [comment]
This behavior is expected by design, given that reordering (drag and drop) in a paginated listing won't allow you to move elements between pages.
We will be exploring some options to allow some sort of compromise, but in the meantime we will update the docs to clarify this.

**Comment by stu177** [comment]
Yeh I had someone on spectrum inform me, it would be a nice feature but yeh having the docs show this would save a lot of confusion :)

What reordering do you mean? I'm somewhat new to Twill so not 100% where this is. Is it possible to reorder records in the list view?
