### ISSUE TITLE
Top left logo and title a href link in the Twill page header is hard coded to redirect to server root /

### ISSUE THREAD

**Issue by arkid** [area17/twill#338]
The html in the vendor/area17/twill/views/partials/_title.blade.php file is defined as follows with a hard coded "/" for the ahref of the page title/logo:

```
<h1 class="header__title">
    <a href="/">{{ config('app.name') }} <span class="envlabel">{{ app()->environment() === 'production' ? 'prod' : app()->environment() }}</span></a>
</h1>
```

This is really inflexible, if you are running twill on a sub-folder this will naturally not work as standard. Please make it access one of the app variables as default or at least have an override with an optional app variable

**Comment by arkid** [comment]
For the record, I've updated mine to {{ config('ADMIN_APP_URL') }}  but I assume this will get overwritten at some point so not ideal

**Comment by arkid** [comment]
Ah Ive just seen this:  https://github.com/area17/twill/pull/337/commits/a43f171672a34687f6ec7edb704e2022f8391bcb   Please merge this change! :)

**Comment by yanhao-li** [comment]
It is kind of a coincidence that we found the same issue at same time. Hope it could be merged soon!

**Comment by yanhao-li** [comment]
Closed because https://github.com/area17/twill/pull/337 has been merged.
