### ISSUE TITLE
Translated fields are empty when a single language is used

### ISSUE THREAD

**Issue by ferpetrelli** [area17/twill#340]
Steps to reproduce:

1. Setup your app to have 2+ languages.
2. Create a model with a translated input field and fill up some data.
3. Reduce the number of languages to 1.
4. The field now looks as a regular non-translated input field (good), but the content is empty (not so good).

NOTE: Inspecting the database shows that the fields are correctly updated.

Tested on: 

* OS: Mac OS Sierra
* Browser: Chrome, Firefox, Safari

**Comment by pboivin** [comment]
Hi @ferpetrelli, catching up on old issues :)

I'm pretty sure this is due to a mismatch between `app.locale` and `translatable.locales` configurations. To summarize, if your are using translations and only one active language, the 2 configs must be set to the same language.
