### ISSUE TITLE
Modifying the list table for Page Crud

### ISSUE THREAD

**Issue by pramithagayan** [area17/twill#345]
Hi Guys,

I have created a new crud page and everything works as expected so far. Thanks for your great CMS. But I have an small issue with list tables. There is a language column in this page listing page which I dont need as I dont use any translations. And I want to add published date column to this table. Can you guide me how do I modify the columns of this table. Thanks.

![image](https://user-images.githubusercontent.com/50757396/62746828-2ec04700-ba6f-11e9-8ecc-07107770fe52.png)

**Comment by lorrenrules** [comment]
@pramithagayan You can adjust the columns in your module controller via the indexColumns array. See https://twill.io/docs/#controllers for an example.

**Comment by pramithagayan** [comment]
> @pramithagayan You can adjust the columns in your module controller via the indexColumns array. See https://twill.io/docs/#controllers for an example.

Yeah I found it after I posted this here. But still im not sure how to remove language column from the table. I can add new new columns though

**Comment by lorrenrules** [comment]
Does your model happen to have the hasTranslation trait? The method which builds the indexColumns in the default ModuleController adds the languages column if the model has that trait.
`
        if ($this->moduleHas('translations')) {
            array_push($tableColumns, [
                'name' => 'languages',
                'label' => 'Languages',
                'visible' => $visibleColumns ? in_array('languages', $visibleColumns) : true,
                'optional' => true,
                'sortable' => false,
            ]);
        }
`

**Comment by pramithagayan** [comment]
> Does your model happen to have the hasTranslation trait? The method which builds the indexColumns in the default ModuleController adds the languages column if the model has that trait.
> 
> ```
>         if ($this->moduleHas('translations')) {
>             array_push($tableColumns, [
>                 'name' => 'languages',
>                 'label' => 'Languages',
>                 'visible' => $visibleColumns ? in_array('languages', $visibleColumns) : true,
>                 'optional' => true,
>                 'sortable' => false,
>             ]);
>         }
> ```

Yes it has a hasTranslation trait. But I actually dont need that. Problem is when I remove the hasTranslation trait and try to create a new post it shows validation fails error message. Do you know why? if I could able to create page module without translation trait my problem will be solved. :)

**Comment by lorrenrules** [comment]
@pramithagayan It sounds like when you created your module, you accidentally added the translation flag. Remove the trait from your model and make sure the `$translatedAttributes` are commented out, and also remove the trait from the module repository. You may also want to remove the translations from your migration as well if you aren't using it. Hope this helps.

**Comment by ifox** [comment]
This should be resolved automatically thanks to #532. As a user, you can also hide columns so that they do not display on subsequent visits to the listing page.
