### ISSUE TITLE
Support `maxlength` in `wysiwyg` fields

### ISSUE THREAD

**Issue by IllyaMoskvin** [area17/twill#35]
Twill gives us the ability to specify a max-length attribute when defining `input` fields:

```
@formField('input', [
    'name' => 'title',
    'label' => 'Title',
    'maxlength' => 60
])

@formField('input', [
    'type' => 'textarea',
    'name' => 'description',
    'label' => 'Description',
    'rows' => 4,
    'maxlength' => 500
])
```
Doing this does not enforce strict input validation AFAICT, but it does give the user a nice countdown of how many characters they have left as they type:

<img width="596" alt="maxlength-indicator" src="https://user-images.githubusercontent.com/3881840/45228481-e4e04700-b288-11e8-983e-ef4bf9682de6.png">

It would be neat if `wysiwyg` inputs could support this `maxlength` indicator too.

(Correct me if this is already implemented in newer versions of Twill.)

**Comment by ifox** [comment]
Hi @IllyaMoskvin,

sorry for the delay here, we're actually about to release Twill 1.2 with a bunch of improvements (no breaking changes for you guys)!

Exactly, the option does not enforce script input validation, but you are free to add a backend validation that would prevent from saving and show an error message next to the field.

Adding the option to the WYSIWYG input has been on our minds for a while actually! Quill has an example available [here](https://codepen.io/quill/pen/wWOdXZ) with a word counter. It should be feasible to update Twill's Quill configuration to have a letter counter. We'd need to strip html tags from the editor content though.
