### ISSUE TITLE
Bug: Setting GLIDE_BASE_PATH=/ overrides all routes 

### ISSUE THREAD

**Issue by tbrasington** [area17/twill#350]
This is on version 1.2.2.

If you set the env GLIDE_BASE_PATH to a / it will cause all routes to be rendered via the glide service. 

e.g.

> www.project.com/projects

Returns the error

> League\Glide\Filesystem\FileNotFoundException thrown with message "Could not find the image `projects`."
 

I came across this when configuring Glide with S3

**Comment by ifox** [comment]
Hi @tbrasington,

I'm not sure I understand the use case for setting the Glide base path to `/`. This path is the entry point to your Glide server on your Laravel app, so you need something behind `/`. To setup S3 storage, you should change the `glide.source` config to reference a S3 filesystem disk.

**Comment by tbrasington** [comment]
So I set GLIDE_SOURCE=s3 but do you have to configure it with Storage::disk('s3') ?

**Comment by ifox** [comment]
You will need to use the configuration file, not `.env`, as you have to provide an instance of a flysystem adapter, see https://glide.thephpleague.com/0.3/config/source-and-cache/. Let me get back to you with a working example asap. We're also going to expand our docs on the various options for Glide soon.

**Comment by tbrasington** [comment]
Thank you! I am hacking around with it so no rush. Looking forward to learning more.

**Comment by tbrasington** [comment]
I have it working !

in twill.php

```
use Aws\S3\S3Client;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;

$client = new S3Client([
    'credentials' => [
        'key'    => env('S3_KEY'),
        'secret' =>  env('S3_SECRET'),
    ],
    'region' => env('S3_REGION'),
    'version' => 'latest',
]);

$adapter = new AwsS3Adapter($client, env('S3_BUCKET'));

$filesystem = new Filesystem($adapter);

```

then in the config array

```
'glide' => [
        'source' => env('GLIDE_SOURCE',  $filesystem ),
        'cache' => env('GLIDE_CACHE', storage_path('app')),
        'cache_path_prefix' => env('GLIDE_CACHE_PATH_PREFIX', 'glide_cache'),
        'base_url' => env('GLIDE_BASE_URL', request()->getScheme() . '://' . config('app.url')),
        'base_path' => env('GLIDE_BASE_PATH', 'img'),
        'use_signed_urls' => env('GLIDE_USE_SIGNED_URLS', false),
        'sign_key' => env('GLIDE_SIGN_KEY'),
        'default_params' => [
            'fm' => 'jpg',
            'q' => '80',
            'fit' => 'max',
        ],
        'lqip_default_params' => [
            'fm' => 'gif',
            'blur' => 100,
            'dpr' => 1,
        ],
        'social_default_params' => [
            'fm' => 'jpg',
            'w' => 900,
            'h' => 470,
            'fit' => 'crop',
        ],
        'cms_default_params' => [
            'q' => '80',
            'dpr' => '1',
        ],
    ],
```

**Comment by impactcolor** [comment]
@tbrasington hi where is the config file to set this up? Is there anything that needs to be set in the .env file?

**Comment by impactcolor** [comment]
@ifox hi any working example?

**Comment by tbrasington** [comment]
> @tbrasington hi where is the config file to set this up? Is there anything that needs to be set in the .env file?

You will need to add the GLIDE_xxxx to Your .env files. 
The rest is in the standard twill config https://github.com/tbrasington/jam-twill/blob/master/config/twill.php

**Comment by impactcolor** [comment]
Hi! Here goes my .env file 
`FILE_LIBRARY_ENDPOINT_TYPE=s3
MEDIA_LIBRARY_ENDPOINT_TYPE=s3
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Glide
MEDIA_LIBRARY_ACL=public-read
S3_KEY=MYKEY
S3_SECRET=MYSECRET
S3_BUCKET=MYBUCKETNAME
S3_REGION=us-west-1
`

Then config/twill.php:
`<?php

use Aws\S3\S3Client;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;

$client = new S3Client([
    'credentials' => [
        'key'    => env('S3_KEY'),
        'secret' =>  env('S3_SECRET'),
    ],
    'region' => env('S3_REGION'),
    'version' => 'latest',
]);

$adapter = new AwsS3Adapter($client, env('S3_BUCKET'));

$filesystem = new Filesystem($adapter);

//'source' => env('GLIDE_SOURCE', storage_path('app/public/' . config('twill.media_library.local_path'))),

return [
  'glide' => [
    'source' => env('GLIDE_SOURCE',  $filesystem),
    'cache' => env('GLIDE_CACHE', $filesystem),
    'cache_path_prefix' => env('GLIDE_CACHE_PATH_PREFIX', 'glide_cache'),
    'base_url' => env('GLIDE_BASE_URL', env('S3_BUCKET')),
    'base_path' => env('GLIDE_BASE_PATH', ''),
    'use_signed_urls' => env('GLIDE_USE_SIGNED_URLS', false),
    'sign_key' => env('GLIDE_SIGN_KEY'),
],
  'enabled' => [
    'users-management' => true,
    'media-library' => true,
    'file-library' => true,
    'block-editor' => true,
    'buckets' => true,
    'users-image' => false,
    'settings' => true,
    'dashboard' => true,
    'search' => true,
    'users-description' => false,
    'activitylog' => true,
    'users-2fa' => false,
    'users-oauth' => false,
],
];
`
I got the uploads to work in twil but on the front end I get this error:
```
League\Glide\Server::makeImage
vendor/league/glide/src/Server.php:499
```
My controller access the image like this:
```
      $printCategory = $this->repository->forSlug($slug);
      abort_unless($printCategory, 404, 'Project ');

      return view('layouts.details', ['printCategory' => $printCategory]);
```

Any idea what's going on with it?

**Comment by denniskong** [comment]
Why is this closed? Where is the solution?
Running into the same issue like @impactcolor

**Comment by impactcolor** [comment]
I jus tended up jumping ship on Twill.  @denniskong
