### ISSUE TITLE
Documentation update: revisions requires block editor to be enabled

### ISSUE THREAD

**Issue by arkid** [area17/twill#351]
Please make clear in the Revisions and Previewing part of documentation (and maybe elsewhere?) that if revisions are enabled that the twill config file must have 'block-editor' set to true.   

You get a routing related error otherwise with Twill looking for admin.blocks.preview

**Comment by arkid** [comment]
I was thinking that maybe another good place to add some comments to stop people getting stuck is inside the default twill.php config file.

If each of the core settings there had some notes it would be really useful!   So many of these settings have knock on effects past the obvious explanation of the function that the setting suggests it controls.

For example, turn off _activitylog_ and the dashboard won't work properly.   Turn off _block-editor_ and revisions won't work.   If very brief common dependencies of these settings could be explained for each setting it would be a really useful reference on initial site setup.

**Comment by ifox** [comment]
Agreed, thank you @arkid. However I think some of those dependencies should be solved in code rather than documented, when possible of course. Revisions should still work when turning off block editor and dashboard should still work when turning the activity log off, so I'd rather fix those bugs than document technical debt.

**Comment by arkid** [comment]
I agree @ifox ideally in code!   

However I'm aware of what a huge amount of things still need doing in Twill so my suggestion was a compromise, one I felt could have real benefits now and stop loads of unnecessary github issues/spectrum chat posts.    

I think the biggest problem with Twill is that it isn't documented enough and there are tons of things that someone will hit upon the first few times setting up Twill, with or without Laravel experience.

Regarding just that point; is it not possible that you setup a new documentation system, one that separates the documentation into multiple pages and either allows for group editing as in a wiki of some kind OR at least allows for comments under each article (ala the PHP documentation).  

Area17 would really be helping themselves if they can help others more with better documentation for Twill I feel.

**Comment by ifox** [comment]
No doubt that our documentation needs improvements however I'm not sure what is preventing collaboration at the moment. The docs are open source in the repo, so commenting and contributions are already possible. I don't want to end up with a cluttered comments section on the documentation itself like PHP docs.

**Comment by arkid** [comment]
Ah ok sorry silly me, I didn't realise they were in the repro!  I will have
a look at submitting some changes ;)

**Comment by arkid** [comment]
Something you may want to take the lead on though is splitting the documentation up into multiple files.   I think it needs to be a lot more verbose and if the doc was split into multiple pages now that may encourage more detailed documentation per topic.

**Comment by ifox** [comment]
Did you take a look at the docs structure in the repo? This is a Vuepress project that is already split into 10 different markdown files. We can definitely split it more as we go.

https://github.com/area17/twill/tree/1.2/docs/.sections

**Comment by arkid** [comment]
Ok thanks good to know.

**Comment by ifox** [comment]
Fixed in #380.
