### ISSUE TITLE
Request: option to make default record state published instead of draft

### ISSUE THREAD

**Issue by arkid** [area17/twill#352]
This is discussed in [this issue](https://github.com/area17/twill/issues/114) but I don't believe there is a clear solution to this and understand it will need a bit of extra functionality within Twill in order to work.

I would also suggest that the whole draft/published functionality can be simplified by a twill config option as well by having the draft state fully disabled with the sliding switch not visible when adding/editing records.    For some very simple data models this is just totally unnecessary functionality / complexity a user shouldn't have to deal with when wanting to create content as quickly as possible.

**Comment by ifox** [comment]
If you do not need a publication state, you can remove the `published` column from your table as well as your model's fillable. You can also visually disable it even if you keep the column, which could be set to default to true in your migration. See: https://github.com/area17/twill/blob/2abd816082a5370beeab72e03084345cb99d613f/views/layouts/form.blade.php#L131.
