### ISSUE TITLE
You forgot to update the VERSION file?

### ISSUE THREAD

**Issue by arkid** [area17/twill#353]
Hi guys... someone forgot to update the VERSION file with this 1.2.2 release ? ;)

**Comment by ifox** [comment]
Ha @arkid, we're busted! I guess 1.2.3 is around the corner then!

**Comment by ifox** [comment]
Fixed in faf7c8debcfecd483e04050c9d5679faa0be9df0!

**Comment by arkid** [comment]
Hahaha I wouldn't have mentioned it otherwise but because twill reads the file into the footer of the site its visible constantly when using the software, hence confusing.
