### ISSUE TITLE
Model files created by artisan:twill module don't uncomment required elements when some traits are used

### ISSUE THREAD

**Issue by arkid** [area17/twill#354]
The model files created in /app/Models  don't seem to uncomment all the required elements.   

For example, I've been using the _artisan:twill module_ command with the _-hasSlug_ handle but the part of the model file that states:

```
 public $slugAttributes = [
    'title',
];
```

is always commented out.   In most cases I imagine users will want to use the default title value.  Not uncommenting this means that creating the first records via Twill will result in "Your submission could not be validated, please fix and retry" errors with such models.

**Comment by arkid** [comment]
I assume there may well be other examples of this as well with other traits...

**Comment by arkid** [comment]
Returning to this, it would be fantastic if other common properties were placed into the files that the CLI creates.    

A common one that would be really useful is listing $indexOptions in the controller file with all the options spelt out, set to their defaults...

    protected $indexOptions = [
      'create' => true,
      'edit' => true,
      'publish' => true,
      'bulkPublish' => true,
      'feature' => false,  // stars
      'bulkFeature' => true,
      'restore' => true,
      'bulkRestore' => true,
      'delete' => true,
      'bulkDelete' => true,
      'reorder' => false,
      'permalink' => true,
      'bulkEdit' => true,
      'editInModal' => false,
  ];

**Comment by ifox** [comment]
A lot of improvements have been made to the generated files for our upcoming release. Thanks for the suggestions @arkid!
