### ISSUE TITLE
create unittests

### ISSUE THREAD

**Issue by Gummibeer** [area17/twill#356]
Atm there is not a single test for anything in the package!?

This should be changed - it would make it easier for contributors to know if they break something and give all a better feeling to merge/release anything.

**Comment by Gummibeer** [comment]
I would like to help but one of the repo admins has to enable StyleCI, TravisCI/CircleCI and all the great tools.^^
I would think that we should start with a simple setup and don't start with a 9x% coverage. This would allow to add unittests for upcoming bugs and also add the planned ones time after time.

I would like to help, and also offer to create the basic php unittests setup. But I can't help with frontend/vue.

Let me know if you want me doing it.

**Comment by titantwentyone** [comment]
I would like to help with this also. Think it would be hugely beneficial to the project. I'm just starting out with Twill and have dived into the source so no expert (yet!) but will help if I can.

**Comment by ifox** [comment]
Hi @Gummibeer! Sorry for the delay in getting back to you. We're working on setting all the tools up right now with the help of @antonioribeiro! Once this is ready, we will of course welcome community contributions to improve our test coverage and code quality.

Thank you so much for offering your help too @titantwentyone!

**Comment by antonioribeiro** [comment]
I just sent a PR to provide the test environment and some of those tools @Gummibeer mentioned: 

https://github.com/area17/twill/pull/419
