### ISSUE TITLE
Unable to add existing model without deleted_at/retired_at

### ISSUE THREAD

**Issue by brianhogg** [area17/twill#359]
I'm not able to add an existing laravel model under Twill, as it's looking for fields `deleted_at` and `retired_at` in the query despite not using the soft deletes trait. I've scoured the docs and not seeing a way to have it work without adding these fields.

It also is adding a couple additional fields to the query, not sure how it's determining which ones to pull when showing the index.

**Expected**

I'm able to add a controller/resource/config for an existing model, and be able to list and edit the fields specified under form.blade.php (and that are fillable).

**Actual**

When going to the index page for the model you get the following error:

```
Column not found: 1054 Unknown column 'projects.deleted_at' in 'where clause' (SQL: select count(*) as aggregate from `projects` where `projects`.`deleted_at` is null and `published` = 1 and (`retired_at` is null or `retired_at` > 2019-09-03 20:06:51) and (`external_shared_project_id` is null or `shared_project_is_main` = 1) and (`description` is not null and `description` != ))
```

so I would need to add `deleted_at` and `retired_at` even if not configured anywhere.

**Comment by ifox** [comment]
`retired_at` is not a column name referenced anywhere in Twill. It seems like you have something in your own code modifying the query, a global scope potentially. As for `deleted_at`, this is indeed a requirement since your model should inherit from Twill's model which uses the SoftDeletes trait.
