### ISSUE TITLE
npm node-sass@4.8.3 is missing

### ISSUE THREAD

**Issue by NACILON** [area17/twill#36]
Hi

I've issue when trying to launch twill.
```
> node-sass@4.8.3 install C:\OSPanel\domains\laravel-twill-cms-builder\vendor\area17\twill\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.8.3 postinstall C:\OSPanel\domains\laravel-twill-cms-builder\vendor\area17\twill\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\OSPanel\domains\laravel-twill-cms-builder\vendor\area17\twill\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
```

Please, may someone update dependencies?

The latest version of node-sass - 4.9.3 for now
https://github.com/sass/node-sass/releases/tag/v4.9.3

**Comment by ifox** [comment]
Hi @NACILON, thanks for reporting your issue.

I'm assuming you are running Node version 10. Twill uses Laravel Mix and SASS sources which requires node-sass 4.8.3 in our current version.

The problem for you is that node-sass does not have a binary for Node 10 available.

 In Twill 1.2, which we are about to release, we've updated our Laravel Mix dependency, which in turn bumped up its node-sass dependency to 4.9 [in their last releeases](https://github.com/JeffreyWay/laravel-mix/commit/8168e939cb6e0ebc453879ca7d60fb7a0f559e30#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

I'll keep you posted here once the new release is up. In the meantime, you can use Node 8 to compile your Twill bundle. I recommend using [nvm](https://github.com/creationix/nvm) to quickly switch between version.

**Comment by ifox** [comment]
Twill 1.2 is available @NACILON! 

Node 10 is now supported, but let us know if you still have any issues.
