### ISSUE TITLE
Search by multiple colums

### ISSUE THREAD

**Issue by amirakbulut** [area17/twill#360]
For my Property module, I want my client to be able to search by title and city on the module's index table view.
(at the moment it's only searching by title as default)

However, I found zero information regarding on how to realise this. The only documentation that I found regarding searching was Global Search, not really what I'm after.

Hope someone can inform me on how to fix this.

**Comment by arkid** [comment]
+1!

**Comment by amirakbulut** [comment]
> +1!

I've been asking this question for about 2 weeks now on Twill's Spectrum chat, without any answers..

**Comment by amirakbulut** [comment]
Thread can be found here:

[https://spectrum.chat/twill/help/extending-default-filter~58a96119-3f18-4213-a3ef-89692ab0b662](https://spectrum.chat/twill/help/extending-default-filter~58a96119-3f18-4213-a3ef-89692ab0b662)

**Comment by ifox** [comment]
Hey there, sorry for the delay. There is an example of doing this in Twill's UserRepository. See: https://github.com/area17/twill/blob/2abd816082a5370beeab72e03084345cb99d613f/src/Repositories/UserRepository.php#L70

**Comment by arkid** [comment]
I think there may be some basic confusion (on our part) about what $defaultFilters is meant to do in the controller?

I'd assumed it was a way in which columns can be specified that the local module search will work on but now I'm not so sure. 

I'm checking the sql of queries when I run them and if I set

```
protected $defaultFilters = ['search' => 'title|custom_field'];
```

I get an sql query of

```
select * from `modulename` where `title` = 'test' and `custom_field` = 'test' and `modulename`.`deleted_at` is null order by `created_at` desc, `position` asc
```

This query I would have expected to use LIKE and also its never going to work if it uses AND for both the fields I specified in $defaultFilters.

**Comment by zedee** [comment]
Hi @arkid 

I applied this solution: (on your repository):

```
public function filter($query, array $scopes = []) {
        /**
         * Custom search methods
         */
        if (isset($scopes['author'])) {
            $query->orWhereHas('author', function ($query) use ($scopes) {
                $query->where('twill_users.name', 'like', '%' . $scopes['author'] . '%');
            });
            unset($scopes['author']);
        }
        if (isset($scopes['play'])) {
            $query->orWhereHas('play', function ($query) use ($scopes) {
                $query->where('plays.title', 'like', '%' . $scopes['play'] . '%');
            });
            unset($scopes['play']);
        }
        if (isset($scopes['title'])) {
            $query->orWhere('critiques.title', 'like', '%' . $scopes['title'] . '%');
            unset($scopes['title']);
        }
        
        // don't forget to call the parent filter function
        return parent::filter($query, $scopes);
    }
```
The "gotcha" for me was the `unset($scopes['field'])` which I think it wasn't well documented, or I did not notice.

It works for me, and they're `OR` conditions in all, whenever you search it will search in `title` OR `author` OR `play`

Tell me if it worked!

**Comment by arkid** [comment]
Hi @zedee thanks for this... close but no still not working.

In the controller I have 

`protected $defaultFilters = ['search' => 'title|name_alias'];`

Then in the repository...

```
if (isset($scopes['name_alias'])) {
            $query->orWhere('composers.name_alias', 'like', '%' . $scopes['name_alias'] . '%');
            unset($scopes['name_alias']);dd($query);
        }

        // don't forget to call the parent filter function
        return parent::filter($query, $scopes);
```

... and the condition isset is definitely being met, yet the query remains unaltered it seems when I look at the queries run in the debugbar.   Any ideas?

**Comment by arkid** [comment]
One question though @zedee , if I wanted to search on a linked column (the column in my model is just saving an integer id link to another model) how do I do that?    In the example below I am trying to allow the user to type in a property name and for the repository logic to join to my properties table to find the value they searched for...

```
if (isset($scopes['apartment'])) {
	$query->join('properties', 'properties.id', '=', 'reviews.apartment')->orWhere('properties.title', 'like', '%' . $scopes['apartment'] . '%');
	unset($scopes['apartment']);
}
```

It seems to produce a valid sql query but still causes twill to produce a 500 error.

**Comment by zedee** [comment]
Sorry for not answering before! I've been ultra-busy solving my own issue with custom Components on the admin :sweat_smile: after the v2.0 update

> It seems to produce a valid sql query but still causes twill to produce a 500 error.
Could you copypaste the error to see if I can gather more info?

**Comment by razvaniacob** [comment]
this is in the documentation

`
// add orWhereHas clauses
    $this->searchIn($query, $scopes, 'field_in_scope', ['field1', 'field2', 'field3']);
 `

But there's no such method in vendor/area17/twill/src/Repositories/ModuleRepository.php

Why is that method missing?
