### ISSUE TITLE
Sticky navigation automatic highlighting as user scrolls through multiple fieldsets never gets to the last item

### ISSUE THREAD

**Issue by arkid** [area17/twill#361]
This bug occured in my own project first but it's also visible in the pentagram demo website.   

Taking that demo site as a working example, login and edit one of the 'Work' items.  Scroll down the page and you will see that the sticky sub menu highlights all the way to 'Related content' but it never gets to 'Home settings'.

**Comment by arkid** [comment]
Amendment: if you have fieldsets that contain very few fields (lets say just one) then its even possible that the highlighted link in the sticky sub menu won't even get to the penultimate item but will end on one even earlier in the list.

**Comment by mrdoinel** [comment]
It really depend on how tall is your screen compared to the height of the fieldsets.
If your screen is smaller that the height of the lastest fieldset it will be selected when reaching the fieldset.

The item get selected when the top of the fieldset is reaching the top of the screen.
A possible change would be to select the item when the top of the fieldset is between the top and 1/4 of the screen.

**Comment by arkid** [comment]
I think anything would likely be an improvement @mrdoinel.   As long as this is working over the whole height of a field set (imagine a field set containing say 20 fields) - in other words, the logic isn't based on the top of the fieldset being either at the top of the screen or simply in the visible viewing area, then this sounds fine.

**Comment by haringsrob** [comment]
Closing this for now.
