### ISSUE TITLE
Default 'content' form area of module view controlled by @section('contentFields') can't be manipulated?

### ISSUE THREAD

**Issue by arkid** [area17/twill#363]
Please correct me if I am wrong but my understanding is that there is now clean way to hide this and certainly not through standard Twill settings/conventions.

Even if I could rename it that would be a start.   But it seems no matter what I do in my module view (ie delete @section('contentFields' ... @stop) or leave it there but empty) it always shows in the interface.

I want to have control to easily:

1. Rename the title of the box from Content to something else
2. Move it to within the @section('fieldsets') ... @stop convention 
3. Hide it all together

**Comment by ifox** [comment]
Hi @arkid, you can use `disableContentFieldset` and `contentFieldsetLabel` when extending the form layout. For example:

```
@extends('twill::layouts.form', [
    'disableContentFieldset' => true
]
```

**Comment by arkid** [comment]
Thank you for this @ifox ! Really useful to improve presentation!
