### ISSUE TITLE
Number form fields can't have min/max/step values assigned

### ISSUE THREAD

**Issue by arkid** [area17/twill#364]
Please correct me if wrong but from what I see number input fields aren't that configurable and don't allow min/max/step values.   To give a common example; you want a number field that contains a price.  

`<input type="number" min="0.01" step="0.01" max="2500" />`

I want to be able to configure this in a view something like...

```
@formField('input', [
    'name' => 'price',
    'label' => 'Price',
    'type' => 'number',
    'required' => true,
    'min' => 0.01,
    'max' => 99999,
    'step' => 0.01
])

```

Neither of these 3 attributes seem to work.  Can this be clarified / added ?

**Comment by yanhao-li** [comment]
Hello @arkid ,

You could achieve the result using [Form Request]: https://twill.io/docs/#form-requests

**Comment by arkid** [comment]
Ok I will have a look @yanhao-li ... 

A kind of related question... when you put `'required' => true` in a view, that doesn't make it required/fail error checking when you save/update the record, is that correct ?   This is also all down to the form request ?

**Comment by yanhao-li** [comment]
There is some basic UI validations on the input field Vue component, for example `maxlength` and `required `
```
@formField('input', [
    'name' => 'subtitle',
    'label' => 'Subtitle',
    'maxlength' => 100,
    'required' => true,
    'note' => 'Hint message goes here',
    'placeholder' => 'Placeholder goes here',
])
```
but remember they are FE validation, I think they should work, means if a required field is empty, you should be unable to save the form.
but for more advanced validations, like your case, `Form Request` is needed, they are BE validation, and you could also validate the `required` and `maxlenght` there, which is also recommended due to security reason.

**Comment by arkid** [comment]
@yanhao-li how odd, I have various 'required'=>true values in fields of various models (very simple stuff, no custom validation present, custom save actions or anything similar) and when I update the record I get the normal yellow success msg

**Comment by yanhao-li** [comment]
@arkid
Can confirm this is happening, I think it is a bug, and I can't quickly find what caused it. 
I will do more investigation next week, for now, you could use form request to perform the validation.

Thanks for reporting!

**Comment by arkid** [comment]
I've raised an issue for this https://github.com/area17/twill/issues/367 and something even worse I've found relating to required fields...    https://github.com/area17/twill/issues/366

**Comment by arkid** [comment]
@yanhao-li : one more related question;  I need to apply another currency type validation rules on a field in a repeater field.     As it stands I have no idea how to apply validation rules of any kind on any fields if they are inside a repeater.  I tried to do a quick test with a text field in my repeater and the 'required'=>true was ignored when it was placed in the request file.    

Is there support for this?  Is there a special syntax ?

**Comment by arkid** [comment]
Can I ask that this original issue post is still made a request for inclusion?  It would seem to me that any standard html5 form field attributes that control validation would be very good to include.   If the idea is that you can make a field required and do more specific things like set a max length, why not a max/min number ?

**Comment by haringsrob** [comment]
Fixed in https://github.com/area17/twill/pull/1578
