### ISSUE TITLE
Using model requests to force a field to be required doesn't work with some field types

### ISSUE THREAD

**Issue by arkid** [area17/twill#366]
Request rules on media fields doesn't seem to work properly when you set it as required.  A simple example of the file: 

```
public function rulesForCreate()
    {
        return [
            'image_field' => 'required'
        ];
    }
```

What doesn't happen...

1) the field doesn't highlight in red when you save/update the record
2) error validation doesn't work as expected.   The field is required, so the user adds an image and yet the record still errors when saving asking you to check the form.     

So having the request validation rule basically makes the model impossible to use as you can't create/save records as the validation ALWAYS fails.

**Comment by arkid** [comment]
Browser fields also don't seem to function via the standard request syntax either.

**Comment by atken** [comment]
Hello @arkid ,

rules for media fields have to contain prefix `medias.`.

so your code should look like this:
```
public function rulesForCreate()
    {
        return [
            'medias.image_field' => 'required'
        ];
    }
```

**Comment by arkid** [comment]
Hi @atken you are absolutely right about the media fields, thanks for clarifying.   I still have the same issue for fields via a browser that are linked to another table. 

For this relationship field with laravel association table I have setup... 

```
public function rulesForUpdate(){
        return [
            'locations.title' => 'required'
        ];
    }
    public function messages() {
        return [
            'locations.title.required' => "A location is required"
        ];
    }
```

...but this doesn't work, the field being required doesn't work and the custom msg doesn't show.    Anything you can see wrong with this syntax if the table is called _locations_ and the visible value selected in the linked table is _title_ ?

**Comment by ifox** [comment]
Hi @arkid, see https://github.com/area17/twill/issues/367#issuecomment-533672546 for browser field validation. Same idea, you need to prefix the field name. Don't hesitate to inspect the request that is coming through. You'll see how it is structured to better understand how to validate it.

Thank you so much for your support @atken!

**Comment by arkid** [comment]
Confirmed all clear now, thanks all!
