### ISSUE TITLE
Required attribute in views doesn't stop a form update and in some cases doesn't even appear

### ISSUE THREAD

**Issue by arkid** [area17/twill#367]
My understanding having spoken to Area17 staff is that adding the required attribute to a view field should stop the form from actually saving and produce a red error msg. 

However this doesn't occur.  In reality, adding `'required'=>true` only adds an asterisk to the field

This was clarified in a discussion here: https://github.com/area17/twill/issues/364

**Comment by arkid** [comment]
Another issue but closely related;  the asterisk doesn't even appear for some fields!   I just discovered this for browser fields.  Ie...

```
    @formField('browser', [
        'moduleName' => 'locations',
        'name' => 'locations',
        'label' => 'Location',
        'required' => true,
        'max' => 1,
        'sortable' => false
    ])
```

**Comment by atken** [comment]
Hello @arkid,

you have to create validation rules in file: `App\Http\Requests\Admin\LocationRequest.php`.

```
    public function rulesForCreate()
    {
        return [];
    }

    public function rulesForUpdate()
    {
        return [
            'browsers.locations' => 'required'
        ];
    }

    public function messages()
    {
        return [
            'browsers.locations.required' => 'Your validation message is here'
        ];
    }
```
![Snímek obrazovky 2019-09-20 v 20 57 59](https://user-images.githubusercontent.com/22528181/65351852-6501f200-dbe9-11e9-829f-aa9e31383eb5.png)

**Comment by arkid** [comment]
Hi @atken this doesn't work for me.   It still doesn't flag with a msg or accept a custom msg.   it just saves the record without complaining at all that it's needed.     I have the entries exactly as you have stated which relates to my definition of the linked field used in the browser:

in the model file Location.php
```
    public function locations()  {
        return $this->belongsToMany(\App\Models\Location::class);
    }
```

in the views/admin/properties/form.blade.php file

```
@formField('browser', [
        'moduleName' => 'locations',
        'name' => 'locations',
        'label' => 'Location',
        'required' => true,
        'max' => 1,
        'sortable' => false
    ])
```

Anything seem wrong with this ?

**Comment by arkid** [comment]
Not sure why this didn't work first time but I've now reviewed and it seems fine, thanks so much @atken
