### ISSUE TITLE
TypeError: n.latlng.split errors handling the geocode data when rendering map field

### ISSUE THREAD

**Issue by arkid** [area17/twill#369]
This may not be determined as being a bug - depending how one decides to code up handing a map field.  However as very incomplete info is currently given on how to code up the map field in the official documentation and the method suggested [here](https://spectrum.chat/twill/help/how-to-save-and-load-a-google-maps-location~5b1998bf-0eff-4d45-af26-97fcac8b46e5) seems very simple and well executed, can I request that the file /vendor/area17/twill/frontend/js/components/LocationField.vue be altered as shown in this modification or at least made more robust to handle the data without producing these errors: 

> TypeError: n.latlng.split is not a function

To clarify, the view file /vendor/area17/twill/frontend/js/components/LocationField.vue is being changed from line 96 as follows....

```
set (value) {
          const coord = value.latlng.split('|')
          this.lat = parseFloat(coord[0])
          this.lng = parseFloat(coord[coord.length - 1])
          this.address = value.address
        }
```

to

```
set (value) {
          const coord = value.latlng.latlng.split('|')
          this.lat = parseFloat(coord[0])
          this.lng = parseFloat(coord[coord.length - 1])
          this.address = value.latlng.address
        }
```

**Comment by ifox** [comment]
Fixed in #371. Casting a single column to array is the simplest approach to use the map field.
