### ISSUE TITLE
Presets for Glide

### ISSUE THREAD

**Issue by tchapi** [area17/twill#370]
Hello

With the new release, is it possible to create presets for Glide ? (https://glide.thephpleague.com/1.0/config/defaults-and-presets/)

The `cms_default_params`, `lqip_default_params`, etc .. seem to be hardcoded. I would like to create specific presets so I can use them in my frontend

Thanks !

**Comment by yanhao-li** [comment]
Created a PR here: https://github.com/area17/twill/pull/397
Feel free to leave comments!
