### ISSUE TITLE
Add Laravel 6.0 to composer.json

### ISSUE THREAD

**Issue by brammittendorff** [area17/twill#376]
Laravel 6.0 is out: https://packagist.org/packages/laravel/laravel#v6.0.2 When will twill be compatible with this version. All our software is up to date only the software that is using twill is not.

# Replace laravel core functions

For this you will need to replace:
```
str_contains(
```
by
```
Str::contains(
```

Check the difference in documentation:
https://laravel.com/docs/5.6/helpers
vs
https://laravel.com/docs/6.0/helpers

# More release changes

https://laravel.com/docs/6.0/releases

Hopefully we can update soon in the future. Thanks in advanced.

**Comment by yanhao-li** [comment]
Yes, we have a PR for doing this: https://github.com/area17/twill/pull/389
Wish it could be merged soon!
Thank you!

**Comment by ManukMinasyan** [comment]
When will Laravel 6.4 support be? Thanks.

**Comment by ifox** [comment]
Hi @ManukMinasyan, it is available on master and we are planning to tag it in the next few days.

**Comment by nkorent** [comment]
so what happened to this ?

**Comment by nkorent** [comment]
hey, what's the status of laravel 6 support then? I read the release will be 2.x?

**Comment by brammittendorff** [comment]
Next few days?

**Comment by bjornbjorn** [comment]
Hi guys, any news on this one?
