### ISSUE TITLE
Tag CSS height fails with long tag names

### ISSUE THREAD

**Issue by arkid** [area17/twill#378]
This is what you get....

![tag height gone wrong](https://i.imgur.com/8bzalFV.png)

The fix I believe is to alter

.a17 .vselect--small.vselect--multiple .selected-tag {}  setting its height from 21px to auto 

I would have made a pull request but not 100% sure where to modify your css as I found multiple references to this.

**Comment by ifox** [comment]
Thanks for reporting and providing a potential solution @arkid, much appreciated!

We'll look into this.
