### ISSUE TITLE
Adding related models using the browser input

### ISSUE THREAD

**Issue by wratke** [area17/twill#38]
I'm following the instructions in the Block Editor>Adding browser fields section of the docs, but I'm not sure where to add the last bit of code (in the section labeled After that, it is required to add the Route Prefixes. e.g.:). Is that something that should be added to the routes/admin.php file? Or should it go somewhere else. It's a bit unclear to me.

**Comment by ifox** [comment]
Hey @wratke! Looks like you figured it out? 

Route prefixes are used by Twill to allow moving modules around in the navigation. When you are using a browser field in a block, Twill needs to know in which section of your CMS those items in a browser are (to be able to have a direct link to them).  If that's annoying, you can also register the browser route of a module at the root of the admin using something like:

```php
Route::module('yourModulePluralName', [], ['only' => ['browser']])
```

By doing that, you can just omit routePrefix from browser form fields and blocks configuration all together, but you need to avoid conflicts.
