### ISSUE TITLE
Unable to change uploads path from storage to public

### ISSUE THREAD

**Issue by elias-eichelberg** [area17/twill#383]
Hello! 
I am trying to change the path of the uploads directory from from storage to public but it does not work.

I've add a this string in the .env file
`MEDIA_LIBRARY_LOCAL_PATH=public/uploads/`

<img width="280" alt="Снимок экрана 2019-09-14 в 11 55 26" src="https://user-images.githubusercontent.com/10980479/64905860-9d379b00-d6e6-11e9-9032-29c3940fe721.png">

**Comment by elias-eichelberg** [comment]
also, I change filesystem.php from storage_path() to public_path(), but is does not have result

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default filesystem disk that should be used
    | by the framework. The "local" disk, as well as a variety of cloud
    | based disks are available to your application. Just store away!
    |
    */

    'default' => env('FILESYSTEM_DRIVER', 'local'),

    /*
    |--------------------------------------------------------------------------
    | Default Cloud Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Many applications store files both locally and in the cloud. For this
    | reason, you may specify a default "cloud" driver here. This driver
    | will be bound as the Cloud disk implementation in the container.
    |
    */

    'cloud' => env('FILESYSTEM_CLOUD', 's3'),

    /*
    |--------------------------------------------------------------------------
    | Filesystem Disks
    |--------------------------------------------------------------------------
    |
    | Here you may configure as many filesystem "disks" as you wish, and you
    | may even configure multiple disks of the same driver. Defaults have
    | been setup for each driver as an example of the required options.
    |
    | Supported Drivers: "local", "ftp", "sftp", "s3", "rackspace"
    |
    */

    'disks' => [
        'local' => [
            'driver' => 'local',
            'root' => public_path(),
        ],

        'public' => [
            'driver' => 'local',
            'root' => public_path(),
            'url' => env('APP_URL').'/public',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],
    ],
];
`

**Comment by arkid** [comment]
What is your 'disk' value set to in the twill.php config?   For me that was the most important change.  You can see how I've customised mine...
```

'media_library' => [
        'disk' => 'twill_media_library',
        'endpoint_type' => env('MEDIA_LIBRARY_ENDPOINT_TYPE', 'local'),
        'cascade_delete' => env('MEDIA_LIBRARY_CASCADE_DELETE', true),
        'local_path' => env('MEDIA_LIBRARY_LOCAL_PATH','/'),
        'image_service' => env('MEDIA_LIBRARY_IMAGE_SERVICE', 'A17\Twill\Services\MediaLibrary\Glide'),
        'acl' => env('MEDIA_LIBRARY_ACL', 'private'),
        'filesize_limit' => env('MEDIA_LIBRARY_FILESIZE_LIMIT', 50),
        'allowed_extensions' => ['jpg', 'jpeg', 'png'],
        'init_alt_text_from_filename' => true,
    ],
    'glide' => [
    	'base_url' => '',
    	'base_path' => '/storage/',
        'cache_path_prefix' => '/storage/',
        'cache' => '/test'
    ],
    'file_library' => [
        'disk' => 'twill_file_library',
        'endpoint_type' => env('FILE_LIBRARY_ENDPOINT_TYPE', 'local'),
        'cascade_delete'=> env('FILE_LIBRARY_CASCADE_DELETE', true),
        'local_path' => '/',
        'file_service' => env('FILE_LIBRARY_FILE_SERVICE', 'A17\Twill\Services\FileLibrary\Disk'),
        'acl' => env('FILE_LIBRARY_ACL', 'private'),
        'filesize_limit' => env('FILE_LIBRARY_FILESIZE_LIMIT', 50),
        'allowed_extensions' => ['pdf'],
    ],

```
