### ISSUE TITLE
New Role or New Crop for old images?

### ISSUE THREAD

**Issue by imknight** [area17/twill#388]
any way to apply the new role or new crop to existing images?

**Comment by ifox** [comment]
Hi @imknight,

This is not something Twill is currently shipping with but could certainly become a great Artisan command with a helper behind it that can be called programmatically if needed. At AREA 17 this is something we've solved by some doing some maths with the current crop values and new ratio value in a database migration. If you're not changing the ratios but only the names you should also be able to identify the appropriate rows in the `mediables` and alter them through a database migration.

**Comment by imknight** [comment]
thanks for the reply, will work on Artisan commit and submit for PR
