### ISSUE TITLE
Models without revisions can't be added to the dashboard

### ISSUE THREAD

**Issue by ferpetrelli** [area17/twill#391]
`mine()` scope used here:

https://github.com/area17/twill/blob/master/src/Http/Controllers/Admin/DashboardController.php#L393

is defined only at the `HasRevisions` trait, causing the dashboard to break if that model has no revisions.

https://github.com/area17/twill/blob/master/src/Models/Behaviors/HasRevisions.php#L12

**Comment by ifox** [comment]
Hi @ferpetrelli!

We should definitely prevent the dashboard from breaking in that case however the idea of the module for drafts in the dashboard is to display drafts records that do have revisions created by the currently logged in user. The drafts feature is disabled by default if not specified in a dashbord module configuration, so we could decide that it is indeed only compatible with models that use revisions. That shouldn't be a reason for breaking the page entirely though and one could argue that all drafts from models that have no revisions could should up there. Going down that path, we could create a configuration key to toggle that decision.

**Comment by ifox** [comment]
Fixed in 0481894d!
