### ISSUE TITLE
Custom storage provider

### ISSUE THREAD

**Issue by tchapi** [area17/twill#394]
Hello

Suppose I want to use a third party API to store files and medias (with an API for instance), a bit like **s3**. Is this possible ?

How can I achieve it ?

Thanks

**Comment by ifox** [comment]
Hi @tchapi, for sure! If this API is from a public service, there's probably a driver for it, but otherwise, you can create custom filesystems with Laravel and Flysystem: https://laravel.com/docs/5.8/filesystem#custom-filesystems.

**Comment by tchapi** [comment]
Alright, thanks for your answer.

I will read this documentation eagerly — on question still : once I have created my driver / adapter, how do I tell Twill to use it for the media / file library ? Because from what I see in the code, it's either 'local' or 's3' ...

https://github.com/area17/twill/blob/master/config/media-library.php#L13

**Comment by ifox** [comment]
You would use the `disk` key and use `local` as your `endpoint_type`. The endpoint type is to let the uploader know if the upload can go directly to S3 or if it is uploading "locally", ie. to your server. Using the local endpoint type and a custom disk will first upload to your server, where it can be saved to your custom "disk".

**Comment by tchapi** [comment]
That makes sense ! Thanks a lot
