### ISSUE TITLE
Exception when trying to follow the Adding browser fields documentation

### ISSUE THREAD

**Issue by wratke** [area17/twill#40]
I'm testing out the browser blocks and I've followed the documentation, adding in a products browser block type. When I run php artisan twill:blocks I get the following exception:

```
 ErrorException  : Route [admin.content.products.browser] not defined. (View: /Users/Beesmum/Dropbox/devilbox/data/www/nin/laravel-project/vendor/area17/twill/views/partials/form/_browser.blade.php) (View: /Users/Beesmum/Dropbox/devilbox/data/www/nin/laravel-project/vendor/area17/twill/views/partials/form/_browser.blade.php)

  at /Users/Beesmum/Dropbox/devilbox/data/www/nin/laravel-project/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:374
    370|         if (! is_null($route = $this->routes->getByName($name))) {
    371|             return $this->toRoute($route, $parameters, $absolute);
    372|         }
    373| 
  > 374|         throw new InvalidArgumentException("Route [{$name}] not defined.");
    375|     }
    376| 
    377|     /**
    378|      * Get the URL for a given route instance.

  Exception trace:

  1   Illuminate\View\Engines\CompilerEngine::handleViewException(Object(ErrorException))
      /Users/Beesmum/Dropbox/devilbox/data/www/nin/laravel-project/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:45

  2   ErrorException::("Route [admin.content.products.browser] not defined. (View: /Users/Beesmum/Dropbox/devilbox/data/www/nin/laravel-project/vendor/area17/twill/views/partials/form/_browser.blade.php)")
      /Users/Beesmum/Dropbox/devilbox/data/www/nin/laravel-project/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:374
```

**Comment by wratke** [comment]
Yes, I did follow your advice in this issue:

https://github.com/area17/twill/issues/38

That allowed me to generate the block using the ```php artisan twill:blocks``` command, but when I add a block on the form, there's no way to attach a project. I'm assuming once I add a block I'll be able to choose the project I want, but it's just blank, there's no button or anything, just a blank box. It's also allowing me to add multiple projects even though I've set max to 1. I've attached a screenshot and all of the code.

![products](https://user-images.githubusercontent.com/10247944/46984157-dbc96d80-d0b1-11e8-8355-3985ef6e58ce.png)

Here's the section in the form.blade.php file where I'm adding the block editor:
```
@section('fieldsets')
	<a17-fieldset title="Images" id="images">
        @formField('block_editor', [
	    	'blocks' => ['product']
	    ])
    </a17-fieldset>
@stop
```

products.blade.php
```
@formField('browser', [
    'moduleName' => 'products',
    'name' => 'products',
    'label' => 'Products',
    'max' => 1
])
```

BlockProducts.vue
```
<template>
    <!-- eslint-disable -->
    <div class="block__body">
        <a17-inputframe label="Products" name="browsers.products"> <a17-browserfield :name="fieldName('products')" item-label="products" :max="1" endpoint="/cp/products/browser" modal-title="Attach products" :draggable="true" >Add one product</a17-browserfield></a17-inputframe>
    </div>
</template>

<script>
  import BlockMixin from '@/mixins/block'

  export default {
    mixins: [BlockMixin]
  }
</script>
```

\routes\admin.php
```
Route::module('products', [], ['only' => ['browser']]);
```

\config\twill.php
```
'block_editor' => [
        'blocks' => [
            'product' => [
                'title' => 'Products',
                'icon' => 'image',
                'component' => 'a17-block-products',
            ],
        ],
        'repeaters' => [
        ],
    ]
```

I've also added HasBlocks to the Project model and HandleBlocks to the ProjectRepository as recommended in the documentation.

**Comment by ifox** [comment]
Hey @wratke! 

Your block is not rendered in the block editor, this is most likely related to a wrong custom blocks copy operation during the build. 

To correctly build with custom blocks, the `copy-blocks` npm script needs to place your blocks generated Vue files under  `vendor/area17/twill/frontend/js/components/blocks/customs`. 

Can you make sure that is the case in your project? If not, feel free to adapt your npm scripts. We're working on phasing out those scripts to avoid inconsistencies across environments.

**Comment by wratke** [comment]
I checked that folder and it was empty, so I copied the BlockProducts.vue file from ```resources/assets/js/blocks``` to ```vendor/area17/twill/frontend/js/components/blocks/customs``` manually, but that doesn't seem to have changed anything.

**Comment by wratke** [comment]
Excellent! That did the trick. Thanks for the assistance.

**Comment by wratke** [comment]
It looks like it's still not quite working yet. I'm getting the following button to add products, but the two products I've created don't show up in the window that pops up. 

![products3](https://user-images.githubusercontent.com/10247944/47043330-61edbe80-d15b-11e8-9a9a-cd3f5d70e6eb.png)
![products2](https://user-images.githubusercontent.com/10247944/47043332-61edbe80-d15b-11e8-9a19-55b3cdb2120b.png)
![products1](https://user-images.githubusercontent.com/10247944/47043333-61edbe80-d15b-11e8-86e9-19fa2d552436.png)

**Comment by ifox** [comment]
Interesting, can you try to manually go to `/products/browser`? 

You should see a JSON response listing products.

**Comment by wratke** [comment]
I get the following error message:

```Route [admin.products.edit] not defined.```

Here's my full routes/admin.php file:

```
Route::module('highlighted_image', [], ['only' => ['browser']]);
Route::module('gridSections', [], ['only' => ['browser']]);
Route::module('products', [], ['only' => ['browser']]);

// Register Twill routes here (eg. Route::module('posts'))
Route::group(['prefix' => 'work'], function () {
    Route::module('projects');
    Route::module('clientLogos');
    Route::module('products');
});

Route::group(['prefix' => 'grid'], function () {
    Route::module('gridSections');
});
```

**Comment by ifox** [comment]
Gotcha, I see what is happening now.

2 options for you now:

- the approach I shared in the other thread wasn't necessarily the best or at least I did not provide full instructions on how to make it work. The problem with it is that attached items in a browser have a link to their own edit page. Since you now have the products browser route at the root of your admin URL structure, the routePrefix when generating `products.edit` URLs is empty, but it should be `work` in your case. You could fix that by overwriting Twlll's `ModuleController` `getRoutePrefix` function in your admin `ProductController`:

```
protected function getRoutePrefix()
{
        return 'work';
}
```

- remove the `Route::module('products', [], ['only' => ['browser']]);` instruction. Products browser should be accessible at `/content/products/browser`, and you should use `content` as routePrefix for the products block, both in the block definition itself, but also in Twill's configuration file:

```
@formField('browser', [
    'routePrefix' => 'content',
    'moduleName' => 'products',
    'name' => 'products',
    'label' => 'Products',
    'max' => 1
])
```

```
'block_editor' => [
    'block_editor' => [
        'blocks' => [
            'product' => [
                'title' => 'Products',
                'icon' => 'image',
                'component' => 'a17-block-products',
            ],
        ],
        'repeaters' => [
        ],
        'browser_route_prefixes' => [
            'products' => 'content',
        ],
    ]
]
```

[This example](https://twill.io/docs/#adding-browser-fields) in the documentation is actually exactly what you're trying to achieve.

**Comment by wratke** [comment]
I've followed all of that, but I feel like I'm missing something. It's not clear to me in the documentation what needs to be added to the admin.php routes file to make ```/content/products/browser``` work.

**Comment by wratke** [comment]
I think I've figured it out. I added this to the admin.php routes file:

```
Route::group(['prefix' => 'content'], function () {
    Route::module('products');
});
```

I ran the ```php artisan twill:blocks```, copied the vue file over manually and then ran ```twill-build-no-blocks-copy``` and now I'm seeing the products show up in the blocks editor. Thank you for all of your help, I appreciate it!
