### ISSUE TITLE
Creating new user returns html error 422

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#401]
Hello,

I have a bizarre situation where creating new user from admin panel returns HTML error 422 and is not processed. This only occurs in production, but everything works as expected in local env. This error is also not present from the beginning.

I have no idea where to start debugging. Any help is really appreciated.

**Comment by ifox** [comment]
Hi @zipavlin, do you have email sending configured on your production environment? Most likely in local you're using the `log` mail driver so not facing the issue when creating new users.

**Comment by yanhao-li** [comment]
facing the same issue several days ago, and finally found out it's because of the UserRequest issue reported here: https://github.com/area17/twill/pull/390

**Comment by bdahlinger** [comment]
I'm also getting a 422 when doing an update on an existing user. Just trying to change the role. "Email already in use".

**Comment by ifox** [comment]
Hi @bdahlinger, this has been fixed for the next release, you can use `1.2.x-dev` in the meantime.

**Comment by zipavlin** [comment]
Pull #390 fixes this issue. Thanks!
