### ISSUE TITLE
Imgix crop not working

### ISSUE THREAD

**Issue by elias-eichelberg** [area17/twill#403]
Hello!
I put media params array into models:
```
    public $mediasParams = [
        'cover' => [
            'default' => [
                [
                    'name' => 'default',
                    'ratio' => 16/9
                ],
            ],
            'mobile' => [
                [
                    'name' => 'landscape',
                    'ratio' => 16 / 9,
                ],
                [
                    'name' => 'portrait',
                    'ratio' => 3 / 4,
                ],
            ],
        ],
    ];
```

and calling:
`return $category->image('cover', 'default');`
this code returns a path to image with a GET parameters like `?auto=compress%2Cformat&fit=min&fm=jpg&q=80&rect=302%2C0%2C687%2C387`

but if open it in browser then the crop settings do not apply.

**Comment by ifox** [comment]
Hi @elias-eichelberg,

are you using [Imgix](https://imgix.com) for this project?

**Comment by elias-eichelberg** [comment]
@ifox yep

**Comment by ifox** [comment]
Ok! Taking a url from Imgix sandbox, I applied your exact same parameters successfully: https://assets.imgix.net/unsplash/raspberries.jpg?auto=compress%2Cformat&fit=min&fm=jpg&q=80&rect=302%2C0%2C687%2C387

I'm thinking that one thing that could happen to you is that your original image might be smaller than the specified crop coordinates.

**Comment by elias-eichelberg** [comment]
Ok, it seems a problem in my settings. Thank you.
