### ISSUE TITLE
Resolving dependancies broken in multiple places (L5.5)

### ISSUE THREAD

**Issue by jeepey** [area17/twill#406]
I found a few breaking bugs in the 1.2.2 release regarding resolving repositories and requests (at least when using Laravel 5.5). @ifox already fixed one I reported before (https://github.com/area17/twill/issues/399), but the same issue happens here as well:

- MediaLibraryController 128
- FeaturedController line 235
- FileLibraryController line 139

Unfortunately this has now broken our Media Library in production as we didn't spot the bug before.

**Comment by ifox** [comment]
All those have been fixed on 1.2.x-dev and master.
