### ISSUE TITLE
Change some `medias` columns from `string` to `text`

### ISSUE THREAD

**Issue by IllyaMoskvin** [area17/twill#41]
We are seeing issues come through via Sentry, which suggest that users are blowing past the column length limits set in the `medias` table. This got me thinking – is there a reason for these columns to be strings in the first place?

https://github.com/area17/twill/blob/1.2/migrations/create_medias_tables.php

    Schema::create('medias', function (Blueprint $table) {
        [...]
        $table->text('uuid');
        $table->text('alt_text');
        [...]
        $table->text('caption')->nullable();
        $table->text('filename')->nullable();
    });

1. `caption` and `alt_text` are free-text fields, so they should be `text`. Consider e.g. the [Coyote Project](https://coyote.pics/), which favors long-form descriptions for accessibility.
2. `filename` is limited to 255 chars in most filesystems, but not all. There's no need to assume filesystem limits by using a string column.
3. I'd normally not suggest that a `uuid` should be `text`, but given that the "uuid" seems to be comprised of [an actual UUID combined with the filename](https://github.com/area17/twill/blob/16ec48037efab10c20ffb09728bd885ad9a1aa4a/src/Http/Controllers/Admin/MediaLibraryController.php#L127), the least disruptive way to reduce inconsistency is to allow it to be a text field. It looks like `medias` is typically queried via `id`, not `uuid`, so performance shouldn't be an issue. 

Similar changes might need to be done to `files` for consistency (`uuid` and `filename`).

Overall, I don't see any advantages in using string over text in modern database systems, except for cases where there's a need to index columns for faster sorting. It just tends to cause issues when users inevitably enter text that's longer than expected. 😢

We are already making these adjustments in our existing project – just throwing the idea your way in case it proves helpful to others!

**Comment by ifox** [comment]
Very good point @IllyaMoskvin! Thanks for bringing this up to our attention, I will update our migrations  with your suggestion and add a note to the docs for existing project!

**Comment by IllyaMoskvin** [comment]
Thanks, @ifox! If I may, `alt_text` should also probably be made `nullable`. We had `Not null violation` events come through on Sentry on that field. Might be an unrelated bug, if there's code in Twill that's meant to ensure `alt_text` is always set.

**Comment by nikhiltri** [comment]
It should be allowed for `alt_text` to be null. For example, you might have the case:

```
<h2>Company name</h2>
<img src="company_logo.png" alt="" />
<p>...</p>
```

Here, the image of the company logo doesn't need to be read out to the screen reader as it's a repeat of the heading. The most reliable way we've found to tell a screen reader to ignore an image is to set the `alt` attribute to an empty string. I'm not sure that Twill has any code that validates that `alt_text` always has text, but it shouldn't! 

So, +1 for making this field nullable. But there might be a need to distinguish between null and empty string, so you can tell whether the user just never entered in alt text vs. intentionally setting it to an empty string.

**Comment by ifox** [comment]
Updated in #96cdebd8.
