### ISSUE TITLE
Dashboard route is not found

### ISSUE THREAD

**Issue by JoshKisb** [area17/twill#42]
I have just freshly installed but completely unable to access the admin route
it gives error 404 
i set the admin app url and path but it is still 404
I do not wish to use subdomains on my local machine

**Comment by ifox** [comment]
Hi @JoshKisb,

you can definitely have Twill running under a path instead of a subdomain.

Did you try to follow the documentation instructions?

> For example, to have the admin console available on a subdirectory of your app (domain.test/admin):
>```
> APP_URL=domain.test
> ADMIN_APP_URL=domain.test
> ADMIN_APP_PATH=admin
> ```

Please share the output of the `php artisan route:list` if you're still stuck with a 404.

Hope that helps!

**Comment by ifox** [comment]
It seems like your `APP_URL` is set to `localhost`. 

Which URL do you use to try to access the admin currently?

**Comment by JoshKisb** [comment]
Yes I am using localhost. I tried using localhost/twill/public, I tried with php artisan serve, I have tried as many different configurations I can think of nothing works
I did have a bit of some success by setting path as /admin with the slash but styles didn't apply. 
I really think the route system used in twill is messed up

**Comment by m4n1ok** [comment]
Hi @JoshKisb,

Did you build UI assets during your setup ?  (https://twill.io/docs/#npm)
````shell
$ npm run twill-build
````
Do you have errors in browser console when you try to access to /admin ?

**Comment by JoshKisb** [comment]
yes i followed the documentation very clearly. twice. laravel 5.7 and 5.6 
maybe try to run a new setup with artisan serve or localhost subdirectory. you probably get similar results

**Comment by ifox** [comment]
Hey @JoshKisb,

thanks for your comment about the route system in Twill. I do not think there is anything worth to be qualified as messed up.

I just did the test with `artisan serve` and the admin under `/admin` and it's working great.

Here's my `.env` (partial) configuration:

```
APP_URL=http://localhost
ADMIN_APP_URL=http://localhost
ADMIN_APP_PATH=admin
```

I'm accessing the admin at `http://locahost:8000/admin`.

I would still recommend you to use a local testing domain by modifying your `hosts` file to be closer to your production environment.

**Comment by splatEric** [comment]
[posting for anyone having a similar issue]

I use docker and run everything over different localhost:[port] for dev. I was having the same issue as described above, but found a work around was to set:

```
ADMIN_APP_URL=null
ADMIN_APP_PATH=admin
```

This seemed to do the trick for me

**Comment by luccazii** [comment]
Thanks @splatEric it worked for me

**Comment by JosephELKHOURY** [comment]
Thanks @splatEric 💯 :D

**Comment by kgnfth** [comment]
@splatEric Thank you for the simple fix.

**Comment by 360hexor** [comment]
Thanks @splatEric - the only time 'null' fixes something :100:

**Comment by fweth** [comment]
Anybody using Twill with Codespaces? I tried everything recommended here in this thread with no success...

```
APP_URL=https://[...]-8000.app.github.dev:8000
ADMIN_APP_URL=https://[...]-8000.app.github.dev:8000
ADMIN_APP_PATH=admin
```
