### ISSUE TITLE
Mandatory semicolons in ECMAScript

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#422]
Looks like the semicolon is [mandatory (according to the grammar)](http://www.ecma-international.org/ecma-262/6.0/#sec-exports) in some cases, those are some:

``` javascript
export default {
    mounted() {
        console.log('Component mounted.');
    },
};

export default {
    mixins: [BlockMixin],
};
```

But we don't need to add them if export default is a function:

``` javascript
export default function() {
    return whatever
}
```

**Comment by ifox** [comment]
Closing this as this is being addressed in #936.
