### ISSUE TITLE
Setting date_picker to be readonly doesn't work

### ISSUE THREAD

**Issue by Stiropor** [area17/twill#435]
A small bug I just noticed - using formField and setting it to be readonly doesn't work, user can still change the date. Works fine on other fields.

And since I'm writing here - is "readonly" the only way to display the record, meaning not being in a form? Trying to display all messages users left on a website through contact form .... changing the data is useless so I'd like to make it only display data, not in form. Readonly works (apart from date_picker), it's just I wanna make it prettier :)

**Comment by yanhao-li** [comment]
I think it's because `DatePicker` component doesn't has the `readonly` even `disabled` props. 
For now, it could be solved with adding a validation rule on the BE, but definitely could be improved in the future!

**Comment by ifox** [comment]
Closing in favor of #836.
