### ISSUE TITLE
Empty array in allowed_extensions does not allow to select all kind of files

### ISSUE THREAD

**Issue by tchapi** [area17/twill#436]
Hi

If we leave this configuration by default : 

    'file_library' => [
        'allowed_extensions' => [],
    ],

.. that is, an empty array, then the file uploader will accept only files _that do not have any extension_ (`accept='.'`).

Either the documentation / default configuration is wrong — and we should put the following :

    'allowed_extensions' => ['*'],

(that would translate to `accept='.*'`) ... or the code needs to be changed (in Uploader.vue [here](https://github.com/area17/twill/blob/b85df5ac2c1982041aa5d6b5766263051fb262c6/frontend/js/components/media-library/Uploader.vue#L38))

Happy to make a PR to change either way
Thanks !

**FWIW**, tested in Firefox latest

**Comment by yanhao-li** [comment]
Hi @tchapi ,
Can you do me a favor to test if this issue works on other browsers? (Chrome, Safari, Edge)

I just tested it, looks like it only happens on Firefox on my laptop, definitely a place needs to be improved, it would be awesome if you could create a PR to fix this.

Thank you!

**Comment by tchapi** [comment]
Hi @yanhao-li 

In fact, Chrome behaves differently, and `.*` does not work on Chrome and Safari. So, the compatible option between Chrome and Firefox seems to be `accept=""` or no `accept` property at all for all file types.

Do you confirm ? I can make a PR then.
BR

**Comment by arkid** [comment]
Hi guys this isn't qutie the same question but I thought you might know... how do I specify different rules for different file fields in the same model?   Ie one that accepts all, another that accepts just jpgs.  There isn't an attribute in the views to define this I believe, any ideas ?

**Comment by haringsrob** [comment]
I have added a fix for this in https://github.com/area17/twill/pull/1584
