### ISSUE TITLE
Rename "admin" to "twill"

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#440]
The name "admin" for Twill is too generic. Being Twill a CMS and not an all purposes administration panel nor a framework for creating management systems, the name "admin" may get in the way of something important for some apps. What I propose here is to change everything publicly named "admin" to **twill**.

Pros:
- Prevent conflicts management classes someone may already have in their apps before installing Twill
- Prevent conflicts with third party admin panels
- Remove ambiguity: easily identify/find code related to Twill. Even if someone is able to rename their code to open some space for Twill, names can still conflit and a simple search for "admin" may be a problem for them
- You can afford this kind of change in a major version (2.0)
- Tests, we are now writing, will help make this change
- Improve Twill's brand awareness

Cons:
- Upgrade may not be as straightforward as we would like
- Upgrade notes would have to be very good

Examples of files and namespaces prone to name clashing today, or which could be improved while renamed to **T/twill**:

```
./routes/admin.php
./public/assets/admin
./app/Http/Requests/Admin
./app/Http/Controllers/Admin

namespace App\Http\Controllers\Admin
namespace App\Http\Requests\Admin
```

And I would also change the "admin" prefix on all route names, because some of those can easily conflict too:

```
admin.dashboard
admin.login
admin.logout
admin.media-library
admin.password
admin.users
admin.impersonate
```

**Comment by yanhao-li** [comment]
We agree this will be a great improvement, and in order to keep backward compatibility, we are thinking to have a variable defaults to "twill" so that developers could upgrade their system easily.

PR are welcomed!
