### ISSUE TITLE
Date_picker form field - value empty

### ISSUE THREAD

**Issue by Insperio** [area17/twill#447]
Field default value is not populated if data is added using getFormFields. For example:

```php
public function getFormFields($object) {
        $fields = parent::getFormFields($object);

        $fields['user'] = $object->user->toArray();
        $fields['fullname'] = $object->user->fullname;

        return $fields;
    }
```

Then field added to form like this:
```html
@formField('date_picker', [
        'name' => 'user.dob',
        'label' => 'DOB',
        'withTime' => false
    ])
```

The dob field will stay empty even if data exists in database. Problem exists only for date_picker form field. 
PHP array shows data correctly. Look like it's a problem with vue, it doesn't receive the value for some reason. 

A quick fix I found is just adding a copy of dob field as "input" and hiding it with css. The date_picker starts working fine then...
```html
<div style="display:none; visibility: hidden">
    @formField('input', [
        'name' => 'user.dob',
        'label' => 'DOB',
        'withTime' => false
    ])
    </div>
```

**Comment by ifox** [comment]
Hi there,

my recommendation when managing form fields manually would be to use a field name that isn't present in your model. In `prepareFieldsBeforeSave` you can then hydrate your model as needed.

Please feel free to open a new issue if you still need any help with this feature.
