### ISSUE TITLE
Saving input from a browser form field

### ISSUE THREAD

**Issue by wratke** [area17/twill#45]
I've added a browser input for a module called services (a taxonomy associated with a project), added a field called services to the project table in the database (which I've assigned the text type in the database), and I've added a browser form field to the project's form.blade.php. Nothing is saving to the database, so I'm wondering if I'm missing something. It seems like Twill is setup to handle that as far as I can tell (add a form field and a corresponding field to the database and Twill will handle the logic of saving the data automatically). Is there some logic that needs to be added manually (e.g. to the projects model) to handle saving the input? It's not really obvious to me how the data entered in a browser input (or the block editor) is saved to the database, the documentation doesn't seem to go over that, so it's a bit of a black box.

**Comment by ifox** [comment]
Hi @wratke!

A browser input usually saves a relationship, not a field in the same table. You would need a regular relationship pivot table following Laravel's conventions.

In the [Migrations](https://twill.io/docs/#migrations) part of the CRUD modules documentation, you'll find a helper for that:

```php
// related content table, holds many to many association between 2 tables
Schema::create('table_name_singular1_table_name_singular2', function (Blueprint $table) {
    createDefaultRelationshipTableFields($table, $table1NameSingular, $table2NameSingular)
    // will add the following inscructions to your migration file 
    // $table->integer("{$table1NameSingular}_id")->unsigned();
    // $table->foreign("{$table1NameSingular}_id")->references('id')->on($table1NamePlural)->onDelete('cascade');
    // $table->integer("{$table2NameSingular}_id")->unsigned();
    // $table->foreign("{$table2NameSingular}_id")->references('id')->on($table2NamePlural)->onDelete('cascade');
    // $table->index(["{$table2NameSingular}_id", "{$table1NameSingular}_id"]);
});
```

In your case, a `project_service` table would need to be created like this:

```php
Schema::create('project_service', function (Blueprint $table) {
    createDefaultRelationshipTableFields($table, 'project', 'service)
    $table->integer('position')->unsigned()->index();
});
```

The position field being used to store the order of the services you add to a project.

Then, to actually save it and retrieve its values, another 2 helpers are available in the [repository](https://twill.io/docs/#repositories), which is where you can basically save every field however you'd like.

In the `afterSave` hook of your `ProjectRepository`, you'll need:

```php
public function afterSave($object, $fields) {
    $this->updateBrowser($object, $fields, 'services');
    parent::afterSave($object, $fields);
}
```

In the `getFormFields ` hook of your `ProjectRepository`, you'll need:

```php
public function getFormFields($object) {
    $fields = parent::getFormFields($object);
    $fields['browsers']['services'] = $this->getFormFieldsForBrowser($object, 'services');
    return $fields
}
```

This is for content outside of a block. Blocks do not need extra code to be saved and retrieved aside from using the `HasBlocks` and `HandleBlocks` traits in the model and repository respectively.

I can see how the documentation for those more complex fields is not necessarily very helpful. Everything is there, but there's a lot that is left to you to glue everything together for sure. Your feedback is very helpful for us to improve it. Auto saving of browser fields in Eloquent relationship is also something we are thinking of. With Twill, we try to find a balance between flexibility and simplicity, and this is exactly the kind of feature where we can simplify even more for the most common use case while keeping flexibility for custom fields and relationships.

Finally, there's nothing preventing you from saving the content of a browser in a text field in the model you attach browsed items to, by manually reading the fields available in the `beforeSave` or `afterSave` hooks, and then reformatting it in the `getFormFields` one, but I would really recommend storing this kind of data structure in a pivot table.

**Comment by wratke** [comment]
Thank you for taking the time to put this all together. It makes sense that you would store the relationship between things in a separate table. I'm new to Laravel so there's a bit of a learning curve for me as I familiarize myself with how Laravel works while I dive into Twill. I think the documentation is really coming along really well (I was pretty lost when I was trying to get things running a few months ago). A tutorial that steps through creating a basic CMS where it threads some of the isolated elements in the documentation into something you can follow step by step would be really useful.

Thanks for all of your assistance, the designers I work with are really excited about using this CMS (they're big fans of area17).

**Comment by wratke** [comment]
I'm getting the following error:

```Call to a member function map() on null```

from the this in the getFormFields hook:

```$fields['browsers']['services'] = $this->getFormFieldsForBrowser($object, 'services');```

Also a heads up that ```return $fields``` is missing a semicolon in the documentation.

**Comment by ifox** [comment]
Did you define a `services` Eloquent relationship in your `Project` model?

Something like this:

```php
public function services()
{
    return $this->belongsToMany(Service::class)->withPivot('position')->orderBy('position');
}
```

**Comment by wratke** [comment]
No, I hadn't, but I'm getting the same error after adding it to the ```Project``` model.

**Comment by ifox** [comment]
That's not good. The relationship should return an empty `Collection` which can be mapped using `map()` without issues.  Any chance you can share your codebase? I can set it up locally to help you out more efficiently.

**Comment by wratke** [comment]
Sure, that would be helpful. I've created a public repo: https://bitbucket.org/wratke/twill_test

**Comment by ifox** [comment]
Awesome!

I think I found the source of your issue. The last migration you created adds a `services` column to the `projects` table. This create a conflict between attribute and relationship in Laravel, with the attribute taking priority. This is why the `map` operation fails, it's trying to do it on a `null` services attribute instead of the `services` relationship.

**Comment by wratke** [comment]
One small wrinkle. I'm adding a second related model, collaborators. As far as I can tell I've set it up exactly the same way as services, but it's expecting a collaborator_project table, not project_collaborator. The services model works fine with a the project_service table I've setup. What determines the order of the names of each model used in the relationship pivot table? I would assume since I'm defining the relationship on the ```Project``` model that project would be the first model name used for the table.

**Comment by wratke** [comment]
It kind of looks like it's assigned alphabetically.

**Comment by wratke** [comment]
I'm assuming it's alphabetical which makes sense. I created a ```collaborator_project``` table and everything is working well.

**Comment by nikhiltri** [comment]
Yes, the alphabetical naming of the pivot table is a Laravel convention:

“The... table is derived from the alphabetical order of the related model names.”
https://laravel.com/docs/5.7/eloquent-relationships#many-to-many

I got hung up on this, too when I first started working working Laravel.

**Comment by milewski** [comment]
```
Schema::create('project_service', function (Blueprint $table) {
    createDefaultRelationshipTableFields($table, 'project', 'service)
    $table->integer('position')->unsigned()->index();
});
```

@ifox what if i dont want use the position? like the order doesn't matter... im still obligated to include this on the table? or is there a way to disable the reordering with `@formField('browser')` ?

**Comment by ifox** [comment]
Hi @milewski,

you should be able to use `'sortable' => false` on `@formField('browser')` to disable the re-ordering UI.

If you do that, removing the position field from database should be fine. Let me know if you run into issues!

**Comment by ifox** [comment]
Ok, sorry about that, I will test this and get back to you asap!

**Comment by nsivertsen** [comment]
I just ran into the same thing, and can confirm that browser fields don't work without a `position` field on the relationship.

**Comment by sebastianlenton** [comment]
Hi,

I have a very similar setup to that described at the beginning of this thread (projecttags related to projects in a browser field).

My problem is, I need to be able to control the order of the projecttags when output with a project on the frontend, but the projecttag position field doesn't save when I update the project module in the backend.

Any advice?

Thanks!

**Comment by poncianodiego** [comment]
The docs need update on this matter. 

Using browser fields and custom pivot tables.
