### ISSUE TITLE
clean install failing laravel 5.7

### ISSUE THREAD

**Issue by nkorent** [area17/twill#457]
I required twill package on clean laravel 5.7 installation but got this error:

`root@b16fe253e280:/var/www# composer require area17/twill:"^1.2.2"
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package dimsav/laravel-translatable is abandoned, you should avoid using it. Use astrotomic/laravel-translatable instead.
Writing lock file
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ServiceProvider.php line 173:

  array_key_exists(): The first argument should be either a string or an inte
  ger

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.`

I found this issue:
https://spectrum.chat/twill/help/installation-failing~9616e158-f018-4ef3-8053-b1243b790c71
Which seems related but nothing new pops up.

Any suggestions?

**Comment by nkorent** [comment]
did a fresh install of laravel 5.8, repeated the steps. seems to work fine now with 1.2 branch 🤷‍♂

**Comment by vitthalghodke1** [comment]
Install of area17/twill failed

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by vitthalghodke1** [comment]
same erroor
