### ISSUE TITLE
Cannot install - error creating setting_translations table

### ISSUE THREAD

**Issue by Stiropor** [area17/twill#474]
On fresh Laravel installation when adding Twill (`master` branch) and doing `twill:install` I get:
```
Migrating: 2019_11_26_30009_create_settings_table
Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1005 Can't create table `triglav_apartmaji`.`#sql-6216_5cee8` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `setting_translations` add constraint `fk_setting_translations_setting_id` foreign key (`setting_id`) references `settings` (`id`) on delete CASCADE)
```
Seems it works if I change `id` field of `settings` table in migration to `bigIncrements`. Hope that helps?

**Comment by arifulhb** [comment]
> Seems it works if I change id field of settings table in migration to bigIncrements. Hope that helps?

It worked perfectly! Thanks @Stiropor

**Comment by ifox** [comment]
Fixed on master!
