### ISSUE TITLE
Unable to locate Mix file: /public/assets/admin/js/manifest.js

### ISSUE THREAD

**Issue by kauaicreative** [area17/twill#477]
The /public/assets/admin/js/manifest.js file is indeed present.
```
"Unable to locate Mix file: /public/assets/admin/js/manifest.js. (View: C:\www\station6-twill\vendor\area17\twill\views\layouts\dashboard.blade.php)"
```
At some point I ran `npm run twill-dev` The script failed (since I am on windows) Twill admin started throwing this error. There is no hot file present. 

At a last resort I will reinstall twill and laravel but I would like to know what happened here how to fix it. 

![image](https://user-images.githubusercontent.com/127033/69844516-970f8000-123a-11ea-9b3a-20e8a7a8fe1b.png)

![image](https://user-images.githubusercontent.com/127033/69844558-cb833c00-123a-11ea-9d24-216876f13cb5.png)

**Comment by imknight** [comment]
I think is similar to my previous issue, need to tweak webpack config #269

**Comment by ifox** [comment]
`npm run twill-build` should have resolved your issue here, and our upcoming release makes building unnecessary, more on that soon!
