### ISSUE TITLE
Remove "Made with Twill" from admin login

### ISSUE THREAD

**Issue by layout-lab** [area17/twill#478]
Hi,

Can I suggest that in the next release the "Made with Twill" and link are removed from the admin login page?

While I agree obscurity should not be relied upon as the sole defence method, removing the link to the CMS source code on the login page is a minor change that could reduce risk.

Thanks!

**Comment by Insperio** [comment]
Most of the platforms I can think of show their logo or "made with" sentence and some even show software version... It helps them get the recognition they deserve :)

Identifying the software takes few minutes max even without it written down clearly anywhere (analyze the dom code or just take screenshot of login page and use google). There are also paid solutions that do all the work for you, you just provide the url.

My point of view in short: I don't think removing the sentence will help anything from security point of view :)

**Comment by yanhao-li** [comment]
I'm aligning with the above reply.
Thank you for supporting the community, closing this issue now, feel free to reopen it if you have further concerns.
