### ISSUE TITLE
Guidelines - Block quantity and complexity

### ISSUE THREAD

**Issue by layout-lab** [area17/twill#479]
Hi,

I am working on a site where an page item may have 10+ blocks. 
These blocks range in complexity from simple text inputs for a heading/paragraph through to repeaters for an image carousel. On this quantity the page save action causes the browser to hang, and in some cases the order of repeater items have not saved correctly.

Are there any guidelines for:
- Max quantity of blocks per item?
- Complexity of the blocks (fields, repeaters)?

Additionally, has anyone experienced repeater items not save in the correct order?

Thanks!

**Comment by philippdaun** [comment]
We've run into the same issue, where saving or switching the language crashes the browser. In that case, the page has about 40 block items with a repeater of 3 items inside.

Would love to get some input from the Twill team about the performance to be expected and ways to optimize block composition.
