### ISSUE TITLE
Dashboard: dashboard breaks when using a global scope and model returns no items

### ISSUE THREAD

**Issue by zedee** [area17/twill#491]
I have two modules which are a bit 'special'. They fetch data from same table, with the difference of the 'type' column, which will differentiate between the two variants. (I haven't used a Polymorphic relation because I didn't want to manage two different tables which are all the same, part of this app is on production and I have no idea if is possible to manage modules which this kind of relations).

The thing is that I have defined global scopes in each model, but when I load the dashboard, in `DashboardController.php`, at line 177 it breaks, as `$activity->subject->title` is not defined.

I added up my own logic on `DashboardController.php` in order to solve this but as I have no global idea of the app, and I'm unaware if there're unit tests for that, I'm unsure if it will fail. The fix I made (on my own fork) is the following:

Lines 168 to 170:
Original:
```
if (!$dashboardModule || !$dashboardModule['activity'] ?? false) {
        return null;
    }
```

Changed to:
```
if ((!$dashboardModule || !$dashboardModule['activity'] ?? false) || empty($activity->subject)) {
        return null;
    }
```

Seems to fix the problem

**Comment by ifox** [comment]
Fixed in 0481894d.
