### ISSUE TITLE
Dashboard: cannot overwrite Controller to add custom behavior

### ISSUE THREAD

**Issue by zedee** [area17/twill#492]
Dashboard is hardcoded on admin routes. Is there any way to overwrite the `DashboardController` and add its own custom logic, or the only workaround is fiddle with the dashboard view?

**Comment by yanhao-li** [comment]
Hi @zedee ,
Unfortunately, there is no way to overwrite the `DashboardController` for now, please check out the discussion in this thread for detail: https://github.com/area17/twill/issues/262
We do have plan to add slots into the blade file so developers could custom the dashboard as they wish.

**Comment by razvaniacob** [comment]
is there any progress in this issue. I wous like to overwrite some logic in that controller also. Thank you!

**Comment by ifox** [comment]
You can always override Twill's controller using Composer, if that's really what you're looking to do. We will improve the dashboard in Twill 3.0 so it can be more easily extended.
