### ISSUE TITLE
Json_encode

### ISSUE THREAD

**Issue by vacoup95** [area17/twill#499]
We keep getting this error on all pages if we use certain php settings (which are very hard to compare with our hosting... So we have no idea what's exactly causing this...)

![Image of the isssue](https://user-images.githubusercontent.com/14930937/52413043-b63cf580-2ae0-11e9-80cc-ee6183411e6c.png)

The error results in: ( look at issue #180 )

![This f*ing page](https://user-images.githubusercontent.com/14930937/52412996-9ad1ea80-2ae0-11e9-83e1-52ca293e5664.png)

Finally I've fixed it.... 

Inside views/layouts/form.blade.php on line 105:
`published: {{ json_encode(isset($item) ? $item->published : false) }},`

This piece of code is creating "1" while it should be creating 1 (notice the quotes...)
So whenever I would change php version this error would occour. I don't know exactly what the underlying issue is and I would REALLY like to know, so please do tell me....

I only know that the way the json_encode behaves you have to add the JSON_NUMERIC_CHECK so that it won't be adding those pesky quotes anymore:

`published: {{ json_encode(isset($item) ? $item->published : false, JSON_NUMERIC_CHECK) }},`

**Comment by nkorent** [comment]
I got the same issue on my production.
locally everything works great, put it on production and a lot of issues pop up - this was one of them. Still trying to fix this as I can't fin the mentioned view anywhere in my project besides the vendor folder.
Got any ideas how I can get this view to show in my project instead of vendor?

**Comment by sauron** [comment]
hey @vacoup95 and @nkorent , can I ask you to verify your DB SERVER versions and charset setting?
Perhaps that can help us notice where the error comes from.

**Comment by ifox** [comment]
Fixed in 1cafa7802.
