### ISSUE TITLE
Retrieving a 404 for all twill routes (/login & users)

### ISSUE THREAD

**Issue by seismicsix** [area17/twill#5]
Hi could someone please let me know if i'm doing something wrong - I just cant get it to show any URL'S so I can login etc.?

Am I missing something in the install docs, I have dd() in the twill routes file and it is being loaded - it just never links to the controller?

<img width="1358" alt="screen shot 2018-07-09 at 11 51 41" src="https://user-images.githubusercontent.com/1272938/42446538-9655575e-836e-11e8-8074-57ca33bd5688.png">

**Comment by crnkovic** [comment]
Yeah, same here. The documentation about the installation process is a bit unclear. I've installed, set up and created a user, however not possible to access any "admin" dashboard.

Running Laravel Valet and cannot run on `admin.domain.test`, and when provided env variables, cannot run on path.

```
APP_URL=domain.test
ADMIN_APP_URL=domain.test
ADMIN_APP_PATH=admin
```

It's pretty unclear how to set this up.

**Comment by seismicsix** [comment]
I dont think this is the exact issue ima having as I can access both URL’s

Have up updated your hosts file to include both records?

**Comment by seismicsix** [comment]
I've found the Admin URL's:
http://admin.domain.test/admin/users
works for me :-)

**Comment by ifox** [comment]
Hi @seismicsix, glad you were able to sort it out!

I noticed your url contains both the `admin` subdomain and the `admin` path prefix. It definitely works this way, but if you want to have the subdomain only, you can comment/remove the `ADMIN_APP_PATH` variable from your `.env` file. The url to access the users management section would then be http://admin.domain.test/users.

In case you want the admin app on a subpath of your frontend domain, you can too! For that, you'd need to keep the `ADMIN_APP_PATH` variable (which can be anything you like, not necessarily `admin`) but also specify the `ADMIN_APP_URL` variable to be exactly the same as `APP_URL`, so in your case `domain.test`. The url to access the users management section would then be http://domain.test/admin/users.

**Comment by ifox** [comment]
Hi @crnkovic, I noticed a reply from you in this thread however it is only displayed under @seismicsix's reply, not sure how Github ended up doing this :/

<img width="793" alt="screen shot 2018-07-09 at 12 30 17 pm" src="https://user-images.githubusercontent.com/708498/42463377-fbfe570e-8373-11e8-9b09-2d6beeeef32c.png">

You can refer to my previous comment here to learn more about the different `.env` variables. Thanks for your feedback, we'll make sure to take it into account to update our installation instructions. 

If you want to run 2 different subdomains pointing to the same Laravel app using Valet, according to https://github.com/laravel/valet/issues/124 it should be automatically available, however I remember having to setup a symbolic link manually, as outlined in [this article](https://medium.com/@rcubitto/configure-subdomains-in-laravel-valet-48ac6759a438).

**Comment by seismicsix** [comment]
Hi, thanks for confirming. I have it up and running now, and look forward to testing out some more - thanks for releasing the code, it looks awesome. Once I had it setup on that extended url (which is how I interpreted the docs) - I went back and could see that I could change the admin url to either a sub domain or uri 😁 thanks again

**Comment by crnkovic** [comment]
Fixed it myself so I deleted my comment! Thanks anyways!
