### ISSUE TITLE
Not yet documented feature regarding parent-child modules

### ISSUE THREAD

**Issue by nikhiltri** [area17/twill#508]
I was working on creating a module that I wanted to be treated as a child under a different module, e.g., a magazine issue that can be comprised of articles. No articles should be able to be created that's not part of an issue.

After trying to some things manually, I came upon some built-in functionality that got me way ahead of where I was:

```
php artisan twill:module issues --hasSlug --hasMedias --hasPosition --hasRevisions
php artisan twill:module issueArticles --hasSlug --hasMedias --hasPosition --hasRevisions
```

From what I gather, naming the articles in such a way allows users to treat articles as a child module of issues. To my understanding, this is different from the [Nested Module](https://twill.io/docs/#nested-module) that's described in the documentation, which refers to a module whose records can be nested to represent a hierarchy—e.g., a Page under another Page. 

If my understanding is correct, I would suggest adding this to the documentation. A few notes that would be worth making:

* In the child module controller, the module and model should be explicitly named:

   ```
   protected $moduleName = 'issues.articles';
   protected $modelName = 'IssueArticle';
   ```
* Also in the child module controller, set `getParentModuleForeignKey()`, assuming you created a foriegn key column in your child table:

   ```
   protected function getParentModuleForeignKey()
   {
      return 'issue_id';
   }
   ```
* In the parent controller, you can reference the child relationship to display the number of related records in `$indexColumns`:
   ```
   'articles' => [
      'title' => 'Articles',
      'nested' => 'articles',
   ]
   ```
* In the child controller, you can add breadcrumbs to help users navigate the content:
   ```
    protected function indexData($request)
    {
        $issue = app(IssueRepository::class)->getById(request('issue'));
        return [
            'breadcrumb' => [
                [
                    'label' => 'Issues',
                    'url' => moduleRoute('issues', 'collection', 'index'),
                ],
                [
                    'label' => $issue->title,
                    'url' => moduleRoute('issues', 'collection', 'edit', $issue->id),
                ],
                [
                    'label' => 'Articles',
                ],

            ],
        ];
    }

    protected function formData($request)
    {
        $issue = app(IssueRepository::class)->getById(request('issue'));
        return [
            'breadcrumb' => [
                [
                    'label' => 'Issues',
                    'url' => moduleRoute('issues', 'collection', 'index'),
                ],
                [
                    'label' => $issue->title,
                    'url' => moduleRoute('issues', 'collection', 'edit', $issue->id),
                ],
                [
                    'label' => 'Articles',
                    'url' => moduleRoute('issues.articles', 'collection', 'index', $request->route('issue')),
                ],
                [
                    'label' => $issue->title,
                ],
            ],
        ];
    }
* The syntax for routing of parent-child modules is:
   ```
    Route::module('issues');
    Route::module('issues.articles');
   ```
* Place the blad views inside the folder that holds the parent module's views:
   ```
   resources/views/admin/issues/...
   resources/views/admin/issues/articles/...
   ```

**Comment by futurewebsites** [comment]
I have implemented as above however I get a 404 when clicking on the child from the parent index view

**Comment by ifox** [comment]
@futurewebsites which link exactly do you mean?

**Comment by ifox** [comment]
>also is it possible to create the child record(s) in the parent view?



Child records can only be created from the child index view, though you could try to put a link in each rows to directly open the create modal from there.

**Comment by futurewebsites** [comment]
@ifox where you add the reference in indexColumns

```
'articles' => [
   'title' => 'Articles',
   'nested' => 'articles',
]
```

in my case it shows a link on the index page 0 addresses this would be x articles in the above example and it links to issues/{id}/articles or customers/{id}/addresses in my case

**Comment by ifox** [comment]
ok, thank you! if the route is registered correctly, that's a bit weird.

@pboivin I think you had worked on a repro for this configuration if I'm remembering well.

**Comment by futurewebsites** [comment]
Ok I've got it 

collection is a prefix changing this to an empty string fixed the issue:

`'url' => moduleRoute('issues', 'collection', 'index'),`

to 

`'url' => moduleRoute('issues', '', 'index'),`

**Comment by ifox** [comment]
Oh, that makes sense. The `collection` route prefix is specific to @nikhiltri's module that is not living at the root of his Twill navigation. For the array, I think that's because of a Laravel change that wasn't updated yet in his snippets.

**Comment by Dmi3yy** [comment]
Not documented 2 thinks: 
1. add relationship in model 
2. save issue_id to db

**Comment by futurewebsites** [comment]
I tried to add a third level i.e:

articles
articles.issues
articles.issues.pages

This wouldn't work for me so I added a dirty work around to the ModuleController getModulePermalinkBase method:
I am sure this can be done in a more elegant way but it allows for multiple depths without it the singluarName resolves to Issue when it should be ArticleIssue

```
protected function getModulePermalinkBase()
    {
        $base = '';
        $moduleParts = explode('.', $this->moduleName);

      // start dirty hack..
        $count = count($moduleParts);
        if($count>1){
            $newModuleParts = '';
            foreach($moduleParts as $index => $part){
                if($index <  $count){
                    $newModuleParts .= Str::studly(Str::singular($part));
                }
            }
            $moduleParts = [$newModuleParts];
        }
      // end dirty hack

        foreach ($moduleParts as $index => $name) {

            if (array_key_last($moduleParts) !== $index) {
                $singularName = Str::singular($name);
                $modelClass = config('twill.namespace') . '\\Models\\' . Str::studly($singularName);
                $model = (new $modelClass)->findOrFail(request()->route()->parameter($singularName));
                $hasSlug = Arr::has(class_uses($modelClass), HasSlug::class);

                $base .= $name . '/' . ($hasSlug ? $model->slug : $model->id) . '/';
            } else {
                $base .= $name;
            }
        }

        return $base;
    }
```

**Comment by Dmi3yy** [comment]
I go another way: 
Category + Pages with nested module

**Comment by futurewebsites** [comment]
Again I am sure this could be done better but what about something like:

https://onecompiler.com/php/3xd2rdu6n

**Comment by pboivin** [comment]
Hi @mtuchi & all, I took some time to complete the docs based on the example from @nikhiltri :
https://github.com/area17/twill/blob/c447cc2fd734ace5ab6417d9d5a288e144c4e65a/docs/.sections/crud-modules.md#parent-child-modules

Let me know if this makes sense. Any feedback will be appreciated :)
