### ISSUE TITLE
Introduce Larastan

### ISSUE THREAD

**Issue by szepeviktor** [area17/twill#514]
Larastan reveals many problem hidden in the codebase.

Please remove PHPStan as a dependency and add `nunomaduro/larastan`

Somehow `'media-library' => false,` should be set in config/enabled.php before analysis.

There are problems.

**Comment by szepeviktor** [comment]
e.g. in `src/Repositories/Behaviors/HandleBrowsers.php` we need

```php
use A17\Twill\Models\Behaviors\HasMedias;
```

**Comment by antonioribeiro** [comment]
Just sent a PR to add the Larastan plugin, hoping you will help us fix all 1107 errors it's now pointing to our codebase :trollface:
