### ISSUE TITLE
Feature Request: add a duplicate record function to the index pages

### ISSUE THREAD

**Issue by arkid** [area17/twill#527]
This is a feature I find myself adding to other CMS solutions very often, both as an end user and as a developer having to sometimes batch test/pre-populate records.    

Having this option on the far right round actions button per row of the index page AND in the bulk actions select list when rows are checked would be incredibly useful.  

It's the kind of feature that naturally needs some configuration as its very possible that duplicating a record could fail due to key constraints/unique indexes etc.   However it would seem that difficult to get around if a few options could be provided for such as telling twill which fields to duplicate, which ones to rename with a suffix to make them unique etc.   It could then handle the slug automatically if slugs exist for the model, suffixing a _2 for example.

**Comment by arkid** [comment]
Just for the record, I know that some work on this was started by Jonathan Hamler, see https://spectrum.chat/twill/feature-requests/duplicating-pages~68ec551f-9d6b-41e7-b5be-92d4ee097f80

Is there any chance that this might be added to the official wish list?

**Comment by ifox** [comment]
Added in #556.
