### ISSUE TITLE
Feature request: make the media popup window show the objects it is linked to stopping it from being deleted

### ISSUE THREAD

**Issue by arkid** [area17/twill#530]
I discovered only recently that if you try and delete a file/image from the media popup interface and that asset is in use somewhere, that it isn't possible to delete the item.

Can this popup at least list the objects that are stopping the deletion, if not handle this better and give the option to remove the links the file is in and to therefore allow deletion ?

**Comment by pboi20** [comment]
Related PR: https://github.com/area17/twill/pull/1019

**Comment by ifox** [comment]
Planned for our next minor release with an update of #1019.
