### ISSUE TITLE
Trying to get property 'title' of non-object in Dashboard controller if record deleted but not in activity_log

### ISSUE THREAD

**Issue by arkid** [area17/twill#531]
I am producing a site where records may be removed from model tables by various means, not just by Twill.

The issue is that if a record is deleted from a model table and any referencing records in activity_log are not deleted, then the dashboard - assuming there is a model entry in twill.php config and 'activity'=>true will error at line 177 of the DashboardController.php

As the activity logger is a general Laravel function and isn't intrinsically related to Twill I really don't feel this should happen, the dashboard checker needs to be more robust and not error here.    

Implementing this would really help in scenarios where users have implemented their own code (either within twill or their front-ends) that deletes records.   This also goes along with the ethos expressed by yanhao-li for Area17 in [this ticket](https://github.com/area17/twill/issues/329)  ;)

**Comment by ifox** [comment]
Fixed in d1a18490.
