### ISSUE TITLE
a17-block-paragraph, quill.js and custom color swatch

### ISSUE THREAD

**Issue by bdahlinger** [area17/twill#547]
Hi,

We need colors added to the paragraph block. Adding the color options create conflicts when certain html code is used within the paragraph text. 

Our client is not tech savy so they do not use the code behind html view to fix things. The result is, copy and paste from a variety of sources, Google sheets, Microsoft Word, web sites, etc., adds certain (safe) artifacts like this one  `<span style="color: black;"><br></span>` which breaks the paragraph tool from updating when you save the model. Since an inline style of `background: black` does not affect updating, it's safe to assume that the css style `color` when used in any way is conflicting with Quill.js when you add the color option in config. But it's more complex than just the color style. Remove the `<br>` from the span and it works fine. 

**Examples:**
`<span style="color: red;"></span>` [good]
`<span style="color: red;"><br></span>` [breaks]
`<span style="background: red;"><br></span>` [good]
`<span style="color: red;">TEXT<br></span>` [good]
`<span style="color: red;"><br>TEXT</span>` [breaks]
`TEXT<span style="color: red;"><br></span>` [good]
`TEXT<p><span style="color: red;"><br></span></p>` [breaks]
`<p><span style="color: red;"><br></span></p>` [breaks]
`<p><span style="color: red;"></span></p>` [good]

![twill-paragraph-bug-02](https://user-images.githubusercontent.com/1479792/75103490-10a3d980-55b0-11ea-8a88-9809db4b3a4a.JPG)

Adding the above code `<span style="color: black;"><br></span>` to any paragraph text will not update the text when you update the model.

*/admin/blocks/paragraph.blade.php*
```
@formField('wysiwyg', [
    'translated' => false,
    'name' => 'paragraph',
    'label' => 'Paragraph',
    'editSource' => true,
    'toolbarOptions' => [
        ["header" => [2, 3, 4, 5, 6, false]],
        'bold', 'italic', 'underline', 'strike', 'link',
        [ 'list' => 'ordered'], [ 'list' => 'bullet' ],
        [ 'indent' => '-1'],
        [ 'indent' => '+1' ],
        [ 'color' => ['#ef9332','#0764b4','#cccccc']],
    ],
    'note' => 'You can edit the source.',
])
```

Searching issues directly on Quill.js didn't come up with anything. I have a hard time believing this is directly a Twill issue, but maybe something in the Vue component wrapper isn't handling some kind of exception from Quill. Something is keeping it from updating. Might seem like a low-level issue, but it's been a challenge with our clients (multiple) who are copying and pasting from several sources with these html artifacts auto-inserted. It renders the component dead for them.

**Comment by bdahlinger** [comment]
update: same issue in twill 2.0. Also another issue that might be related that was in previous versions and still in 2.0 is console errors when editing the WYSIWYG in "source code" mode.

![image](https://user-images.githubusercontent.com/1479792/77490898-82fb1a00-6df9-11ea-8c8a-bc1210fce6df.png)

Probably somehow related.

**Comment by Onatcer** [comment]
Ok so just to keep things a little structured, this is very likely related to #458

The issue is the custom Clipboard matcher used in Wysiwyg.vue in defaultModules on line 138. It uses the configuration from libe/Quill/QuillConfiguration.js 

Pretty sure the issue is the lineBreakMatcher() function, probably has something with the Delta thing there. I don't really understand why this is even in place maybe @m4n1ok can help, most of the frontend code is done by him according to the git history. 

Anyways if you need a fix right now: You can override the _wysiwyg.blade.php by copying it from the vendor folder into /resources/views/vendor/twill/partials/form/_wysiwyg.blade.php and extending the toolbar options like this to get rid of the custom matcher

```php
        $toolbarOptions = [
            'modules' => [
                'toolbar' => $toolbarOptions,
                'syntax' => $activeSyntax,
                'clipboard' => ['matchers' => []]
            ]
        ];
```

hope it helps someone until it is fixed.

**Comment by bdahlinger** [comment]
@Onatcer much appreciated! I'll give this a shot. I always forget you can override the blade templates by placing them locally.

**Comment by bdahlinger** [comment]
@Onatcer that fixed my issue! Thank you!
