### ISSUE TITLE
Browsers with deleted items attached

### ISSUE THREAD

**Issue by layout-lab** [area17/twill#548]
Hi,

I've come across an issue with one of my sites where if an existing attached browser item is deleted from the related model, the browser field no longer renders. Restoring the item or removing the browser item ID from the array fixes the issue and the field renders again.

Has anyone else come across this issue?

Thanks

**Comment by ifox** [comment]
Hi @layout-lab, I believe this has been fixed a while ago. Feel free to comment to reopen if you are still facing this issue. Thank you!
