### ISSUE TITLE
Translation models

### ISSUE THREAD

**Issue by wratke** [area17/twill#55]
I'm trying to add in translations to the ```page``` module I've generated. The documentation suggests that models should be generated in a ```App\Models\Translations``` folder. I've added in  ```UseTranslations``` and ```HasTranslation``` to the repository and the model manually, is there something I can run that will generate the translation models? Or is that something that needs to happen when the module is initially created using the ```php artisan twill:module``` command?

**Comment by ifox** [comment]
I assume you meant `HandleTranslations` in the repository, right?

Right now, that is something that needs to happen when the module is initially created.

@m4n1ok and myself actually discussed this last week and we're thinking about supporting your exact use case.

In the meantime, one way would be to make sure your Git repo is clean of any pending changes, re-generate your module with the -T option, and discard all changes except the newly created file.

**Comment by wratke** [comment]
Yes, that's correct, I used ```HandleTranslations```. Now that I know about it, in the future I'll make sure I use the ```-T``` option when I'm creating the module when I want to use translations. For testing I'll just do what you suggested. Thanks!
