### ISSUE TITLE
Feature Improvement: Image field defined for the index page has to be the first field otherwise errors

### ISSUE THREAD

**Issue by arkid** [area17/twill#552]
In my Twill controller if I define a thumbnail field as the first field everything is fine.  For example

```
protected $indexColumns = [
'label_image' => [
   'thumb' => true, // image column
   'variant' => [
	   'role' => 'label_image',
	   'crop' => 'default',
   ],
   'sort' => false
],
// more fields...
```

However as soon as I copy/paste that particular field into say 2nd position in the array then it fails and I get the error

"Undefined index: field" at line 897 of twill\src\Http\Controllers\Admin\ModuleController.php

I thought I was making errors in my copy/pasting when this first happened but I've now done it multiple times and the issue occurs reliably.  

I'd argue that there are valid reasons why an admin may want to setup an indexpage with something else prefixing a thumbnail image and that this is therefore somewhat unreasonably restrictive to force the thumbnail to be the first column of the index.

**Comment by haringsrob** [comment]
Fixed in https://github.com/area17/twill/pull/1586
