### ISSUE TITLE
File Uploads fail when custom root path is supplied

### ISSUE THREAD

**Issue by stiknoltz** [area17/twill#553]
First off, I'm enjoying the experience developing with Twill and hope to be able to contribute more as I go. 

I ran into a blocker in the file upload process that I think I've been able to solve, but I'm open to better options if my solution doesn't fit. 

When using S3 as the disk for file_library and a custom path by setting either AWS_ROOT or S3_ROOT in .env, the call to the `admin/file-library/files` to post the returned values failed due to the storage of the file path in it's entirety including the custom path [it's returned as `key` from the uploader success endpoint]. The error appears to be due to an eventual `has` check in the `AwsS3Adapter` which prepends the custom path prefix already so it's duplicated in the path that is checked. 

Additional checks on the Media Library side didn't produce an upload failure, but would create an issue subsequently displaying the image.

**Comment by ddxor** [comment]
I am also affected by this and spent some time drilling through twill libraries before identifying this exact issue as the cause.

**Comment by kirkbushell** [comment]
If by path you mean bucket, I get this exact problem. Remove the bucket, file uploads work, media fails. Add the bucket, media works, files fail. I'm not really sure why these two systems aren't using the same upload solution.
