### ISSUE TITLE
Error on custom modules: cannot edit an item (JS error) after Twill Update.

### ISSUE THREAD

**Issue by zedee** [area17/twill#568]
Hi, I recently merged all the changes made on Twill on my fork (which, with minor differences in translations and locale support in the `Datepicker` component, it follows it almost in parallel).

But now, when I'm editing an item from a custom Module, I get the following error on JS console:

```
edit:387 Uncaught TypeError: Cannot read property 'STORE' of undefined
    at edit:387
edit:533 Uncaught TypeError: Cannot set property 'TWILL_BLOCKS_COMPONENTS' of undefined
    at edit:533
```

Looking at the JS' `:387` line, I see this:

```JS
 window['TWILL'].STORE.form = { /* ... more code inside which is not relevant for this */ }
```

And in line `:533` I see this:

```JS
window['TWILL'].TWILL_BLOCKS_COMPONENTS = []
```

By some reason, which I'm unable to guess at this moment, `TWILL` property it is not set on `window`.

I ran all the `npm` build scripts, and published and ran `php artisan twill:update` as well

What I'm doing wrong? Which additional information do you need to help me find what is going on?

Should i report this as an issue on GitHub? I've saw a very similar issue but it's not quite explaining what is going on... https://github.com/area17/twill/issues/180

Edit: I add a Gist with the HTML edit page source code: [removed because of accidentally exposed keys :fearful: ]

Thanks!

**Comment by ifox** [comment]
Hi @zedee thank you so much for reporting this! Your gist was very helpful.
Question: are you overriding Twill layouts?

If you take a look at https://github.com/area17/twill/blob/master/views/layouts/main.blade.php#L81, we are now namespacing everything under `window.TWILL`, but in your gist you still have non namespaced window assignments.

**Comment by zedee** [comment]
@ifox 

> Question: are you overriding Twill layouts?

Now I've checked my app source code, and yes, I did override the layout... or at least had the intention to do so, because I got a copy of that file on `resources/views/vendor/twill/layouts/main.blade.php`

The reason I did so was to translate some CMS strings to the final user language.

OK, tomorrow I'll try to update my overriden layout to the current version and update this with more news, but I'm 99.99% confident that this will solve the issue :)

thanks!

**Comment by zedee** [comment]
UPDATE:

I updated my layout overrides and merged with the changes you made on the new release.
Now it is working as intended, and I will close the issue.

By the way, is anywhere on the docs about how:
1. Inject additional CSS, as I have a custom dashboard with a specific layout (where are Twill's resource files?)
2. Where to put twill interface translation files? (I see a call to `twillTrans('twill::lang.dashboard.empty-message');`), but how I should create my own translation files on the base `lang` folder?

**Comment by arkid** [comment]
> Inject additional CSS, as I have a custom dashboard with a specific layout (where are Twill's resource files?)

Copy the vendor\area17\twill\views\vendor\twill\partials\head.blade.php  default file into your \resources\views\vendor\twill\partials\ path.   Then just add references to extra CSS/JS at the bottom of this.

**Comment by ifox** [comment]
You can also push into the `extra_css` Blade stack: https://github.com/area17/twill/blob/f66aaa6821debdeeb3c7b24633d65d66d444a3d4/views/partials/head.blade.php#L30-L31
