### ISSUE TITLE
Multiple browser inputs for a single module

### ISSUE THREAD

**Issue by wratke** [area17/twill#57]
Does the ```name``` for a browser input need to match the module name? I would like to have three separate browser inputs that all use a single module, but when I gave each input a unique name, nothing was saved. Changing the name to match the ```module``` name allows me to save them, but that prevents me from having three separate inputs with different items from the module for each one. Is there a way around this? Or in this instance would I need to create three separate tables in the database, one for each input?

**Comment by ifox** [comment]
The default behavior would be to use 3 different relationships in your module, with 3 tables, yes.

Laravel allows you to apply scope to relationship definitions though, so you should able to store everything in the same table for those 3 relationships, but with an additional pivot field indicating in which browser it is saved. This will requires some custom logic when saving in `afterSave`, but it shouldn't be too complicated. Happy to help if you can share a demo codebase!

**Comment by power-media** [comment]
That issue has never been resolved, still happening for Twill v 2.12
