### ISSUE TITLE
Bug display _multi_select field with formData($request)

### ISSUE THREAD

**Issue by Romulus21** [area17/twill#578]
Hello,
On Twill 2 :  `vendor/area17/twill/views/partials/form/multiselect.blade.php` at line 63, I change `Arr`  by `\Illuminate\Support\Arr` to fix display of multiselect box on backoffice.

**Comment by ifox** [comment]
Hi @Romulus21, we can definitely prevent this issue in Twill but this is a Laravel upgrade issue first and foremost. Starting with Laravel 5.8, the Arr and Str facades have been added to `config/app.php`. See https://github.com/laravel/laravel/commit/590ae1703103011cc9d1d6abd924261748d7b8ac.

**Comment by Romulus21** [comment]
Thanks @ifox, this is effectively an update from Laravel 5.8. I add this to my `config/app.php`
