### ISSUE TITLE
Add CSS to the control panel

### ISSUE THREAD

**Issue by wratke** [area17/twill#58]
Is there a nice and clean way to add some extra CSS to the control panel? I'd like to add a section title to the forms to break things up visually a bit. I can inline it easily enough, but it would be nice to have the ability to append some CSS.

**Comment by ifox** [comment]
Definitely, checkout the Blade stack we added to the head partial here: https://github.com/area17/twill/blob/19e6f8fefde5c9a4635f3dbbcfc05f1d5022b934/views/partials/head.blade.php#L19

Using the following in your views, you can drop inline CSS or a link to a file:

```blade
@push('extra_css')
    <style>
    // some inline CSS
    </style
@endpush
```

We also have a stack for blocking JS in the head and JS at the end of the document:

https://github.com/area17/twill/blob/19e6f8fefde5c9a4635f3dbbcfc05f1d5022b934/views/partials/head.blade.php#L20

https://github.com/area17/twill/blob/19e6f8fefde5c9a4635f3dbbcfc05f1d5022b934/views/layouts/main.blade.php#L103

Feel free to create your own layout file to use in all `form.blade.php` files of all your modules if you're looking to apply your extra CSS/JS globally.

**Comment by wratke** [comment]
Perfect, thank you.

**Comment by arkid** [comment]
Can it be confirmed if this can be done universally throughout all the pages in the twill admin?   

At the moment I would have to edit each of my models views and add the extra css/js in the push statements.   And what about other pages of the admin like the home/welcome page?

**Comment by Tofandel** [comment]
For future reference, you can run `php artisan vendor:publish --provider="A17\Twill\TwillServiceProvider" --tag=views`

Which will copy the twill blade template in your resources folder

From there you can delete pretty much everything and only keep `partials/head.blade.php` (or `partials/footer.blade.php` if you don't need to change the auth pages styles) and/or keep the `layouts` you need based on your needs

The most straightforward is to simply create a `resources/views/vendor/twill/partials/head.blade.php` and put this in it

```
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="robots" content="noindex,nofollow" />

<title>{{ config('app.name') }} {{ config('twill.admin_app_title_suffix') }}</title>

<!-- Fonts -->
@if(app()->isProduction())
    <link href="{{ twillAsset('Inter-Regular.woff2') }}" rel="preload" as="font" type="font/woff2" crossorigin>
    <link href="{{ twillAsset('Inter-Medium.woff2') }}" rel="preload" as="font" type="font/woff2" crossorigin>
@endif

<!-- CSS -->
@if(app()->isProduction())
    <link href="{{ twillAsset('chunk-common.css') }}" rel="preload" as="style" crossorigin/>
    <link href="{{ twillAsset('chunk-vendors.css') }}" rel="preload" as="style" crossorigin/>
@endif

@unless(config('twill.dev_mode', false))
    <link href="{{ twillAsset('chunk-common.css') }}" rel="stylesheet" crossorigin/>
    <link href="{{ twillAsset('chunk-vendors.css' )}}" rel="stylesheet" crossorigin/>
@endunless

<!-- head.js -->
<script>
    !function(e){var i=window.A17||{},n=e.documentElement,l=window;i.browserSpec="html5",i.touch=!!("ontouchstart"in l||l.documentTouch&&e instanceof DocumentTouch),i.objectFit="objectFit"in n.style,window.A17=i,n.className=n.className.replace(/\bno-js\b/," js "+i.browserSpec+(i.touch?" touch":" no-touch")+(i.objectFit?" objectFit":" no-objectFit"))}(document);
</script>

@stack('extra_css')
@stack('extra_js_head')
```

In which you can add any style you want and will apply to all pages in the twill admin
