### ISSUE TITLE
Feature request: $indexOptions doesn't seem to have an option to disable destroy feature

### ISSUE THREAD

**Issue by arkid** [area17/twill#582]
$indexOptions doesn't seem to have an option to disable the new destroy feature introduced in Twill 2.0

This is really vital for any project where data policies prohibit such destructive actions.

**Comment by ifox** [comment]
Totally vital and actually it is there:

<img width="319" alt="Screen Shot 2020-03-12 at 3 17 18 PM" src="https://user-images.githubusercontent.com/708498/76558950-a1195f80-6474-11ea-80ab-cc34004e373a.png">

`forceDelete` and `forceBulkDelete`.

**Comment by arkid** [comment]
Ah phew!  But it doesn't seem to work.   It's simply ignored having added it and refreshed my index page on the trash folder.

**Comment by arkid** [comment]
Ah ok I know why.... you just wrote it wrong in your note ;)   Its bulkForceDelete not forceBulkDelete.

**Comment by arkid** [comment]
Dammit sorry, no it definitely doesn't work still even with bulkForceDelete set as false

**Comment by arkid** [comment]
Also just to clarify, force delete is "destroy", its just got two names, one in the code, another in the interface ?

**Comment by ifox** [comment]
🤦‍♂️sorry about that, fixed! And yes, you are right. Force delete didn't feel right in the UI, and the destroy action was already taken by the soft delete feature in the code.

**Comment by arkid** [comment]
Ok great thanks, is it possible to update the manual for this to clarify ?  I'd do myself but not 100% confident I have it all correct.
