### ISSUE TITLE
Querying a module and it's associated data

### ISSUE THREAD

**Issue by wratke** [area17/twill#59]
I'm studying the Laravel docs trying to figure out the best way to pull all of the content associated with a module. Is there a simple way of doing this in Twill that enables me to pull everything (media, translations, associated browser content) at once? Or do I need to query all of the associated content in separate queries? I just want to make sure I'm not missing some sort of helper that simplifies this task before I dig into figuring out how to pull everything manually.

I've set up a ```PageController``` that serves the content for the pages from the ```Page``` module and added a route in the ```web.php``` file that's working as expected:

```
namespace App\Http\Controllers;

use App\Models\Page;
use App\Models\Translations\PageTranslation;
use Illuminate\Http\Request;

class PageController extends Controller
{
    public function home()
    {
    	$page = Page::find(1); 
    	$translations = PageTranslation::where('page_id', '=', 1)->get();
        return view('home', [
        	'page' => $page,
        	'translations' => $translations
        ]);
    }
}
```
It's not clear to me how I can make a query to the ```mediables``` table if I do need to pull that content manually.

**Comment by wratke** [comment]
I see the eager loading provides a way to do this that is pretty effective, however I still don't see how I can pull the images from the ```mediables``` table:

```$page = Page::with('clientLogos', 'testimonials', 'translations', 'callToActions')->where('id', '=', 1)->get(); ```

**Comment by ifox** [comment]
For translations, the underlying package, dimsav/translatable, already does the work by using the current app locale to eager load the right translation row. Translatable fields are accessible like normal attributes on your `$page` object.

For medias, you can eager load the `medias` relationship for performance using `with`, definitely. When it comes to actually rendering image urls, Twill comes with a good share of helpers, check out this [media library section](https://twill.io/docs/#role-crop-params) in the docs.

For browsers, eager loading with `with` is definitely the way to go.

**Comment by ifox** [comment]
Interesting, it should be set to what you have in `config/app.php`:

```php
/*
|--------------------------------------------------------------------------
| Application Locale Configuration
|--------------------------------------------------------------------------
|
| The application locale determines the default locale that will be used
| by the translation service provider. You are free to set this value
| to any of the locales which will be supported by the application.
|
*/

'locale' => 'en',
```

Then you most likely will need a route middleware to dynamically set the locale using a url segment or parameter. There are also a lot of Laravel packages to choose from to setup routing for i18n.
