### ISSUE TITLE
php artisan twill:dev not watching changes on custom components

### ISSUE THREAD

**Issue by zedee** [area17/twill#595]
Hi, after a bit of poking, I successfully ran `php artisan twill:dev` from a docker container ( issue #584 )  the odd thing now is that despite it's compiling successfully all changes, it does not 'sense' any changes and I have to run again `php artisan twill:dev` in order to reload changes.

My work directory is `./resources/assets/js/components`

Is there anything I'm not doing right?

**Comment by is-blackhole** [comment]
Same problem here, `php artisan twill:dev` doesnt detect files changes while running inside docker container
