### ISSUE TITLE
Position dragging no longer works in 2.0.0

### ISSUE THREAD

**Issue by zipavlin** [area17/twill#599]
Console notice says that Vuedraggable has deprecated options props in version v2.20.

**Comment by galingong** [comment]
Confirmed, same here. I tried implementing the migration suggestions provided [here](https://github.com/SortableJS/Vue.Draggable/blob/master/documentation/migrate.md#options-props) and rebuilt Twill, but couldn't fix the problem.

**Comment by zipavlin** [comment]
Yes, as @galingong stated, suggested migration does not seem to work.

**Comment by galingong** [comment]
There's already a [commit](https://github.com/area17/twill/commit/a79e3d2ee95c4f8ef0e08bbc0f14ae8abad9c7c7) for fixing the issue, so you could use `2.x-dev` if you really need the feature working right now (that's what I did). I'm hoping there should be a bugfix release in a couple of days.

**Comment by zipavlin** [comment]
@galingong thanks for pointing me to existing commit. I am closing this issue as it seems fixed, we just need to wait for next release
