### ISSUE TITLE
Repeaters inside Settings

### ISSUE THREAD

**Issue by dacastro4** [area17/twill#606]
I'm creating another tab inside the settings module and then adding a repeater form field but when I save I get `Array to string conversion`.

Am I doing something wrong? Do I have to set up something in the Setting to allow repeaters?

```
@extends('twill::layouts.settings')

@section('contentFields')
    @formField('repeater', [
        'type' => 'repeatablecustomerexperiences'
    ])
@stop
```

![Screen Shot 2020-03-24 at 4 16 14 PM](https://user-images.githubusercontent.com/7808930/77472790-d2861980-6dea-11ea-88d4-c8e87706d7f8.png)

**Comment by smalic** [comment]
@dacastro4  did you ever figure this out?

**Comment by dacastro4** [comment]
@smalic I was never able to do it. Sorry

**Comment by smalic** [comment]
@dacastro4 yeah, I tried last night, but realized it wouldn't be an easy fix at all. It's kind of half-done, but the repeater block also needs to be edited in Vue as well :/
