### ISSUE TITLE
Twill 2.0 is not compatible with laravel 5.7

### ISSUE THREAD

**Issue by venkataadithan** [area17/twill#608]
Twill 2.0 requires laravel/ui package.

laravel/ui package is available in laravel5.8.

Can't able to install twill 2.0 in 5.7

**Comment by pboivin** [comment]
Sorry for the delay @venkataadithan. At this point, Twill 2.5 technically supports 5.8 and up. The docs will be updated to reflect that.

**Comment by venkataadithan** [comment]
No problem @pboivin. i have moved to L6 with Twill2
