### ISSUE TITLE
Items can go missing from dashboard activity log

### ISSUE THREAD

**Issue by adam-jones-net** [area17/twill#609]
Some events in my activity_log table are prefixed with a backslash, some are not.   

The dashboard only finds events that seem to be identical to the path specified in the twill config file.

So for example, if my config file refers to 

```
'dashboard' => [
        'modules' => [
              '\App\Models\Property' => [
```

then any activity_log entry that is defined as \App\Models\Property will appear, however if they are logged as App\Models\Property they won't appear.

Can this be made a bit more flexible to catch both.

**Comment by arkid** [comment]
This may be a little more complex than I thought because it seems that on a live site I have, I am definitely referring to modules in the twill config file with a leading backslash, yet still recent records in the activity log are without that and hence there are missing items from the activity log.

**Comment by ifox** [comment]
Why are there 2 different style of activity causer in your database though? If you setup a morphmap on a model you ensure they always have the same value, but if you don't, it is supposed to save the FQCN of the model class.

**Comment by arkid** [comment]
So to clarify, you'd expect as standard that twill is creating activity log records with a prefixing backslash as standard or not?

I see in front of me from a database tool that the latest records in this site are being created in the activity_log table without an initial backslash.        

If I set my dashboard modules configuration to not include a prefixing slash, ie

```
'dashboard' => [
        'modules' => [
              'App\Models\Property' => [
```

then I have no problem.   I just thought that this difference of a single character is making the activity log either work or fail and it seemed a little too picky.

BTW; why/where would I define the morph map, I thought that was for just specific relations between multiple models ?

**Comment by ifox** [comment]
I would expect no backslash, as the FQCN of your model should be `App\Models\Model.php`.

For morph maps, check this out, as I don't think I can explain it better: https://laravel.com/docs/7.x/eloquent-relationships#custom-polymorphic-types

> By default, Laravel will use the fully qualified class name to store the type of the related model. For instance, given the one-to-many example above where a Comment may belong to a Post or a Video, the default commentable_type would be either App\Post or App\Video, respectively. However, you may wish to decouple your database from your application's internal structure. In that case, you may define a "morph map" to instruct Eloquent to use a custom name for each model instead of the class name:
> 
> ```
> use Illuminate\Database\Eloquent\Relations\Relation;
> 
> Relation::morphMap([
>     'posts' => 'App\Post',
>     'videos' => 'App\Video',
> ]);
> ```
> You may register the morphMap in the boot function of your AppServiceProvider or create a separate service provider if you wish.

**Comment by ifox** [comment]
One thing that might be confusing you might be a bug I recently spotted in the activity log UI: Activities that are not displayed count towards the 20 items displayed limit.

**Comment by arkid** [comment]
Thanks for all the clarification, I will ensure that the initial backslash is removed from my twill configs from now on.

Is there any chance of making the activities log code left trim a backslash in case someone silly like me adds it by accident?

**Comment by arkid** [comment]
> One thing that might be confusing you might be a bug I recently spotted in the activity log UI: Activities that are not displayed count towards the 20 items displayed limit.

It's possible I've seen that in the past as well but certainly this initial backslash is the root of a lot of the issues I've had and twill not finding valid logs as a result.
