### ISSUE TITLE
File Uploader assumes HTTP instead of HTTPS on external upload (S3)

### ISSUE THREAD

**Issue by carlagouveia** [area17/twill#616]
Twill uses the fine-uploader library to upload files to the media library. Unfortunately, this library has been abandoned by its author (https://github.com/FineUploader/fine-uploader/issues/2073) and it contains a bug in this method:

https://github.com/FineUploader/fine-uploader/blob/fb09dc444ac7bd14f30e3f929819e62eba9db8d6/client/js/s3/uploader.basic.js#L216

What happens here is that fine-uploader assumes HTTP when there is no scheme in the path. So, when running Twill Admin in HTTPS, and you try to upload a file to S3, the browser blocks you due to mixed content. 

I've been able to successfully "fix" this issue by manually patching the `public/assets/admin/js/vendor.js` file that Twill generates, but a proper fix would be more complicated. Maybe Twill can fork fine-uploader? Open to suggestions.

**Comment by kirkbushell** [comment]
Have just encountered this issue - was wondering wtf was going on here. Thanks for the report!

**Comment by kirkbushell** [comment]
How did you patch that file? I can't see it anywhere.

**Comment by antonioribeiro** [comment]
May I ask why your paths have no scheme?
And how are you configuring/setting this up?

**Comment by madalinignisca** [comment]
I do have the same issue.
What configurations/settings are you interested @antonioribeiro ?

It might happen if the app is on an instance with an http only server and a load balancer is terminating https, as Laravel now has no idea if it is on https or http.

**Comment by madalinignisca** [comment]
Just tested, and
`$_SERVER['REQUEST_SCHEME'] | https`
is there. Only this uploader is not switching to https. Everything else is generated correct with https://

**Comment by ifox** [comment]
@madalinignisca how is your media library disk configured? The endpoint that is provided to the uploader depends on this configuration which is true by default: https://github.com/area17/twill/blob/d8167ff260e74dd2eb4d6328c2d9f21b11353a2a/config/disks.php#L24

See also: https://github.com/area17/twill/blob/d8167ff260e74dd2eb4d6328c2d9f21b11353a2a/src/Helpers/media_library_helpers.php#L12

**Comment by ifox** [comment]
Now I do realize this is not a standard S3 disk configuration and that this needs to be improved to be more compatible without it. 

Refactoring out of FineUploader is a necessity that will be addressed in the future, and vendoring it in Twill to fix minor issues could be an option in the meantime (as we do not necessarily want to maintain a fork).

**Comment by ifox** [comment]
Fixed by #1414.
