### ISSUE TITLE
Attempting to edit content that doesn't exist results in an error

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#62]
Manipulating the URL to attempt to edit content that doesn't exist (eg http://admin.mysite.localhost:8000/projects/10/edit) produces the following error:

**Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException
No query results for model [App\Models\Project] 10**

Is there something I need to be doing to handle this (eg is it possible to route to the 404 page under these circumstances)?

Thanks

**Comment by ifox** [comment]
In production, this should display Twill's 404 page. Try the following in your `.env` file:

```
APP_ENV=production
ADD_DEBUG=false
```

**Comment by sebastianlenton** [comment]
Just setting ADD_DEBUG=false solves it. Good to know- thanks again!
