### ISSUE TITLE
Mysql 1064 violation

### ISSUE THREAD

**Issue by impactcolor** [area17/twill#633]
Using mysql 5.7 I get the following error:

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json not null, `type` varchar(191) not null, `child_key` varchar(191) null, `par' at line 1 (SQL: create table `blocks` (`id` bigint unsigned not null auto_increment primary key, `blockable_id` int unsigned null, `blockable_type` varchar(191) null, `position` int unsigned not null, `content` json not null, `type` varchar(191) not null, `child_key` varchar(191) null, `parent_id` int unsigned null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')`

This happens when running `php artisan twill:install`.
According to the documentation 5.7 should work.  Any idea what's going on?

**Comment by arkid** [comment]
Json field types aren't compatible with mysql 5.7 as far as I'm aware. I experienced the same kinds of issues so altered such columns to text.

**Comment by impactcolor** [comment]
Thanks for the response where are the json fields that I should change?  @arkid

**Comment by impactcolor** [comment]
Never mind found it, thank you!
