### ISSUE TITLE
How to actually render an image uploaded from block editor with Glide

### ISSUE THREAD

**Issue by shabaz-ejaz** [area17/twill#634]
Hi,

I'm kind of new to Twill. It's been great so far but ran into a stumbling block with figuring out how to render an image using Glide that was uploaded directly through the block editor.

So here is what I have: 

In my custom block I have a form field as such:
```
@formField('medias', [
'name' => 'image',
'label' => 'Image',
'note' => 'Also used in listings',
'fieldNote' => 'Minimum image width: 1500px'
])
```

In my block template I try and render the image like this:

`{{ $block->image('image') }}`

This outputs the following:

data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7

How do I actually render this  in my HTML?

My config:

```
'media_library' => [
        'disk' => 'twill_media_library',
        'endpoint_type' => env('MEDIA_LIBRARY_ENDPOINT_TYPE', 's3'),
        'cascade_delete' => env('MEDIA_LIBRARY_CASCADE_DELETE', false),
        'local_path' => env('MEDIA_LIBRARY_LOCAL_PATH', 'uploads'),
        'image_service' => env('MEDIA_LIBRARY_IMAGE_SERVICE', 'A17\Twill\Services\MediaLibrary\Imgix'),
        'acl' => env('MEDIA_LIBRARY_ACL', 'private'),
        'filesize_limit' => env('MEDIA_LIBRARY_FILESIZE_LIMIT', 50),
        'allowed_extensions' => ['svg', 'jpg', 'gif', 'png', 'jpeg'],
        'init_alt_text_from_filename' => true,
        'prefix_uuid_with_local_path' => config('twill.file_library.prefix_uuid_with_local_path', false),
        'translated_form_fields' => false,
    ],
```

.env values:

```
MEDIA_LIBRARY_ENDPOINT_TYPE=local
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Glide
```

**Comment by droplister** [comment]
You need to specify a crop name, like this:
```{{ $block->image('image', 'desktop') }}```

https://twill.io/docs/#role-crop-params

**Comment by shabaz-ejaz** [comment]
Perfect thank you!

**Comment by kirkbushell** [comment]
It strikes me as odd that "default" is the fallback, but it's never actually generated by the CLI, to avoid this sort of issue.
