### ISSUE TITLE
@formFieldset directive not rendering

### ISSUE THREAD

**Issue by stuartcusackie** [area17/twill#645]
I'm just starting with Twill and I've set up my posts/form.blade.php to have a fieldset like so:

```
@extends('twill::layouts.form', [
    'additionalFieldsets' => [
        ['fieldset' => 'meta', 'label' => 'META'],
    ],
    'disableContentFieldset' => true
])

@section('fieldsets')
    @formFieldset(['id' => 'meta', 'title' => 'META'])
        @formField('input', [
            'name' => 'meta_description',
            'label' => 'META Description',
            'maxlength' => 255
        ])
    @endformFieldset
@stop
```

But it doesn't render the directive correctly. This is what I see:

![image](https://user-images.githubusercontent.com/20210934/81125041-ed41c700-8f2e-11ea-94f1-b72085c5d8ad.png)

**Comment by sauron** [comment]
Hey @stuartcusackie,
I know you have a similar example to what you are implementing in the documentation, but I'd suggest to use it like the below example instead while we debug it.
```php
@extends('twill::layouts.form', [
    'disableContentFieldset' => true
])

@section('fieldsets')
    <a17-fieldset title="Meta" id="meta" :open="true">
        @formField('input', [
            'name' => 'meta_description',
            'label' => 'META Description',
            'maxlength' => 255
        ])
    </a17-fieldset>
@stop
```

**Comment by stuartcusackie** [comment]
Will do! Thank you.

**Comment by marinaglancy** [comment]
Hi, thanks for the workaround, it works but both documentation and readme files still instruct to use @formFieldset , I had to search in the closed issues to find the workaround. Should not this issue remain open?
