### ISSUE TITLE
Symfony\Component\Routing\Exception\RouteNotFoundException Route [admin.tests.store] not defined. 

### ISSUE THREAD

**Issue by michaeljcoyne** [area17/twill#649]
Hi I have just tried installing the CMS following the docs and get:

Symfony\Component\Routing\Exception\RouteNotFoundException Route [admin.tests.store] not defined. 

after running:
php artisan twill:module test

I thought this command generated the store route?

`Route::module('test');`

It doesn't say to create one in docs.

Please advise.

Thanks

Michael

**Comment by tchapi** [comment]
Hello,

The command does not generate the route automatically. It's clearly indicated in the documentation here: https://twill.io/docs/#cli-generator.

You must add the routes in your `routes/admin.php` file and setup the CMS navigation item too.

Don't forget to migrate your database too afterwards if needed.

**Comment by michaeljcoyne** [comment]
Thanks I did add the route as a resource then
`Route::resource('test',` `'TestController');`
as well as the module which I thout would take care of this and then it said I was missing the publish route.

So I think the documentation could be clearer hear as I though there would be some in build methods to handle this. And I also do not know what to do with the publish route.

**Comment by tchapi** [comment]
You don't need to add `Route::resource()`. Just the `Route::module()` as stated in the docs.

Note that you should use your module plural name in the route macro (see https://twill.io/docs/#routes):

    Route::module('tests');

**Comment by michaeljcoyne** [comment]
When i use plural I get the

`Route [admin.moduleName.index] not defined`

I have followed the documentation with a new Laravel install.

And I am aware it is clear - hence why I am raising the issue.

**Comment by nacelley** [comment]
A more suitable place to resolve issues like this would be on [Twill's Spectrum](https://spectrum.chat/twill) channel as it isn't a bug to be honest, but a seek for an advice.

When creating new module, the setup tells you what next steps are needed to be completed.
The output after creating the test module is as the following below:

**Migration** created successfully! **Add some fields!**
**Models** created successfully! **Fill your fillables!**
**Repository** created successfully! **Control all the things!**
**Controller** created successfully! **Define your index/browser/form endpoints options!**
**Form request** created successfully! **Add some validation rules!**
**Form view** created successfully! **Include your form fields using @formField directives!**
**Add Route::module('tests');** to your **admin routes** file.
**Setup** a new CMS menu item in **config/twill-navigation.php**:

            **'tests' => [
                'title' => 'Tests',
                'module' => true
            ]**
        
**Migrate** your **database**.

Enjoy.


At the end, you may be in need to clear the caches to make the Laravel aware about it.
```
php artisan config:cache
php artisan cache:clear
php artisan route:cache
```

**Comment by michaeljcoyne** [comment]
Ok so I had to pluralise route and menu item. Wasn't aware this was a macro.
Working now.
I will check it out.
Thanks for your help.

**Comment by Naimbouz** [comment]
Add new config at headers

"Accept"=>"application/json"

Laravel will check the configuration for "Accept", it will return the web page or html if no value is set at "Accept" by default
