### ISSUE TITLE
Glide not serving up the proper image

### ISSUE THREAD

**Issue by impactcolor** [area17/twill#656]
I have uploaded a file through twill.  My settings are s3 bucket with Glide.
The image is viewable in the admin panel with the name 'postcards.jpg'
However on the front end when I try to serve the image I get an error.

```
League\Glide\Server::makeImage
vendor/league/glide/src/Server.php:499
```
The error is coming from here:
```
  $sourcePath = $this->getSourcePath($path);
        $cachedPath = $this->getCachePath($path, $params);
```
When I dd the $path I get this:` "printing/postcards-printing"`
In my .env
```
FILE_LIBRARY_ENDPOINT_TYPE=s3
MEDIA_LIBRARY_ENDPOINT_TYPE=s3
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Glide
MEDIA_LIBRARY_ACL=public-read
```

My config/twill 
```
$client = new S3Client([
    'credentials' => [
        'key'    => env('S3_KEY'),
        'secret' =>  env('S3_SECRET'),
    ],
    'region' => env('S3_REGION'),
    'version' => 'latest',
]);

$adapter = new AwsS3Adapter($client, env('S3_BUCKET'));

$filesystem = new Filesystem($adapter);
  'glide' => [
    'source' => env('GLIDE_SOURCE',  $filesystem),
    'cache' => env('GLIDE_CACHE', $filesystem),
    'cache_path_prefix' => env('GLIDE_CACHE_PATH_PREFIX', 'glide_cache'),
    'base_url' => env('GLIDE_BASE_URL', env('S3_BUCKET')),
    'base_path' => env('GLIDE_BASE_PATH', ''),
    'use_signed_urls' => env('GLIDE_USE_SIGNED_URLS', false),
    'sign_key' => env('GLIDE_SIGN_KEY'),
],
```

It appears as if Glide isn't finding the image and able to post it.  Any idea what is going on or what else I need to set?

**Comment by ifox** [comment]
Hi @impactcolor, sorry we haven't been responding to your issue for so long. Your configuration looks good, but I'm not sure I understand your `"printing/postcards-printing"` output if the image you're requesting is named `postcards`.

I'm going to close this issue as I'm assuming you probably moved on since then, but feel free to ping me or open a new issue if that's still something you'd like us to look into.
