### ISSUE TITLE
Duplicate record feature not working

### ISSUE THREAD

**Issue by shabaz-ejaz** [area17/twill#662]
The duplicate record feature doesn't seem to be working.

I get the following error:
`You must define the field title in your model`

![2020-05-22_19h49_38](https://user-images.githubusercontent.com/29374282/82699892-66e2f000-9c65-11ea-958a-fbf6d4bc8b8f.png)

In my controller I have the following:

```
 protected $indexOptions = [
        'create' => true,
        'edit' => true,
        'publish' => true,
        'duplicate' => true,
        'bulkPublish' => true,
        'feature' => false,
        'bulkFeature' => false,
        'restore' => true,
        'bulkRestore' => true,
        'delete' => true,
        'bulkDelete' => true,
        'reorder' => true,
        'permalink' => true,
        'bulkEdit' => true,
        'editInModal' => false,
        'forceDelete' => true,
        'bulkForceDelete' => true,
    ];
```

When I try and duplicate a record, it seems to create a blank record however it throws this error int the console.

Any idea what's going on here?

**Comment by hugomeruma** [comment]
I have the same problem. It seems to be working with $slugAttribute instead of $this->$slugAttribute on line 269 in HasSlug.php.

**Comment by Jacq** [comment]
Using a Model without the trait HasRevisions causes an error: 
<code>
exception: "BadMethodCallException"
file: "/var/app/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php"
line: 50
message: "Call to undefined method App\Models\Activities::revisions()"
</code>

**Comment by razvaniacob** [comment]
Any fix for this? I still get error when using a Model without the trait HasRevisions. Undefined method App\Models\Event::revisions()

**Comment by ifox** [comment]
Duplicating is currently only possible if revisions are enabled.
