### ISSUE TITLE
Several problems with Duplicate action

### ISSUE THREAD

**Issue by marinaglancy** [area17/twill#673]
Amazing new feature introduced in https://github.com/area17/twill/pull/556 , thanks for it!

Some problems:

1. The "Duplicate" appears in the actions list even when indexOption 'duplicate' is set to false.
2. Default implementation of duplication does not work if the model does not have revisions.
3. Action "Duplicate" appears for the items in the "Trash" list but it does not work there at all (even when enabled in indexoptions and the implementation fixed)

Thanks in advance!

**Comment by ifox** [comment]
Hi @marinaglancy thanks! 1 and 3 should be fixed now, however I'm afraid 2 is a requirement right now. We could look into supporting duplication on models that do not have revisions if you feel like this is important for your use case.
