### ISSUE TITLE
Glide MEDIA_LIBRARY_LOCAL_PATH doesn't accept nested path

### ISSUE THREAD

**Issue by EPInformatyka** [area17/twill#677]
I think, env MEDIA_LIBRARY_LOCAL_PATH should accept a nested path route like 'uploads/frontend/media/another_nested_dir/' - At this moment, my proposition returned some errors.

BTW, FILE_LIBRARY_LOCAL_PATH pass nested path

**Comment by haringsrob** [comment]
Hey @EPInformatyka,

I just did a quick check and this should be working in the latest version.

If you still have this issue, please let us know.

Kind regards,
