### ISSUE TITLE
Greater control over ability to crop media?

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#69]
Hi,

Just wondering, is it possible to do the following re media cropping (on a per-image basis):
- disable cropping completely
- enable cropping ratio but prevent users from being able to adjust the crop size and/or position

Thanks
Seb

**Comment by ifox** [comment]
Hi Seb,

sorry for the delay here!

It is possible to allow free ratio cropping by specifying `0` as the ratio in `$mediaParams` or `twill.block-editor.crops` configurations, which in the end is similar to disabling cropping as it means any ratio could come out of this image field. I definitely see a use case where completely disabling the cropping UI elements in the form would be useful though, we'll think about supporting it!

Your second point is very interesting too and should be easy to support regarding the size by making the cropper only respond to position change, not dimensions. However, I'm not sure I understand what you mean by preventing users from moving position, can you explain? What would be the fixed position, centered?

Thanks!

**Comment by sebastianlenton** [comment]
Hi,

Thanks for clarifying re ratio 0- very useful for my use case.

Re position, yes I'm talking about being able to remove the ability to move the crop around, as well as removing the ability to change the crop size. Maybe the position could be pre-configured in the `$mediasparams` somehow.

It's not urgent, but for certain use cases I would find it useful to have more control over what users can and can't do re cropping.

Thanks again,
Seb
