### ISSUE TITLE
[Bug?] saved non-empty "checkboxes" value caused "Invalid argument supplied for foreach()" on next edit

### ISSUE THREAD

**Issue by ResetButton** [area17/twill#693]
I'm trying to implement "checkboxes" in module.

When I'm creating new module item all is fine, but after I save item and checking some checkboxes  - I get "Invalid argument supplied for foreach()" when I try to edit this page next time or just refresh it.

Steps to reproduce
1. create a module with checkboxes and add demo checkboxes to form (https://twill.io/docs/#checkboxes)
2, in admin area create new module item, then edit this item checking some checkboxes and save it., 
3. check database - you'll see something like ["finance","arts","civic"] in database record.
4. reopen page for editing or just refresh it.

**Comment by ResetButton** [comment]
Problem is here
https://github.com/area17/twill/blob/2.x/views/partials/form/_checkboxes.blade.php
line 42 Arr::pluck($item->$name, 'id')
but value passed from database is like ['1','2', '3'] - not array

**Comment by ResetButton** [comment]
Here is quickfix
replace line 42 with
`value: {!! json_encode(isset($item) && isset($item->$name) ? json_decode($item->$name) : $formFieldsValue) !!}`

**Comment by antonioribeiro** [comment]
Are you casting it? And creating the "id" for it?

``` php
protected $casts = ['mission' => 'array'];

public function getMissionAttribute($value)
{
    return collect(json_decode($value, true))
        ->filter()
        ->mapWithKeys(fn($value) => [$value => ['id' => $value]])
        ->toArray();
}
```

**Comment by ifox** [comment]
Fixed in https://github.com/area17/twill/commit/736a064262bafd4c47b0562136b8a2d859c00ca0.
