### ISSUE TITLE
Form fields error messages are not flashed when validating (still)

### ISSUE THREAD

**Issue by tchapi** [area17/twill#697]
Following https://github.com/area17/twill/issues/605 that I cannot reopen, I did some more testing following https://github.com/area17/twill/commit/fc5b16a9179fcba57d3424ef2456a9efa74ce68f.

The fields are now correctly highlighted as errored (in red) as expected, but the `required` fields do not have any text message:

<img width="1440" alt="Screenshot 2020-04-21 at 16 08 40" src="https://user-images.githubusercontent.com/1944007/79875949-b033eb80-83ea-11ea-8e92-e45883f49161.png">

(In this example, both fields have the `required|alpha_num` requirement)

The return from the API is good though, with the correct error messages:

<img width="568" alt="Screenshot 2020-04-21 at 16 43 16" src="https://user-images.githubusercontent.com/1944007/79879628-3baf7b80-83ef-11ea-983a-174777628fcb.png">

The culprit is in `mixins/inputFrame.js` here : https://github.com/area17/twill/blob/4b61b78e1ab746fbe9975be23993adfd4a6d1391/frontend/js/mixins/inputFrame.js#L58

I don't really understand why you would silence the messages finishing with 'is required.' — that is the bug here. More over, this is quite dangerous since now the UI is localized ...

**Comment by tchapi** [comment]
Let me add that this is still the case in Twill `2.1.0` (latest release as of today)

**Comment by arkid** [comment]
I'm now using Twill 2.1.0 on a site and I don't have this problem on standard fields - I just checked and a simple text field that has required defined in the requests file and it works fine with the custom msg appearing exactly as I'd expect.   Using Laravel 5.8.x still on this particular site.

![Capture](https://user-images.githubusercontent.com/3810108/87673919-4013d800-c743-11ea-8b7a-857369273d36.JPG)

However, to muddy the water somewhat, I can't make error msgs show at all within repeaters.     I don't know if this has always been problematic or is a recent bug?  

I have simple text fields defined in a repeater and I'm positive that my request rules are written correctly.    If I leave these fields blank then correctly the update fails with the red bar msg at the bottom of the page.  However absolutely nothing occurs inline where the problem input field is.  No red msg, no red outline of the field.

**Comment by ifox** [comment]
@tchapi that was a silly product requirement at some point, simply because required is kind of explicit when a field is empty and red, but you're totally right that it is confusing, and that it certainly doesn't work with i18n. Feel free to PR to drop it and I will happily release 2.1.1 with it.

**Comment by ifox** [comment]
@arkid I will need to dig deeper for repeaters validation errors display but it is probably not functional and has never been. It should be possible to implement though, no worries.

**Comment by arkid** [comment]
> @arkid I will need to dig deeper for repeaters validation errors display but it is probably not functional and has never been. It should be possible to implement though, no worries.

Ok thanks @ifox , yes it would be really great to have this (any chance to add to roadmap?!), validation seems only half complete if this isn't possible within repeaters.

**Comment by ifox** [comment]
I'm definitely adding to the roadmap, however backend validation is functional as you described above yourself, saving is prevented. This is a message display issue in the UI. A simpler solution I'm thinking about that could resolve all of our uses cases would be to group all validation errors at the top or bottom of the form, if we are not able to render errors at every single nested field level. But I'm pretty sure we should be able to!

**Comment by arkid** [comment]
The thing with repeaters is that by their definition, they instantly allow a huge amount of content to be added to a form.   So what could otherwise be a very simple form with few fields to manually check suddenly becomes much more likely to be a large form due to repeated elements alone.   Therefore for the user to not see any visual red guide highlighting where within the form the problem is makes it quite unfriendly and hard to resolve the error.    Hopin it can work nested ;)

**Comment by tchapi** [comment]
@arkid yours work because there is no point (`.`) at the end of the sentence 
@ifox let me see how I can fix that quickly !

**Comment by tchapi** [comment]
See https://github.com/area17/twill/pull/699
I'm not sure why the CHANGELOG.md file shows differences, though, I haven't touched it... 🤔

**Comment by ifox** [comment]
Thank you! I guess because your 2.x forked branch is not up to date. You should be able to rebase your PR to clean it up. I think the condition on the blocks field key is still needed, as block validation is handled differently. I'll try it out. Thanks for the quick contribution!

**Comment by tchapi** [comment]
Oh, ok, I didn't know that (for the blocks). I did update from the upstream though, so it's bizarre that there is a difference, but well, sometimes I don't understand git fully.

Do you want to make a clean fork and re-make a PR or are you going to do the change on your own ?

**Comment by ifox** [comment]
No worries, I will rebase it before merging. Thanks again!

**Comment by arkid** [comment]
@ifox messages inside repeaters is still outstanding and on the roadmap ?
