### ISSUE TITLE
Command twill:dev stuck on building assets

### ISSUE THREAD

**Issue by Insperio** [area17/twill#698]
It gets stuck on building assets and never completes. Files don't get updated. 
When I run twill:build it all works fine. 

I think the problem existed before the recent update so it's not a new issue for me. 

Any ideas how to debug this ?

**Comment by tchapi** [comment]
`twill:dev` is meant to launch a development server that watches the files and hot-reloads when one changes, so that you have instant updates. So yes, it never completes, it's a running process, it's .. normal.

**Comment by Insperio** [comment]
Makes sense except like I mentioned the files don't update. 
Am I correct trying to use  `twill:dev` when updating custom vue components?

**Comment by tchapi** [comment]
See https://github.com/area17/twill/blob/2.x/CHANGELOG.md#blocks-and-frontend-build-workflow

**Comment by Insperio** [comment]
Thanks for the help ! I was missing the `dev_mode = true` in twill.php  Once added I had to solve few other problems but eventually it started to work correctly :) Thanks again
