### ISSUE TITLE
Strip out HTML tags in slugify filter

### ISSUE THREAD

**Issue by IllyaMoskvin** [area17/twill#7]
For our website, we implemented the ability to render titles as raw HTML, so that content editors can italicize titles embedded within other titles. However, we noticed that the `formatPermalink` function doesn't strip out HTML tags when generating the slug. Since doing so would not impact projects that do not enter HTML into title fields, I'd like to see the `slugify` filter expanded to strip out HTML tags. 

https://github.com/area17/twill/blob/4d58468db4c2aec3bcbb7ed8c8de3dfb78c5240b/frontend/js/mixins/formatPermalink.js#L27

https://github.com/area17/twill/blob/4d58468db4c2aec3bcbb7ed8c8de3dfb78c5240b/frontend/js/utils/filters.js#L4-L16

I'll submit a PR for this shortly!

**Comment by ifox** [comment]
Closing this as we discussed in #8 that it would prevent urls like `/history-of-the-blink-tag` and @IllyaMoskvin shared a couple possible approaches to give publishers access to html tags in titles. Extensibility of Twill's frontend is on our roadmap, we'll share more about that soon!
