### ISSUE TITLE
[BUGFIX] Sortable <table></table> disappear

### ISSUE THREAD

**Issue by EPInformatyka** [area17/twill#700]
After enabled nested modules [Twill 2.0 & 2.1] table with sortable header will be disappear
In class .datatable__table .table margin-top need 0 or auto
![Zrzut ekranu (209)](https://user-images.githubusercontent.com/53084555/87824857-5bcbcb00-c876-11ea-8a70-b2269ba5f6c2.png)
![Zrzut ekranu (210)](https://user-images.githubusercontent.com/53084555/87824861-5cfcf800-c876-11ea-80c0-0c366a6898eb.png)

@sauron @ifox

**Comment by ifox** [comment]
At the moment self-nested module purposefully hide it because the nested rows do not render more columns as everything would be misaligned, as we can already see on your screenshot with the languages header.
