### ISSUE TITLE
Settings forms are broken in 2.1.0 (with quick workaround)

### ISSUE THREAD

**Issue by marinaglancy** [area17/twill#701]
Two changes in 2.1.0 each broke settings forms in 2.1.0, just posting my solution here hoping it will help somebody else

1. "Skip modal to create records" https://github.com/area17/twill/pull/642
2. "Add self-contained blocks" https://github.com/area17/twill/pull/597

Here is a quick workaround: Copy `vendor/area17/twill/views/layouts/settings.blade.php` to `resources/views/vendor/twill/layouts/settings.blade.php`

Add in line 4 (as a parameter when you extend 'twill::layouts.form'):
`'availableRepeaters' => "''"`

Add after `@push('vuexStore')`:
`window['{{ config('twill.js_namespace') }}'].STORE.publication.createWithoutModal = false`

--
Or just copy this file to `resources/views/vendor/twill/layouts/settings.blade.php`:
[settings.blade.php.txt](https://github.com/area17/twill/files/4941362/settings.blade.php.txt)

**Comment by ifox** [comment]
Thank you so much for sharing your resolution @marinaglancy!

**Comment by marinaglancy** [comment]
Thank you very much, I'm very impressed with your fast reaction. And thanks for tagging it :)
