### ISSUE TITLE
Visual glitch: Dashboard count modules don't seem to wrap if you add more than 6

### ISSUE THREAD

**Issue by adam-jones-net** [area17/twill#707]
It seems if I add more than 6 modules to the dashboard then I get this...

![Capture](https://user-images.githubusercontent.com/3810108/88306832-378a4700-ccd9-11ea-9564-5df8e6a6b18d.JPG)

Can it just be made to wrap onto a second row?   

Also I see that as standard once the screen width reduces to a certain size 6 become 3 which is somewhat arbitrary.   Again at this point it would be much better if they all appear and just wrap into more rows if required.

**Comment by haringsrob** [comment]
Hey @ifox,

Do we need some design input on this?
