### ISSUE TITLE
Saving Image in Settings Page Error

### ISSUE THREAD

**Issue by jeeann02** [area17/twill#711]
**Problem:**
I added a @formField['medias'] in my settings page for my site logo. I have added all the pre-requisite needed to save an image. But, when I clicked the update button, I am getting this error:
![save-image-error](https://user-images.githubusercontent.com/29726609/88534249-43a83880-d03a-11ea-9914-375dbd950db8.png)

I have 2 test projects with twill, one was created last May 2020 and the other one (which was having the error) was created in July 2020.

**Actions Taken:**
1. Duplicate the settings page of the July 2020 Test Project to the May 2020 Test Project. Tested it and everything works so well. No problems encountered.

2. Compare the vendor/area17/twill folders of the 2 projects. Used dump and die to display the $fields in the getMedias function in the HandleMedias file in both projects.
This is the result of the May 2020 Test Project:
![May2020](https://user-images.githubusercontent.com/29726609/88534991-bd8cf180-d03b-11ea-9a52-faabeadaf3f4.png)
This is the result of the July 2020 Test Project:
![July2020](https://user-images.githubusercontent.com/29726609/88535034-d09fc180-d03b-11ea-99c1-5441f1d123de.png)

3. Checked the SettingRepository File of both projects then compared their saveAll Function. I found that when mapping the medias my July 2020 Test Project is using mapWithKeys while my May 2020 Test Project is using map.

I hope this would help.

Thanks!

**Comment by ifox** [comment]
Hi @jeeann02, can you make sure you are running the latest patch version (2.1.1 as of today)? This was a regression introduced in 2.1.0 rapidly fixed in 2.1.1.

**Comment by jeeann02** [comment]
Hi @ifox, it's all good now. Thanks!
