### ISSUE TITLE
Call to undefined method Kalnoy\Nestedset\QueryBuilder::withActiveTranslations()

### ISSUE THREAD

**Issue by IllyaMoskvin** [area17/twill#723]
We are currently using Twill 1.2.2, and we are seeing some 500 errors when we would expect 404 due to this line:

https://github.com/area17/twill/blob/1.2.2/src/Repositories/Behaviors/HandleSlugs.php#L82

The error we are seeing is in the title of the issue; copying it here for reference:

> Call to undefined method Kalnoy\Nestedset\QueryBuilder::withActiveTranslations()

I see that changes have been made to this file since `1.2.2`, and if we use the changes from this commit:

https://github.com/area17/twill/commit/c48ca39632b95c5584df438111f94459ab2c373a

...the error disappears. However, I'm not sure: is this a fix to the issue, or is it just skipping that block of code in our case?

**Comment by Larsklopstra** [comment]
Setting the locale in `app.php` to `en` fixes it...

**Comment by IllyaMoskvin** [comment]
In our case, we did have `locale` set to `en`, so that doesn't seem to have been the cause.

We added a work-around, wherein instead of having our repositories extend `A17\Twill\Repositories\ModuleRepository` directly, we extend an intermediate application-level `ModuleRepository` class that extends Twill's `ModuleRepository`. In there, we added this method:

```php
    /**
     * Temporary work-around for https://github.com/area17/twill/issues/723
     */
    public function safeForSlug($slug, $with = [], $withCount = [], $scopes = [])
    {
        try {
            return $this->forSlug(...func_get_args());
        } catch (BadMethodCallException $e) {
            abort(404);
        }
    }
```

So we use `safeForSlug()` instead of `forSlug()` now. But you could probably just as easily override `forSlug()` and call `parent::forSlug()` in the method. Whichever you prefer. For us, we wanted to make the override explicit.

**Comment by ifox** [comment]
Closing this as the implementation has changed since then, but @IllyaMoskvin feel free to ask to reopen if that is something you still need to do after migrating to 2.x, or if you have any suggestion for improvements.

**Comment by hugomeruma** [comment]
@IllyaMoskvin I had the same issue. It was fixed by setting use_property_fallback to false in the translatable config file.

**Comment by nikhiltri** [comment]
@ifox After upgrading to 2.x we've removed this function and are now using the built-in `forSlug()` method. Thanks for circling back!
