### ISSUE TITLE
Multiple models in browser field

### ISSUE THREAD

**Issue by biosonic** [area17/twill#73]
I have 3 models:
- Article
- Gallery
- Video

My wish is to add list of related Galleries and Videos to each Article, with single browser field.
Is it possible to join multiple related models trough browser field?

**Comment by ifox** [comment]
Hi @biosonic,

glad you ask! It is not possible in 1.2.0, but will be in our next release. @m4n1ok has been working on the frontend changes needed on the browser module and I'm about to integrate.

It is actually already possible to do it using custom (but way too complex) code so if you really need it quickly I can share more about that, let me know.

**Comment by biosonic** [comment]
Thank you very much for your efforts

I realized that I should do some work in Repository::getFormFields and Repository::afterSave (I might be wrong) but I can not figure out how to prepare multiple model content that should appear in the browser. 

You did a great job by adding model selecting drop-list to the buckets in featured content.

many thanks
