### ISSUE TITLE
WYSIWYG height overflows viewport 

### ISSUE THREAD

**Issue by rico** [area17/twill#739]
I have a problem with the the WYSIWYG field height. It always overflows the viewport. In the picture below, I have scrolled to the bottom of the browser window and can't even see the end of the first wysiwyg field. The `rows` option is set to 3.

![image](https://user-images.githubusercontent.com/92818/92629251-574bed80-f2ce-11ea-8288-19471815b5d6.png)

What could be the problem? I'm not loading any custom css into the admin layout - afaik ;-)

**Comment by sauron** [comment]
Hey @rico,
Can you paste the whole `form` view?
We've had a similar issue before and it was caused by a misplaced semicolon `;`.

**Comment by rico** [comment]
@sauron - interesting, thanks for the answer.  Went through the form view and found an extra parenthesis :-)
