### ISSUE TITLE
Failed to updated nested repeaters

### ISSUE THREAD

**Issue by milewski** [area17/twill#74]
Hello i have a nested repeater

whenever i try to update it i get this error:

```
error: {type: "ErrorException", message: "Undefined index: type",…}
file: "/home/vendor/area17/twill/src/Repositories/BlockRepository.php"
line: 34
message: "Undefined index: type"
type: "ErrorException"
``` 

this is my current setup

**admin/regions/form.blade.php**

```php
@extends('twill::layouts.form')

@section('contentFields')
 
    @formField('repeater', ['type' => 'regions'])

@stop

```

**admin/blocks/region.blade.php**

```php
@formField('input', [
    'name' => 'name',
    'label' => 'Name'
])

@formField('repeater', ['type' => 'locations'])
```

any idea what is the cause of the error?

/// edit
i suspect that the nested repeater data is being sent as `blocks:{}...` instead of `repeaters: {}` as if i move the `$fields['repeaters'] = $fields['blocks'];` it seems to work properly but then the "HandleBlocks" trait stop working...

**Comment by ifox** [comment]
Hi @milewski,

nested repeaters are not supported, but I do not see a technical limitation that would prevent us from implementing it. Design-wise it can quickly become messy though.

I guess this is worth adding a note to our docs (as well as improving repeaters documentation as a whole because I know it is a bit weak right now).

**Comment by milewski** [comment]
hi @ifox 

Also `block_editor` is not supported inside repeaters?

```
@formField('block_editor', [
    'blocks' => ['quote']
])
```

this example works outside repeaters but inside i see like this screenshot: 

![image](https://user-images.githubusercontent.com/2874967/48297371-6058b180-e4e1-11e8-8461-1077c141f81f.png)

**Comment by ifox** [comment]
Hi Rafael,

Block editor is not supported inside repeaters, but repeaters are supported in blocks.

I guess a matrix of fields compatibility would be very helpful in our docs! Sorry about the confusion.
