### ISSUE TITLE
Cannot Save

### ISSUE THREAD

**Issue by sgtcoder** [area17/twill#749]
I am getting this error whenever I try to save in the CMS

message: "Argument 2 passed to str_contains() must be of the type string, array given, called in /var/www/domain.com/vendor/area17/twill/src/Repositories/Behaviors/HandleFiles.php on line 65"

**Comment by dan-pascu** [comment]
I have the same issue. It's because probably you are running Laravel 5.8, you updated composer and now it includes the new "symfony/polyfill-php80". 
On twill 1.2 you can't update to Laravel 6 so, what I found, is to add this in your composer, to ignore that package:
"conflict": {
        "symfony/polyfill-php80": "*"
    }
Hope it helps.

**Comment by ptrckvzn** [comment]
Hello, please feel free to reopen this issue and provide a reproducible setup or more information about your environment. Thanks!
