### ISSUE TITLE
[Bug] scopeWithActiveTranslations in HasTranslation trait doesn't respect the use_fallback config

### ISSUE THREAD

**Issue by jandol5** [area17/twill#750]
A comment on use_property_fallback config states *Note that 'use_fallback' must be enabled.*

https://github.com/area17/twill/blob/9ead6d5c588243f2727906799e1d36c22d5c7c3c/config/translatable.php#L61

But line 26 at scopeWithActiveTranslations in HasTranslation trait doesn't respect that

https://github.com/area17/twill/blob/9ead6d5c588243f2727906799e1d36c22d5c7c3c/src/Models/Behaviors/HasTranslation.php#L26

To fix the bug the line 26 should be
```php
if (config('translatable.use_fallback', false) && config('translatable.use_property_fallback', false)) {
```

**Comment by henzeb** [comment]
This sounds like a bug that is translatable related. try here: https://github.com/Astrotomic/laravel-translatable/issues

And when it's fixed there, you can probably just do `composer update astrotomic/laravel-translatable` to get the fix.

**Comment by haringsrob** [comment]
Thank you @jandol5

PR is made for 3.x: https://github.com/area17/twill/pull/1594
