### ISSUE TITLE
Slug bug when publish in listing page

### ISSUE THREAD

**Issue by petertsoisstuff** [area17/twill#756]
I have a model which `HasTranslation` and `HasSlug`.

![Screenshot 2020-10-29 183756](https://user-images.githubusercontent.com/33865429/97654798-b17f5880-1a9e-11eb-8b02-01d4a4c8126e.png)

I created a record with a different title but the same slug. (I edited the slug `testing`, instead of using the auto-generated slug)

Chinese title: `title in Chinese`

English title: `testing in English`

​

![image](https://user-images.githubusercontent.com/33865429/115177051-ee98df00-a100-11eb-9c65-fcefe277dc69.png)

![image](https://user-images.githubusercontent.com/33865429/115177076-fc4e6480-a100-11eb-93df-b8a7643ff738.png)

So far it is working fine.

When I publish/unpublish it on the listing page, it changed the slug to auto-generated slug, which is

Chinese slug: `testing` -> `title-in-chinese`

English slug: `testing` -> `testing-in-english`

**Comment by ptrckvzn** [comment]
Hello, thanks for opening this issue. Please feel free to reopen this issue and provide a reproducible case in order to help you out. Thanks!
