### ISSUE TITLE
[Bug] laravel's create/update methods not working when having slugs

### ISSUE THREAD

**Issue by henze-housepedia** [area17/twill#757]
I'd like to do MyTable::create(['column'=>1]); and similar, but when I use HasSlugs, this breaks....

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'active' cannot be null\

laravel 8 branch... It only works via the Repository

Found out why: translatedAttributes aren't only for translated keys, but also for fields that are in the translated table, like "active"

**Comment by haringsrob** [comment]
Had this issue myself today, If anyone runs into this, you have to mark the model as active or inactive.

$model->active = true/false;
