### ISSUE TITLE
QueryException when running 'twill:install'

### ISSUE THREAD

**Issue by sprklinginfo** [area17/twill#758]
Installed the package to an existing Laravel 7 application from Composer. When running 'php artisan twill:install' command, I saw migrations and config files are copied successfully. Then it asked for an email for Superadmin, after entering a valid email, it threw a QueryException as following:

 SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your
MySQL server version for the right syntax to use near 'where `email` = ?' at line 1 (SQL: select count(*) as aggregate where `email` = xxxx@xxx.com)

MySQL version is  5.7.30. Searched open and closed issues where some mentioned about JSON type was not supported on some MySQL version. But my application also uses JSON type in a couple of tables. so it is not my case. Any idea?

**Comment by ptrckvzn** [comment]
Hello, please feel free to reopen this issue and provide a reproducible setup of more information about your environment. Thanks!
