### ISSUE TITLE
Make the WYSIWYG editor (quill.js) taller?

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#76]
Hi,

I'd like my WYSIWYG editors to be taller, so more text can be seen at once. How do I go about doing this?

Thanks again,
Seb

**Comment by ifox** [comment]
Hi Seb,

it should automatically grow with content. What exactly is happening for you, it scrolls?

**Comment by sebastianlenton** [comment]
I'll tell you what's happening- I didn't test it beyond a couple of lines! Sorry... :)

Looks like I can inject some CSS to make them a bit taller from the get-go, anyway.

Thanks!
