### ISSUE TITLE
[bug] Slug is not saving as active

### ISSUE THREAD

**Issue by ResetButton** [area17/twill#760]
Slug is not saving as active, if you don't tick checkbox http://prntscr.com/vg49xa during item creation

Steps to reproduce (Laravel 6, Twill 2.1.1)
1. Create module with revisions (maybe it is not necessary) 
2. Setup several languages. 
3. If you don't tick checkbox with secondary languages when creating module item, it don't be marked as active in database

**Comment by pboi20** [comment]
Hey @ResetButton,

I'm inclined to think that this is more of a feature than a bug. From my own experience working on multilingual websites, the focus is often on a single language at first and the translations arrive later in the process. Having the primary language active by default supports this workflow. Does this make sense? I curious to know more about your own workflow with multilingual content :)
