### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by richardfeliciano** [area17/twill#763]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - area17/twill 2.x-dev requires guzzlehttp/guzzle ^6.2 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for area17/twill ^2.2 -> satisfiable by area17/twill[2.x-dev].
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].

Fresh new laravel instalation

        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5"

**Comment by talvbansal** [comment]
Laravel 8 support is still being reviewed atm you can follow its progress here:

https://github.com/area17/twill/pull/740

**Comment by sedatsevgili** [comment]
Until updating dependencies for Laravel 8, it seems Laravel version "7.29" fine.

**Comment by ptrckvzn** [comment]
Closing as Laravel 8 and PHP 8 is now supported.
