### ISSUE TITLE
File library greyed out in Firefox

### ISSUE THREAD

**Issue by weissingerh** [area17/twill#764]
Hello! First, thank you for your wonderful CMS, I'm really impressed with it.

I noticed a minor bug in Firefox: The file library seems not to be working correctly. When I click on "Add new" and use the file explorer, all files are greyed out and none could be uploaded to my project. However, when I try to upload files via drag & drop, everything works as expected.

**Comment by ptrckvzn** [comment]
Hi @weissingerh, I've looked into this and I believe you need to populate the "allowed_extensions" in the file library config key in order to allow the types you want selectable. By default, Twill provide an empty array, but adding this to `config/twill.php` works fine in Firefox for me.

```
'file_library' => [
    'allowed_extensions' => ['pdf'],
],
```
