### ISSUE TITLE
Mediables table not being updated when used as a block by block_editor

### ISSUE THREAD

**Issue by milewski** [area17/twill#77]
Hello i have the following:

```php
// some form.blade.php
@formField('block_editor', [
    'blocks' => ['gallery_tab'],
    'withoutSeparator' => true
])

/// gallery_tab.blade.php with the following

@formField('input', [
    'name' => 'tab_title',
    'label' => 'Tab Title'
])

@formField('medias', [
    'name' => 'images',
    'label' => 'Images',
    'note' => 'Minimum image width 1300px',
    'max' => 10,
])
```

![image](https://user-images.githubusercontent.com/2874967/48332763-f4687b80-e68f-11e8-9139-9fe6392919d8.png)

when click save it does not persist the images to db.. only if i dont use it as a `block_editor`.. perhaps medias inside a block is not yet supported?

i have also noticed that it didnt work initially if i didnt add  `$mediasParams` to my model, the docs wasn't clear if that was a requirement.. perhaps this should be optional?

**Comment by ifox** [comment]
Hi Rafael,

As you correctly identified, `$mediasParams` is required as it is letting the model know about fields you'd like to save from your module's form. We could make it optional by providing a default configuration when a `medias` field name is not found in `$mediasParams`, thanks for your suggestion.

It works similarly in blocks, except the `Block` model is living in Twill's codebase which means it's `mediasParams` is controlled through your `twill.php` configuration file, under `crops`.  You can take a look at the default block editor configuration [here](https://twill.io/docs/#default-configuration). I'll admit naming is not consistent here, and documentation is not as straightforward as it should be. So something to improve, definitely!
