### ISSUE TITLE
Is there a way to add/edit formFields?

### ISSUE THREAD

**Issue by jamestylerpatton** [area17/twill#787]
Hello,

There are a few custom fields I would like to add to my admin panel and I was wondering if this would be possible.
 
For example: An uploader (like the medias formField) that can upload videos directly to Vimeo, or a wysiwyg field that allows for custom image handlers so I could use the image field and have them uploaded to Imgur or AWS.

These are both examples where I could handle the upload functionality, I just need to be able to add the fields to my forms.

Thanks!

**Comment by kirkbushell** [comment]
Yeah, there is - check out the documentation around blocks.

**Comment by jamestylerpatton** [comment]
@kirkbushell I'm more asking if it's possible to create an entirely new formField option. 

The reason I need to do this is to extend the wysiwyg formField to change the image handler to upload directly to S3.

Another example might be to extend the 'input' formField but make it so phone numbers are automatically formatted on input. Then it could be used like this:
```blade
@formField('phone', [
    'name' => 'phone',
    'label' => 'Phone Number',
    'required' => true,
    'note' => 'Phone number goes here',
])
```

**Comment by kirkbushell** [comment]
@jamestylerpatton ah, I see. I've been looking into this myself. Unfortunately, there doesn't seem to be any easy way to do this. In fact, I'd go so far as to say I think the system needs a decent plugin architecture to support things like this (and move away from bloody array config everywhere! maybe version 3? lol)

**Comment by razvaniacob** [comment]
I would love to see a way to extend the functionality and to be able to add my custom fields.

**Comment by antonioribeiro** [comment]
[This post](https://spectrum.chat/twill/tips-and-tricks/adding-a-custom-block-to-twill-admin-view-with-vuejs~028d79b1-b3cd-4fb7-a89c-ce64af7be4af) can help you start creating new custom blocks (or fields) using VueJS and Vuex on Twill.

**Comment by jamestylerpatton** [comment]
@antonioribeiro That's exactly what I was looking for, thank you!
