### ISSUE TITLE
File Library upload fails

### ISSUE THREAD

**Issue by milewski** [area17/twill#79]
Hello i have the following env vars:

```
MEDIA_LIBRARY_ENDPOINT_TYPE=local
MEDIA_LIBRARY_LOCAL_PATH=uploads/
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Local

FILE_LIBRARY_ENDPOINT_TYPE=local
FILE_LIBRARY_LOCAL_PATH=files/
FILE_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\FileLibrary\Disk
```

and i get the following error:
![image](https://user-images.githubusercontent.com/2874967/48336563-8de95a80-e69b-11e8-8f82-4e56ded4565b.png)

i have also tried to override the file_library manually on twill.php 

```php
'file_library' => [
    'disk' => 'libraries',
    'endpoint_type' => 'local', ///<------
    'cascade_delete' => env('FILE_LIBRARY_CASCADE_DELETE', false),
    'local_path' => env('FILE_LIBRARY_LOCAL_PATH'),
    'file_service' => A17\Twill\Services\FileLibrary\Disk::class, ///<------
    'acl' => env('FILE_LIBRARY_ACL', 'public-read'),
    'filesize_limit' => env('FILE_LIBRARY_FILESIZE_LIMIT', 50),
    'allowed_extensions' => ['woff'],
],
```

but it somehow is still attempting to connect to S3...

Quickly workaround is to set these env var with dummy values:

```
S3_KEY=ANYTHING
S3_SECRET=ANYTHING
S3_BUCKET=ANYTHING
```

i guess the intended behavior is to work without these env vars if the endpoint is not set to S3.. 

**Second Problem:**

My model uses `HasFiles`, repository uses: `HandleFiles`, and my form.blade.php has

```php
@extends('twill::layouts.form')

@section('contentFields')

    @formField('files', [
        'name' => 'map',
        'label' => 'Map file',
        'note' => 'it needs to be the a proper obj file'
    ])

@stop
```

![image](https://user-images.githubusercontent.com/2874967/48337758-d22a2a00-e69e-11e8-9ce2-5a00a26ccd91.png)

i can pick a file and save it, however it is not persisted to the `fileables` table on db. am i missing some required settings on the model? or somewhere? there is no error and i can see the payload is being sent to the server "correctly": 

![image](https://user-images.githubusercontent.com/2874967/48338177-ef132d00-e69f-11e8-8fd0-8d057cdfe545.png)

> note the aws urls there when i am not using S3 at all..

**Comment by ifox** [comment]
Hi Rafael,

about empty S3 credentials, I've seen that too in the past, it seems like the AWS SDK requires those to be filled, even though you're not using it. It doesn't make any sense, I feel you, and I'll investigate to understand why, and make sure that the SDK provider is only loaded if the S3 endpoint is used.

Regarding your other issue, similarly with #77, the file input requires you to provide the associated model configuration, using `$filesParams`, as documented [here](https://twill.io/docs/#models) under the HasFiles bullet point. A future improvement I identified for our docs: link or repeat documentation next to each form fields.

Finally, about the S3 urls still showing up when you opted for `local` endpoint type, this is definitely not normal, are you sure your configuration cache was cleared?

**Comment by milewski** [comment]
> Finally, about the S3 urls still showing up when you opted for local endpoint type, this is definitely not normal, are you sure your configuration cache was cleared?

yeah looks like it was a config cache issue, after cleaning the cache it is showing relative local paths..

![image](https://user-images.githubusercontent.com/2874967/48686407-cab2d580-ebf6-11e8-941b-175e44cfe610.png)

**Comment by tbrasington** [comment]
> Regarding your other issue, similarly with #77, the file input requires you to provide the associated model configuration, using `$filesParams`, as documented [here](https://twill.io/docs/#models) under the HasFiles bullet point. A future improvement I identified for our docs: link or repeat documentation next to each form fields.

Hi @ifox if you are using files in blocks, do you define $fileParams in twill.php? If so, what do you use to reference it? I have tried `'files'=>['video_file']` `'media'=>['video_file']` `'file'=>['video_file']` but it still isn't saving into the fileables table. No errors either. Any help would be appreciated!

p.s the cms is amazing!

**Comment by tbrasington** [comment]
Thank you very much!
