### ISSUE TITLE
Blocks won't be populated with fields if the block name contains underscores

### ISSUE THREAD

**Issue by dkre** [area17/twill#808]
This could be a broader issue but following the documentation to create a block using underscores in the name of the block will result in the block being available on the model but the fields won't be populated.

Eg. Twill config (twill.php)

`'twocol' => [
    'title' => 'Two Column Block',
    'icon' => 'text',
    'component' => 'a17-block-twocol',
],
'full_breakout' => [
    'title' => 'Full Breakout',
    'icon' => 'image',
    'component' => 'a17-block-full-breakout',
],
`

twocol will show fields as defined in it's blade file: twocol.blade.php but full_breakout (full_breakout.blade.php) will be blank with no fields on the model form.

**Comment by ptrckvzn** [comment]
Hi @dkre, thanks for reporting the issue. We noted this regression on branch 2.x and we're working to fix the issue (#813). You can test this PR and let us know if that fixes your issue – we hope to merge it soon. I will close this for now, but feel free to re-open this if you need to.
