### ISSUE TITLE
How to render browser fields inside blocks on the frontend?

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#82]
Hi,

I have some browser fields inside blocks. All is working on the backend but I can't work out how to access and render the models added via the browser fields on the frontend, inside my block views.

Any help would be much appreciated- my code is at https://github.com/sebastianlenton/twill-test if that helps.

Thanks again,
Seb

**Comment by ifox** [comment]
Hi Seb,

this use case really needs some documentation, sorry about that.

There is a helper on blocks to retrieve the list of ids added to a browser:

```php
$block->browserIds('browserFieldName')
```

From there, you can retrieve the corresponding model records, using something like this for example:

```php
@php
  $tagsIds = $block->browserIds('projecttags');
  $tags = app(\App\Models\Projecttag::class)->find($tagsIds);
@endphp
```

**Comment by sebastianlenton** [comment]
Thanks- got it working. This is very helpful!
