### ISSUE TITLE
Pass related modal instance for blocks in form preview

### ISSUE THREAD

**Issue by jgulledge19** [area17/twill#823]
I am new to Twill and have been building out some pages. I have a simple field on the main model, called theme_class. This is a simple select for the user to select a predefined CSS class, the options presented are Gold, Rose, Blue, ect. I am then using Blocks to allow for easy visual edits. When in the Editor the preview iframe per block needs to have that option for the `resources/views/site/layouts/block.blade.php`. My template for the related code looks like this:

```html
<div id="page" class="{{ $item->theme_class ?? 'rose' }}">
    @yield('content')
</div>
```

It looks like the controller that does the rendering: `A17\Twill\Http\Controllers\Admin\BlocksController.php::preview()` only sends the Block to that view, no other data, or I am missing something?

It would be ideal to have the full related object when rendering a block preview.

Thanks for reviewing!

**Comment by ptrckvzn** [comment]
Hello @jgulledge19, have you tried to use the block relationship to its parent. Something like this would get you the item it is linked to:

```
{{ $block->blockable->theme_class }}
```

If you're editing a new item, the value of `theme_class` might not have been saved and might not be accessible, but if your `theme_class` is set in the modal when creating the item, I believe it might already be saved and available.

**Comment by ptrckvzn** [comment]
@jgulledge19 I will close this one as it is an issue that was raised here. https://github.com/area17/twill/issues/797
