### ISSUE TITLE
File/media upload handled differently

### ISSUE THREAD

**Issue by kirkbushell** [area17/twill#829]
I'm not entirely sure what's going on here, but effectively what's happening is that media uploads work fine, but when files are uploaded, it seems to append the bucket to the domain when using a custom endpoint, ie:

`S3_ENDPOINT=https://mydomain.nyc3.digitaloceanspaces.com`

The requests for file uploads work fine (it uploads the file). It's the subsequent request posting to the server to save the files that fails:

`Error executing "ListObjects" on "https://mydomain.mydomain.nyc3.digitaloceanspaces.com`

I have tried all sorts of configuration changes and updates, all to no avail.

Any ideas?

**Comment by antonioribeiro** [comment]
Endpoint is not being handled/changed by Twill, so you probably need to check what Laravel or Flysystem does with it: https://flysystem.thephpleague.com/v1/docs/adapter/aws-s3-v3/

**Comment by kirkbushell** [comment]
So there's definitely something weird here - I'm using Digital Ocean's spaces, and the configuration I use on another project, does not work when using Twill. Ie.:

```
S3_KEY=ASDFLKJSDF
S3_SECRET=SECRET
S3_BUCKET=bucket
S3_REGION=nyc3
S3_ENDPOINT=https://nyc3.digitaloceanspaces.com
```

This does not work in twill, but works normally otherwise. I think it has something to do with the configuration management twill is doing to manage filesystems, and honestly I'm not entirely sure why it does that. 

Now, I CAN get this to work for media, but not files, by adding my bucket to the endpoint, such as:

> S3_ENDPOINT=https://bucket.nyc3.digitaloceanspaces.com

But then I'm back at the problem - media works, files do not. It's really bizarre.

**Comment by ifox** [comment]
Hi guys, this is all due to this change https://github.com/area17/twill/commit/5894ccce4c4a8dd0e60b3583c6fa3069d1119640. See this comment: https://github.com/area17/twill/commit/5894ccce4c4a8dd0e60b3583c6fa3069d1119640#r40789394 and pull request: https://github.com/area17/twill/pull/703. My suggestion to avoid a breaking change but officially support DO Spaces would be to add a new config property `endpoint_interpolation` that defaults to `false`. This would let the `s3Endpoint` helper do what it currently does to support Minio locally (which was the intention of that change initially from @schaschjan) while allowing the option to be set to `true` for DO Spaces support. Any suggestions? I'm not fully convinced that this is the right change.

**Comment by kirkbushell** [comment]
Thanks for the clarification, @ifox - that certainly looks like it would be it.

The config idea is an interesting one, and agreed not sure it's the right idea. That said, because that helper checks for function existence first, I think for now I'll just implement my own to resolve it. Hopefully we get a long-term solution soon :)

**Comment by kirkbushell** [comment]
Yup, just implemented the function myself - thank you SO MUCH @ifox !!! That was a rough day. haha

This definitely needs to be fixed, it needs to be smarter. Basically, if the endpoint does not contain the bucket, add it - else return as-is. Happy to create a PR if needs be.

**Comment by antonioribeiro** [comment]
What do you guys think about making it full custom?

``` php
function s3Endpoint($disk = 'libraries')
{
    $config = config("filesystems.disks.{$disk}");

    // parse the custom endpoint or use the internal one
    $endpoint = parse_url(
        $config['endpoint']
        ?? Storage::disk($disk)->getAdapter()->getClient()->getEndpoint()
    );

    // an optional scheme can be set via config or extracted from the endpoint
    $scheme = $config['scheme'] ?? $endpoint['scheme'] ?? '';

    // suffixing with scheme is optional
    $scheme = $config['prefix_with_scheme'] ?? true
              ? "$scheme://"
              : '';

    // prefixing with bucket is optional
    $prefix = $config['prefix_with_bucket'] ?? true
              ? $config['bucket'] . '.'
              : '';

    // if a custom host is not set, use the one from the endpoint
    $host = $config['host'] ?? $endpoint['host'];

    // suffixing with root is optional
    $suffix = prefixWithSlash(
        ($config['suffix_with_root'] ?? false)
            ? $config['root']
            : ''
    );

    // endpoint may contain a path, suffix with it
    $path = prefixWithSlash(
        ($config['suffix_with_path'] ?? true)
            ? $config['path'] ?? $endpoint['path']
            : ''
    );

    // build the final URL
    return $scheme . $prefix . $host . $suffix . $path;
}
```

Max drive config:

``` php
'media_library' => [
    'driver' => 's3',
    'key' => env('AWS_ACCESS_KEY_ID'),
    'secret' => env('AWS_SECRET_ACCESS_KEY'),
    'region' => env('AWS_DEFAULT_REGION'),
    'bucket' => env('AWS_BUCKET'),
    'url' => env('AWS_URL'),
    'endpoint' => env('AWS_ENDPOINT'),
    'prefix_with_scheme' => env('AWS_PREFIX_WITH_SCHEME', true),
    'prefix_with_bucket' => env('AWS_PREFIX_WITH_BUCKET', true),
    'suffix_with_root' => env('AWS_SUFFIX_WITH_ROOT', false),
    'suffix_with_path' => env('AWS_SUFFIX_WITH_PATH', false),
    'host' => env('AWS_HOST'),
    'path' => env('AWS_PATH'),
    'scheme' => env('AWS_SCHEME', 'https'),
    'root' => env('AWS_ROOT', ''),
],
```

Minimal `.env` config:

``` 
AWS_ACCESS_KEY_ID=key_aws
AWS_SECRET_ACCESS_KEY=secret_aws
AWS_DEFAULT_REGION=region_aws
AWS_BUCKET=bucket_aws
AWS_ENDPOINT=https://endpoint.aws.com/path_aws
```

Results in 

```
https://bucket_aws.endpoint.aws.com
```

Max `.env` config

```
AWS_ACCESS_KEY_ID=key_aws
AWS_SECRET_ACCESS_KEY=secret_aws
AWS_DEFAULT_REGION=region_aws
AWS_BUCKET=bucket_aws
AWS_ENDPOINT=https://endpoint.aws.com/path_aws
AWS_ROOT=custom-root/
AWS_HOST=custom-host.com
AWS_PATH=custom-path
AWS_SCHEME=tftp
AWS_PREFIX_WITH_SCHEME=true
AWS_PREFIX_WITH_BUCKET=true
AWS_SUFFIX_WITH_ROOT=true
AWS_SUFFIX_WITH_PATH=true
```

Results in 

```
tftp://bucket_aws.custom-host.com/custom-root/custom-path
```

Turning scheme, bucket and root off:

```
custom-host.com/custom-path
```

**Comment by kirkbushell** [comment]
That honestly feels like overkill and really over-complicated. The issue is really just whether or not the bucket needs to be included. If an endpoint is provided, and the bucket has not been included as part of the URL, add it. Else leave as-is.

Alternatively, craft an endpoint by using something like an S3_ENDPOINT_DOMAIN env variable, and can construct an endpoint from that + the bucket?

**Comment by kirkbushell** [comment]
This is the solution I went with (updated based on recent discussions):

```
function s3Endpoint($disk = 'libraries')
{
    $endpoint = parse_url(config("filesystems.disks.{$disk}.endpoint"));
    $bucket = config("filesystems.disks.{$disk}.bucket");

    if (strpos($endpoint['host'], $bucket) !== 0) {
        $endpoint['host'] = "$bucket.{$endpoint['host']}";
    }

    $endpoint['scheme'] .= '://';

    return implode('', $endpoint);
}
```

**Comment by antonioribeiro** [comment]
I agree it's a lot, but the problem is that these S3 "API compatible" storage (Scaleway is another one) are popping up like rabbits now, and they are never 100% aligned to AWS, so we will end up having a new one, that has a slightly different URL structure, which will end up becoming a new ticket/change.
