### ISSUE TITLE
Add twill:update to docs

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#830]
I believe it would be nice to have this (needs more phrasing of course):

``` json
"post-autoload-dump": [
    ...
    "@php artisan twill:update --ansi"
],
```

For the `composer.json`, as part of the install process in the docs. As people may now know when they get a new Twill version that requires to update the frontend.

**Comment by haringsrob** [comment]
Added this in https://github.com/area17/twill/pull/1593
