### ISSUE TITLE
Document "related" relationships

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#831]
I believe we have no documentation for

``` php
$this->updateRelatedBrowser($object, $fields, 'posts');
$this->saveRelated(...);
$this->getFormFieldsForRelatedBrowser($object, 'posts')
```

**Comment by pboivin** [comment]
The docs now have an example using the new `$relatedBrowsers` property:
https://twill.io/docs/#using-browser-fields-as-related-items
