### ISSUE TITLE
Add position ordering for browsers to docs

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#832]
I believe the `orderBy()` is necessary to make browsers to show them in the proper position:

``` php
public function sectors()
{
    return $this->belongsToMany('App\Models\Sector')
        ->orderBy('post_sector.position');
}
```

**Comment by haringsrob** [comment]
Hey @antonioribeiro,

I was checking this, but I feel that I cannot find a use case for this.

A browser can refer to an external entity. But that can be referred to multiple times, so if we would store/use that position updating other models would constantly overwrite each other.

Or maybe I am missing something here?

**Comment by adam-jones-net** [comment]
@haringsrob - this is really needed in the documentaiton, I spent a long time trying to work this out.  I'm using a browser field outside of blocks and getting it to read the order in the position value of the database when the form rendered was the last piece of the puzzle

**Comment by ifox** [comment]
This is now in the docs here: https://twillcms.com/docs/form-fields/browser.html#content-using-a-custom-pivot-table
