### ISSUE TITLE
Change admin panel language?

### ISSUE THREAD

**Issue by Pepino483** [area17/twill#833]
How can i change UI language? When i open /lang dir i see lot of langs but in user settings i see only few:

![image](https://user-images.githubusercontent.com/1336233/116775359-f2aef000-aa62-11eb-8c9b-94fb13d1bbfc.png)

PS: I know that change directly in DB it possible

**Comment by antonioribeiro** [comment]
On `config/twill.php`: 

``` php
return [
    ...

    'available_user_locales' => ['en', 'pt-BR', 'de'],
]
```
