### ISSUE TITLE
Missing icons after commit 5ff29afe

### ISSUE THREAD

**Issue by daun** [area17/twill#834]
Looks like commit [5ff29afe](https://github.com/area17/twill/commit/5ff29afee21d2a46a8112b30b746ea4855c2651e) broke SVG sprites by using the `asset()` helper which always prepends the domain name, thus breaking the local file path required for inlining svg sprites.

**Comment by ifox** [comment]
Thanks for catching and reporting this @daun. Stay tuned for the release next week! 🙂
