### ISSUE TITLE
Components not respecting the "readonly" option

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#836]
It's not possible to make these components "readonly":

```
Browser
Radio
Checkbox
Image
Select
DatePicker
```

Also relates to https://github.com/area17/twill/issues/435

**Comment by haringsrob** [comment]
In https://github.com/area17/twill/pull/1439 I have done most.

I am not sure about browsers disable. Because we will have to disable every action except for the expand/collapse.

Perhaps we can just add a `pointer-events: none;` to the expanded content + hide the delete/clone?

**Comment by ifox** [comment]
You meant blocks, right?

**Comment by haringsrob** [comment]
No, I meant browsers as is described in the issue.

**Comment by ifox** [comment]
Expand/Collapse are blocks features, I'm confused 😅

On a browser field, we would need to disable/hide the add button

**Comment by ifox** [comment]
I think I gotcha. You meant expand/collapse as the button that opens the modal? I think we can prevent opening the modal entirely if the field is disabled.

**Comment by haringsrob** [comment]
Yea, but the point might be to be able to see the browser data but not modify it.

(just to give an example, an "order" entity with "products")
