### ISSUE TITLE
Frontend does not allow to input medias/files simultaneously 

### ISSUE THREAD

**Issue by milewski** [area17/twill#88]
Hey sorry just found another bug:

I have 1 `@formField('medias')` and one `@formField('files')` on a `form.blade.php` whenever i try to add both content i get an runtime error, i can only add 1 or the other at time by saving and refreshing the page before adding the other..

![image](https://user-images.githubusercontent.com/2874967/48697940-d74c2380-ec20-11e8-8505-cf32fccef77a.png)

![image](https://user-images.githubusercontent.com/2874967/48697910-c4d1ea00-ec20-11e8-8ad8-1fed8ba3d582.png)

**Comment by ifox** [comment]
Hi @milewski,

This was fixed by @yanhao-li in #72, we will be release a new version this week.
