### ISSUE TITLE
Part of the Block Editor's dropdown menu will be hidden and unable to scroll in some context.

### ISSUE THREAD

**Issue by yanhao-li** [area17/twill#89]
Under some context (for instance, very small height window), when clicked the Add Content button, the dropdown menu may be displayed underneath the button, there will be chances that part of the menu's options area hidden and unable to scroll to reveal them.

**Comment by ifox** [comment]
@mrdoinel @m4n1ok very small height window is not necessarily something we need to solve, however this came from a client using Firefox 63 on Windows.

In the following screenshot, you'll notice the publisher module alignments are quite off, and the add content dropdown is not using available space on the top and prevents users from selecting blocks at the end of the list.

![firefox_63_windows_ui_issues](https://user-images.githubusercontent.com/708498/48738111-f1383700-ec1d-11e8-9410-eabca74a270c.png)

**Comment by haringsrob** [comment]
Closing as per follow up of https://github.com/area17/twill/pull/1464
