### ISSUE TITLE
Document a17-fieldset 

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#902]
## Add to docs

There's no reference on docs to the prop `:open="false"` on the docs, not sure if there's any other prop that could be documented.

**Comment by haringsrob** [comment]
<img width="860" alt="Screenshot 2022-02-07 at 09 02 41" src="https://user-images.githubusercontent.com/866743/152748286-e348a2b7-791a-406d-a308-60f72fe34e79.png">

I think we never really document the Vue components.

But instead, I have added the option the blade directive + documented this.

See https://github.com/area17/twill/pull/1420
