### ISSUE TITLE
[BUG] capsule:make without translations with revisions throws an error

### ISSUE THREAD

**Issue by devingray** [area17/twill#905]
## Description

Running `php artisan twill:make:capsule pages` creates a folder in `Twill/Capsules`

I then add 

```
'pages' => [
                'title' => 'Pages',
                'module' => true
            ]
```

And 

```
'capsules' => [
                    'list' => [
                        [
                            'name' => 'Pages',
                            'enabled' => true
                        ]
                    ]
                ]
```

And Migrate

Navigating to the Pages section in the CMS throws the following error

```
Call to undefined method App\Twill\Capsules\Pages\Models\Page::getCapsuleRevisionClass()
```

### Expected result

To Get to the index

### Actual result

```
Call to undefined method App\Twill\Capsules\Pages\Models\Page::getCapsuleRevisionClass()
```

### Versions

Latest *

**Comment by antonioribeiro** [comment]
Hey @devingray , 

Thanks for reporting it.

I could not reproduce it doing it from scratch answering "yes" to all questions. What were your answers?

Cheers!

**Comment by ifox** [comment]
From our chat on Discord:

![CleanShot_2021-05-17_at_14.47.592x.png](https://user-images.githubusercontent.com/708498/118454672-ea101800-b6f8-11eb-91e5-7e95737ee8f6.png)

**Comment by devingray** [comment]
```
  -B, --hasBlocks
  -T, --hasTranslation
  -S, --hasSlug
  -M, --hasMedias
  -F, --hasFiles
  -P, --hasPosition
  -R, --hasRevisions
```

Using the above, the command can be 

```
php artisan twill:make:capsule pages -S -M -F -R
```
