### ISSUE TITLE
Field value change is slow in block editor with large amount of elements

### ISSUE THREAD

**Issue by dioned** [area17/twill#910]
## Description

Hi. We have questionnaire page that has complex dynamic structure. We using repeaters for pages, each page has browser and it's possible to have large number of conditional nested repeaters with static fields. When page gets large ( 40+ pages, 1k+ fields total on page ), clicking to change any value in any type of field takes few seconds.

### Steps to reproduce

To reproduce, you have to create few nested repeaters with large amount of fields. More fields are added to the page, slower value change will become, as if emitted change reevaluates every field with new value.
I have attached a zip file of views/admin folder with questionnaire form and all blocks and repeaters
[admin.zip](https://github.com/area17/twill/files/6501514/admin.zip) for reference

### Expected result
It will be great if value change was faster with large amount of fields on page.
### Actual result
When page gets large ( 40+ pages, 1k+ fields total on page ), clicking to change any value in any type of field takes few seconds.
### Versions
Twill: 2.1.1
Laravel version: 7.30.4
PHP version: 7.3.15
Database engine: InnoDb

**Comment by vplotvinov** [comment]
Hello! Same for me. Do you have any fixes for this?

**Comment by vplotvinov** [comment]
Goi it, nice fix but not for me. I found a problem with front-end of Vue components **LocaleField**. That field rendered inputs by each language. For me, it's working very slowly. 

For example, I have a block with 10 inputs and 24 languages that are equal to 240 inputs for a single block... 10 blocks on pages, and this 2400 inputs... My chrome trying not dead when I edit the page and try to switch language. I will try to find another way to fix it, thank you for sharing details and your widgets (I found columns and want's to use it in my blocks too)

**Comment by ifox** [comment]
Should be fixed by #1350.

**Comment by michaeljcoyne** [comment]
It is still quite slow for me, And memory size is gigatic - often the page will freeze.

**Comment by michaeljcoyne** [comment]
This has helped with the field changes - however saving is still pretty slow. Not sure if it is a related issue.
