### ISSUE TITLE
[Question] How to customize WYSIWYG in Block Editor

### ISSUE THREAD

**Issue by noxify** [area17/twill#92]
Hi,

while testing the new version of twill I tried to update the existing toolbar.

My configuration for the block editor is the following (`config/twill.php`):
 ```
<?php

return [

    'block_editor' => [
        'blocks' => [
            'text' => [
                'title' => 'Body text 1',
                'icon' => 'text',
                'component' => 'a17-block-wysiwyg',
            ],
            'image' => [
                'title' => 'Image',
                'icon' => 'image',
                'component' => 'a17-block-image',
            ]
        ]    
    ]
];
```

I created a simple module, the `form.blade.php` is the following:

```
@extends('twill::layouts.form')

@section('contentFields')
    @formField('input', [
        'name' => 'description',
        'label' => 'Description',
        'maxlength' => 100
    ])

    @formField('wysiwyg', [
        'name' => 'description',
        'label' => 'Description',
        'toolbarOptions' => [ [ 'header' => [1, 2, false] ], 'list-ordered', 'list-unordered', [ 'indent' => '-1'], [ 'indent' => '+1' ] ],
        'maxlength' => 200,
        'editSource' => true,
    ])

    @formField('block_editor')
@stop

```

As you can see, i have modified the `@formField('wysiwyg')` and the changes are shown correctly.
But if the wysiwyg field is part of the block editor, I can't see a option to do this.

Changing the `config/twill.php` to this doesn't worked (in my tests):

 ```
<?php

return [

    'block_editor' => [
        'blocks' => [
            'text' => [
                'title' => 'Body text 1',
                'icon' => 'text',
                'component' => 'a17-block-wysiwyg',
                'toolbarOptions' => [ [ 'header' => [1, 2, false] ], 'list-ordered', 'list-unordered', [ 'indent' => '-1'], [ 'indent' => '+1' ] ],

            ],
            'image' => [
                'title' => 'Image',
                'icon' => 'image',
                'component' => 'a17-block-image',
            ]
        ]    
    ]
];
```

Did I missed something? 

Thanks!

Tested with:
* Homestead (with mySQL)
* Laravel 5.7.15
* Twill 1.2.0

**Comment by noxify** [comment]
Hi @ifox,

thanks for your feedback.

Are there some reserved words for the blocks?
I mean, can I create a block with the name `wysiwyg` ? If I understood it correctly, the `component` name will be `a17-block-wysiwyg` and then, for my understanding, the existing block will be overwritten.

Or is there some "magic" which knows what is a `core` component and what is a `custom` component?

**Comment by ifox** [comment]
You can create a block with the name `wysiwyg`, for sure, it will be preferred over the existing one.

**Comment by ifox** [comment]
Not sure I'm following you. Why would you need to use the existing `a17-block-wysiwyg` if you create your own block that include a WYSIWYG field with more styling options? Maybe to have 2 different blocks with a WYSIWYG but with different styling options? You could create your own 2 blocks to do that too, or like you said, keeping the existing one and adding another one with a different name. In the end, that component name is just technical glue, in the UI you can give each block a title that makes sense to your CMS users.

**Comment by noxify** [comment]
Hi, 

Maybe my wording was not the best, here a new try :)

Twill comes with some ready-to-use Block components (for me, they are `core` components).
One of them is `a17-block-wysiwyg`.

When I create a new component (for me they are `custom` components) they can have the same name. 
Example: creating a new component with the name `wysiwyg` will be also accessible via `a17-block-wysiwyg`. 

For me, it sounds like that I can overwrite existing `core` components with this. (Tbh, I have no clue, if the used code from this component is used somewhere else or not)

But I think I have overcomplicated this case - just creating my custom block with a custom name and adding the form inside the form should solve everything.

My main question is answered already and the solution makes sense and keeps the config and everything clean and small :)

Thanks again for your fast feedback!

**Comment by helloiamlukas** [comment]
Hey @ifox 
First of all thank you for the awesome work, have been working with Twill now for quite some time and love it!

Right now I'm struggling a bit with the custom block editor. I did everything exactly like you described [in your first answer](https://github.com/area17/twill/issues/92#issuecomment-442658086) and with your example it works out fine. But as soon as I want to modify the parameters, I can't get it to work anymore 🤔


For Example, if I set the `toolbarOptions` parameter like this:
```
@formField('wysiwyg', [
    'name' => 'content',
    'label' => 'Text',
    'toolbarOptions' => [ [ 'header' => [1, 2, false] ], [ 'font' => [] ], 'link', [ 'align' => [] ] ],
    'maxlength' => 200,
    'editSource' => true,
])
```
No alignment Icon will be shown, the dropdown is also empty.
<img width="435" alt="" src="https://user-images.githubusercontent.com/15997450/54049843-fe356200-41dd-11e9-9fce-63b4771a5850.png">

The same also happens with other attributes like `color` or `background`.

What am I doing wrong? Thank you in advance 🙂

**Comment by adelinferaru** [comment]
Hi @helloiamlukas ! Have found what was the issue? I am currently struggling as well to have the toolbar buttons to display. Quill.js docs explain it pretty straightforward ... but some buttons like "align", "color", "background" do not show on TWILL.

```
'toolbarOptions' => [
                "bold", "italic", "underline", "strike","blockquote", "code-block",
                ["header" => [2, 3, 4, 5, 6, false]],
                ["list" => "ordered"],  ["list" => "bullet"],
                ["indent" => "-1"], ["indent" => "+1"],
                ["size" => ["small", false, "large", "huge"]],
                "link", "image", "video",
                ["color" => []],
                ["background" => []],
                ["align" => []],
            ],
```

**Comment by helloiamlukas** [comment]
@adelinferaru No, I still haven't found out why this isn't working unfortunately...

**Comment by m4n1ok** [comment]
Hello @helloiamlukas, @adelinferaru. 
There are some conflit between Quill default style and our custom styles. Default buttons should be definitely present. I'm currently working on that. I will open a PR soon.

**Comment by mcylinder** [comment]
@ifox 

> Hi @noxify,
> 
> the `a17-block-wysiwyg` component is provided by default in the block editor, but it is not intended to be customized directly. I do like the way you tried to though, and might think about implementing that support.


Would it be possible to include a plugin option used by Quill.js ? Specifically I'm trying to incorporate
https://github.com/kensnyder/quill-image-resize-module

Maybe something like...
```
@formField('wysiwyg', [
    'name' => 'case_study',
    'label' => 'Case study text',
    'toolbarOptions' => [ [ 'header' => [1, 2, false] ], 'list-ordered', 'list-unordered', [ 'indent' => '-1'], [ 'indent' => '+1' ] ],
    'modules' => ['imageResize' =>[]]
  ])
```

**Comment by nikhiltri** [comment]
Hey @ifox,

Looping into this thread because we're hoping to customize Quill's behavior in our WYSIWYG editor. What we'd like to do is use Quill's `text-change` hook to inject some formatting to the display of the text in the editor in the CMS, but I don't see a way to access the quill object and add to it. We have a number of custom blocks, but it's the `<a17-wysiwyg>` Vue component that we'd want to customize. 

Even though it seems like an anti-pattern, I'm not sure how we could make a copy Twill's WYSIWYG component to add a few lines of code to it. Since `npm run twill-build` copies code back into the `area17/twill` vendor folder, and only deals with the custom blocks, we'd need a way copy overrides of Twill components. I've tried a few ways to do this but haven't been able to.

Any thoughts on approaches we could take?

Thanks!
nikhil

**Comment by dacastro4** [comment]
Do we have another issue or discussion regarding the customization of the WYSIWYG component? I'm having a similar issue where I have to customize or add more modules to Quill.
