### ISSUE TITLE
Unresolvable dependency resolving [Parameter #1 [ <required> string $manifestPath ]] in class BladeUI\Icons\IconsManifest

### ISSUE THREAD

**Issue by ozgurkaragoz** [area17/twill#943]
## Description

Hi, i want use https://github.com/blade-ui-kit/blade-icons and "twill" packages together. But when i run "composer require blade-ui-kit/blade-icons" command this error occurs:

```
In Container.php line 1067:
                                                                               
Unresolvable dependency resolving [Parameter #1 [ <required> string $manifestPath ]] in class BladeUI\Icons\IconsManifest
```

No error occurs when I installed "twill" or "blade-ui-kit/blade-icons" alone.

### Steps to reproduce

composer require area17/twill
composer require blade-ui-kit/blade-icons

### Versions

Twill version:  2.2.1
Laravel version: 8.43.0
PHP version: 7.4

**Comment by Andreas-Halemba** [comment]
did u run `php artisan vendor:publish --tag=blade-icons` ?

**Comment by ozgurkaragoz** [comment]
I found the update causing this problem: https://github.com/area17/twill/commit/f0b9bf12f4ac5e212c33c9206fbf6b2d57a5e9ef 

When I revert this commit on local (for temporary as manually) it's work!

**Comment by ozgurkaragoz** [comment]
> did u run `php artisan vendor:publish --tag=blade-icons` ?

yes, but this command doesn't work anyway because the "blade-ui-kit/blade-icons" package could not be installed.
