### ISSUE TITLE
Users management

### ISSUE THREAD

**Issue by awgul** [area17/twill#95]
Hey,

I've just started to use Twill.
I wanted to test User Management.

So I added a User with Disabled option.
Now I can't change it to Active.
I can't add another user.

Just nothing happens, no warnings etc.

I just have only 1 User that is Disabled and I can move it to Trash.

**Comment by ifox** [comment]
Hi @awgul!

Activating a user sends an email out for that user to choose password. You should check your application's mail configuration. If you set your MAIL_DRIVER .env variables to log you can see the content of that email in your logs.

We should definitely work on adding an appropriate error message when this is failing.

Regarding not being able to add another user, that's definitely not normal. Anything in your logs when you try that?

**Comment by AlexandrDolzhikov** [comment]
Hello) I have this problem to. When i edit user, i got message in bottom of the screen:

> Your submission could not be validated, please fix and retry.

My setting - `MAIL_DRIVER=smtp`.
After that i got Error in `log`:

`[2018-12-07 08:39:48] local.ERROR: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
" {"userId":1,"email":"workcomputer199612@gmail.com","exception":"[object] (Swift_TransportException(code: 530): Expected response code 250 but got code \"530\", with message \"530 5.7.1 Authentication required
\" at /home/alexandr/Projects/CMS/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457)
[stacktrace]
#0 /home/alexandr/Projects/CMS/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('530 5.7.1 Authe...', Array)
#1 /home/alexandr/Projects/CMS/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('MAIL FROM:<hell...', Array, Array, false, NULL)
#2 /home/alexandr/Projects/CMS/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(390): Swift_Transport_EsmtpTransport->executeCommand('DATA\
\
', Array, Array)
#3 /home/alexandr/Projects/CMS/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(497): Swift_Transport_AbstractSmtpTransport->doDataCommand(Array)
#4 /home/alexandr/Projects/CMS/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(516): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'hello@example.c...', Array, Array)
#5 /home/alexandr/Projects/CMS/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'hello@example.c...', Array, Array)
#6 /home/alexandr/Projects/CMS/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(479): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(259): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(65): Illuminate\\Mail\\Mailer->send(Object(Illuminate\\Support\\HtmlString), Array, Object(Closure))
#10 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(144): Illuminate\\Notifications\\Channels\\MailChannel->send(Object(A17\\Twill\\Models\\User), Object(A17\\Twill\\Notifications\\Welcome))
#11 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(103): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(A17\\Twill\\Models\\User), 'a72e43cf-b0e3-4...', Object(A17\\Twill\\Notifications\\Welcome), 'mail')
#12 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#13 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(105): Illuminate\\Notifications\\NotificationSender->withLocale(NULL, Object(Closure))
#14 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(77): Illuminate\\Notifications\\NotificationSender->sendNow(Object(Illuminate\\Database\\Eloquent\\Collection), Object(A17\\Twill\\Notifications\\Welcome))
#15 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(42): Illuminate\\Notifications\\NotificationSender->send(Object(Illuminate\\Database\\Eloquent\\Collection), Object(A17\\Twill\\Notifications\\Welcome))
#16 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send(Object(A17\\Twill\\Models\\User), Object(A17\\Twill\\Notifications\\Welcome))
#17 /home/alexandr/Projects/CMS/vendor/area17/twill/src/Models/User.php(108): A17\\Twill\\Models\\User->notify(Object(A17\\Twill\\Notifications\\Welcome))
#18 /home/alexandr/Projects/CMS/vendor/area17/twill/src/Repositories/UserRepository.php(60): A17\\Twill\\Models\\User->sendWelcomeNotification('385e56fdb88f2c6...')
#19 /home/alexandr/Projects/CMS/vendor/area17/twill/src/Repositories/UserRepository.php(52): A17\\Twill\\Repositories\\UserRepository->sendWelcomeEmail(Object(A17\\Twill\\Models\\User))
#20 /home/alexandr/Projects/CMS/vendor/area17/twill/src/Repositories/ModuleRepository.php(179): A17\\Twill\\Repositories\\UserRepository->afterSave(Object(A17\\Twill\\Models\\User), Array)
#21 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): A17\\Twill\\Repositories\\ModuleRepository->A17\\Twill\\Repositories\\{closure}(Object(Illuminate\\Database\\MySqlConnection))
#22 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\\Database\\Connection->transaction(Object(Closure), 3)
#23 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\\Database\\DatabaseManager->__call('transaction', Array)
#24 /home/alexandr/Projects/CMS/vendor/area17/twill/src/Repositories/ModuleRepository.php(180): Illuminate\\Support\\Facades\\Facade::__callStatic('transaction', Array)
#25 /home/alexandr/Projects/CMS/vendor/area17/twill/src/Http/Controllers/Admin/ModuleController.php(279): A17\\Twill\\Repositories\\ModuleRepository->update('2', Array)
#26 [internal function]: A17\\Twill\\Http\\Controllers\\Admin\\ModuleController->update('2', NULL)
#27 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#28 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('update', Array)
#29 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(A17\\Twill\\Http\\Controllers\\Admin\\UserController), 'update')
#30 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#31 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#32 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'edit-user', 'user')
#35 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/alexandr/Projects/CMS/vendor/area17/twill/src/Http/Middleware/ValidateBackHistory.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): A17\\Twill\\Http\\Middleware\\ValidateBackHistory->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/alexandr/Projects/CMS/vendor/area17/twill/src/Http/Middleware/Impersonate.php(17): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): A17\\Twill\\Http\\Middleware\\Impersonate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'twill_users')
#44 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#65 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#66 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#67 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#68 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#69 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#70 /home/alexandr/Projects/CMS/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /home/alexandr/Projects/CMS/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#74 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#77 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#80 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#83 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#86 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#89 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#90 /home/alexandr/Projects/CMS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#91 /home/alexandr/Projects/CMS/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#92 /home/alexandr/Projects/CMS/server.php(21): require_once('/home/alexandr/...')
#93 {main}
"} 
`
P.S. Sorry for my English, I'm study it.

**Comment by noxify** [comment]
Hi,

as already mentioned from @ifox, set the `MAIL_DRIVER` to `log` (if you're working on a local machine).
Alternative you can configure your endpoint to solve the problem:

```
[2018-12-07 08:39:48] local.ERROR: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "
```

Detailed information about how to configure the mail driver can be find here: https://laravel.com/docs/5.7/mail#driver-prerequisites
