### ISSUE TITLE
Force user logout on frontend when session expires

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#964]
## Summary

If a user's session expires and the user clicks on any button that makes an ajax call, what they will see is this

<img width="2280" alt="Screenshot 2021-06-07 at 15 10 57" src="https://user-images.githubusercontent.com/3182864/121022452-9f873600-c7a2-11eb-89b1-62f4eed19883.png">

And the 401 error response is 

``` json
{"message":"Unauthenticated."}
```

## Describe the solution you'd like

I believe I nice solution for this would be an automatic logout done by frontend.

**Comment by ifox** [comment]
@antonioribeiro it needs to be improved, but we do have a session timeout mechanism in place. If you try saving while your session expired, a notification should show up offering you to login again in a different tab to be able to save changes again. https://github.com/area17/twill/blob/a5b3ffc20ab7826bff6825f28982444e7272537d/frontend/js/utils/errors.js#L18.

**Comment by antonioribeiro** [comment]
I remember seeing it, @ifox! Thanks! 

I just sent a [PR](https://github.com/area17/twill/pull/966) to improve it a bit. I'm not really a JavaScript developer, so feel free to close it! 😆

**Comment by ifox** [comment]
Thanks @antonioribeiro, your changes make a lot of sense to me!
