### ISSUE TITLE
Add Blade "x-component" example to docs

### ISSUE THREAD

**Issue by pboivin** [area17/twill#969]
## Summary

Laravel 7.x introduced a new syntax for [Blade components](https://laravel.com/docs/7.x/blade#displaying-components). It would be useful to have one example for all the different ways to use Twill components or partials in Blade views (ie. long-form, alias, x-component). 

## Related

Mentioned while discussing this PR :
https://github.com/area17/twill/pull/955

**Comment by haringsrob** [comment]
This is done in https://github.com/area17/twill/pull/1360
