### ISSUE TITLE
Make JsonRepeaters translatable

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#971]
## Summary

If you create a json repeater and make it translatable, Twill will save it correctly in all languages, but then it will not be able to load it back into the CMS frontend because the trait is not translation aware.

**Comment by antonioribeiro** [comment]
It is translatable, but I was using it wrong, this is how you do it:

- Create the JSON field on the main table, not the translations
- Set the form fields as `"translated" => true`
- Done! 😆

**Comment by LucaRed** [comment]
Thank you, you saved my life!

In case @antonioribeiro's solution is not clear enough:

* JSON field goes on the main table (not the `_translations` one)
* There's no need to specify the translation on the `@formField('repeater')` field (in the main form Blade view)
* In the repeater Blade file, set `'translated' => true` on the inputs you want to translate (you can translate some of them or all of them)
* On the model, **don't** add the json field in the `$translatedAttributes` array
* Add it however on both the `$fillable` and `$casts` arrays

This is the working solution on my current Twill version, which is 2.11.0.

**Comment by magiceupho** [comment]
Hi,
I followed the @LucaRed process, but a A17\Twill\Exceptions\NoCapsuleFoundException is throwing.
I don't understand that error because I don't use Capsule.
If I remove HasTranslation from the model, the error doesn't throw, but the field in the repeater isn't translatable.
Can someone help me please ?

**Comment by antonioribeiro** [comment]
@magiceupho, We need to improve this exception and message, but this usually means that Twill was not able to find a Module or a Capsule (which is a Module just containerised). Most of the times this is due to us, mixing up case, or refering to the Module as singular instead of plural

**Comment by magiceupho** [comment]
Thx @antonioribeiro, I forgot to create a `ModuleTranslation.php` file.

Now I can edit and save the json repeatable, but the field that is translatable doesn't provide the interface to translate it.
Can you help me please ?

**Comment by magiceupho** [comment]
@antonioribeiro I've understand why the interface to translate isn't showing: my model doesn't have translated field.
If I add one, the interface shows up.
Would it be possible to display the translation interface/buttons, even if there are no translatable fields?

**Comment by antonioribeiro** [comment]
I'm not sure this is possible today and if it makes sense @magiceupho. If we show a translatable interface to users they expect at least one field translatable. But you can create a feature request ticket with your reasoning.

**Comment by magiceupho** [comment]
@antonioribeiro My model include a JsonRepeater containing one field who is translatable. But this is the only translatable field.
So I must create a fantom/empty translatable field in order to display the interface.

**Comment by antonioribeiro** [comment]
So this is actually a bug, right, @antonioribeiro? If you have one translatable field in your form and Twill is not showing the translation interface, can you please open a new ticket and report this as a bug?

**Comment by magiceupho** [comment]
Ok
