### ISSUE TITLE
site-link: true - bug?

### ISSUE THREAD

**Issue by awgul** [area17/twill#98]
I have my test app as:
http://twill.local

I set `site-link` to `true` and I see "Open Live site" link but it goes to `http://admin.twill.local/twill.local` instead of `http://twill.local`

**Comment by ifox** [comment]
Hi @awgul!

I see that the `site-link` feature is visible in our docs but it shouldn't, it is deprecated, as it is in conflict with our installation instructions regarding `APP_URL` without scheme. It should work if you set both `APP_URL` and `ADMIN_APP_URL` to include http or https.
