### ISSUE TITLE
BigInt or Int is not friendly regarding Microservice!

### ISSUE THREAD

**Issue by weburnit** [area17/twill#988]
## Summary

One of the best practices for Microservices relates to a primary key that UUID is much friendlier!
https://dzone.com/articles/7-strategies-for-assigning-ids-to-microservices
## Describe the solution you'd like

Support UUID for twillMethodIncrements.

**Comment by antonioribeiro** [comment]
@weburnit , you can probably overload those helpers and use whatever you want instead:

``` php
if (!function_exists('twillIncrementsMethod')) {
    /**
     * @return string
     */
    function twillIncrementsMethod()
    {
        return config('twill.migrations_use_big_integers')
            ? 'bigIncrements'
            : 'increments';
    }
}

if (!function_exists('twillIntegerMethod')) {
    /**
     * @return string
     */
    function twillIntegerMethod()
    {
        return config('twill.migrations_use_big_integers')
            ? 'bigInteger'
            : 'integer';
    }
}
```

**Comment by weburnit** [comment]
> @weburnit , you can probably overload those helpers and use whatever you want instead:
> 
> ```
> if (!function_exists('twillIncrementsMethod')) {
>     /**
>      * @return string
>      */
>     function twillIncrementsMethod()
>     {
>         return config('twill.migrations_use_big_integers')
>             ? 'bigIncrements'
>             : 'increments';
>     }
> }
> 
> if (!function_exists('twillIntegerMethod')) {
>     /**
>      * @return string
>      */
>     function twillIntegerMethod()
>     {
>         return config('twill.migrations_use_big_integers')
>             ? 'bigInteger'
>             : 'integer';
>     }
> }
> ```

Yeahh! That's what I did, but migration is not compatible with UUID!

**Comment by pboivin** [comment]
Hi @weburnit, on the Twill side, it's true that switching to UUIDs would require extending the internal models which is not really straightforward at the moment. But implementing UUID's on your app's entities is possible and compatible with integer primary keys.
